### PR TITLE
[server] verify members of paying orgs

### LINKED ISSUE #17583: Do not require phone verification for launching workspaces for projects in a billed org.
### Bug description

I'm an admin for a paid organization using GitPod. I was onboarding a new user and had added them to the org, and everything looked good… until they tried to start a workspace for a project in the organization. After clicking to start a workspace, they were presented with a prompt to verify their phone number: https://github.com/gitpod-io/gitpod/issues/11339

The only ostensible reason for the phone number is to prevent the use of free quota but **the project is in a billed organization**, so this should be unnecessary to prevent abuse.

If every org user individually has to give GitPod their phone number, we do not feel comfortable using GitPod going forward. As mentioned at https://github.com/gitpod-io/gitpod/issues/11339#issuecomment-1243417932 , the current flow might also not be GDPR-compliant (and we have EU citizens in the organization).

I'd like to ask that  we can allow users to use our organization billing instead of individually entering a phone number.

### Steps to reproduce

1. Onboard a new user to an billed org.
2. Try to start a new workspace as that user.

### Workspace affected

_No response_

### Expected behavior

No phone number prompt.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

Verify members of paying orgs

## Related Issue(s)

Fixes WEB-369
Fixes #17583

#### Preview status

gitpod:summary

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [x] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

File: components/server/src/auth/verification-service.ts [hunk 1]
```diff
@@ -58,6 +59,24 @@ export class VerificationService {
...
 
+    public async verifyOrgMembers(organizationId: string): Promise<void> {
+        const members = await this.teamDB.findMembersByTeam(organizationId);
+        for (const member of members) {
+            const user = await this.userDB.findUserById(member.userId);
+            if (user) {
+                await this.verifyUser(user);
+            }
+        }
+    }
```
Comment (easyCZ) [inline components/server/src/auth/verification-service.ts:70]: What if we used the `TeamService` here instead to list the members? The benefit I can see is we're not duplicating the logic on fetching the users and (should we need to adjust the returned data, we do that in a single place). It would also remove the dependency of the Verification Service on the Team DB directly

Comment (svenefftinge) [reply components/server/src/auth/verification-service.ts:70]: you mean the grpc api?

Comment (easyCZ) [reply components/server/src/auth/verification-service.ts:70]: No, not grpc. I just checked and there isn't one for Teams/Orgs, but something like the `UserService`. The rough outline is that it would have 

```
interface OrganizationsService {
  listMembers()
  get(id)
  delete(id)
}
```

The main benefit I see is when go and move these into gRPC, we'll need to share the implementation between the websocket and gRPC at least for the duration of the migration but it would also give us a place to co-locate operations done on Organizations, which are not strictly just DB operations

Comment (svenefftinge) [reply components/server/src/auth/verification-service.ts:70]: I believe TeamDB provides that level of abstraction already

Comment (easyCZ) [reply components/server/src/auth/verification-service.ts:70]: I'll do an example in a follow up PR to show the duplication, and how it would help in particular with keeping the implementation between the grpc and websocket APIs the same

**Review by easyCZ — APPROVED** [review]

**Comment by lgarron** [comment]
Glad to see this landed!

We were onboarding someone an hour after this landed and they were still asked for their phone number when starting an org-billed instance — is it expected the fix is not completely in place yet?

**Comment by svenefftinge** [comment]
It is deployed tomorrow morning 10am CEST
