### PR TITLE
ws-daemon: ignore error when workspace persistent state location not exist

### LINKED ISSUE #11715: [ws-daemon] Unexpected error during workspace dispose
### Bug description

Jaeger-UI (1)

### Steps to reproduce

- n/a

### Workspace affected

_No response_

### Expected behavior

Log the error when its encountered and include context (instance ID) so its easier to track down what happened. 

### Example repository

_No response_

### Anything else?

This is just the first step for now, get some insight to whether this condition is happening, with related context, so we can react later.

### PR DESCRIPTION
**Pull request by jenting**
## Description

The initial workspace failed at the beginning, so the workspace's persistent state location never exist.

## Related Issue(s)

Fixes #11715

## How to test

Not sure, but we did see some nodes path `/var/gitpod/workspaces` with the folders
- `<instance-id>`
- `<instance-id>-daemon`

but without the corresponding `<instance-id>.workspace.json`.

## Release Notes

```release-note
None
```

## Documentation

None

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

File: components/ws-daemon/pkg/internal/session/workspace.go [hunk 1]
```diff
@@ -204,7 +204,12 @@ func (s *Workspace) Dispose(ctx context.Context) (err error) {
 	// old workspace content we can garbage collect that content later.
 	err = os.Remove(s.persistentStateLocation())
 	if err != nil {
-		return xerrors.Errorf("cannot remove workspace persistent state location: %w", err)
+		if os.IsNotExist(err) {
+			log.WithError(err).Warn("workspace persistent state location not exist")
+			err = nil
```
Comment (jenting) [inline components/ws-daemon/pkg/internal/session/workspace.go:209]: I'm not sure should we keep running the following code?
https://github.com/gitpod-io/gitpod/blob/5fb85e47e307e8b2acc1ea5ac990ccd07abaceeb/components/ws-daemon/pkg/internal/session/workspace.go#L210-L232
or directly return at here.

**Review by sagor999 — APPROVED** [review]
I think this is a good fix. LGTM.
