### PR TITLE
[dashboard] handle unlimited users condition in license page

### LINKED ISSUE #9763: Admin license screen showing "exceeded usage limit" on unlimited user license
### Bug description

There is an error message on the admin license page saying that we've exceeded the number of users allotted by the license. 

image

### Steps to reproduce

Go to Admin panel, license on gitpod.io

### Workspace affected

_No response_

### Expected behavior

The error message should not be visible for an unlimited user plan

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nandajavarma**
## Description

In `gitpod.io` the unlimited number of users is specified by `seats === 0`. Currently in the License dashboard, this condition is not handled properly and hence gives the wrong alert message. This PR fixes this issue. 

## Related Issue(s)

Fixes #9763

## How to test

Update the license to have user seats value `0`. I tested it by updating the user seats on a replicated license. One can ideally test it also on [preview environment by updating the Werft secret for license.
](https://www.notion.so/gitpod/Create-a-Gitpod-Self-Hosted-License-fef6b0e3548b4676a9d782f6d5a3df9a)
## Release Notes

```release-note
None
```

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hi @nandajavarma, many thanks for this fix! 🙏 Happy to take a look today for team WebApp. The first thing will be for me to figure out how licenses work -- thanks also for linking to the [relevant docs](https://www.notion.so/gitpod/Create-a-Gitpod-Self-Hosted-License-fef6b0e3548b4676a9d782f6d5a3df9a)! 💯

**Comment by jankeromnes** [comment]
Werft seems to have failed with:

```
Copy over CertManager resources from core-dev
Waiting for certificate readiness
```

Let's try this again:

/werft run with-clean-slate-deployment

File: components/dashboard/src/admin/License.tsx [hunk 1]
```diff
@@ -202,7 +203,8 @@ function communityPlan(userCount: number, seats: number, fallbackAllowed: boolea
         }
     };
 
-    const aboveLimit: boolean = userCount > seats;
+    // seats === 0 means unlimited number of users
+    const aboveLimit: boolean = seats === 0 ? false : userCount > seats;
```
Comment (jankeromnes) [inline components/dashboard/src/admin/License.tsx:207]: I wonder if this could be de-duplicated as a single, `isAboveLimit(userCount, seats)` function. 💭 But not very important.

**Review by jankeromnes — APPROVED** [review]
Code looks good to me, thanks!

And phew, I was finally able to install a license into the preview environment, thanks to:
- [the docs](https://www.notion.so/gitpod/Create-a-Gitpod-Self-Hosted-License-fef6b0e3548b4676a9d782f6d5a3df9a) (slightly outdated)
- @mads-hartmann's help to adjust the docs for VMs 🙏

| LIMITED | UNLIMITED |
| --- | --- |
| Screenshot 2022-05-06 at 10 40 00 | Screenshot 2022-05-06 at 11 48 18 |

Looks good to me! 🚀
