### PR TITLE
check for repository property on context

### LINKED ISSUE #16926: New "StartWorkspace" broken for SnapsnotContexts (and all other non-commit contexts as well)
Error message: `Cannot read properties of undefined (reading 'cloneUrl')`

[internal thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1679327293940209)

### PR DESCRIPTION
**Pull request by selfcontained**
## Description

Fixes a bug when using a snapshot context url with the new create workspace page. Needed to make the logic that checks for a matching project a bit more resilient to missing properties on the workspace context object.

## Related Issue(s)

Fixes #16926

## How to test

* Create a Workspace
* Create a Snapshot from your workspace
* Load the Snapshot URL and ensure it doesn't render an error page like in the issue.

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

File: components/dashboard/src/workspaces/CreateWorkspacePage.tsx [hunk 1]
```diff
@@ -66,12 +66,20 @@ export function CreateWorkspacePage() {
...
     const isLoading = workspaceContext.isLoading || projects.isLoading;
+
+    // see if we have a matching project based on context url and project's repo url
     const project = useMemo(() => {
         if (!workspaceContext.data || !projects.data) {
             return undefined;
         }
-        const cloneUrl = (workspaceContext.data as CommitContext).repository.cloneUrl;
-        return projects.data.projects.find((p) => p.cloneUrl === cloneUrl);
+        if ("repository" in workspaceContext.data) {
```
Comment (AlexTugarev) [inline components/dashboard/src/workspaces/CreateWorkspacePage.tsx:75]: fyi, there is `CommitContext.is` type guard for that
