### PR TITLE
[installer] add an experimental config section

### LINKED ISSUE #7776: [installer] The rendered manifest does not contains the required env var KUBE_STAGE
### Bug description

Several components rely on the value. 

### Steps to reproduce

-

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR adds an `experimental` section to the config surface. The intent is to give the product engineering teams a home for their configuration specifically for operating Gitpod SaaS. 

As a first use-case we introduce the "kubeStage" used for the content-service to compute bucket names.

**Note:** we want to keep a close eye on the use of experimental config, so as to not introduce too much variance. That's why ordinarily the experimental config is nil always, and one has to access it using `RenderContext`'s new `WithExperimental` function. This way, we can group and keep tabs on code which relies on this kind of configuration.

## Related Issue(s)

Fixes #7776

Note: this issue blocks/hinders the workspace team's adoption of the installer.

## How to test
1. `installer init > config.yaml`
2. edit `config.yaml` and add:
    ```YAML
    experimental:
      workspace:
        stage: prod
    ```
3. render the config and observe the warning re experimental config: `installer render --config config.yaml`
4. render the config with experimental config enabled: `installer render --config config.yaml --danger-use-experimental-config`

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mrsimonemms** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mrsimonemms` in a comment when ready.

Associated issue: *#7776*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by corneliusludmann** [comment]
Great to see this and that this unblocks the workspace team! :rocket: 

The PR https://github.com/gitpod-io/gitpod/pull/7727 introduces something similar for Jaeger sampling parameters. @MrSimonEmms: Can you make sure you two agree on an approach and merge your approaches into a common one? Let me know if you need me or in case something is unclear.

File: installer/pkg/common/storage.go [hunk 1]
```diff
@@ -87,6 +89,11 @@ func StorageConfig(context *RenderContext) storageconfig.StorageConfig {
 	// 5 GiB
 	res.BlobQuota = 5 * 1024 * 1024 * 1024
 
+	_ = context.WithExperimental(func(ucfg *experimental.Config) error {
+		res.Stage = storageconfig.Stage(ucfg.Workspace.Stage)
```
Comment (MrSimonEmms) [inline installer/pkg/common/storage.go:93]: Just a thought - if the `Stage` isn't added in the config file, this gives a null pointer error. Do we want to add a check in to ensure that doesn't happen?

I'll approve it and you can merge if you're happy to proceed without it

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7a88adc870ba68ad1884da2f92d6592d5cd04c53</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7851#issuecomment-1023129798" title="Approved">MrSimonEmms</a>*

Associated issue: *#7776*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [MrSimonEmms]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 20132c5c7ffa307d223688a4fde266fb6957b304</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7851#issuecomment-1023237338" title="Approved">MrSimonEmms</a>*

Associated issue: *#7776*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [MrSimonEmms]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
