### PR TITLE
[usage] reduce possibility for races in ResetUsage

### LINKED ISSUE #14973: [UBP] Duplicate ledger reset entries
A couple of usage accounts show duplicate reset entries in the ledger.  
The impact in the cases below is an incorrect balance with extra credits in favor of the user or team.  
More details in [discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1669136926283269) (internal)

Attribution IDs below modified for privacy.

```
[{
  "id": "b5106ec4-bb77-4cc6-8d5e-59936725b3f9",
  "attributionId": "user:xxx",
  "description": "Credits",
  "creditCents": "-8722",
  "effectiveTime": "2022-11-16T12:11:38.545Z",
  "kind": "invoice",
  "workspaceInstanceId": null,
  "draft": "0",
  "metadata": null,
  "_created": "2022-11-16 12:11:38.556265 UTC",
  "_lastModified": "2022-11-16 12:11:38.556265 UTC"
}, {
  "id": "467cb50c-ef9b-4b3d-9914-ca53766dc046",
  "attributionId": "user:xxx",
  "description": "Credits",
  "creditCents": "-8722",
  "effectiveTime": "2022-11-16T12:11:38.510Z",
  "kind": "invoice",
  "workspaceInstanceId": null,
  "draft": "0",
  "metadata": null,
  "_created": "2022-11-16 12:11:38.537253 UTC",
  "_lastModified": "2022-11-16 12:11:38.537253 UTC"
}]
```

and

```
[{
  "id": "329243bf-d090-48ef-8bd5-604682b18ab7",
  "attributionId": "team:yyy",
  "description": "Credits",
  "creditCents": "-19539",
  "effectiveTime": "2022-11-10T17:42:15.226Z",
  "kind": "invoice",
  "workspaceInstanceId": null,
  "draft": "0",
  "metadata": null,
  "_created": "2022-11-10 17:42:15.408721 UTC",
  "_lastModified": "2022-11-16 16:26:01.661318 UTC"
}, {
  "id": "60c862f8-98b1-45fb-bfbe-80210ddf7b87",
  "attributionId": "team:yyy",
  "description": "Credits",
  "creditCents": "-19539",
  "effectiveTime": "2022-11-10T17:42:15.267Z",
  "kind": "invoice",
  "workspaceInstanceId": null,
  "draft": "0",
  "metadata": null,
  "_created": "2022-11-10 17:42:15.408987 UTC",
  "_lastModified": "2022-11-16 16:26:01.661318 UTC"
}]
```

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Fetch the cost center from db immediately before deciding to resetting the usage. So that the time window in which a parallel resetting for the same cost center could happen is minimized.

We saw eight cases in Nopvember where thsi happened. But teh likely hood was very high due to:
- no resetting scheduler was active (so every cost center was outdated at some point)
- we fetch the cost center first and do quite some computation before inserting the update.

## Related Issue(s)

Fixes #14973

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@svenefftinge: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/gitpod-db/go/cost_center_test.go [hunk 1]
```diff
@@ -408,12 +408,16 @@ func TestCostCenterManager_ResetUsage(t *testing.T) {
...
-		_, err := mnr.ResetUsage(context.Background(), db.CostCenter{
+		cc := &db.CostCenter{
 			ID:              db.NewUserAttributionID(uuid.New().String()),
 			CreationTime:    db.NewVarCharTime(time.Now()),
 			SpendingLimit:   500,
 			BillingStrategy: db.CostCenter_Stripe,
-		})
+		}
+
+		err := conn.Save(cc).Error
```
Comment (easyCZ) [inline components/gitpod-db/go/cost_center_test.go:418]: You could use `dbtest.CreateCostCenter`.

File: components/gitpod-db/go/cost_center.go [hunk 2]
```diff
@@ -262,31 +262,36 @@ func (c *CostCenterManager) ListLatestCostCentersWithBillingTimeBefore(ctx conte
...
 		return CostCenter{}, fmt.Errorf("cannot reset usage for Billing Strategy %s for Cost Center ID: %s", cc.BillingStrategy, cc.ID)
 	}
+	if !cc.IsExpired() {
+		logger.Info("Skipping ResetUsage because next billing cycle is in the future.")
+		return cc, nil
+	}
 
-	now := time.Now().UTC()
-
+	logger.Info("Running `ResetUsage`.")
```
Comment (easyCZ) [inline components/gitpod-db/go/cost_center.go:280]:
```suggestion
	logger.WithField("attribution_id", id).WithField("cost_center", cc).Infof("Resetting usage for Attribution ID %s", id)
```

**Review by easyCZ — APPROVED** [review]
LGTM

/hold for improved log which can be used to correlate any future duplicates with logs

File: components/gitpod-db/go/cost_center.go (hunk 2 above)
Comment (svenefftinge) [reply components/gitpod-db/go/cost_center.go:281]: 👍  Added the cost center. the attributiond id was already included and I like to keep the message static, as it's a bit easier to filter on that way.
