### PR TITLE
blobserve redirect improvements

### LINKED ISSUE #2061: [staging]: diff view does not work properly
### Describe the bug

On staging the diff view does not work properly i.e there is no colour highlighting for the additions and the subtractions:

image

image

### Steps to reproduce

- Open a workspace on gitpod staging i.e https://gitpod-staging.com/#https://github.com/vuejs/vuex.
- Try changing some files.
- Open the Diff View from Source control for any chnaged file.

### LINKED ISSUE #2093: don't redirect to blobserver if URL has a query
~Also don't drop fragment while redirecting.~ - does not matter, fragment is only processed by the user agent

### PR DESCRIPTION
**Pull request by akosyakov**
- [x] /werft ws-feature-flags=registry_facade
- [x] /werft https

#### What it does

- fix #2093: URIs with query cannot be static and should not be redirected to the blobserve, it breaks loading of icons for Gitpod Code from 3rd party extensions
- fix #2061: install proxying (Shared)Worker which serve from the workspace origin but fetch the worker content from the blobserve
- utilize [fetch metadata](https://developer.mozilla.org/en-US/docs/Glossary/Fetch_metadata_request_header) to prevent redirect to blobserve for user navigation and same-origin requests (if not workers, see point above)
- use permament redirect for the same workspace to avoid extra requests on page reload or workspace restart

#### How to test

- Start Theia workspace: https://ak-enh-blobserve-redirect.staging.gitpod-dev.com/#https://github.com/gitpod-io/go-gin-app
- Open devtools.
- Amend the last commin in the scm view and open the changed file. Check that the diff is properly highlighted.
- In the network tab of devtools check that workerMain is properly loaded.
- In the source tab of devtools check that editorWorkerService worker is running.
- Reload the page, check everything again.
- Stop this workspace, start another one (new), everything again and at the end check that workerMain was served from the browser cache.
- Enabel devops role for your user: `update d_b_user set rolesOrPermissions = '["admin","devops"]' where name = 'akosyakov';`
- Start Code workspace: https://ak-enh-blobserve-redirect.staging.gitpod-dev.com/#https://github.com/akosyakov/go-gin-app
- Check that file icons are loaded, i.e. in the explorer you see real icons, not placeholders.
- Run check similar to Theia workspace from above.
- In addition check an extension host worker (thread which handles web extensions) is running.
- Test everything in Chrome, FF and Safari.

### CODE REVIEW

File: components/supervisor/frontend/src/ide/ide-worker.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+        };
+    }
+}
+
+function proxyUrl(scriptUrl: string | URL): string {
+    scriptUrl = typeof scriptUrl === 'string' ? new URL(scriptUrl, document.baseURI) : scriptUrl;
+    if (scriptUrl.protocol !== 'http:' && scriptUrl.protocol !== 'https:') {
+        return scriptUrl.toString();
+    }
+    return new URL('_supervisor/frontend/worker-proxy.js?mode=same-origin#' + encodeURI(scriptUrl.toString()), document.baseURI).toString();
```
Comment (akosyakov) [inline components/supervisor/frontend/src/ide/ide-worker.ts:30]: query can break browser caching, so just always proxy pass worker-proxy.js

**Review by csweichel — APPROVED** [review]
