### PR TITLE
[content-service] Revert #11895

### LINKED ISSUE #13512: Prebuild on a branch failed when fetching additional repository that didn't have that branch
### Bug description

Pushed commits to a new branch `lldb-attempts` in GitLab repo, prebuild was triggered, it seemed to completely build the custom `.gitpod.Dockerfile` but then failed with

```
SYSTEM ERROR
Prebuild failed for system reasons. Please contact support. undefined
```

Log cut/pasted from prebuild window: https://gist.github.com/david-bakin/51c7240de342148f228133e57983c1bd

Oh wait a sec!  When I _reopened_ the prebuild window I see a _different_ SYSTEM ERROR:

```
Prebuild failed for system reasons. Please contact support. cannot initialize workspace: cannot initialize workspace: git initializer clone: Remote branch lldb-attempts does not exist in https://github.com/lldb-tools/lldb-mi.git
```

And this is true!  My main repo is trying to prebuild branch `lldb-attempts` but I expected the _additional repo_ to _pull_ its _default_ branch!  

**Note that the documentation says it will do this!!**

> When the above configuration is defined then the following additional steps happen when Gitpod workspace is started:
>
> 1. If you open a workspace on a branch, Gitpod will clone the same-named branch in all repositories. **If such a branch doesn’t exist Gitpod checks out the default branch.**

And by the way the "undefined" error on the first prebuild window I saw is bad - it is only by sheer chance, wanting to file an issue on the "SYSTEM ERROR", that I opened the window again from the prebuilds dashboard page and saw the _real_ error.

### Steps to reproduce

Set up a repo with an additional repo - any arbitrary one off of the web.  Main repo needs a .gitpod.yml that triggers a prebuild when any new branch is pushed.  Then push a new branch to the main repo _making sure the new branch name is not one that is present in the additional repo_.  See if it fails this way.

### Workspace affected

https://gitpod.io/projects/env-wrappers-cpp/e9acba92-0005-452d-8319-927c48f6db4e

### Expected behavior

I expected either the additional repo to _pull_ its _default branch_, or for there to be a way to _specify_ which branch to pull for the additional repos.

### Example repository

_No response_

### Anything else?

_No response_

Front logo [Front conversations](https://app.frontapp.com/open/top_3rbt6)

### LINKED ISSUE #13527: Branch names should not be used to checkout additionalRepositories
### Bug description

When a repository contains a .gitpod.yml with `additionalRepositories`, and we open a branch, that branch name does not necessarily exist in the additional repositories.

Screenshot from 2022-10-03 08-40-21

### Steps to reproduce

Open a workspace using https://github.com/gitpod-io/gitpod-test-repo/tree/aledbf/test-additional-repositories

### Workspace affected

gitpodio-gitpodtestrepo-77i2bt10ohp

### Expected behavior

Use the default branch name

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aledbf**
## Description

When we open a workspace from a branch and the repository contains a .gitpod.yml file with `additionalRepositories`, we should not assume the branch exists in those repositories. Also, when we specify a branch in one of the `additionalRepositories`, we should be able to use that branch.

## Related Issue(s)

Fixes #13527
Fixes #13512
Reverts #11895

## How to test
- Open a workspace using
  - https://github.com/gitpod-io/gitpod-test-repo/tree/aledbf/test-additional-repositories
  - https://github.com/gitpod-io/gitpod-test-repo/tree/aledbf/test-additional-repositories-with-branches

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: test/tests/components/ws-manager/additional_repositories_test.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+					ContextURL: "https://github.com/gitpod-io/gitpod-test-repo",
+					CloneTaget: "aledbf/test-additional-repositories-with-branches",
+				},
+			}
+			ctx, cancel := context.WithTimeout(context.Background(), time.Duration(5*len(tests))*time.Minute)
+			defer cancel()
+
+			for _, test := range tests {
+				t.Run(test.Name, func(t *testing.T) {
+					t.Parallel()
```
Comment (utam0k) [inline test/tests/components/ws-manager/additional_repositories_test.go:45]: Limit concurrency. Otherwise, we will eventually fail with Too Many Requests.
https://github.com/gitpod-io/gitpod/blob/18c147fe4d92337d61161900fb029a67843fcf83/test/tests/workspace/contexts_test.go#L110

Comment (aledbf) [reply test/tests/components/ws-manager/additional_repositories_test.go]: removed

File: test/tests/components/ws-manager/additional_repositories_test.go [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+		WithLabel("component", "ws-manager").
+		Assess("can open a workspace using the additionalRepositories property", func(_ context.Context, t *testing.T, cfg *envconf.Config) context.Context {
+			tests := []struct {
+				Name       string
+				ContextURL string
+				CloneTaget string
+			}{
+				{
+					Name:       "workspace with additionalRepositories using a branch",
+					ContextURL: "https://github.com/gitpod-io/gitpod-test-repo",
```
Comment (jenting) [inline test/tests/components/ws-manager/additional_repositories_test.go:31]: I know this repo from this PR, nice!

File: test/tests/components/ws-manager/additional_repositories_test.go [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+
+					rsa, closer, err := integration.Instrument(integration.ComponentWorkspace, "workspace", cfg.Namespace(), kubeconfig, cfg.Client(),
+						integration.WithInstanceID(ws.Req.Id),
+					)
+					if err != nil {
+						t.Fatal(err)
+					}
+
+					integration.DeferCloser(t, closer)
+					defer rsa.Close()
```
Comment (jenting) [inline test/tests/components/ws-manager/additional_repositories_test.go:85]: We could check the workspace pod branch name here.

**Review by jenting — APPROVED** [review]
Code LGTM. But it would be good if we could enhance the integration test to check the workspace pod branch name is as expected.

/hold

**Review by svenefftinge — APPROVED** [review]
Thanks! Cloning multi-repos on branches now works again as advertised.

File: test/tests/components/ws-manager/additional_repositories_test.go (hunk 3 above)
Comment (aledbf) [reply test/tests/components/ws-manager/additional_repositories_test.go:90]: done

**Comment by aledbf** [comment]
/werft run with-integration-tests=workspace with-large-vm with-clean-slate-deployment
