### PR TITLE
[gitlab/webhook] return code 200 on Unauthorized

### LINKED ISSUE #13985: Webhooks for GitLab projects are disabled on Unauthorized Errors
**Issue**

We've learned now that GitLab webhooks are disabled automatically if the receiver (Gitpod) is responding with status codes other than 2xx. The rules for [failing webhooks](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#failing-webhooks) are basically:
* on 5xx responses -> disable temporarily
* on 4xx responses -> disable permanently, which requires manual re-enabling on GitLab

There seems to be at least two cases where the Unauthorized Error might occur:
* when the Gitpod user who created the project disconnects from the GitLab integration.
* (as we assume after scanning logs) when there are repository forks involved, for which webhook events are registered, but the Gitpod users is not authorized. 

In any case, we should not upset GitLabs when webhooks cannot be triggered. 

**Solution**

On Unauthorized Errors the GitLab webhook handler should respond with a code 2xx. 

Further we should investigate
* the errors on events for repository forks.
* how to make Unauthorized Errors visible to project owners.

### PR DESCRIPTION
**Pull request by AlexTugarev**
To avoid provoking permanent deactivation of the webhooks we need to stop responding with status 401. In future we need to make the Unauthorized situation fixable from Gitpod.

## Related Issue(s)

Fixes #13985

## How to test
1. Do a manual test with a GitLab project, including pushing to a repo and verifying that a prebuild was triggered. 
2. Delete your test account.
3. Push a change to the test repo, and verify that Gitpod is not responding with code 401. See: https://gitlab.com/YOUR_ACCOUNT/TEST_REPO/-/hooks/WEBHOOK_ID/edit

## Release Notes

```release-note
Gitlab webhooks: play nice, don't respond with code 401.
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

File: components/server/ee/src/prebuilds/gitlab-app.ts [hunk 1]
```diff
@@ -75,11 +75,11 @@ export class GitLabApp {
...
             }
             if (!user) {
-                // If the webhook installer is no longer found in Gitpod's DB
-                // we should send a UNAUTHORIZED signal.
+                // Gitpod is not supposed to return 4xx codes on issues with project permissions.
                 span.finish();
-                res.status(401).send("Unauthorized.");
+                res.status(200).send("Unauthorized.");
                 await this.webhookEvents.updateEvent(event.id, { status: "dismissed_unauthorized" });
+                // TODO(at) explore ways to mark a project having issues with permissions.
```
Comment (AlexTugarev) [inline components/server/ee/src/prebuilds/gitlab-app.ts:82]: this as a followup to https://github.com/gitpod-io/gitpod/issues/13985

File: components/server/ee/src/prebuilds/gitlab-app.ts [hunk 2]
```diff
@@ -75,11 +75,11 @@ export class GitLabApp {
                 TraceContext.setError({ span }, error);
             }
             if (!user) {
-                // If the webhook installer is no longer found in Gitpod's DB
-                // we should send a UNAUTHORIZED signal.
+                // Gitpod is not supposed to return 4xx codes on issues with project permissions.
```
Comment (easyCZ) [inline components/server/ee/src/prebuilds/gitlab-app.ts:78]: Given this behaviour (200 on Error) is gonna look pretty bizzare to future readers, could you explain WHY it's doing it, rather than WHAT it's doing?

What I mean is to elaborate on why we cannot return a 4xx, and what are the implications if we do.

Comment (AlexTugarev) [reply components/server/ee/src/prebuilds/gitlab-app.ts:78]: That's a good question. The complete answer and docs are already contained at the top of this handler.

From the webhook event sender's perspective this is is not a 4xx case. We are not interested in a permanent disablement of the webhook if project permissions are temporarily "broken", instead prebuilds won't be executed until the maintainer had a chance to fix the issue. 

Also noteworthy, the response text is completely optional and helps us to understand the delivery logs on GitLab, but it's ignored otherwise. So this is the place where we may encode the App level error. 

The sender expects a 2xx response whenever it was a successful and legit delivery. It's up to the receiver to deal with issues of the application. For more on this see the linked issue and https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#failing-webhooks

Comment (geropl) [reply components/server/ee/src/prebuilds/gitlab-app.ts:78]: > The complete answer and docs are already contained at the top of this handler.

@AlexTugarev Looks like it only mentions 500. Can you add a line about 4xx as well? :pray:

**Comment by geropl** [comment]
Start ŧesting now...

**Comment by geropl** [comment]
Worked: 
image

**Review by geropl — APPROVED** [review]
Code LGTM, tested and works :tada: 

/hold for this [small ask](https://github.com/gitpod-io/gitpod/pull/14421/files#r1013827300)

File: components/server/ee/src/prebuilds/gitlab-app.ts (hunk 2 above)
Comment (AlexTugarev) [reply components/server/ee/src/prebuilds/gitlab-app.ts]: Thanks both of you for the hint. Just added some more details on the special behavior of webhooks, so that reading code makes more sense to future readers.
