### PR TITLE
GetUpcomingInvoice for BillingService

### LINKED ISSUE #11692: Implement BillingService.GetLatestInvoice
Currently, when showing spending notifications to users we use the `UsageService.ListUsage` RPC and we sum up all the records. This is suboptimal, but more importantly it is the wrong data. Instead, we need to be looking at the current value of an Invoice (unpaid).

To that end, we want to add a new RPC to the `BillingService`. The RPC should be able to do the following:
* Given a UserID, or TeamID, it find details about the latest invoice and retrieves the current value of that invoce (along with more info if needed)

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
This PR implements ~`GetLatestInvoice`~  `GetUpcomingInvoice`. The rename is done intentionally, to a) align with terminology used in stripe, and b) to distinguish between the next invoice and an already paid invoice. The upcoming invoice contains the the amount of credits currently used (🤞🏻 after discounts), which can be compared with the spending limit configured.

- [x] rename GetLatestInvoice to GetUpcomingInvoice

## Related Issue(s)

Fixes #11692 

## How to test
Setup UBB in for a team and lower the spending limit to 1 or 2 credits for a simple test, then start a workspace or two to hit that limit. After a while, cannot tell it precisely, you'll need to reload the dashboard to refresh the spending limit checks. In the `server` component you'll find a log message on spending limit events, and the known dashboard notification should be visible:
Screen Shot 2022-08-23 at 16 21 48

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [x] /werft with-payment

### CODE REVIEW

**Comment by roboquat** [comment]
@AlexTugarev: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/server/ee/src/billing/billing-service.ts [hunk 1]
```diff
@@ -40,50 +44,45 @@ export class BillingService {
...
-            {},
-            attributionId,
-            startedTimeOrder as number,
-            timestampFrom,
-            timestampTo,
-        );
-        const sessions = response.getSessionsList().map((s) => UsageService.mapBilledSession(s));
-        return sessions;
+    async getUpcomingInvoice(teamId: string): Promise<GetUpcomingInvoiceResponse> {
+        const response = await this.billingServiceClientProvider.getDefault().getUpcomingInvoice(teamId);
```
Comment (AlexTugarev) [inline components/server/ee/src/billing/billing-service.ts:85]: WDYT of using `attributionId` here, and using `ParseAttributionID` on the side of `BillingService`?

Comment (geropl) [reply components/server/ee/src/billing/billing-service.ts:85]: :point_up: Thought about the same. :brain: :sparkles: :+1:

**Review by easyCZ — COMMENTED** [review]
This is a great example where splitting the PR up into the following blocks would greatly help with quality of review:
1. Proto changes
2. Implement GetUpcoming rpc
3. Update Server to use it.

File: components/server/ee/src/billing/billing-service.ts (hunk 1 above)
Comment (easyCZ) [inline components/server/ee/src/billing/billing-service.ts:85]: When this rolls out, you can't guarantee that when this is executed, the `usage` component has been rolled out to a newer version and that the `getUpcomingInvoice` RPC actually exists.

In the happy case, this inconsistency won't happen, but in the bad case, where for example usage fails to start and remains on the old version, it will start failing here.

File: components/usage/pkg/stripe/stripe.go [hunk 2]
```diff
@@ -122,6 +130,38 @@ func (c *Client) updateUsageForCustomer(ctx context.Context, customer *stripe.Cu
...
+	query := fmt.Sprintf("metadata['teamId']:'%s'", teamId)
+	searchParams := &stripe.CustomerSearchParams{
+		SearchParams: stripe.SearchParams{
+			Query:   query,
+			Expand:  []*string{stripe.String("data.subscriptions")},
+			Context: ctx,
+		},
+	}
+	iter := c.sc.Customers.Search(searchParams)
+	if !iter.Next() {
```
Comment (easyCZ) [inline components/usage/pkg/stripe/stripe.go:144]: First check for errors:
```suggestion
	if iter.Error() != nil {
```

File: components/usage/pkg/stripe/stripe.go [hunk 3]
```diff
@@ -122,6 +130,38 @@ func (c *Client) updateUsageForCustomer(ctx context.Context, customer *stripe.Cu
...
+		return nil, fmt.Errorf("failed to find customer data for team %s", teamId)
+	}
+	customer := iter.Customer()
+	invoiceParams := &stripe.InvoiceParams{
+		Customer: stripe.String(customer.ID),
+	}
```
Comment (easyCZ) [inline components/usage/pkg/stripe/stripe.go:150]: What are the semantics when the search returns multiple customers? That should never happen, but we must be defensive here. I'd recommend collecting all the customers (or checking number of results), checking there's exactly one, and then returning.

File: components/usage/pkg/stripe/stripe.go [hunk 4]
```diff
@@ -122,6 +130,38 @@ func (c *Client) updateUsageForCustomer(ctx context.Context, customer *stripe.Cu
...
+	searchParams := &stripe.CustomerSearchParams{
+		SearchParams: stripe.SearchParams{
+			Query:   query,
+			Expand:  []*string{stripe.String("data.subscriptions")},
+			Context: ctx,
+		},
+	}
+	iter := c.sc.Customers.Search(searchParams)
+	if !iter.Next() {
+		return nil, fmt.Errorf("failed to find customer data for team %s", teamId)
```
Comment (easyCZ) [inline components/usage/pkg/stripe/stripe.go:145]: Worth returning a special error for this case. We want the API to return a useful error message to the client. In this case, we want to say that for a given TeamID, there's no customer in Stripe. The general error here can't be classified (or compared, aside from string comparisons).

The pattern for this is to do:

```
var CustomerNotFoundError = errors.New(...)
...

if errors.Is(err, CustomerNotFoundError) {
  return NotFound
}
```

File: components/usage/pkg/stripe/stripe.go [hunk 5]
```diff
@@ -122,6 +130,38 @@ func (c *Client) updateUsageForCustomer(ctx context.Context, customer *stripe.Cu
...
+	if err != nil {
+		return nil, fmt.Errorf("failed to fetch the upcoming invoice for customer %s", customer.ID)
+	}
+
+	return &StripeInvoice{
+		ID:             invoice.ID,
+		SubscriptionID: invoice.Subscription.ID,
+		Amount:         invoice.AmountRemaining,
+		Currency:       string(invoice.Currency),
+		Credits:        invoice.Lines.Data[0].Quantity,
```
Comment (easyCZ) [inline components/usage/pkg/stripe/stripe.go:161]: Check that Data has a 0 item, this would panic if it was empty.

File: components/usage/pkg/stripe/stripe_test.go [hunk 6]
```diff
@@ -83,3 +85,25 @@ func TestCustomerQueriesForTeamIds_MultipleQueries(t *testing.T) {
 		})
 	}
 }
+
+func TestGetUpcomingInvoice(t *testing.T) {
+	secretKey := os.Getenv("TEST_KEY_STRIPE")
+	teamId := os.Getenv("TEST_TEAM_ID")
```
Comment (easyCZ) [inline components/usage/pkg/stripe/stripe_test.go:91]: How are these injected during test runs on CI?

Comment (easyCZ) [reply components/usage/pkg/stripe/stripe_test.go:91]: If it's not gonna run most of the time on CI, does it make sense to keep it here?

File: components/usage/pkg/apiv1/billing.go [hunk 7]
```diff
@@ -58,6 +58,21 @@ func (s *BillingService) FinalizeInvoice(ctx context.Context, in *v1.FinalizeInv
 	return &v1.FinalizeInvoiceResponse{}, nil
 }
 
+func (s *BillingService) GetUpcomingInvoice(ctx context.Context, in *v1.GetUpcomingInvoiceRequest) (*v1.GetUpcomingInvoiceResponse, error) {
+	invoice, err := s.stripeClient.GetUpcomingInvoice(ctx, in.GetTeamId())
```
Comment (easyCZ) [inline components/usage/pkg/apiv1/billing.go:62]: Check that TeamID is set, return InvalidArgument if not

**Review by easyCZ — CHANGES_REQUESTED** [review]

File: components/server/ee/src/billing/billing-service.ts (hunk 1 above)
Comment (easyCZ) [reply components/server/ee/src/billing/billing-service.ts:85]: The way to fix this is to roll-out the RPC first, and only then change the behaviour on server. Alternatively, you can use a feature flag to control this also.

Comment (AlexTugarev) [reply components/server/ee/src/billing/billing-service.ts:85]: Good point! Let me thinks about where to add the feature flag. First idea is to guard the spending limit check.

Comment (easyCZ) [reply components/server/ee/src/billing/billing-service.ts:85]: Personally, I think you can achieve the same thing (with fewer extra pieces) by splitting the PR up and first landing (and deploying) the changes which introduce the RPC on the proto level, but also implement it.

File: components/usage/pkg/stripe/stripe_test.go (hunk 6 above)
Comment (AlexTugarev) [reply components/usage/pkg/stripe/stripe_test.go:91]: removing...

File: components/usage/pkg/stripe/stripe.go (hunk 3 above)
Comment (AlexTugarev) [reply components/usage/pkg/stripe/stripe.go:150]: Good point. Copied from UpdateUsage without thinking about that further.

**Comment by AlexTugarev** [comment]
GitHub, why? :-( 

> merged commit [1cd0fbf](https://github.com/gitpod-io/gitpod/commit/1cd0fbfd1d96ff1320d61cb78a31f5242ff7829e) into main

**Comment by AlexTugarev** [comment]
Reopened as https://github.com/gitpod-io/gitpod/pull/12377

**Comment by laushinka** [comment]
> GitHub, why? :-(

😢

**Comment by easyCZ** [comment]
How did this PR get merged? I'm really confused.
