### PR TITLE
[dashboard] Fixes Project URLs with dots are broken

### LINKED ISSUE #6680: Project URLs with dots are broken
Since https://github.com/gitpod-io/gitpod/pull/6596 project URLs including dots are broken. 

### How to reproduce
1. create a repo with a dot in its name (e.g. "foo.bar")
2. add that repo as a new project to a team 
3. navigate to `/t/acme/foo.bar` and see it's redirected to `/#t/acme/foo.bar`

### Possible solution
Change the regex from the mentioned PR to match `github.com` and `gitlab.com` URLs explicitly.

cc. @iQQBot

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

Fixes Project URLs with dots are broken

## Related Issue(s)

Fixes #6680

## How to test

1. create a repo with a dot in its name (e.g. "foo.bar")
2. add that repo as a new project to a team
3. navigate to /t/acme/foo.bar/workspaces and see it's not redirected to /#t/acme/foo.bar/workspaces

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#6680*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by laushinka** [comment]
@AlexTugarev I was testing this but when I tested prod, I don't find that it goes to `#t/...`. I've also communicated with @iQQBot but wanted to make sure that I'm understanding the issue correctly?

File: components/dashboard/src/App.tsx [hunk 1]
```diff
@@ -371,7 +371,7 @@ function App() {
         toRender = <CreateWorkspace contextUrl={hash} />;
     } else if (isWsStart) {
         toRender = <StartWorkspace workspaceId={hash} />;
-    } else if (/.+?\..+?\/.+?/i.test(window.location.pathname)) {
+    } else if (/^\/[^\/]+?\.[^\/]+?\/.+?/i.test(window.location.pathname)) {
```
Comment (AlexTugarev) [inline components/dashboard/src/App.tsx:374]: @iQQBot, I think it would be less error-prone to test if the `pathname` starts with either `github.com/` or `gitlab.com/`. that's also what we used to have in nginx ages ago and are now trying to replicate in dashboard code.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **alextugarev** after the PR has been reviewed.

Associated issue: *#6680*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
Thanks for this Pull Request @iQQBot!

> 3. navigate to /t/acme/foo.bar/workspaces and see it's not redirected to /#t/acme/foo.bar/workspaces

Whoa, I somehow missed this change. Since when do we have /#t/acme/foo.bar/workspaces ? And why?

I don't seem to have this behavior in production (either with or without dot):

- https://gitpod.io/t/gitpod/gitpod/workspaces doesn't redirect to https://gitpod.io/#t/gitpod/gitpod/workspaces
- https://gitpod.io/t/test-jan/gitpod.test/workspaces also doesn't redirect to https://gitpod.io/#t/test-jan/gitpod.test/workspaces

And, personally, I much prefer the URLs without the "#". I was already quite sad when we added this random-looking `/t` prefix (`/gitpod/gitpod` looks much "cleaner" than `/t/gitpod/gitpod`), and adding yet another special trick to these URLs would feel very awkward.

For example, imagine if https://github.com/gitpod-io/gitpod was something like https://github.com/?t=gitpod-io#gitpod instead 😅

**Comment by jankeromnes** [comment]
> in prod, direct open https://gitpod.io/t/test-jan/gitpod.test/workspaces will redirect to https://gitpod.io/#t/test-jan/gitpod.test/workspaces which is not we expected

Aha, indeed:

Screenshot 2021-11-19 at 16 58 44

I see now -- you're actually removing this accidental redirection, not adding it... 😅

Thanks a lot, and so sorry for the noise! 🙏

**Comment by AlexTugarev** [comment]
/lgtm 

thanks! it works as advertised

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 621e82838eea581af2ff836355e5e9a03ebb2d42</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6683#issuecomment-975328790" title="LGTM">AlexTugarev</a>*

Associated issue: *#6680*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
