### PR TITLE
[server] IAM: Report missing session info as client error

### LINKED ISSUE #15175: Login SLO should identify user/system errors
### Bug description
When we fail to authenticate with a provider, we increment a login counter. In this case, we do not differentiate between user and system errors which results in us being paged when invalid arguments are supplied.

### Steps to reproduce
https://gitpod.slack.com/archives/C04DGADN3GX

CC @geropl for more details

### PR DESCRIPTION
**Pull request by geropl**
## Description
The intention here is to make our reporting and alerting more precise, as mentioned in #15175 .

## Related Issue(s)

Fixes #15175

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

File: components/server/src/prometheus-metrics.ts [hunk 1]
```diff
@@ -30,7 +30,15 @@ const loginCounter = new prometheusClient.Counter({
...
 });
 
-export function increaseLoginCounter(status: string, auth_host: string) {
+type LoginCounterStatus =
+    // The login attempt failed due to a system error (picked up by alerts)
+    | "failed"
+    // The login attempt succeeded
+    | "succeeded"
+    // The login attempt failed, because the client failed to provide complete session information, for instance.
+    | "failed_client";
```
Comment (easyCZ) [inline components/server/src/prometheus-metrics.ts:39]: `user_error`? Feels like it's inventing a new terminology

**Review by easyCZ — APPROVED** [review]
LGTM % comment on status name

/hold if you want to make changes

File: components/server/src/prometheus-metrics.ts (hunk 1 above)
Comment (geropl) [reply components/server/src/prometheus-metrics.ts:39]: I started out with user, but I felt wrong because we're still before the login phase. This is more about the technical level and the client behaving correctly.

Comment (easyCZ) [reply components/server/src/prometheus-metrics.ts:39]: How is the client behaving correctly? In this case, they supplied the wrong auth flow so it's an Invalid Argument - Category of User Errors.
