### PR TITLE
Remove the PVC object if the workspace pod is never been ready

### LINKED ISSUE #11635: Remove the PVC object if the workspace pod is never been ready
### Bug description

We found that in some scenarios (eg, the workspace pod in ErrImagePull), the workspace pod never goes into the Running state.
After that, the workspace is stopped, but the PVC object doesn't be deleted.

### Steps to reproduce

No idea, but I saw it in workspace preview that the workspace pod is in ErrImagePull state and then terminating state.

image

After that, the PVC is orphaned, and we don't have to create VolumeSnapshot object since this workspace doesn't have to take backup.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by jenting**
## Description

Remove the PVC object if the workspace pod is never been ready; we still go through the stopping phase even if the workspace is not ready. However, we don't perform backup but we just remove the finalizer in the end (and remove the PVC object if it existed).

## Related Issue(s)

Fixes #11635

## How to test

I have no idea how to make the workspace pod has never been in a ready state. 🤔 
But you could use this cluster for testing this PR https://jenting-10531.preview.gitpod-dev.com/workspaces, and open the workspace ID `gitpodio-templatenix-kzpw34u`. This workspace always hits the ErrImagePull error which belongs to the workspace pod that has never been in a ready state.

image
image

## Release Notes

```release-note
None
```

## Documentation

None

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

File: components/ws-manager/pkg/manager/status.go [hunk 1]
```diff
@@ -354,11 +354,6 @@ func (m *Manager) extractStatusFromPod(result *api.WorkspaceStatus, wso workspac
 			// While the pod is being deleted we do not care or want to know about any failure state.
 			// If the pod got stopped because it failed we will have sent out a Stopping status with a "failure"
 			result.Conditions.Failed = ""
-		} else {
-			if _, ok := pod.Annotations[workspaceNeverReadyAnnotation]; ok {
```
Comment (sagor999) [inline components/ws-manager/pkg/manager/status.go:358]: why this part is being removed?

Comment (jenting) [reply components/ws-manager/pkg/manager/status.go:358]: Because I think if the workspace pod is **never ready**, it still needs to go through the [Stopping](https://github.com/gitpod-io/gitpod/blob/093e8c6586183660a4bdb9f218e4afd12ca1ad9e/components/ws-manager/pkg/manager/monitor.go#L430) phase to do extra logic (e.g.: resource clean up). The idea is like the Kubernetes controller reconcile loop, and we do extra logic if the resource is Terminating with the finalizer protected, and then remove the finalizer.

From my testing, the scenario ErrImagePull makes the `status.Conditions.Failed != ""`, so the annotation `workspaceFailedBeforeStoppingAnnotation` be added.
https://github.com/gitpod-io/gitpod/blob/093e8c6586183660a4bdb9f218e4afd12ca1ad9e/components/ws-manager/pkg/manager/monitor.go#L333-L341

During the workspace pod in the Stopping state, it contains the annotation `workspaceFailedBeforeStoppingAnnotation` and `workspaceNeverReadyAnnotation`.
https://github.com/gitpod-io/gitpod/blob/093e8c6586183660a4bdb9f218e4afd12ca1ad9e/components/ws-manager/pkg/manager/monitor.go#L487-L501

Comment (jenting) [reply components/ws-manager/pkg/manager/status.go:358]: @utam0k
Do you know how to simulate the workspacekit faiI?
I want to check for this PR changes, would it break your previous contribution #10085.

Comment (sagor999) [reply components/ws-manager/pkg/manager/status.go:358]: Ah, it makes sense then.
Only concern is to do some extra testing, just to make sure there is no code that was made on the assumption of this code existing. 
I think you already tested regular workspaces, can you also test prebuilds and image builds? Just to be extra safe.

File: components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden [hunk 2]
```diff
@@ -20,7 +20,7 @@
             },
             "class": "default"
         },
-        "phase": 6,
+        "phase": 5,
```
Comment (sagor999) [inline components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden:23]: Slightly concerned over this test case change. It shows that phase would be potentially stuck in "stopping", instead of being "stopped". We might have a regression here where some workspaces would not stop correctly?

**Review by sagor999 — CHANGES_REQUESTED** [review]
I like this change :rocket: but asking to do a bit more testing to verify nothing else would break. Left comments.

File: components/ws-manager/pkg/manager/status.go (hunk 1 above)
Comment (utam0k) [reply components/ws-manager/pkg/manager/status.go:354]: @jenting 
- Make this time short
     https://github.com/gitpod-io/gitpod/blob/90b8032d1c78e8d21549dbd5a01eacf7d056d860/components/workspacekit/cmd/rings.go#L971
- Change this socket file name
    https://github.com/gitpod-io/gitpod/blob/90b8032d1c78e8d21549dbd5a01eacf7d056d860/components/ws-daemon/pkg/iws/iws.go#L156

Comment (jenting) [reply components/ws-manager/pkg/manager/status.go:354]: Thank you @sagor999 for the suggestion and @utam0k for the hack way.

- prebuild
image
image
- image build
image
image

File: components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden (hunk 2 above)
Comment (jenting) [reply components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden:23]: 🤔 I need to double check the `status_workspace_startup_failed.json`.
I just ran the golden file update `go test ./... -update -force`.

Comment (jenting) [reply components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden:23]: Okay, the root cause is that the status test tests the output of the function [getWorkspaceStatus](https://github.com/gitpod-io/gitpod/blob/77d57bcb0a08d881070291d0ba8cfa0a8b45fa83/components/ws-manager/pkg/manager/status_test.go#L114) matches the golden file or not, and only executes _once_.

Since we remove changing the state at [here](https://github.com/gitpod-io/gitpod/blob/347af9bff0b870590f4da5b8df49a98b7297800b/components/ws-manager/pkg/manager/status.go#L352-L358). Therefore, the function output of the `phase` field would be `stopping`, not `stopped`.

However, for this case, the code goes into [here](https://github.com/gitpod-io/gitpod/blob/77d57bcb0a08d881070291d0ba8cfa0a8b45fa83/components/ws-manager/pkg/manager/monitor.go#L489-L502), removing the finalizer, and reenter into the `getWorkspaceStatus` at [here](https://github.com/gitpod-io/gitpod/blob/77d57bcb0a08d881070291d0ba8cfa0a8b45fa83/components/ws-manager/pkg/manager/status.go#L371). In the end, the phase would be `stopped`, that's the server receives final state.

File: components/ws-manager/pkg/manager/status.go (hunk 1 above)
Comment (sagor999) [reply components/ws-manager/pkg/manager/status.go:354]: I am confused. Why those screenshots show errors? 
I would have expected that prebuilds\imagebuild work with this change? Or am I misreading something here?

Comment (sagor999) [reply components/ws-manager/pkg/manager/status.go:354]: Or is this testing workspacekit failure?

File: components/ws-manager/pkg/manager/monitor.go [hunk 3]
```diff
@@ -498,6 +498,11 @@ func actOnPodEvent(ctx context.Context, m actingManager, manager *Manager, statu
 					}
 				}
 
+				// delete PVC because the workspace pod is never ready
+				if err = manager.deleteWorkspacePVC(ctx, pod.Name); err != nil {
+					log.Error(err)
```
Comment (sagor999) [inline components/ws-manager/pkg/manager/monitor.go:503]: can you change this back to WithError and provide a short blurb that error is due to failure to delete workspace pvc? otherwise it will be hard to understand where error might be getting logged and coming from.

File: components/ws-manager/pkg/manager/monitor.go [hunk 4]
```diff
@@ -1183,16 +1188,10 @@ func (m *Monitor) finalizeWorkspaceContent(ctx context.Context, wso *workspaceOb
...
-							Name:      pvcName,
-							Namespace: m.manager.Config.Namespace,
-						},
-					},
-				)
-				if pvcErr != nil && !k8serr.IsNotFound(pvcErr) {
-					log.WithError(pvcErr).Errorf("failed to delete pvc `%s`", pvcName)
+				err = m.manager.deleteWorkspacePVC(ctx, pvcName)
+				if err != nil {
+					log.Error(err)
```
Comment (sagor999) [inline components/ws-manager/pkg/manager/monitor.go:1193]: same here

File: components/ws-manager/pkg/manager/status.go (hunk 1 above)
Comment (jenting) [reply components/ws-manager/pkg/manager/status.go:354]: > Or is this testing workspacekit failure? 

Sport for missing add the context.

Yes, I was testing the workspacekit failure against regular, prebuild, and imagebuild cases, verify that the workspace pod is able to be terminated and removed, and also the pod phased is stopped in the end.

File: components/ws-manager/pkg/manager/monitor.go (hunk 3 above)
Comment (jenting) [reply components/ws-manager/pkg/manager/monitor.go:503]: Because if the error happens, the error message from the `deleteWorkspacePVC` would be `return xerrors.Errorf("cannot delete workspace pvc: %w", err)`. And I think it contains enough information. WDYT?

**Review by sagor999 — APPROVED** [review]
🚀
