### PR TITLE
[pvc] potential workaround for mount volume failure

### LINKED ISSUE #13353: [PVC] loadgen testing Pod can't mount Volume
### Bug description

Running the loadgen test with PVC feature flag, some of the pods can't mount the volume
We ran the loadgen test twice
- 1st round: 1 of 100 workspaces can't be up
- 2nd round: 16 of 100 workspaces can't be up

The pod event log
```console
  Warning  FailedMount             21m (x25 over 56m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-b5d1cab4-5261-4ad0-8fc3-fb87f773558c" : rpc error: code = Internal desc = Error when getting device path: rpc error: code = Internal desc = error verifying GCE PD ("pvc-b5d1cab4-5261-4ad0-8fc3-fb87f773558c") is attached: failed to find and re-link disk pvc-b5d1cab4-5261-4ad0-8fc3-fb87f773558c with udevadm after retrying for 3s: failed to trigger udevadm fix of non existent disk for "pvc-b5d1cab4-5261-4ad0-8fc3-fb87f773558c": udevadm --trigger requested to fix disk pvc-b5d1cab4-5261-4ad0-8fc3-fb87f773558c but no such disk was found
  Warning  FailedMount             5m (x22 over 54m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[vol-this-workspace], unattached volumes=[vol-this-workspace daemon-mount]: timed out waiting for the condition
  Warning  FailedMount             54s (x5 over 23m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[vol-this-workspace], unattached volumes=[daemon-mount vol-this-workspace]: timed out waiting for the condition
```

### Steps to reproduce

https://gitpod.slack.com/archives/C02F19UUW6S/p1664263343721969?thread_ts=1664240249.861729&cid=C02F19UUW6S

Related upstream issue https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/608

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by sagor999**
## Description

Potential workaround for random mount volume failures. 

## Related Issue(s)

Fixes #13353 

## How to test

It is very hard to repro this issue.
So another way to test this PR is to ensure opening workspace works. 

## Release Notes

```release-note
none
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by Furisto — APPROVED** [review]

File: components/ws-manager/pkg/manager/manager.go [hunk 1]
```diff
@@ -671,6 +671,12 @@ func podRunning(clientset client.Client, podName, namespace string) wait.Conditi
 					return true, nil
 				}
 			}
+			// if we failed to mount volume, we need to re-create the pod
+			// ref: https://github.com/gitpod-io/gitpod/issues/13353
+			// ref: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/608
+			if strings.Contains(pod.Status.Reason, "MountVolume.MountDevice failed for volume") {
```
Comment (jenting) [inline components/ws-manager/pkg/manager/manager.go:677]: Could we have a log when we-manager detects the issue happens? So we could know the number of times we hit this issue.

Comment (sagor999) [reply components/ws-manager/pkg/manager/manager.go:677]: We already have it. On line 361.

Comment (jenting) [reply components/ws-manager/pkg/manager/manager.go:677]: Since we haven't reproduced it yet, and also we did not dump the pod YAML manifest when the last time Toru was able to reproduce. I worried that the ws-manager did not recreate the pod because one of the conditions mismatch
https://github.com/gitpod-io/gitpod/blob/e3d962295e9529d3c40bce0008e1e08295f0dc05/components/ws-manager/pkg/manager/manager.go#L703-L707
