### PR TITLE
[bridge] Marks stuck stopping and pending instances as stopped

### LINKED ISSUE #11397: workspaces which cannot be scheduled to a cluster get stuck in Pending
### Bug description

Workspaces which cannot be scheduled to a cluster get stuck in Pending.

### Steps to reproduce

In a preview environment, `kubectl cordon` the node. Try starting a workspace. It'll stay stuck in Pending for-ev-er!

### Workspace affected

n/a

### Expected behavior

The workspace should fail, and land in a permanent Failed phase

### Example repository

n/a

### Anything else?

This becomes a problem when you're trying to delete a cluster, because `ws-manager-bridge` reports that there are still active workspaces in the database for the cluster, even though there are no workspace pods in the governed workspace cluster.

This prevented the delete of `us53` (which was empty, and had no workspace clusters), until we ran the following queries:

```sql
-- find pending workspaces that aren't really pending
SELECT dbwi.id
FROM gitpod.d_b_workspace dbw  
inner join gitpod.d_b_workspace_instance dbwi 
on dbw.id = dbwi.workspaceId  
WHERE 
dbwi.phasePersisted not in ('stopped','failed') 
# change to match a region you're interested in
and dbwi.region = 'us53'
ORDER by dbwi.creationTime asc
;

-- force stop the pending workspaces
UPDATE gitpod.d_b_workspace_instance AS wsi
SET
			wsi.stoppedTime = IF(wsi.startedTime = '', wsi.creationTime, wsi.startedTime),
			wsi.stoppingTime = IF(wsi.startedTime = '', wsi.creationTime, wsi.startedTime),
			wsi.phasePersisted = 'stopped',			
			wsi.status = '{"phase": "stopped", "conditions": {}}'
WHERE wsi.id IN ('fb52614b-927b-4412-b583-dd3cc7bc3087',
'04eedb5b-1f35-4e4b-a8b3-56ea13c0f2dd',
'9b3d3928-59dd-46f0-9876-cc2bab905a2e',
'261bbde5-100f-4a19-8085-125ef82a0f0a',
'7878cc2a-544e-4f24-82ee-62a24c4f9c34',
'5dda17bf-1fe9-4cc6-b5ae-82aa6603049c',
'ad40bce6-a74c-47a9-b9a4-d9490afbfd41',
'028d826e-49b2-45ce-b829-8b4f693e93d3',
'99b74f2b-0a49-45c6-9c59-c4339a6dcb48',
'3695365a-0b4c-4df2-96f3-700598fe3baf')
;
```

- [ ] Delete [this page](https://www.notion.so/gitpod/Force-stop-bogus-active-workspaces-to-help-delete-a-workspace-cluster-a994631574564fa3aa695f5a7fc76856) once resolved

### PR DESCRIPTION
**Pull request by laushinka**
## Description
After validating through logging of the past two weeks (since 15.09.2022), this change marks `stopping` and `pending` states after the timeout duration to be stopped. 
Findings from the [logging](https://github.com/gitpod-io/gitpod/pull/12902):
1. Most of the logs were for `stopping` state, and we could not find a clear explanation whether they were cases that we want to be stopped. Instances could be in a `stopping` state for longer than we expect (in the previous PR it was 10 seconds after `stoppingTime`) because instances with a big back-up size can take longer.
2. A lot of the `pending` states were stuck in that state for days, and we do want them stopped.
3. We found a few `creating` states that ended up running, and these we should not stop. 

We are still unsure why these instances end up in these states. Therefore we:
1. Will focus on only stopping stuck instances in `pending` and `stopping` states, and after the timeout duration. These we know for sure we want stopped.
2. To understand the why, we will create an issue. 

## Related Issue(s)

Fixes #11397

## How to test
1. `kubectl cordon` the preview node
2. Run a workspace. It should be stuck in pending.
3. Change the creationTime in `d_b_workspace_instance` to 1 hour before (or wait 1 hour). It should be marked as stopped with a message `"Stopped by ws-manager-bridge. Previously in phase pending`.
4. Once done, `kubectl uncordon` the node, otherwise builds will fail because the node can't be scheduled.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@laushinka: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/ws-manager-bridge/src/bridge.ts [hunk 1]
```diff
@@ -508,36 +514,33 @@ export class WorkspaceManagerBridge implements Disposable {
...
-                        region: instance.region,
-                    });
+
+                // When ws-manager is not aware of the following instances outside of the timeout duration,
+                // they should be marked as stopped.
+                // pending states timeout is 1 hour after creationTime.
+                // stopping states timeout is 1 hour after stoppingTime.
+                if (
+                    (phase === "pending" &&
+                        durationLongerThanSeconds(Date.parse(instance.creationTime), maxInstanceDuration)) ||
```
Comment (geropl) [inline components/ws-manager-bridge/src/bridge.ts:524]: Would be great to have separate timeouts per phase. This is something that does change, even if it's very rare.

Comment (laushinka) [reply components/ws-manager-bridge/src/bridge.ts:524]: Aha, sure. So for now they would be something like `maxPendingInstanceDuration` and `maxStoppingInstanceDuration`? And both would be 3600 seconds for now.

Comment (geropl) [reply components/ws-manager-bridge/src/bridge.ts:524]: Why not continue the pattern [here](https://github.com/gitpod-io/gitpod/pull/13350/files#diff-679f493f2181427cc1a110c353e46be2ac044f9f0648b7b89a84b0d0958101d6R31-R33): `pendingPhaseSeconds` and `stoppingPhaseSeconds`? Not caring so much about the particular names, more about consistency. :lotus_position:

File: components/ws-manager-bridge/src/bridge.ts [hunk 2]
```diff
@@ -508,36 +514,33 @@ export class WorkspaceManagerBridge implements Disposable {
...
-                        creationTime: instance.creationTime,
-                        region: instance.region,
-                    });
+
+                // When ws-manager is not aware of the following instances outside of the timeout duration,
+                // they should be marked as stopped.
+                // pending states timeout is 1 hour after creationTime.
+                // stopping states timeout is 1 hour after stoppingTime.
+                if (
+                    (phase === "pending" &&
```
Comment (geropl) [inline components/ws-manager-bridge/src/bridge.ts:523]: The `running` case is missing, right? Or am I misinterpreting the diff/indentation? :see_no_evil:

Comment (laushinka) [reply components/ws-manager-bridge/src/bridge.ts:523]: I guess I misinterpreted our sync yesterday 🤔 I thought we would only focus on `pending` and `stopping`, also because we didn't find any of the other states (other than `creating`) in the logs. Do you think the other states are also still relevant?

File: components/ws-manager-bridge/src/bridge.ts [hunk 3]
```diff
@@ -508,36 +516,33 @@ export class WorkspaceManagerBridge implements Disposable {
...
+                        { instanceId, workspaceId: instance.workspaceId },
+                        "Database says the instance is running, but ws-man does not know about it. Marking as stopped in database.",
+                        { installation },
+                        { phase },
+                    );
+                    await this.markWorkspaceInstanceAsStopped(ctx, ri, new Date());
                     continue;
                 }
 
-                log.info(
```
Comment (geropl) [inline components/ws-manager-bridge/src/bridge.ts:536]: @laushinka Sorry for the long turnaround. I like the new layout of the loop! But we need it to include this case: If an instance in `runningInstancesIdx` is `running`, we still need to stop it unconditionally, as we do it at the moment.

File: components/ws-manager-bridge/src/bridge.ts [hunk 4]
```diff
@@ -508,36 +516,33 @@ export class WorkspaceManagerBridge implements Disposable {
...
+                if (
+                    (phase === "pending" &&
+                        durationLongerThanSeconds(Date.parse(instance.creationTime), pendingPhaseSeconds)) ||
+                    (phase === "stopping" &&
+                        instance.stoppingTime &&
+                        durationLongerThanSeconds(Date.parse(instance.stoppingTime), stoppingPhaseSeconds))
+                ) {
+                    log.info(
+                        { instanceId, workspaceId: instance.workspaceId },
+                        "Database says the instance is running, but ws-man does not know about it. Marking as stopped in database.",
```
Comment (geropl) [inline components/ws-manager-bridge/src/bridge.ts:533]: `is running` is potentially misleading here. What do you think about `is present`?

File: components/ws-manager-bridge/src/bridge.ts [hunk 5]
```diff
@@ -508,36 +516,33 @@ export class WorkspaceManagerBridge implements Disposable {
...
+                        { installation },
```
Comment (geropl) [inline components/ws-manager-bridge/src/bridge.ts:534]:
```suggestion
                        { installation, phase },
```

Next line can be dropped, then.

File: components/ws-manager-bridge/src/config.ts [hunk 6]
```diff
@@ -31,6 +31,8 @@ export interface Configuration {
         preparingPhaseSeconds: number;
         buildingPhaseSeconds: number;
         unknownPhaseSeconds: number;
+        pendingPhaseSeconds: number;
```
Comment (geropl) [inline components/ws-manager-bridge/src/config.ts:34]: :+1:

File: components/ws-manager-bridge/src/bridge.ts (hunk 4 above)
Comment (laushinka) [reply components/ws-manager-bridge/src/bridge.ts:533]: Ah yes, good point. Feels like there could be a better one than "is present", but I can't come up with a better one and it's definitely better than "is running". Let's go with `is present`!

**Comment by geropl** [comment]
Code LGTM, thx @laushinka ! :pray: 
Will test now...

**Comment by laushinka** [comment]
> Code LGTM, thx @laushinka ! 🙏 Will test now...

@geropl Cool! Let me know if the steps I described were helpful, or if you test in a different way 🙏🏽

**Review by geropl — APPROVED** [review]
Code LGTM, tested and works as expected! :1st_place_medal:
