### PR TITLE
[ws-manager] fix workspace status flipping pending to deleted 

### LINKED ISSUE #8703: Accessing server API at gitpod.io from within workspaces might fail sometimes
### Bug description

Sometimes, when you start a workspace ~~around the same time as a Gitpod WebApp deployment (typically on Tuesdays and Thursdays around ~08:30 UTC)~~, it can get into a bad state.

Symptoms:
- The IDE theme is always Light (quite noticeable if you normally use Dark theme)
- The Git credential-helper doesn't work (e.g. if you try to push to a new branch, it will ask you for username and password)
- Some Gitpod features are missing (e.g. if you look for `Gitpod: Stop Workspace` in `F1`, you won't find it)

The only solution is to stop the workspace (e.g. from your workspaces list) and restart it.

Screenshot 2022-03-10 at 09 29 12

### Steps to reproduce

1. Start a workspace ~~on a Tuesday or Thursday around ~08:30 UTC~~
2. Try to push something to a branch
3. It will ask for username and password

### Workspace affected

gitpodio-gitpod-ykfphcb8pwd

### Expected behavior

1. The workspace should not land into such a bad state or require a restart

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sagor999**
## Description

Fixes an issue where workspace status can get flipped from PENDING to TERMINATED back and forth if workspace pod is stuck in pending state (can happen if we are scaling up). When this happens, ws-manager will delete the pod after 5s and try again. Deletion of the pod would trigger workspace status update to get flipped into TERMINATED state causing webapp to delete workspace token from db. 
This PR fixes this issue.

@geropl there is a small UX issue when pod is stuck in pending: it doesn't seem like there is any way to signal to stop the workspace. It will be stuck in pending with no way to stop it unless ws-manager will be able to schedule it.

## Related Issue(s)

Fixes #8703 

## How to test

Spin up workspace preview env
Start workspace and observe it starts normally
Stop workspace
Cordon the node
Start workspace again
Observe that ws-manager keeps re-creating the pod every 5s as it is stuck in pending state but dashboard will remain now on Preparing workspace phase. Also observe that ws-manager-bridge is now only getting status updates that indicate phase is pending.

## Release Notes

```release-note
[ws-manager] fix a bug when opening workspace you would be signed out from git and not able to do git commands
```

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/ws-manager/pkg/manager/manager.go [hunk 1]
```diff
@@ -200,6 +200,9 @@ func (m *Manager) StartWorkspace(ctx context.Context, req *api.StartWorkspaceReq
 	}
 	span.LogKV("event", "pod description created")
 
+	// add an annotation to the pod to signal that ws-manager will now attempt to create this pod
+	pod.Annotations[attemptingToCreatePodAnnotation] = "true"
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/manager.go:204]: this should be part of the `createDefiniteWorkspacePod` and corresponding tests (`cd pkg/manager && go test -update -force .`)

File: components/ws-manager/pkg/manager/manager.go [hunk 2]
```diff
@@ -290,6 +293,33 @@ func (m *Manager) StartWorkspace(ctx context.Context, req *api.StartWorkspaceReq
...
+		if err != nil {
+			clog.WithError(err).WithField("pod.Namespace", pod.Namespace).WithField("pod.Name", pod.Name).Error("was unable to get pod to remove annotation")
+			return err
+		}
+		delete(tempPod.Annotations, attemptingToCreatePodAnnotation)
+		err = m.Clientset.Update(ctx, &tempPod)
+		if err != nil {
+			return err
+		}
+		return nil
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/manager.go:316]: this should use `markWorkspace` instead which carries the concurrent modification retry logic

File: components/ws-manager/pkg/manager/manager.go (hunk 1 above)
Comment (sagor999) [reply components/ws-manager/pkg/manager/manager.go:204]: I disagree. :sweat_smile: 
Adding it into `createDefiniteWorkspacePod` will lose some context as to why it is added, and also this whole retry logic is a temporary workaround for OutOfMemory error. Once we have 1.23.6 k8s and confirm it is working, we might consider removing retry logic all together.
Another reason not to add this into `createDefiniteWorkspacePod` is that it is not obvious that someone has to remove that annotation when pod is created. So if that function will be used later somewhere else, it will have unexpected side effects for someone who is using it.

**Comment by sagor999** [comment]
@csweichel PTAL :pray:

**Comment by geropl** [comment]
> @geropl there is a small UX issue when pod is stuck in pending: it doesn't seem like there is any way to signal to stop the workspace. It will be stuck in pending with no way to stop it unless ws-manager will be able to schedule it.

@sagor999 Agreed, thx for hinting: Will add a note to #8274

File: components/ws-manager/pkg/manager/manager.go (hunk 1 above)
Comment (csweichel) [reply components/ws-manager/pkg/manager/manager.go:204]: I understand the intent to keep the code together - it is however a break in current style.

Today, all pod creation is covered by the very same createDefiniteWorkspacePod (CDWP) function and tests. I.e. no modifications happen outside of the initial pod struct production prior to creating it in Kubernetes. Adding this annotation outside of the regular pod creation path means we have no coverage that it's added, and we can no longer be sure that what our fixtures say will be used is what's actually used.

`createDefiniteWorkspacePod` only makes sense in the path of creating a pod, and is very unlikely to be used elsewhere.

Also, I don't think this workaround will go away any time soon. When `1.23.6` comes around, we might be able to upgrade in SaaS. But self-hosted users might face the very same problem still. IMHO this code is here to stay for a good while longer.

I have no hard feelings on this (would be ok either way), but a clear preference towards making this part of CDWP for the reasons outlined above.

Comment (sagor999) [reply components/ws-manager/pkg/manager/manager.go]: @csweichel I see your point. Fair enough, code and tests updated.

**Review by csweichel — APPROVED** [review]

**Comment by geropl** [comment]
:tada: :rocket: :pray:

**Comment by geropl** [comment]
Is there an ETA for this? I guess sometime next week?
