### PR TITLE
actually allow to select custom IDE image

### LINKED ISSUE #2477: [staging] Unable to select custom image
### Describe the bug

I am unable to select the image option on clicking it

### Steps to reproduce

1. Have custom IDE permission enabled
2. Go to settings
3. Try to select "Image" option

### Expected behavior

Able to select a custom image.

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #2477: actually allow to select custom IDE image

#### How to test

- Have custom IDE permission enabled: `update d_b_user set rolesOrPermissions = '["admin","devops","ide-settings"]';`
- Go to settings
- Try to select "Image" option
- Try to play by typing image and switching radio button. You should not get anything surprising and on reload values should be persisted.

### CODE REVIEW

**Comment by akosyakov** [comment]
@csweichel I think it would be good to add some placehoder for image, do you have something in mind which points to the pattern which shoudl be used.

File: components/dashboard/src/components/ide-settings.tsx [hunk 1]
```diff
@@ -38,47 +66,32 @@ export class IDESettings extends React.Component<IDESettingsProps> {
...
+    private fireStateChange(): void {
+        const { value, image } = this.state;
 
         const additionalData = (this.props.user.additionalData || {});
         const settings = additionalData.ideSettings || {};
         if (value === 'theia') {
             delete settings.defaultIde;
         } else if (value === 'image') {
-            settings.defaultIde = image;
+            settings.defaultIde = image || '';
```
Comment (csweichel) [inline components/dashboard/src/components/ide-settings.tsx:94]: if someone tried to start a workspace with this setting, i.e. just selected image and didn't enter an actual image, workspace starts fail without an error message.

We should add validation here to prevent this case.

**Comment by csweichel** [comment]
> @csweichel I think it would be good to add some placehoder for image, do you have something in mind which points to the pattern which shoudl be used.

We could use something that looks like a docker image reference, e.g. `index.docker.io/gitpod-io/theia-ide:latest`.
For now we don't have a minimal example custom IDE, let alone documentation of how that contract looks like (my Todo, see https://github.com/gitpod-io/gitpod/issues/2419)

File: components/dashboard/src/components/ide-settings.tsx (hunk 1 above)
Comment (akosyakov) [reply components/dashboard/src/components/ide-settings.tsx:94]: or fall back to theia alias instead?

**Comment by akosyakov** [comment]
> We could use something that looks like a docker image reference, e.g. index.docker.io/gitpod-io/theia-ide:latest.
For now we don't have a minimal example custom IDE, let alone documentation of how that contract looks like (my Todo, see #2419)

We could use our theia image in the placeholder? or it is internal secret

btw @JesterOrNot is already looking in to #2419

File: components/dashboard/src/components/ide-settings.tsx (hunk 1 above)
Comment (csweichel) [reply components/dashboard/src/components/ide-settings.tsx:94]: it didn't for me. I was able to just select image and leave it at that.
When I tried to start a workspace the startup broke - as expected.

**Comment by csweichel** [comment]
> > We could use something that looks like a docker image reference, e.g. index.docker.io/gitpod-io/theia-ide:latest.
> > For now we don't have a minimal example custom IDE, let alone documentation of how that contract looks like (my Todo, see #2419)
> 
> We could use our theia image in the placeholder? or it is internal secret

It's not a secret per se, but not something we'd want to surface either. Also, it depends on the deployment, i.e. is not a fixed value.

**Comment by akosyakov** [comment]
@csweichel I added the empty value validation and the placeholder.

**Review by csweichel — APPROVED** [review]
LGTM

**Comment by yyoncho** [comment]
Why Select custom IDE image is disabled for the public gitpod? What are the chances to have that enabled for the public gitpod?

**Comment by csweichel** [comment]
We've not made this selection public for now, because we fret it would lead to more confusion than do good. The IDE image has very particular requirements that are hard to fulfil, not intuitive and can break things in really strange ways. For example, the IDE image must be built `FROM scratch` and ideally not touch anything outside of `/ide`.

Which use-case/IDE do you have in mind?

**Comment by yyoncho** [comment]
@csweichel 

> Which use-case/IDE do you have in mind?

I am working on integration between Emacs and gitpod see https://github.com/emacs-lsp/lsp-mode/issues/2845 and 
https://github.com/emacs-lsp/lsp-gitpod . It is still a work in progress but it works fine. The issue is that I can specify the image in several ways but there is no way to specify the emacs image globally so I can just open any gitpod project using that image. This issue is one of the blockers.

 > We've not made this selection public for now, because we fret it would lead to more confusion than do good.

It will work fine for me if this is not public but accessible in a certain way. (e. g. uri param, env variable, etc).

**Comment by svenefftinge** [comment]
Hey @yyoncho, what you are trying to accomplish sounds pretty cool. I'm not an emacs user myself but if you are interested we could talk through your plans and see how Gitpod can support that and where we would need to change.
https://calendly.com/efftinge/emacs-gitpod

**Comment by yyoncho** [comment]
@svenefftinge thank you, I scheduled a meeting on Monday.
