### PR TITLE
jetbrains: launch with interactive login shell in async manner

### LINKED ISSUE #13815: JetBrains server starts without loading user's bashrc
### Objective

I ran into an issue when using PyCharm with the [workspace-full](https://hub.docker.com/r/gitpod/workspace-full).
The server-ide started without the initialization steps defined in `.bashrc`.

## Description and how to reproduce
- Launch any workspace with PyCharm and workspace-full image.
- Create a python script and run it using PyCharm's run [configuration](https://www.jetbrains.com/help/pycharm/run-debug-configuration.html).
  ```python
  import subprocess
  import os
  
  path_available_to_jb = os.getenv("PATH").split(":")
  print(list(p for p in path_available_to_jb if "java" in p))
  print(subprocess.check_output(['java', "--help"]))
  ```
- Get outputs: empty list for the first print and FileNotFoundError for the subprocess.check_output
  image

- Navigate to a terminal to print the PATH
  image

## Reasons?
Workspace-full install `java` by [sdkman](https://github.com/gitpod-io/workspace-images/blob/0d67cc6cff34711a48063c6e4e3dd441a2743a79/chunks/lang-java/Dockerfile#L24-L25).
As we can see, it makes `java` available using sdkman's initialization script which is sourced by `.bashrc`. (`.profile` also source `.bashrc`)

**How Gitpod adds IDE layers to the user's image and how the server-side ide is launched is not well documented.**

I guess the JB server started neither sourcing  `$HOME/.bashrc` nor `$HOME/.profile`. (non-interactive and non-login?)

## Workarounds
One might add the `java` path into PATH by docker `ENV` instruction. 

However, it might be common that users having some of their initialization in the `.bashrc`. I don't know if starting the JB server-ide in a `well-prepared` shell (`bash -i` or `bash -l`?) is a good idea.

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

This PR ensures:
- JB GW can try to connect to JB backend as soon as workspace content and .dotflies are initialised, before we will wait for all preparation steps to run the backend before letting a user to attempt
- JB backend is started with proper user envs, i.e. collected from the login user shell, before they were ignored

After this PR is merged we should try to revert work arounds for detecting JDK and retest. We should also see whether other products can detect properly other SDKs, i.e. golang for gitpod repo, rubymine ruby, pycharm python and so on. cc @felladrin @andreafalzetti 

## Related Issue(s)

fix #13815

## How to test

- Start a workspace with JB product
- Export some env var in `/etc/profile`
- Run `kill <pid-of-status>` to emulate graceful shutdown
- When JB backend is restarted like that, investigate env vars of the backend `/proc/<pid-of-backend>/environ`. It should have env var from `/etc/profile`
- Investigate logs of workplace you should see `asked IDE to terminate` meaning that JB backend was restarted gracefully via codeWithMe endpoint [[1](https://github.com/gitpod-io/gitpod/blob/8b1eff9e06a8b37ea12ef4b730fb690ea7350797/components/ide/jetbrains/image/status/main.go#L302)]

## Release Notes

```release-note
JetBrains: Start JB backend with the interactive login shell.
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

File: components/ide/jetbrains/image/status/main.go [hunk 1]
```diff
@@ -443,16 +431,46 @@ func run(launchCtx *LaunchContext) {
...
-	cmd.Env = append(cmd.Env,
-		fmt.Sprintf("IJ_HOST_CONFIG_BASE_DIR=%s", productContext.configDir),
-		fmt.Sprintf("IJ_HOST_SYSTEM_BASE_DIR=%s", productContext.systemDir),
-	)
+		// Emulate the interactive login shell to ensure that all users defined shell scripts are loaded
+		shell := os.Getenv("SHELL")
+		if shell == "" {
+			shell = "/bin/bash"
+		}
+		envCmd := exec.Command(shell, []string{"-ilc", "env"}...)
```
Comment (akosyakov) [inline components/ide/jetbrains/image/status/main.go:443]: it is better to have a custom go program which print os.Environ to avoid issues with escapes characters by using JSON

File: components/ide/jetbrains/image/status/main.go [hunk 2]
```diff
@@ -443,16 +441,44 @@ func run(launchCtx *LaunchContext) {
 	os.Exit(cmd.ProcessState.ExitCode())
 }
 
-func remoteDevServerCmd(args []string, productContext *LaunchContext) *exec.Cmd {
-	cmd := exec.Command(BackendPath+"/bin/remote-dev-server.sh", args...)
-	cmd.Env = os.Environ()
+func remoteDevServerCmd(args []string, launchCtx *LaunchContext) *exec.Cmd {
+	if launchCtx.env == nil {
+		launchCtx.env = os.Environ()
```
Comment (iQQBot) [inline components/ide/jetbrains/image/status/main.go:446]: is duplicate?

Comment (akosyakov) [reply components/ide/jetbrains/image/status/main.go:446]: We start JB backend twice `installPlugins` and then `run`

Comment (iQQBot) [reply components/ide/jetbrains/image/status/main.go:446]: I mean os.Environ() is duplicates because we fetch env from `status env` it contain everything

Comment (akosyakov) [reply components/ide/jetbrains/image/status/main.go:446]: ah, yes!

**Comment by akosyakov** [comment]
/hold

brr, I broke it trying to resolve a comment, will check tomorrow

**Comment by akosyakov** [comment]
@andreafalzetti @iQQBot @felladrin Now it is good to review.

**Comment by felladrin** [comment]
ℹ️ I'm reviewing it now!

**Review by andreafalzetti — APPROVED** [review]
Tested and works as expected! Good work 🎉 

/hold

wait for others to finish the review, feel free to unhold

**Review by felladrin — APPROVED** [review]
Worked as described! ✅ 
I've also noticed it resolved the issue of Goland and package dependencies. Now when opening GoLand, it already indexes all Go Modules! (Tested with two different Go repos)

image
image
image
