### PR TITLE
singleton SupervisorServiceClient

### LINKED ISSUE #14782: Request ideReady and contentReady twice in supervisor-frontend
### Bug description

Request ideReady and contentReady twice in supervisor-frontend

image (10)

### Steps to reproduce

- Start a workspace in Gitpod
- Open DevTool / Network tab
- Check request number

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

Makes sure that supervisor-frontend only check for ide and content readiness once.

## Related Issue(s)

fix #14782

## How to test

- Open a new window with devtools.
- In this window start a workspace with IntelliJ and check that both VS Code and IntelliJ can be opened.
- Check in devtool that we send only successful request for ide and content readiness.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by akosyakov** [comment]
@gitpod-io/engineering-ide There are many formatting changes. I guess it is because of prettier. You can ignore whitespace changes while reviewing.

File: components/supervisor/frontend/src/ide/supervisor-service-client.ts [hunk 1]
```diff
@@ -4,23 +4,32 @@
...
 
 export class SupervisorServiceClient {
-    readonly supervisorReady = this.checkReady('supervisor');
-    readonly ideReady = this.supervisorReady.then(() => this.checkReady('ide'))
-    readonly contentReady = Promise.all([
-        this.supervisorReady,
-        this.gitpodServiceClient.auth
-    ]).then(() => this.checkReady('content'));
+    private static _instance: SupervisorServiceClient | undefined;
+    static get(gitpodServiceClient: GitpodServiceClient): SupervisorServiceClient {
```
Comment (akosyakov) [inline components/supervisor/frontend/src/ide/supervisor-service-client.ts:17]: the main change is here.

**Review by mustard-mh — COMMENTED** [review]
Code LGTM, going to test it in preview env

**Review by mustard-mh — APPROVED** [review]
Tested with Browser Code and IntelliJ, both only have `ide` and `content` wait one time 🎉
