### PR TITLE
[installer] Embed helm dependencies

### LINKED ISSUE #6570: [Installer]: include Helm chart tar.gzs in binary
The downloading of the files can take ages (and sometimes fails). As the versions are locked, embed the files in the binary so they don't need to be downloaded

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR embeds the helm dependencies in the installer binaries, which makes the render process much quicker and more reliable.

## Related Issue(s)

Fixes #6570

## How to test
Run `installer render` and observe the fast render time (less than 2 seconds).

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#6570*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: installer/third_party/charts/charts.go [hunk 1]
```diff
@@ -4,13 +4,54 @@
...
+
+	// The entire chart content
+	Content *embed.FS
+
+	// Location is the location of the chart within the content
+	Location string
+
+	// AddionalFiles list files in the content filesystem that
+	// would be applied via "kubectl apply -f"
+	AddionalFiles []string
```
Comment (MrSimonEmms) [inline installer/third_party/charts/charts.go:28]: Should be `AdditionalFiles`

**Review by MrSimonEmms — COMMENTED** [review]
Fine aside from the typo

**Review by MrSimonEmms — APPROVED** [review]
/lgtm
/approve no-issue

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 319f7f434db86974309da81a57451f6f3eeb176d</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6583#pullrequestreview-799030480" title="Approved">MrSimonEmms</a>*

Associated issue: *#6570*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [MrSimonEmms]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
