### PR TITLE
[content-service] Handle err to prevent segfault

### LINKED ISSUE #4077: panic: runtime error: invalid memory address or nil pointer dereference
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xba6730]

goroutine 33971 [running]:
github.com/gitpod-io/gitpod/content-service/pkg/storage.(*PresignedGCPStorage).DeleteObject(0xc000595b80, 0xf0c258, 0xc001fc6690, 0xc0012c4200, 0x35, 0xc001fc4240, 0x0, 0x0)
	github.com/gitpod-io/gitpod/content-service/pkg/storage/gcloud.go:926 +0x8d0
github.com/gitpod-io/gitpod/content-service/pkg/service.(*WorkspaceService).DeleteWorkspace(0xc00025c1e0, 0xf0c258, 0xc001fc6660, 0xc0007dbae0, 0x0, 0x0, 0x0)
	github.com/gitpod-io/gitpod/content-service/pkg/service/workspace-service.go:78 +0x3ea
github.com/gitpod-io/gitpod/content-service/api._WorkspaceService_DeleteWorkspace_Handler.func1(0xf0c258, 0xc001fc6660, 0xd634c0, 0xc0007dbae0, 0xdf4a67, 0xd, 0xe12737, 0x30)
	github.com/gitpod-io/gitpod/content-service/api@v0.0.0-00010101000000-000000000000/workspace_grpc.pb.go:122 +0x89
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0xf0c258, 0xc001fc65a0, 0xd634c0, 0xc0007dbae0, 0xc001fc4160, 0xc001fc2888, 0x3, 0x3, 0x7ffb40468570, 0xc0007e0a20)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/tracing/opentracing/server_interceptors.go:34 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xf0c258, 0xc001fc65a0, 0xd634c0, 0xc0007dbae0, 0x30, 0xc0007dbc20, 0x7ffb402e0540, 0x20)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0xf0c258, 0xc001fc65a0, 0xd634c0, 0xc0007dbae0, 0xc001fc4160, 0xc001fc4180, 0xbad3ba, 0xd4faa0, 0xc001fc41a0, 0xc001fc4160)
	github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xb0
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xf0c258, 0xc001fc65a0, 0xd634c0, 0xc0007dbae0, 0xc000177000, 0x0, 0xc0016ecb30, 0x40e278)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0xf0c258, 0xc001fc65a0, 0xd634c0, 0xc0007dbae0, 0xc001fc4160, 0xc001fc2888, 0xc0016ecba0, 0x59dea6, 0xd6e380, 0xc001fc65a0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xd7
github.com/gitpod-io/gitpod/content-service/api._WorkspaceService_DeleteWorkspace_Handler(0xceed00, 0xc00025c1e0, 0xf0c258, 0xc001fc65a0, 0xc001fca180, 0xc0001fb230, 0xf0c258, 0xc001fc65a0, 0xc001b98b90, 0x42)
	github.com/gitpod-io/gitpod/content-service/api@v0.0.0-00010101000000-000000000000/workspace_grpc.pb.go:124 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d5a40, 0xf146d8, 0xc0005c0780, 0xc0007f4000, 0xc0001fbb00, 0x13ebbd8, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.36.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002d5a40, 0xf146d8, 0xc0005c0780, 0xc0007f4000, 0x0)
	google.golang.org/grpc@v1.36.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00024f024, 0xc0002d5a40, 0xf146d8, 0xc0005c0780, 0xc0007f4000)
	google.golang.org/grpc@v1.36.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.36.0/server.go:876 +0x1fd 
```

seen in prod 5x+ today. E.g. https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-27T09:20:16.291752749Z;query=%22content-service-6668c975cb-vcltp%22%0Aseverity%3DERROR%0Atimestamp%3D%222021-04-27T09:20:16.291752749Z%22%0AinsertId%3D%221qzr8oug3vm35z0%22;timeRange=PT3H?project=gitpod-191109

### PR DESCRIPTION
**Pull request by geropl**
Fixes #4077 .

Not sure how to test this as we have not clue what triggers this errors. But the stacktraces is straight forward.

### CODE REVIEW

File: components/content-service/pkg/storage/gcloud.go [hunk 1]
```diff
@@ -923,6 +923,10 @@ func (p *PresignedGCPStorage) DeleteObject(ctx context.Context, bucket string, q
 		if err == iterator.Done {
 			break
 		}
+		if err != nil {
+			log.WithField("bucket", bucket).WithField("object", attrs.Name).Error(err)
+			break
```
Comment (corneliusludmann) [inline components/content-service/pkg/storage/gcloud.go:928]: Should it probably return an error instead?

Comment (geropl) [reply components/content-service/pkg/storage/gcloud.go:928]: Yeah, that would be more in line with expectations.

Thinking about it, it might be nice to continue deleting, but returning the last error (if any). WDYT? @corneliusludmann

Comment (corneliusludmann) [reply components/content-service/pkg/storage/gcloud.go:928]: Trying to continue deleting sounds reasonable. However, just use break will not work:

> [...] if Next returns an error other than iterator.Done, all subsequent calls will return the same error. To continue iteration, a new `ObjectIterator` must be created.

Thus, it would be great to have some kind of re-try mechanism.

Unfortunately, we don't know which error we usually get there.

Comment (csweichel) [reply components/content-service/pkg/storage/gcloud.go:928]: then let's return. We'd need the retry mechanism either way. Just one undeleted object is one object too many.

Comment (geropl) [reply components/content-service/pkg/storage/gcloud.go]: > then let's return

Done.

Looking at the code again I noticed that the "ErrNotFound" at the bottom does not make any sense: it can never be reached. Maybe we should separate `itErr` and `err` in the `for` loop.
But I assume this is out-of-scope for now: We just want to learn what this error is.

**Review by corneliusludmann — APPROVED** [review]
Looks good so far. :+1:
