### PR TITLE
ws-manager: skip failure from terminated message

### LINKED ISSUE #12021: [ws-manager] The container could not be located when the pod was terminated
### Bug description

We have observed in production, in preview-env and integration tests an error that results in the status of the workspace being "The container could not be located when the pod was terminated". We check the related GCP log and there is no data loss happened.

### Questions

- Is "The container could not be located when the pod was deleted.  The container used to be Running" also happening?
  > Yes! Check this [GCP log](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-01-04T05:22:19.977165741Z;query=%22workspace%20failed%22%0Atimestamp%3D%222023-01-04T05:22:19.977165741Z%22%0AinsertId%3D%22domvix05xh6189z6%22;timeRange=PT3H?project=workspace-clusters).
- Is this only happening on stop? Milan's scenario seems to indicate otherwise.

### Plan

1. [x] Verify whether as it is now there is data loss when this error occurs
2. [ ] Check Milan's case to understand if it happened during the running workspace phase.

<details>
  <summary>Old description</summary>

  We try to get the status of the pod, when is not running anymore, at a time we are not sure.  [logs](https://cloudlogging.app.goo.gl/EALr6Wbfh8q4VNBS7)

Impact to the user: 
(1) the workspace is generally left in a failed state. Users can try to restart, as failed is a terminal phase.
(2) user data may be lost.

This error message(`The container could not be located when the pod was terminated`) comes from kubelet.
https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet_pods.go#L1810-L1817

Potentially related with this Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/104107

### Steps to reproduce

I don't know

### Workspace affected

_No response_

### Expected behavior

There isn't this error message in production.

### Example repository

_No response_

### Anything else?

This has been happening in `gen59`, `gen60` and `gen61`, too. [Logs.](https://cloudlogging.app.goo.gl/86UASif6LeCtkS8T9)

### Definition of done

Let's spend some time researching if this is a Kubernetes bug, or in fact could be caused by other circumstances too. Please timebox at 2 hours, after which please share results with the team in Slack, so we can socialize next steps. 

Why research? Because the workspaces impacted by this bug end with a Failed status. cc @geropl I'm not sure if a workspace ending in a failed status will negatively impact UBP...assume not, but, wanted to check.

Front logo [Front conversations](https://app.frontapp.com/open/top_3sf4a)
</details>

### PR DESCRIPTION
**Pull request by jenting**
## Description

For some reason, the pod is killed with unknown container status and no taints on the underlying node.
Therefore, we skip extracting the failure from the terminated message.

## Related Issue(s)

Fixes #12021

## How to test

Ensure the workspace integration test pass.

I ran the integration test three times
- https://werft.gitpod-dev.com/job/gitpod-custom-jenting-12021.15
- https://werft.gitpod-dev.com/job/gitpod-custom-jenting-12021.16
- https://werft.gitpod-dev.com/job/gitpod-custom-jenting-12021.17

## Release Notes

```release-note
None
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

File: components/ws-manager/pkg/manager/status.go [hunk 1]
```diff
@@ -607,15 +609,14 @@ func (m *Manager) extractFailure(wso workspaceObjects, metrics *metrics) (string
...
-				// TODO(jenting)
-				// remove the debug log after we address the issue https://github.com/gitpod-io/gitpod/issues/12021
-				log.WithField("phase", status.Phase).WithField("code", terminationState.ExitCode).WithField("reason", terminationState.Reason).Infof("reason: %s, message: %s", status.Reason, status.Message)
-				// dump the underlying node taint
-				var node corev1.Node
-				if m.Clientset != nil {
-					if err := m.Clientset.Get(context.TODO(), types.NamespacedName{Namespace: "", Name: wso.NodeName()}, &node); err == nil {
-						for _, taint := range node.Spec.Taints {
-							log.WithField("nodeName", wso.NodeName()).Infof("taint key: %v, value: %v, effect: %v, time: %v", taint.Key, taint.Value, taint.Effect, taint.TimeAdded.String())
+				if terminationState.ExitCode == containerKilledExitCode && terminationState.Reason == "ContainerStatusUnknown" {
```
Comment (utam0k) [inline components/ws-manager/pkg/manager/status.go:612]: Reaching here, has a workspace already completed backup?

Comment (jenting) [reply components/ws-manager/pkg/manager/status.go:612]: From the log we observed over the past seven days, the backup is completed `jsonPayload.conditions.finalBackupComplete=true`.

Comment (utam0k) [reply components/ws-manager/pkg/manager/status.go:612]: Before ignoring this case, should we check `finalBackupComplete`?

**Review by utam0k — APPROVED** [review]
