### PR TITLE
[installer]: fix incorrectly configured pod security policies

### LINKED ISSUE #7095: [Installer]: incorrect pod security policies
In my Terraform-build environment, I have enabled pod security policy and network config on GCP and found that there are issues with the pod security policies forbidding pod creation. Investigate and fix

Affected resources:
 - statefulset/mysql
 - statefulset/messagebus
 - daemonset/registry-facade
 - replicaset/minio-fcc44c67 
 - replicaset/server-7d44ddf94f
 - replicaset/registry-7759cf6c97 
 - replicaset/image-builder-mk3-746c88dfc 
 - replicaset/jaeger-operator-77984858bc

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

This now makes Gitpod work in a cluster with pod security policies enabled. Seems there was some missed configurations.

This does not include the work for InCluster Docker registry, see #7107

## Related Issue(s)

Fixes #7095

## How to test

Deploy to a cluster with Pod Security Policies enabled. Have tested with all combinations of incluster and external dependencies

## Release Notes

```release-note
[installer]: fix incorrectly configured pod security policies
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** and additionally assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

Associated issue: *#7095*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)**
- **[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)**
- **[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** and additionally assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

Associated issue: *#7107*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)**
- **[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)**
- **[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: installer/pkg/common/constants.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ const (
 	RegistryAuthSecret          = "builtin-registry-auth"
 	RegistryTLSCertSecret       = "builtin-registry-certs"
 	RegistryFacadeComponent     = "registry-facade"
-	RegistryFacadeServicePort   = 3000
+	RegistryFacadeServicePort   = 30000
```
Comment (MrSimonEmms) [inline installer/pkg/common/constants.go:37]: Changed value as [registry-facade/podsecuritypolicy.go](https://github.com/gitpod-io/gitpod/blob/bdcae19a962677399ed58df79028df4847fb3a65/installer/pkg/components/registry-facade/podsecuritypolicy.go#L40-L43) set to `30000-33000`. It seems that this is post-processed in SaaS/Core Dev to be in that range

Comment (kylos101) [reply installer/pkg/common/constants.go:37]: Yes, that is done with Helm now [like so](https://github.com/gitpod-io/gitpod/blob/main/.werft/build.ts#L298-L302).

File: installer/pkg/components/rabbitmq/helm.go [hunk 2]
```diff
@@ -277,6 +277,7 @@ var Helm = common.CompositeHelmFunc(
 					helm.KeyValue("rabbitmq.auth.password", password),
 					helm.KeyValue("rabbitmq.auth.existingErlangSecret", CookieSecret),
 					helm.KeyValue("rabbitmq.auth.tls.existingSecret", TLSSecret),
+					helm.KeyValue("rabbitmq.serviceAccount.name", Component),
```
Comment (kylos101) [inline installer/pkg/components/rabbitmq/helm.go:280]: I like this, this is much better than changing the component!

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7106#issuecomment-988068194" title="Approved">kylos101</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** and additionally assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

Associated issue: *#7107*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)**
- **[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)**
- **[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by geropl — APPROVED** [review]
Have not tested, but change LGTM

Please feel free to ignore [this comment](https://github.com/gitpod-io/gitpod/pull/7106/files#r764150894); I assume you already considerd that.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 1ddb68ae75214623e26b1c34775485aee0c717e5</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7106#pullrequestreview-825497300" title="Approved">geropl</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7106#issuecomment-988068194" title="Approved">kylos101</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#7107*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)**
- **[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)**
- ~~[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: installer/pkg/components/minio/objects.go [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+
+package minio
+
+import (
+	"github.com/gitpod-io/gitpod/installer/pkg/common"
+)
+
+const Component = "minio"
+
+var Objects = common.CompositeRenderFunc(
```
[the remark this answers is not in the document]
Comment (MrSimonEmms) [reply installer/pkg/components/minio/objects.go:13]: @geropl not any more. I think the old Minio-provided chart may have done, but that's been deleted so I can't check it. The Bitnami chart doesn't appear to have anything like "with roles" https://github.com/bitnami/charts/tree/master/bitnami/minio

**Comment by kylos101** [comment]
LGTM

**Comment by MrSimonEmms** [comment]
> Have not tested, but change LGTM
> 
> Please feel free to ignore [this comment](https://github.com/gitpod-io/gitpod/pull/7106/files#r764150894); I assume you already considerd that.

It's always worthwhile checking I've not done something daft. Thanks

File: installer/pkg/common/constants.go (hunk 1 above)
Comment (aledbf) [inline installer/pkg/common/constants.go:37]: that value could produce some collision (default [initial value](https://kubernetes.io/es/docs/concepts/services-networking/service/#nodeport) for node ports)

Comment (MrSimonEmms) [reply installer/pkg/common/constants.go:37]: Yes it could. @kylos101 has done some post-processing for Core Dev on daemonsets to avoid collisions as part of his Werft job. Is that the collision you're talking about?

Comment (kylos101) [reply installer/pkg/common/constants.go:37]: The range core-dev uses for [registry-facade is 30000-31000](https://github.com/gitpod-io/gitpod/blob/main/.werft/build.ts#L300). @aledbf is that the potential collision you were referring? If yes, I think we'll be okay, because this is referring registry-facade.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7106#pullrequestreview-825497300" title="Approved">geropl</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7106#issuecomment-988081218" title="LGTM">kylos101</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#7107*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)**
- **[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)**
- ~~[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: installer/pkg/common/constants.go (hunk 1 above)
Comment (aledbf) [reply installer/pkg/common/constants.go:37]: Yes. Are we doing the same post-processing on user clusters?

Comment (MrSimonEmms) [reply installer/pkg/common/constants.go:37]: No we're not. The general principle that we're working on is one deployment of Gitpod per cluster. It's not explicitly noted at the moment, but it's one that will be documented when we do the public introductory docs

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7106#pullrequestreview-825497300" title="Approved">geropl</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7106#issuecomment-988081218" title="LGTM">kylos101</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7106#issuecomment-988119230" title="Approved">MrSimonEmms</a>*

Associated issue: *#7107*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [MrSimonEmms]
- ~~[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)~~ [MrSimonEmms]
- ~~[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)~~ [MrSimonEmms]
- ~~[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
