### PR TITLE
Unshallow repo after workspace is ready

### LINKED ISSUE #6796: shallow clone breaks git rebase, gitlens, timeline and other features
### Bug description

At the same time Codespaces doing shallow clone as well, but don't have such issues. Some should investigate why it does not work nicely in Gitpod.

Creation log from a Codespace:
```
2021-11-19T08:00:15: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch ft/publish-ms-version --depth 1 ******/****** "/var/lib/docker/codespacemount/workspace/publish-extensions"
2021-11-19T08:00:16: Cloning into '/var/lib/docker/codespacemount/workspace/publish-extensions'...
2021-11-19T08:00:16: git process exited with exit code 0
2021-11-19T08:00:17: $ git -C "/var/lib/docker/codespacemount/workspace/publish-extensions" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2021-11-19T08:00:17: git process exited with exit code 0
2021-11-19T08:00:17: $ git -C "/var/lib/docker/codespacemount/workspace/publish-extensions" config --local remote..github-pr-remote true
2021-11-19T08:00:17: git process exited with exit code 0
2021-11-19T08:00:17: $ git -C "/var/lib/docker/codespacemount/workspace/publish-extensions" config --local branch..github-pr-owner-number open-vsx#publish-extensions#494
2021-11-19T08:00:17: git process exited with exit code 0
```

I noticed that Codespaces using git 2.33.0, but Gitpod is using 2.30.1 Maybe new git has some special handling.

### Steps to reproduce

Start a workspace on big repo and try to do rebase (PR with more than 20 commits will fail to rebase properly), use blame or see timeline.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Unshallows a repo automatically in the background

## Related Issue(s)

Fixes #6796

## How to test

1. Open a workspace
2. Check that after a few seconds(maybe minutes depending on the repo size) the repo has been unshallowed `git rev-parse --is-shallow-repository`

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#6796*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aledbf** [comment]
> Unshallows a repo automatically in the background

I thought this idea was rejected when I proposed it in https://github.com/gitpod-io/gitpod/pull/6464

**Comment by jeanp413** [comment]
Not sure why it was not included in the original PR but some of us (myself included) have been having [issues](https://github.com/gitpod-io/gitpod/issues/6796) with the shallow clone so we agree to unshallow the repo (codespaces also do it)

File: components/supervisor/pkg/supervisor/supervisor.go [hunk 1]
```diff
@@ -318,7 +318,12 @@ func Run(options ...RunOption) {
 			log.Debugf("unshallow of local repository took %v", time.Since(start))
 		}()
 
-		cmd := runAsGitpodUser(exec.Command("git", "fetch", "--depth", "20"))
+		var cmd *exec.Cmd
+		if cfg.isHeadless() {
+			cmd = runAsGitpodUser(exec.Command("git", "fetch", "--depth", "20"))
```
Comment (svenefftinge) [inline components/supervisor/pkg/supervisor/supervisor.go:323]: I think we can do without any fetching on prebuilds.

**Comment by svenefftinge** [comment]
> > Unshallows a repo automatically in the background
> 
> I thought this idea was rejected when I proposed it in #6464

There has been discussions around pressure on always doing unshallow right after ready. Which made us think about more complex solutions (time-based, only certain cases, etc.). Also my analyzation of codespaces seems to have been wrong, as Jean Pierre found that they indeed just always do an unshallow after start. So, I think we should do the same here now as our current approach has negative effects as mentioned by Jean Pierre.

File: components/supervisor/pkg/supervisor/supervisor.go [hunk 2]
```diff
@@ -318,7 +318,12 @@ func Run(options ...RunOption) {
...
+		} else {
+			cmd = runAsGitpodUser(exec.Command("git", "fetch", "--unshallow", "--tags"))
```
Comment (csweichel) [inline components/supervisor/pkg/supervisor/supervisor.go:325]: If we do this for all workspaces, chances are we'll be consuming considerable CPU time again at the cost of workspace startup time.

It might be useful as a stop-gap measure though.

**Comment by csweichel** [comment]
We've just merged a fix for the broken chart. Please rebase which should solve the issue

**Comment by jeanp413** [comment]
Ready for review cc @akosyakov

**Review by akosyakov — APPROVED** [review]
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7750ed822b8b487cb00897db665c9892677683a1</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6857#pullrequestreview-816458154" title="LGTM">akosyakov</a>*

Associated issue: *#6796*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
