### PR TITLE
Adjust the Workspace Start URL the in JetBrains Gateway workspaces list

### LINKED ISSUE #11284: "Connect" button on Gitpod Workspaces list in JetBrains Gateway points to a URL that may be outdated
### Bug description

"Connect" button on the side of each workspace name on the list of workspaces leads to outdated workspace URLs (e.g. `https://gitpodio-empty-z3ml0fq4itx.ws-eu51.gitpod.io/`) when it should lead to `https://gitpod.io/start/#gitpodio-empty-z3ml0fq4itx`.

image

image

In this case, the error happened because the Cluster `eu51` doesn't exist anymore. Using `https://gitpod.io/start/#` correctly leads the user to an actual cluster (`eu53` at the time of writing).

### Steps to reproduce

- Create a workspace from gitpod.io UI.
- Stop the workspace.
- Open Gitpod Workspaces list in JetBrains Gateway.
- Click the "Connect" button.
- Observe the URL opened in the browser: it's the workspace URL from the last time it was opened.

### Expected behavior

It should lead to an URL with the format `https://gitpod.io/start/#<WORKSPACE_ID>`.

### PR DESCRIPTION
**Pull request by felladrin**
## Description

Adjust the Workspace Start URL the in JetBrains Gateway workspaces list.
This is now aligned with the URL used in WebApp workspaces list.

It's aligned with the URL used in the workspaces list from Gitpod Dashboard:
https://github.com/gitpod-io/gitpod/blob/05ae248a7c4e2527dac6f23fab9ba89d9f3ac6b8/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L56-L59
https://github.com/gitpod-io/gitpod/blob/05ae248a7c4e2527dac6f23fab9ba89d9f3ac6b8/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L66-L69

## Related Issue(s)

Fixes #11284

## How to test

- Follow the instructions from [how to test it from a Pull Request](https://github.com/gitpod-io/gitpod/blob/bebfb53a007d14269d8d9383073f7bf15d4dc49c/components/ide/jetbrains/gateway-plugin/README.md#how-to-test-from-a-pull-request).
- Check if when clicking the "Connect" button from a workspace that is not running opens `https://gitpod.io/start/#<WORKSPACE_ID>` in the browser.

## Release Notes

```release-note
Fixed the Connect Button on JetBrains Gateway workspaces list to avoid opening an invalid URL in case the workspace was not running.
```

## Documentation

None.

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

File: components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt [hunk 1]
```diff
@@ -276,7 +277,7 @@ class GitpodWorkspacesView(
                                         browserLink(info.workspace.id, info.latestInstance.ideUrl)
                                     }
                                     info.workspace.context.normalizedContextURL.ifPresent {
-                                        contextUrlRow.rowComment("<a href='${it}'>${it}</a>")
+                                        contextUrlRow.rowComment("<a href='$it'>$it</a>")
```
Comment (felladrin) [inline components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt:280]: ℹ️ Updated automatically by JetBrains IntelliJ IDEA.

File: components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt [hunk 2]
```diff
@@ -286,7 +287,7 @@ class GitpodWorkspacesView(
                                         it.totalUncommitedFiles + it.totalUntrackedFiles + it.totalUnpushedCommits
                                     } ?: 0
                                     row {
-                                        info.workspace.context.ref.ifPresentOrElse({ label(it) },{ label("(detached)") })
+                                        info.workspace.context.ref.ifPresentOrElse({ label(it) }, { label("(detached)") })
```
Comment (felladrin) [inline components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt:290]: ℹ️ Updated automatically by JetBrains IntelliJ IDEA.

File: components/ide/jetbrains/gateway-plugin/README.md [hunk 3]
```diff
@@ -14,5 +14,19 @@ This project is not yet Gitpodified as testing it requires running the local Gat
 
 **Note**: Gradle should run with Java 11.
 
----
-Plugin based on the [IntelliJ Platform Plugin Template][template].
+This plugin is based on the [IntelliJ Platform Plugin Template](https://github.com/JetBrains/intellij-platform-plugin-template).
+
+## How to test from a Pull Request
```
Comment (andreafalzetti) [inline components/ide/jetbrains/gateway-plugin/README.md:19]: # 🙌
