### PR TITLE
[ws-manager] Add validation of grpc connections in the pool

### LINKED ISSUE #5763: [ws-manager] Maintains stale connections to ws-daemon
### Bug description

ws-manager might maintain connections to endpoints which are no longer valid/available, because it doesn't re-validate that connections in its pool. This causes stray error messages and memory leaks.

### Steps to reproduce

not sure

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Existing connections in the grpc pool could not be valid anymore. In the logs is possible to find errors like:
"transport: Error while dialing dial tcp 10.12.9.78:8080: i/o timeout". Reconnecting..."

Internal link https://cloudlogging.app.goo.gl/tbxez3C2b1L2Dpkj9

## Related Issue(s)

Fixes #5763

## How to test

- delete `ws-daemon` pod
- wait until next validation window (five minutes)
- check `ws-manager` log contains a `SHUTDOWN` output

```
{"component":"grpc","level":"info","message":"INFO: 2021/09/18 14:38:38 [core] Subchannel Connectivity change to TRANSIENT_FAILURE","serviceContext":{"service":"ws-manager","version":""},"severity":"INFO","time":"2021-09-18T14:38:38Z"}
{"component":"grpc","level":"info","message":"INFO: 2021/09/18 14:38:38 [core] Channel Connectivity change to TRANSIENT_FAILURE","serviceContext":{"service":"ws-manager","version":""},"severity":"INFO","time":"2021-09-18T14:38:38Z"}
{"component":"grpc","level":"info","message":"INFO: 2021/09/18 14:38:39 [core] Channel Connectivity change to SHUTDOWN","serviceContext":{"service":"ws-manager","version":""},"severity":"INFO","time":"2021-09-18T14:38:39Z"}
{"component":"grpc","level":"info","message":"INFO: 2021/09/18 14:38:39 [core] Subchannel Connectivity change to SHUTDOWN","serviceContext":{"service":"ws-manager","version":""},"severity":"INFO","time":"2021-09-18T14:38:39Z"}
``` 
 
## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-manager/pkg/manager/internal/grpcpool/pool.go [hunk 1]
```diff
@@ -27,13 +28,16 @@ type Pool struct {
 	factory     Factory
 	closed      bool
 	mu          sync.RWMutex
+
+	checkFn func(string) error
 }
 
 // New creates a new connection pool
-func New(factory Factory) *Pool {
+func New(factory Factory, checkFn func(string) error) *Pool {
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/internal/grpcpool/pool.go:36]: The connection validation function type could be a tad more explicit, e.g.
```
type ConnectionValidationFunc func(hostIP string) (valid bool)
```

`valid` would always indicate if we should keep the connection around. If the ConnectionValidationFunc needs to do error handling, it has to do this itself (e.g. log).
There's no sensible way we could do this outside the function right now, other than log ourselves.

File: components/ws-manager/pkg/manager/internal/grpcpool/pool.go [hunk 2]
```diff
@@ -98,3 +102,25 @@ func (p *Pool) Close() error {
 
 	return nil
 }
+
+// ValidateConnections check if existing connections in the pool
+// are using valid addresses and remove them from the pool if not.
+func (p *Pool) ValidateConnections() {
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/internal/grpcpool/pool.go:108]: Why not do this on every Get() call directly? This way we're not "wasting" five minutes until we identify invalid addresses.

File: components/ws-manager/pkg/manager/manager.go [hunk 3]
```diff
@@ -109,14 +109,25 @@ const (
...
 // New creates a new workspace manager
 func New(config config.Configuration, client client.Client, rawClient kubernetes.Interface, cp *layer.Provider) (*Manager, error) {
-	wsdaemonConnfactory, _ := newWssyncConnectionFactory(config)
+	wsdaemonConnfactory, err := newWssyncConnectionFactory(config)
+	if err != nil {
+		return nil, err
+	}
+
+	wsdaemonPool := grpcpool.New(wsdaemonConnfactory, checkWSDaemonEntpoint(config.Namespace, client))
+	go func() {
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/manager.go:118]: As a matter of taste, I'd have pulled the Go func and ticker into `grpcpool.New`. Makes the pool easier to use.

File: components/ws-manager/pkg/manager/manager.go [hunk 4]
```diff
@@ -1232,3 +1243,40 @@ func newWssyncConnectionFactory(managerConfig config.Configuration) (grpcpool.Fa
 		return conn, nil
 	}, nil
 }
+
+func checkWSDaemonEntpoint(namespace string, clientset client.Client) func(string) error {
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/manager.go:1247]: would a unit test for this function make sense?

File: components/ws-manager/pkg/manager/internal/grpcpool/pool.go (hunk 2 above)
Comment (aledbf) [reply components/ws-manager/pkg/manager/internal/grpcpool/pool.go:108]: I tried that but introduces some delay (up to two seconds). If that's ok I can do that

File: components/ws-manager/pkg/manager/manager.go (hunk 3 above)
Comment (aledbf) [reply components/ws-manager/pkg/manager/manager.go]: done

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

Associated issue: *#5763*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-manager/pkg/manager/internal/grpcpool/pool.go (hunk 1 above)
Comment (aledbf) [reply components/ws-manager/pkg/manager/internal/grpcpool/pool.go]: done

File: components/ws-manager/pkg/manager/manager.go (hunk 4 above)
Comment (aledbf) [reply components/ws-manager/pkg/manager/manager.go]: done

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: b5714b884c91fb872683a8f07c3625e9c6e6017b</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5756#issuecomment-923108149" title="LGTM">csweichel</a>*

Associated issue: *#5763*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-manager/pkg/manager/internal/grpcpool/pool.go [hunk 5]
```diff
@@ -98,3 +112,27 @@ func (p *Pool) Close() error {
...
+	p.mu.RLock()
+	addresses := make([]string, 0, len(p.connections))
+	for address := range p.connections {
+		addresses = append(addresses, address)
+	}
+	p.mu.RUnlock()
+
+	for _, address := range addresses {
+		found := p.checkFn(address)
+		if !found {
```
Comment (iQQBot) [inline components/ws-manager/pkg/manager/internal/grpcpool/pool.go:128]: 😂 Here it should skip the connection found in endpoints, not !found , the logic is reversed ?

Comment (iQQBot) [inline components/ws-manager/pkg/manager/internal/grpcpool/pool.go:128]: 😂 Here it should skip the connection found in endpoints, not !found , is the logic reversed ?

Comment (aledbf) [reply components/ws-manager/pkg/manager/internal/grpcpool/pool.go:128]: Yes, you are right. https://github.com/gitpod-io/gitpod/pull/5799
