### PR TITLE
  [ws-manager] fix incorrect handling of failure state for workspaces 

### LINKED ISSUE #10315: [ws-manager] workspaces failed to start
### Bug description

Tried opening workspaces for a side-project and it failed to start at least two times. 

Two errors I didn't have time to read showed up in quick succession, and the workspace stopped before it actually started. When I clicked in the "Open Workspace" button that showed up in the "Stopped" page, I got the following error: "cannot initialize workspace: cannot initialize workspace: no backup found".

### Steps to reproduce

It was happening for every workspace started, but not anymore.

### Workspace affected

atduarte-revispt-960nm6i1khz, atduarte-revispt-jsh4ofkpnyz

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sagor999**
## Description

This PR fixes two issues:
1. As described in https://github.com/gitpod-io/gitpod/issues/10315#issuecomment-1185810931 it resolves an issue of sending sometimes incorrectly to server empty failed state, even though prior to that we might have sent failure error message. This breaks opening that workspace again, as server will incorrectly assume that there was a backup created (no failure error) and will attempt to restore second workspace from backup, which will fail, thus completely breaking opening that workspace for the customer.
2. We incorrectly mark completed container as an error.  When container is stopped, it is will be in a completed state. That is not an error. 
This two fixes need to go hand in hand.
For more info, see the link above for the comment describing the issue in greater detail.

## Related Issue(s)

Fixes #10315

## How to test

Open workspace in preview env
Close it
It should close normally.

## Release Notes

```release-note
none
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by sagor999** [comment]
/hold
I would like to get input from @csweichel and @aledbf for this change, to verify that will not break some other assumptions somewhere else inside the gitpod.

File: components/ws-manager/pkg/manager/status.go [hunk 1]
```diff
@@ -591,11 +587,8 @@ func extractFailure(wso workspaceObjects) (string, *api.WorkspacePhase) {
 					return fmt.Sprintf("container %s ran with an error: exit code %d", cs.Name, terminationState.ExitCode), &phase
 				}
 			} else if terminationState.Reason == "Completed" {
-				if wso.IsWorkspaceHeadless() {
-					// default way for headless workspaces to be done
-					return "", nil
-				}
-				return fmt.Sprintf("container %s completed; containers of a workspace pod are not supposed to do that. Reason: %s", cs.Name, terminationState.Message), nil
+				// container terminated successfully - this is not a failure
```
Comment (csweichel) [inline components/ws-manager/pkg/manager/status.go:590]: The original intent with this branch was to cover the case that a regular workspace stops without being deleted. An unintentional stop, so to speak. That said, the failure mode is actually nicer if your workspace just stops compared to get getting an inactionable error message ("containers of a workspace pod are not supposed to do that" 🤷).

The `failed` condition on workspace status indeed isn't stable (but should be). ws-manager-bridge should protect us against that by not resetting that condition if it ever was set. Because we have nothing like an at-least-once delivery semantic, we might just miss the "failed" message though.

**Review by csweichel — APPROVED** [review]
I think this will do more good than harm.
We could consider adding a metric to count unintentional pod termination - either in this PR (hence the hold), or in a separate one, or not at all :) 

/hold

**Comment by sagor999** [comment]
Added metric to track unintentional stops
