### PR TITLE
[gp cli] fix gp init

### LINKED ISSUE #3975: "gp init" prints "not found" instead of opening .gitpod.yml
### Bug description

cf. https://community.gitpod.io/t/executing-gp-init-results-in-not-found-message/3303/2

`gp init` might have an issue when `code` is used as IDE.

### Steps to reproduce

run `gp init` without any flags. 
1. it creates the default `.gitpod.yml` file
2. it prints `not found`
3. nothing else happens

### Expected behavior

maybe open the created `.gitpod.yml` file?

### Example repository

any

### PR DESCRIPTION
**Pull request by svenefftinge**
Fixes `gp init`
 - opens `.gitpod.yml`
 - removes creation of a sticky `.gitpod.dockerFile`
fixes #3975

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]
Works nicely! 
Just tested with `gp init`, `gp init -d`, and `gp init -i`. It works as expected.

File: components/gitpod-cli/cmd/init.go [hunk 1]
```diff
@@ -104,18 +99,9 @@ tasks:
...
-		}
-
-		_, err = service.OpenFile(theialib.OpenFileRequest{Path: ".gitpod.yml"})
-		if err != nil {
-			log.Fatal(err)
-		}
 		if v, ok := cfg.Image.(gitpodlib.GitpodImage); ok {
 			if _, err := os.Stat(v.File); os.IsNotExist(err) {
-				if err := os.WriteFile(v.File, []byte(`FROM gitpod/workspace-full
+				if err := os.WriteFile(v.File, []byte(`FROM gitpod/workspace-base
```
Comment (AlexTugarev) [inline components/gitpod-cli/cmd/init.go:104]: Why changing this?
Maybe considering to add alternatives as comment below, wdyt?
