### PR TITLE
Wait the Guest Client to be connected to the workspace before executing "gp preview" on JetBrains IDEs.

### LINKED ISSUE #10118: [jb] gp preview fails if running from .gitpod.yml
### Bug description

See https://github.com/jenkinsci/design-library-plugin/pull/66#discussion_r876189440

The issue is that JB backend is not running yet. We should await always instead.

### Steps to reproduce

See above.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by felladrin**
## Description

Wait the Guest Client to be connected to the workspace before executing "gp preview" on JetBrains IDEs.

## Related Issue(s)

Fixes #10118

## How to test

- Access the following URL to open Jenkins Design Library in Gitpod's Preview Environment in IntelliJ IDEA:
  https://vn-10118-j8f802b11df.preview.gitpod-dev.com/#referrer:jetbrains-gateway:intellij/https://github.com/jenkinsci/design-library-plugin/tree/73f12733d95932c333ba4155521ff78b4ed40dfc
- As soon as the IDE opens, it stats building the project. Meanwhile, if you want, you can use `gp tasks attach` to attach to "Preview" task. (See the project's [.gitpod.yml](https://github.com/jenkinsci/design-library-plugin/blob/73f12733d95932c333ba4155521ff78b4ed40dfc/.gitpod.yml))
- After the build completes, port 8080 will be available, and at this moment, the IDE should ask if you want to open the browser at the address `$(gp url 8080)/jenkins/`.
    image
    image
    Note: Sometimes the project build fails with messages like `java: error reading /workspace/m2-repository/jaxen/jaxen/1.2.0/jaxen-1.2.0.jar; zip file is empty` and the only solution is to manually delete the dependency folder (`rm -rf /workspace/m2-repository/jaxen/`) and then run `mvn hpi:run` again.
- Stop the workspace and restart it. Now the build will happen pretty quickly, as all dependencies are already downloaded. So as soon as you open the workspace on IntelliJ you should see the popup asking if you want to open Jenkins URL in the browser.

## Release Notes

```release-note
Fixed a bug that was preventing "gp preview" to work in JetBrains IDEs when executed as a task in ".gitpod.yml".
```

## Documentation

None.

### CODE REVIEW

**Comment by felladrin** [comment]
I've noticed that if I stop the workspace, start it again and run `gp tasks attach` and select the `Preview` task, I always see the "500 Internal Server Error" message:
image

**Comment by felladrin** [comment]
> I've noticed that if I stop the workspace, start it again and run `gp tasks attach` and select the `Preview` task, I always see the "500 Internal Server Error" message: image

This has been fixed by the [changes on GitpodCLIService.kt](https://github.com/gitpod-io/gitpod/pull/10129/files#diff-81d1cb74ab7142c7fba14c9bb140bb6a38eedf7d9e72a5f10065b130f95d2801)

File: components/ide/jetbrains/cli/cmd/root.go [hunk 1]
```diff
@@ -15,10 +17,21 @@ var rootCmd = &cobra.Command{
...
+	waitUntilBackendPluginIsAccessible()
 	err := rootCmd.Execute()
 	if err != nil {
 		os.Exit(1)
 	}
 }
 
+func waitUntilBackendPluginIsAccessible() {
+	for {
+		resp, httpError := http.Get("http://localhost:63342/api/gitpod/cli?op=ping")
```
Comment (akosyakov) [inline components/ide/jetbrains/cli/cmd/root.go:29]: It can race no? after successful ping a client can drop and then command will fail

why don't we do a request which does not timeout and resolve await on server only?

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt [hunk 2]
```diff
@@ -46,9 +52,20 @@ class GitpodCLIService : RestService() {
             if (url.isNullOrBlank()) {
                 return "url is missing"
             }
-            return withClient(request, context) { project ->
-                BrowserUtil.browse(url, project)
+            GlobalScope.launch {
```
Comment (akosyakov) [inline components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:55]: all client based requests should await client, i.e open as well

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt [hunk 3]
```diff
@@ -46,9 +52,20 @@ class GitpodCLIService : RestService() {
...
+                val controllerClientId = getControllerClientIdAsync()
+                runInEdt {
+                    ClientId.withClientId(controllerClientId) {
+                        BrowserUtil.browse(url)
+                    }
+                }
             }
+            sendOk(request, context)
```
Comment (akosyakov) [inline components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:63]: does it really work with open --wait?

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt [hunk 4]
```diff
@@ -85,7 +102,17 @@ class GitpodCLIService : RestService() {
         }
     }
 
+    private tailrec suspend fun getControllerClientIdAsync(): ClientId? {
```
Comment (akosyakov) [inline components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:105]: we should follow logic in withClient to get last focused or opened client, why don't we poll like each 1s with it?

**Comment by akosyakov** [comment]
Should not we just change withClient that it loops till client is found and waits for 1s? It should be cancellable in case if incoming request is cancelled.

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 3 above)
Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:63]: I think we should look into "gp open" in another PR, otherwise the "How to Test" section will become gigantic.

We also need another repo to test, cause Jenkins doesn't use "gp open" in their .gitpod.yml tasks.

(I suspect we don't need to change the "gp open" command as the file can be opened on the backend before the Thin Client connects. But we really need to investigate and confirm it.)

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 2 above)
Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:55]: Cross-posting: https://github.com/gitpod-io/gitpod/pull/10129#discussion_r881477632

File: components/ide/jetbrains/cli/cmd/root.go (hunk 1 above)
Comment (akosyakov) [reply components/ide/jetbrains/cli/cmd/root.go:29]: adding port as a parameter makes sense for testing, you don't need prev env for that

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 3 above)
Comment (akosyakov) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:63]: There are only 3 scenarios:
- open
- open --wait
- preview

I don't think we need a special handling for each but one holistic solution about how to wait for a client.

Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:63]: Got it.

I'll create a test-repo that has all those command in gitpod-tasks and use in place of Jenkins. Should also allow us to test the PR faster.

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 4 above)
Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt]: Updated!

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 3 above)
Comment (akosyakov) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt]: To make sure you are trying to open files within project? 
There is a bug that it is not possible to open files outside of the project.

File: components/ide/jetbrains/cli/cmd/root.go (hunk 1 above)
Comment (felladrin) [reply components/ide/jetbrains/cli/cmd/root.go]: Added the support for it to work on Dev Server.
I've also added one line to `launch-dev-server.sh`.

File: components/ide/jetbrains/backend-plugin/launch-dev-server.sh [hunk 5]
```diff
@@ -39,4 +39,7 @@ export IJ_HOST_SYSTEM_BASE_DIR=/workspace/.cache/JetBrains
 # Enable host status endpoint
 export CWM_HOST_STATUS_OVER_HTTP_TOKEN=gitpod
 
-$TEST_BACKEND_DIR/bin/remote-dev-server.sh run $TEST_DIR
\ No newline at end of file
+# Build and move ide-cli to its respective place.
+(cd ../cli && go build && mv cli /ide-desktop/bin/idea-cli)
```
Comment (akosyakov) [inline components/ide/jetbrains/backend-plugin/launch-dev-server.sh:43]: why not update PATH instead?

Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/launch-dev-server.sh:43]: 💡 Good idea!
I'll update it.

I'll move it to `/ide-desktop/bin/idea-cli-dev` and then update the PATH, just for the file don't be listed as a newly-added-file-ready-to-commit to git.

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 3 above)
Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt]: Finally fixed the "gp open --wait" 🎉
Needed to wrap it with `ApplicationManager.getApplication().executeOnPooledThread`.

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt [hunk 6]
```diff
@@ -53,22 +54,31 @@ class GitpodCLIService : RestService() {
...
+        } else {
+            Thread.sleep(1000L)
+            getClientSessionAsync()
         }
-        ClientId.withClientId(session.clientId) {
-            action(project)
+    }
+
+    private fun withClient(request: FullHttpRequest, context: ChannelHandlerContext, action: (project: Project?) -> Unit): String? {
+        ApplicationManager.getApplication().executeOnPooledThread {
```
Comment (akosyakov) [inline components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:75]: @felladrin Could you clarify what it does and why it is necessary please? 🙏

**Comment by akosyakov** [comment]
@felladrin open --wait still does not work for me

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt [hunk 7]
```diff
@@ -53,22 +54,31 @@ class GitpodCLIService : RestService() {
...
+            val session = getClientSessionAsync()
+            ClientId.withClientId(session.clientId) {
+                action(getLastFocusedOrOpenedProject())
```
Comment (akosyakov) [inline components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt:78]: you should pass here a project from getClientSessionAsync

**Comment by felladrin** [comment]
> @felladrin open --wait still does not work for me
> 
> I tried to perform `git rebase -i origin/master` and cli hangs for me forever.

Seems to be an issue with JetBrains Remote Development, cause we need to explicit click "Release" (in the editor) for it to detect that the file was closed/release. Closing the file tab is not working.

image

Let me confirm it with JetBrains team.

File: components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt (hunk 7 above)
Comment (felladrin) [reply components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt]: Updated!

File: components/ide/jetbrains/cli/cmd/root.go [hunk 8]
```diff
@@ -21,4 +25,16 @@ func Execute() {
 	}
 }
 
+func getCliApiUrl() *url.URL {
+	var backendPort = 63342
+	if _, fileStatError := os.Stat("/ide-desktop/bin/idea-cli-dev"); !errors.Is(fileStatError, os.ErrNotExist) {
+		backendPort = backendPort + 1
```
Comment (mustard-mh) [inline components/ide/jetbrains/cli/cmd/root.go:31]: What's this used for? If we make `backendPort` in func, it can only be `63342` or `63343`

Comment (felladrin) [reply components/ide/jetbrains/cli/cmd/root.go:31]: `63342` is the default port used by JetBrains "remote-dev-server.sh".

For developing the `components/ide/jetbrains/backend-plugin`, we need to use IntelliJ IDEA on Gitpod. Which means we'll be connecting to the remote-dev-server that is running in `63342`.

For testing changes on backend-plugin, we run `launch-dev-server.sh`.
This starts a new remote-dev-server on that workspace [[1](https://github.com/gitpod-io/gitpod/blob/8a1930a9ea5eeb955bb3ae0564f9e53e1a9d1c98/components/ide/jetbrains/backend-plugin/README.md#development)].
This new remote-dev-server will look for the availability of port `63342`, and if it's not available, it will increment the port by 1 until it finds an open port.
So we can say it's always going to pick `63343`.

Also note that `/ide-desktop/bin/idea-cli-dev` is created by `launch-dev-server.sh` right before launching the remote-dev-server. That's why we're using port `63343` if that file exists.

Comment (felladrin) [reply components/ide/jetbrains/cli/cmd/root.go:31]: Let me update the code with the addition of this comment explaining the magic number.

Thanks for asking!

**Comment by felladrin** [comment]
> @felladrin Please open a follow up issue about broken `gp open --wait`, assign it to yourself and add to team sycn under port management for JB. We need to fix it with help of JB.

Issue created.

- https://github.com/gitpod-io/gitpod/issues/10299
