### PR TITLE
Hide the latest editor warning on stopping/stopped phases of a workspace

### LINKED ISSUE #11035: Remove the latest editor release warning alert on workspace time out
### Bug description

Back in https://github.com/gitpod-io/gitpod/pull/8783, we introduced a warning alert to notify users when they've opted in for using the latest editor release for workspaces.

This is also shown on the workspace pages like `Timed Out`, `Stopping`, `Stopped`  which can be inaccurate as the user may have changed the setting in the meantime.

Instead, relying on showing this warning during workspace (re)start could be better.

**When the latest warning should be shown**
- It's before or (re)starting the workspace -> ref to phases https://github.com/gitpod-io/gitpod/blob/9d2d729b378acfc895f4700922b553655e206d86/components/dashboard/src/start/StartPage.tsx#L26-L50
- Workspaces start/stopped failed for some unexpected reasons (i.e. with exit code from supervisor) -> when it shows error https://github.com/gitpod-io/gitpod/blob/9d2d729b378acfc895f4700922b553655e206d86/components/dashboard/src/start/StartPage.tsx#L116

### Steps to reproduce

1. Go to **[/preferences](https://gitpod.io/preferences)** and opt in for the _Latest Release (Unstable)_ option.
2. Open a new workspace and let it time out (~30 min)
3. Notice the on the _Timed Out_ page we're still showing the latest editor release warning alert.

Screenshot 2022-06-30 at 1 34 34 PM

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
## Description

- Removes the latest ide alert warning on the workspace stopping and stopped pages and only shows it during workspace (re)start.

## Related Issue(s)

Fixes #11035 

## Release Notes

```release-note
Removes the latest ide alert warning on the workspace stopping and stopped pages
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by mustard-mh** [comment]
Hey, @Devansu-Yadav Thank you for your follow-up contribution 🙏 I'd like to suggest the following conditions to show/hide this alert to close the issue https://github.com/gitpod-io/gitpod/issues/11035

- Show if the workspace stopped or failed to start because of some unexpected errors (in case it failed due to the latest IDEs)
- Hide if its phase is after running

The issue description https://github.com/gitpod-io/gitpod/issues/11035 has some code refers. Please let me know if you have any questions or suggestions.

**Comment by Devansu-Yadav** [comment]
> I'd like to suggest the following conditions to show/hide this alert to close the issue #11035
> 
> * Show if the workspace stopped or failed to start because of some unexpected errors (in case it failed due to the latest IDEs)
@mustard-mh I have pushed a change to address this. Could you please have a look and let me know if it's the correct way to do it?

> * Hide if its phase is after running
> I think the very first change in this PR should address this. We now hide the alert on `Stopping`, `Stopped`, and `TimeOut`, which are the phases after `Running`.

File: components/dashboard/src/start/StartWorkspace.tsx [hunk 1]
```diff
@@ -712,7 +716,12 @@ export default class StartWorkspace extends React.Component<StartWorkspaceProps,
                 break;
         }
         return (
-            <StartPage phase={phase} error={error} title={title} showLatestIdeWarning={!isTimedOut && useLatest}>
+            <StartPage
+                phase={phase}
+                error={error}
+                title={title}
+                showLatestIdeWarning={isError || (!isTimedOut && !isStoppingOrStopped && useLatest)}
```
Comment (mustard-mh) [inline components/dashboard/src/start/StartWorkspace.tsx:723]:
```suggestion
                showLatestIdeWarning={useLatest && (isError || (!isTimeout && !isStoppingOrStopped))}
```

But it would be good to name `isTimeout` and `isStoppingOrStopped` together (I can find a proper name for it XD).

Comment (Devansu-Yadav) [reply components/dashboard/src/start/StartWorkspace.tsx:723]: @mustard-mh Do you mean we should combine both the variables `isTimeout` and `isStoppingOrStopped`?

Comment (gtsiolis) [reply components/dashboard/src/start/StartWorkspace.tsx]: @mustard-mh Could you help or confirm if what @Devansu-Yadav is suggesting above is ok? 🏓

Comment (mustard-mh) [reply components/dashboard/src/start/StartWorkspace.tsx]: > mustard-mh Could you help or confirm if what Devansu-Yadav is suggesting above is ok? 🏓

From the code, yes 👍

Comment (gtsiolis) [reply components/dashboard/src/start/StartWorkspace.tsx]: Thanks, @mustard-mh! Let me loop in @gitpod-io/engineering-webapp to bring this up to the team attention in case this could be ready to merge.

**Comment by gtsiolis** [comment]
Deployed a preview environemnt in https://hide-editor-warning.preview.gitpod-dev.com/workspaces.

**Comment by Devansu-Yadav** [comment]
@gtsiolis Any updates on this PR?

**Comment by gtsiolis** [comment]
@Devansu-Yadav Let me loop in @gitpod-io/engineering-webapp to take a closer look at the recent[[1](https://github.com/gitpod-io/gitpod/pull/16940#commits-pushed-9f60da9)] code changes.

**Comment by Devansu-Yadav** [comment]
@gtsiolis Could you pls re-open this PR?

> @Devansu-Yadav Let me loop in @gitpod-io/engineering-webapp to take a closer look at the recent[[1](https://github.com/gitpod-io/gitpod/pull/16940#commits-pushed-9f60da9)] code changes.

Seems like there hasn't been any update since this 😅

**Comment by gtsiolis** [comment]
Sure, @Devansu-Yadav.

Thanks for hanging here! 🙏 

Let me re-loop in @gitpod-io/engineering-webapp.

**Comment by akosyakov** [comment]
@gtsiolis Do you know what is blocking it?

**Comment by gtsiolis** [comment]
@akosyakov Unless code changes are no longer applicable, changes should be good to merge since @mustard-mh reviewed this a while ago, see https://github.com/gitpod-io/gitpod/pull/16940#discussion_r1153742116. 🏓 

The problem with merging this is that we no longer can merge community contributions directly from PRs, see [relevant section](https://www.notion.so/gitpod/How-we-develop-e8ce7e562478458a9223eb9b797415b2?pvs=4#ef8b432a56b6425db16039d603ac97f4) (internal) from our handbook:

> Until we completely switch to GitHub Actions, **merging community contributions from forks is not possible**. A workaround for now is to adjust the PR from the fork to merge into a branch we create instead of main first and open a separate PR to merge the changes into main. See [SID-104](https://linear.app/gitpod/issue/SID-104/dont-support-forks) for more context.

Let me merge this in a branch and reopen. ➰
