### PR TITLE
[payment] cancel all subscriptions on user deletion

### LINKED ISSUE #4229: [Admin] Cannot delete account if team subscription slot is assigned
### Bug description

Account deletion fails if there is a team subscription slot assigned. 

### Steps to reproduce

1. Assign a team subscription slot.
2. Try to delete the account of the assignee.
3. See deletion fails with no feedback.

### Expected behavior

Team subscription slot should be made available and deletion should succeed.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JanKoehnlein**
fixes #4229

### CODE REVIEW

**Comment by JanKoehnlein** [comment]
Looks like we won't get a preview environment for these kind of changes in the near future. Please review such that we can test it on staging,

File: components/server/ee/src/user/user-deletion-service.ts [hunk 1]
```diff
@@ -10,38 +10,58 @@ import { SubscriptionService } from "@gitpod/gitpod-payment-endpoint/lib/account
...
+                        const teamSlots = await this.teamSubscriptionService.findTeamSubscriptionSlotsByAssignee(id);
+                        teamSlots.forEach(async ts => await this.teamSubscriptionService.deactivateSlot(ts.teamSubscriptionId, ts.id, now))
+                    } else if (paymentReference.startsWith("github:")) {
+                        throw new Error("Cannot delete user subscription from GitHub")
+                    } else {
+                        // cancel Chargebee subscriptions
+                        const subscriptionId = subscription.uid;
+                        const chargebeeSubscriptionId = subscription.paymentReference!;
+                        await this.chargebeeService.cancelSubscription(chargebeeSubscriptionId, { userId: user.id }, { subscriptionId, chargebeeSubscriptionId });
+                    }
```
Comment (corneliusludmann) [inline components/server/ee/src/user/user-deletion-service.ts:54]: Is it on purpose that this block is not in an else block anymore? Is it because team subscriptions have a free plan but no `paymentReference`? I would like to have a short comment here that explains this.

```suggestion
                    } else {
                        if (!paymentReference) {
                            const teamSlots = await this.teamSubscriptionService.findTeamSubscriptionSlotsByAssignee(id);
                            teamSlots.forEach(async ts => await this.teamSubscriptionService.deactivateSlot(ts.teamSubscriptionId, ts.id, now))
                        } else if (paymentReference.startsWith("github:")) {
                            throw new Error("Cannot delete user subscription from GitHub")
                        } else {
                            // cancel Chargebee subscriptions
                            const subscriptionId = subscription.uid;
                            const chargebeeSubscriptionId = subscription.paymentReference!;
                            await this.chargebeeService.cancelSubscription(chargebeeSubscriptionId, { userId: user.id }, { subscriptionId, chargebeeSubscriptionId });
                        }
                    }
```

File: components/server/ee/src/user/user-deletion-service.ts [hunk 2]
```diff
@@ -10,38 +10,58 @@ import { SubscriptionService } from "@gitpod/gitpod-payment-endpoint/lib/account
...
+                    if (Plans.isFreeNonTransientPlan(planId)) {
+                        // only delete those plans that are persisted in the DB
+                        await this.subscriptionService.unsubscribe(user.id, now.toISOString(), planId);
+                    } else if (Plans.isFreePlan(planId)) {
+                        // we do not care about transient plans
+                        continue;
+                    }
+                    if (!paymentReference) {
+                        const teamSlots = await this.teamSubscriptionService.findTeamSubscriptionSlotsByAssignee(id);
+                        teamSlots.forEach(async ts => await this.teamSubscriptionService.deactivateSlot(ts.teamSubscriptionId, ts.id, now))
```
Comment (corneliusludmann) [inline components/server/ee/src/user/user-deletion-service.ts:46]: Could `teamSlots` be empty (expectedly or unexpectedly)? Do we need to handle this (logging/throwing an error etc.)?

**Review by corneliusludmann — COMMENTED** [review]
2 smaller comments or rather questions because I don't understand team subscriptions well enough.

File: components/server/ee/src/user/user-deletion-service.ts [hunk 3]
```diff
@@ -10,38 +10,59 @@ import { SubscriptionService } from "@gitpod/gitpod-payment-endpoint/lib/account
...
+                    errors.push(error);
+                    log.error("Error cancelling subscription", error, { subscription })
                 }
             }
         }
 
-        return super.deleteUser(id);
+        await super.deleteUser(id);
+        if (errors) {
+            throw new Error(errors.join("\n"))
```
Comment (svenefftinge) [inline components/server/ee/src/user/user-deletion-service.ts:65]: why throwing the errors here? We still deleted the user and already logged it.

**Review by svenefftinge — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 42ac6fcc6c88268a670da9bd7992049d64369590</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4501#pullrequestreview-728433036" title="Approved">svenefftinge</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)~~ [svenefftinge]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [svenefftinge]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/server/ee/src/user/user-deletion-service.ts (hunk 3 above)
Comment (JanKoehnlein) [reply components/server/ee/src/user/user-deletion-service.ts:65]: The idea was to give feedback to the caller, e.g. the admin dashboard.

In particular in the case of GitHub subscription, it may be worthwhile to notify the customer that their subscription will still be charged as we have no means to cancel it.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4501#issuecomment-897546464" title="Approved">JanKoehnlein</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4501#pullrequestreview-728433036" title="Approved">svenefftinge</a>*

Associated issue: *#4229*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)~~ [JanKoehnlein,svenefftinge]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [JanKoehnlein,svenefftinge]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
@svenefftinge Thanks a lot for the review!
