### PR TITLE
[ws-daemon] Enable workspace content housekeeping

### LINKED ISSUE #11369: `ws-daemon` sometimes didn't delete workspace file after backup
### Bug description

`ws-daemon` sometimes didn't delete workspace file after backup

### Steps to reproduce

see workspace folder in node `/var/gitpod/workspaces`

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

The current mitigation for this is to `kubectl cordon` the node, but, it'd be ideal not to have this condition occur in the first place, this way the alert doesn't page on-callers.

This can cause alerts such as [NodeFilesystemAlmostOutOfSpace](https://gitpod.pagerduty.com/incidents/Q21LINWL2K6GGU)

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR re-instates ws-daemon's content garbage collection which removes workspace content from disk once the state file is gone. We had originally disabled this behaviour because it interfered with the ws-daemon/ws-sync migration three years ago.

There's a grace period for content built-in which ensures we only delete content older than two hours. The motivation is to guard against accidental state mishaps.

>**Warning**
> This PR carries the risk that it might delete workspace content unintentionally. 

## Related Issue(s)

Fixes #11369

## How to test
- see unit test
- start a workspace, produce a file in the workspace content directory which cannot be deleted and stop the workspace
- make the workspace content directory deletable again and see it being deleted

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

File: components/ws-daemon/pkg/internal/session/store.go [hunk 1]
```diff
@@ -242,36 +244,49 @@ func (s *Store) doHousekeeping(ctx context.Context) (errs []error) {
 	// 	log.WithField("workspace", ws).Info("deleted workspaces without content directory")
```
Comment (Furisto) [inline components/ws-daemon/pkg/internal/session/store.go:244]: Can we remove the commented out code? If need be we can get it from history.

File: components/ws-daemon/pkg/internal/session/store.go [hunk 2]
```diff
@@ -242,36 +244,49 @@ func (s *Store) doHousekeeping(ctx context.Context) (errs []error) {
...
+			continue
+		}
 
-	// 	log.WithField("directory", f.Name()).Info("deleted workspace content directory without corresponding state file")
-	// }
+		// We have found a workspace content directory without a workspace state file, which means we don't manage this folder.
+		// Within the working area/location of a session store we must be the only one who creates directories, because we want to
+		// make sure we don't leak files over time.
+
+		// For good measure we wait a while before deleting that direcotry.
```
Comment (sagor999) [inline components/ws-daemon/pkg/internal/session/store.go:270]:
```suggestion
		// For good measure we wait a while before deleting that directory.
```

File: components/ws-daemon/pkg/internal/session/store_test.go [hunk 3]
```diff
@@ -0,0 +1,118 @@
+// Copyright (c) 2020 Gitpod GmbH. All rights reserved.
```
Comment (sagor999) [inline components/ws-daemon/pkg/internal/session/store_test.go:1]: copy paste copyright? (should be 2022)

**Review by sagor999 — APPROVED** [review]
LGTM
/hold
for nits

**Review by jenting — COMMENTED** [review]
/lgtm

File: components/ws-daemon/pkg/internal/session/store.go [hunk 4]
```diff
@@ -242,36 +244,49 @@ func (s *Store) doHousekeeping(ctx context.Context) (errs []error) {
...
+		nfo, err := f.Info()
+		if err != nil {
+			log.WithError(err).Warn("Found workspace content directory without a corresponding state file, but could not retrieve its info")
+			errs = append(errs, err)
+			continue
+		}
+		if time.Since(nfo.ModTime()) < 2*time.Hour {
```
Comment (utam0k) [inline components/ws-daemon/pkg/internal/session/store.go:277]: Why not give the 2h a name and make it const?
