### PR TITLE
[supervisor] Don't nil-deref on broken Gitpod connection

### LINKED ISSUE #2558: [workspace] nil-deref on workspace start (cased by outdated tokens?)
### Describe the bug
Gitpod version: `master.3057`

Trying to start a workspace using `loadgen` and outdated tokens leads to this nil-deref:
```
goroutine 8 [running]:
github.com/gitpod-io/gitpod/supervisor/pkg/gitpod.(*APIoverJSONRPC).GetWorkspace(0x0, 0xdbc240, 0xc000614000, 0xc00003a154, 0x24, 0x0, 0x0, 0x0)
	/tmp/build/components-supervisor--app.9771a56eb3b9db016c97abf9e87e1221fb15ca5a/_deps/gitpod-core-components-supervisor--app/pkg/gitpod/gitpod-service.go:567 +0x116
github.com/gitpod-io/gitpod/supervisor/pkg/ports.(*ConfigService).Observe.func1(0xc00003c180, 0xc0000902a0, 0xc0005572c0, 0xdbc240, 0xc000614000)
	/tmp/build/components-supervisor--app.9771a56eb3b9db016c97abf9e87e1221fb15ca5a/_deps/gitpod-core-components-supervisor--app/pkg/ports/ports-config.go:120 +0x154
created by github.com/gitpod-io/gitpod/supervisor/pkg/ports.(*ConfigService).Observe
	/tmp/build/components-supervisor--app.9771a56eb3b9db016c97abf9e87e1221fb15ca5a/_deps/gitpod-core-components-supervisor--app/pkg/ports/ports-config.go:112 +0xac
```
Using up-to-date tokens fixes the issue, but nonetheless it'd be nice to find and fix the path to the deref.

### Steps to reproduce
Start loadgen on any environment, using the value for `THEIA_SUPERVISOR_TOKENS` that's in the code (and outdated).

### Expected behavior
`supervisor` should never deref nil, not even with wrong outdated tokens.

### Additional information
Interestingly we got a similar stack trace yesterday: https://github.com/gitpod-io/gitpod/issues/2544

### PR DESCRIPTION
**Pull request by csweichel**
This PR fixes a nil-deref in supervisor if we cannot connect to the Gitpod server upon startup, e.g. because we don't have a token.

Note: we have this issue because we choose to roll our own RPC tech here. Another good reason to consider moving to something more standard (gRPC?).

Fixes #2558 

The root cause, i.e. reason we can be nil in the first place is this in [`createGitpodService`](https://github.com/gitpod-io/gitpod/blob/master/components/supervisor/pkg/supervisor/supervisor.go#L233-L236) where we just log an error and return nil if there's no token.

### CODE REVIEW

File: components/supervisor/pkg/gitpod/gitpod-service.go [hunk 1]
```diff
@@ -559,6 +641,10 @@ func (gp *APIoverJSONRPC) GetFeaturedRepositories(ctx context.Context) (res []*W
 
 // GetWorkspace calls getWorkspace on the server
 func (gp *APIoverJSONRPC) GetWorkspace(ctx context.Context, id string) (res *WorkspaceInfo, err error) {
+	if gp == nil {
```
Comment (geropl) [inline components/supervisor/pkg/gitpod/gitpod-service.go:644]: @csweichel Could you elaborate on why this might be the case? Especially when we come from [here](https://github.com/gitpod-io/gitpod/blob/c2c0629e37964a3046a929d1e5a6da9c0fa7511b/components/supervisor/pkg/ports/ports-config.go#L120)? I think I'm missing out something important here...

Comment (csweichel) [reply components/supervisor/pkg/gitpod/gitpod-service.go:644]: The issue is [`createGitpodService`](https://github.com/gitpod-io/gitpod/blob/master/components/supervisor/pkg/supervisor/supervisor.go#L233-L236) which returns nil when there's no token.
At this point its easier to handle the nil case within the functions of `APIoverJSONRPC` rather than outside.

Comment (akosyakov) [reply components/supervisor/pkg/gitpod/gitpod-service.go:644]: I still don't get why [this guard](https://github.com/gitpod-io/gitpod/blob/c2c0629e37964a3046a929d1e5a6da9c0fa7511b/components/supervisor/pkg/ports/ports-config.go#L119) does not catch it, but new guard within the function will do it. 😬 

Is there a way that we can simulate the issue to confirm it? We could always return `nil` from `createGitpodService`  to verify it? Sorry if you already done it.

**Review by akosyakov — APPROVED** [review]
I was able to verify it by changing `porst-config_test.go` with:

```go
func createNilGitpodService() *gitpod.APIoverJSONRPC {
	return nil
}
...
service := NewConfigService(workspaceID, configService, createNilGitpodService())
```

There is something weird about nils and interfaces in go which I don't understand though.
