### PR TITLE
Pagination design fixes

### LINKED ISSUE #12537: Pagination links not properly themed
The links on the bottom of a paginated table are not properly themed.

Screenshot 2022-08-31 at 08 57 20

### PR DESCRIPTION
**Pull request by Hardik500**
## Description
Changed the design of pagination component to match more with the current theme

Dark Mode:
image

Light Mode:
image

Disabled Dark Mode:
image

Disabled Light Mode:
image

Hover Dark Mode:
image

Hover Light Mode:
image

## Related Issue(s)

Fixes #12537, #12027

## How to test
Go to any page which has some pagination involved and check the pagination buttons 

## Release Notes

```release-note
Improve pagination usability
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@Hardik500: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
@gtsiolis The preview env had to be run manually[[internal](https://gitpod.slack.com/archives/C032A46PWR0/p1665654406500859?thread_ts=1665654254.753599&cid=C032A46PWR0)]. Now it's available in case you'd like to test it.

**Comment by meysholdt** [comment]
hi @Hardik500, For us to be able to merge this PR, can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via moritz@gitpod.io.

**Comment by Hardik500** [comment]
@meysholdt I've signed the DocuSign

**Comment by meysholdt** [comment]
Thank you for signing the CLA @Hardik500!

**Comment by laushinka** [comment]
Hi @Hardik500, sorry for the long delay in reviewing! I hope you don't mind that I rebased your branch so that we don't have to go back and forth too much again.
From testing I found this issue where the pagination disappeared on number 4. 

I recorded a short [loom](https://www.loom.com/share/7e7b00719f8f4d36a9ee9998220e9afb). Let me know if you can't view it.

**Comment by Hardik500** [comment]
> Hi @Hardik500, sorry for the long delay in reviewing! I hope you don't mind that I rebased your branch so that we don't have to go back and forth too much again. From testing I found this issue where the pagination disappeared on number 4.
> 
> I recorded a short [loom](https://www.loom.com/share/7e7b00719f8f4d36a9ee9998220e9afb). Let me know if you can't view it.

Hey @laushinka , I am unable to reproduce it. Attaching the video ref below

https://user-images.githubusercontent.com/28431356/198866071-adaf959b-69e4-4165-b6c6-954bd5ac63e4.mov

**Comment by laushinka** [comment]
@Hardik500 Thanks for the recording! That does help. It could be my test cases in my preview environment that's causing it. Could you squash and rebase?

File: components/dashboard/src/Pagination/Pagination.tsx [hunk 1]
```diff
@@ -29,23 +29,23 @@ function Pagination(props: PaginationProps) {
...
-                        <Arrow direction={"left"} />
-                        Previous
-                    </span>
-                </li>
+            <ul className="flex justify-center items-center space-x-4">
+                <PaginationNavigationButton
+                    isDisabled={currentPage === 1}
+                    onClick={prevPage}
+                    label={"Previous"}
+                    arrowReversed={false}
```
Comment (laushinka) [inline components/dashboard/src/Pagination/Pagination.tsx:47]: Instead of calling this `arrowReversed`, could you keep the arrow direction prop? This prop is used not only for left and right, but also up and down.

Comment (Hardik500) [reply components/dashboard/src/Pagination/Pagination.tsx:47]: Got it

Comment (Hardik500) [reply components/dashboard/src/Pagination/Pagination.tsx:47]: One question, @laushinka so for "up" and "down" arrowDirection, do I need to handle code for those too in `PaginationNavigationButtons` component. Cause right now the code flow would be like this?

image

Comment (laushinka) [reply components/dashboard/src/Pagination/Pagination.tsx:47]: You don't have to handle "up" and "down" here because we won't see those in Pagination. The intention is to be consistent with what the `<Arrow />` [component](https://github.com/gitpod-io/gitpod/blob/e0579ef9388cee0c4c7a2c85588683167e0cb0f7/components/dashboard/src/components/Arrow.tsx) expects :)

Comment (Hardik500) [reply components/dashboard/src/Pagination/Pagination.tsx]: Understood, I have made the respective changes

Comment (laushinka) [reply components/dashboard/src/Pagination/Pagination.tsx]: Thanks! Could you squash and rebase please? :)

**Comment by gtsiolis** [comment]
Rebased and pushed, but job keeps failing. Looping this internally, see [relevant discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1667405842202829) (internal). Cc @laushinka

**Comment by laushinka** [comment]
I'm going to approve this to unblock, but holding due to: 
- GitHub not taking into account the already green build
- @gtsiolis' review

/hold

**Review by laushinka — APPROVED** [review]

**Comment by gtsiolis** [comment]
Looking at this now! 👀

**Review by gtsiolis — APPROVED** [review]
Thanks @Hardik500 @laushinka! 🔮 

I couldn't test this sufficiently as the preview environment is getting removed always under ~15 minutes, see [relevant discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1667565531762529?thread_ts=1667405842.202829&cid=C032A46PWR0) (internal). Cc @vulkoingim @mads-hartmann 

From what I see from the screenshots, this looks good. We can always make minor adjustments later in the styles. ✔️ 

I hope this is not adding a pagination in the workspaces list as seen in https://github.com/gitpod-io/gitpod/pull/13590#issuecomment-1296136779. From the code changes it seems not but let me know if this is not the case. ⚠️ 

Approving and merging.

**Comment by Hardik500** [comment]
> Thanks @Hardik500 @laushinka! 🔮
> 
> I couldn't test this sufficiently as the preview environment is getting removed always under ~15 minutes, see [relevant discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1667565531762529?thread_ts=1667405842.202829&cid=C032A46PWR0) (internal). Cc @vulkoingim @mads-hartmann
> 
> From what I see from the screenshots, this looks good. We can always make minor adjustments later in the styles. ✔️
> 
> I hope this is not adding a pagination in the workspaces list as seen in [#13590 (comment)](https://github.com/gitpod-io/gitpod/pull/13590#issuecomment-1296136779). From the code changes it seems not but let me know if this is not the case. ⚠️
> 
> Approving and merging.

Thanks @gtsiolis 
Don't worry this won't be adding any pagination to workspaces. I just added some dummy code to test my changes easily

**Comment by laushinka** [comment]
Thank you @Hardik500 for the patience and @gtsiolis for the co-reviewing 🙏🏽
