### PR TITLE
 Make the licensing match what's advertised 

### LINKED ISSUE #6932: [Self-hosted]: cannot search users/workspaces without enterprise license and error is console only
### Bug description

When I go to `/admin/users` in my self-hosted instance and click "search", I'm not able to search without an enterprise license. Whilst this is fine, the error only appears in the console.

It would be nice to have the error in the actual dashboard - an alert-style error

image

### Steps to reproduce

Install self-hosted, go to admin and click "search"

### Workspace affected

_No response_

### Expected behavior

Should display the "enterprise license required" in the dashboard, not just the console

### Example repository

_No response_

### Anything else?

_No response_

### LINKED ISSUE #8328: Make the licensing match what's advertised
On [Gitpod](https://www.gitpod.io/self-hosted), we advertise three self-hosted plans - community, free and professional.

In the [application](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/ee/pkg/licensor/licensor.go#L81), we only provide two plan types - team and enterprise

This ticket is to make the application match what we advertise.

---

There are a few potential things that need to be thought about here

- Any changes need to maintain backwards compatibility with existing customers (including SaaS)
- We should support automatic downgrading to the community license if a user has a free license and the number of users increases from 10 to 11
- I would suggest that the admin dashboard is enabled for all license levels. This will allow us to put useful things in here in future

Linked to #8329

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

The self-hosted licensing now matches [what we advertise](https://www.gitpod.io/self-hosted), namely:

- Default to free/professional license which allows full access for a specific number of users. Free is for 10 users, pro is for however many their license allows. Internally, this is the "Enterprise" license.
- Fallback to community license, which allows for none of the EE features (except admin dashboard) for an unlimited number of users. Internally, this is the "Team" license.

This introduces the concept of a fallback license, in addition to the default license. It also adds the number of seats to the `Enabled` call in the licensor. As a workflow, if the license exceeds the number of seats requested in the call, it will try again with the fallback license, which is the community license.

### Fallback rules

| License type | Fallback allowed |
| --- | --- |
| No license (ie, installed via Installer) | Y |
| Gitpod paid license | N |
| Replicated community license | Y |
| Replicated paid license | N |

This table shows the fallback rules. It is done so that a user who is paying for Gitpod will have additional users rejected rather than having their service downgraded. It would be a pretty poor user experience if someone was paying for Gitpod, had an additional user sign up and then everyone lost all their premium services.

Gitpod licenses are always considered "paid". Now we are moving to Replicated for most licensing, Gitpod licenses will only be issued to paying customers who cannot use Replicated (eg, SaaS). Replicated has the concept of a community license - if their license is marked as "community", it will allow for fallback.

## Related Issue(s)

Fixes #8328
Fixes #6932

## How to test

Deploy to a self-hosted instance with a Replicated license. Tests already done:
 - Test prebuilds work with <=10 users
 - Test new user rejected when paid license has run out of seats
 - Test new user accepted when paid license changed to a community license
 - Test prebuilds rejected when on community license and > 10 users
 - Test prebuilds accepted when community license changed to a paid license with 20 users

## Release Notes

```release-note
 Make the licensing match what's advertised
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by MrSimonEmms** [comment]
@geropl I kept the caching of the `getUsersCount` call as a [separate commit](https://github.com/gitpod-io/gitpod/pull/8593/commits/28b8f8d586e1b499b3933c036edaaaa337929b84), to make it easier for you to check I'm on the right track with what you suggested. Happy to keep as-is or to merge into the other `[server]` commit - your call

**Comment by corneliusludmann** [comment]
Great progress, @MrSimonEmms! :pray: 

### Suggestion
I'm totally fine with moving this suggestion to a follow-up PR (since this PR is already a minimum viable change). However, in order to fix https://github.com/gitpod-io/gitpod/issues/8412 I would suggest the following change:

1. Allow **fallback** here:
https://github.com/gitpod-io/gitpod/blob/9c5a4d017f454744856ea2c2e11f886813aebfb8/components/licensor/ee/pkg/licensor/replicated.go#L90-L100
1. Return an **invalid license** that allows fallback here instead of the default replicated license:
https://github.com/gitpod-io/gitpod/blob/9c5a4d017f454744856ea2c2e11f886813aebfb8/components/licensor/ee/pkg/licensor/replicated.go#L118-L128 
3. Allow **fallback in case of an invalid license** here instead of returning `false`:
https://github.com/gitpod-io/gitpod/blob/dd508e3ffb903fb1869d6190626a4cdd72645a77/components/licensor/ee/pkg/licensor/licensor.go#L168-L171
https://github.com/gitpod-io/gitpod/blob/dd508e3ffb903fb1869d6190626a4cdd72645a77/components/licensor/ee/pkg/licensor/licensor.go#L186-L189


With this, we can display the result of
https://github.com/gitpod-io/gitpod/blob/dd508e3ffb903fb1869d6190626a4cdd72645a77/components/licensor/ee/pkg/licensor/licensor.go#L158-L165
in the admin dashboard and users know why the license is invalid and they still have basic functionality (as you would have with no license).

**Review by corneliusludmann — DISMISSED** [review]
Licensor part looks good to me.

:information_source:  I would like to leave the final review of the server part to **Team WebApp**.

**Comment by MrSimonEmms** [comment]
@corneliusludmann I'll remove the "Fixes" for #8412 and we can continue the discussion there

File: components/server/ee/src/user/user-counter.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+@injectable()
+export class UserCounter {
+    public expires: Date | null = null;
+
+    protected data: number | null = null;
+
+    protected readonly timeout: number = 60 * 1000; // Cache data for 1 minute
+
+    get count(): number | null {
```
Comment (geropl) [inline components/server/ee/src/user/user-counter.ts:17]: nit: we usually do not use `null` but `undefined` instead. But ignore this for how, we'll have a lint for it shortly.

**Review by geropl — APPROVED** [review]
Thx @MrSimonEmms , looks good to me! 

Did not test the self-hosted setup, though. :wink:

File: components/server/ee/src/user/user-counter.ts (hunk 1 above)
Comment (MrSimonEmms) [reply components/server/ee/src/user/user-counter.ts:17]: @geropl Would you like me to change this? I don't mind - normally, I use `undefined` as well so I can't understand why I used `null`

**Review by corneliusludmann — APPROVED** [review]
