### PR TITLE
[ws-manager-bridge] Add status update metric

### LINKED ISSUE #5754: [ws-manager-bridge] Export status update received metric
Such a metric is a good indicator for a broken connection to the workspace cluster. We would do well to establish an alert on this metric: if the rate drops to zero that's a problem, and we'll want an alert in addition to forcefully restart the bridge.

related: #5753

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR adds a metric that counts the total status updates we've received from a workspace cluster.

## Related Issue(s)

Fixes #5754

## How to test
1. Start a workspace
2. Check the ws-manager-bridge metrics and find `gitpod_ws_manager_bridge_status_updates_total`

Shoud look something like this:
image

## Release Notes

```release-note
[ws-manager-bridge] Introduce `gitpod_ws_manager_bridge_status_updates_total` metric to monitor workspace cluster stability
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5754*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-manager-bridge/src/prometheus-metrics-exporter.ts [hunk 1]
```diff
@@ -39,6 +40,11 @@ export class PrometheusMetricsExporter {
             help: 'Cordoned status of the individual registered workspace cluster',
             labelNames: ["workspace_cluster"]
         });
+        this.statusUpdatesTotal = new prom.Counter({
```
Comment (geropl) [inline components/ws-manager-bridge/src/prometheus-metrics-exporter.ts:43]: :+1:

**Review by geropl — APPROVED** [review]
LGTM and tested: :+1:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 403592f24041ce83008e2eba71cfdd1c2ac39444</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5755#pullrequestreview-758340262" title="Approved">geropl</a>*

Associated issue: *#5754*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
