### PR TITLE
credential-helper: validate parsed git command data

### LINKED ISSUE #7702: "Unknown repository" toast notification when using private git npm dependencies
### Bug description

👋  Hey there folks! We've noticed that when we install npm dependencies for one of our applications there's a toast message thrown in Gitpod's VS Code IDE alerting about an unknown repository. It looks like this:
image

We've simply been ignoring the message since everything does install correctly. I recorded a Loom for you to review that recreates the issue with a minimal set-up: https://www.loom.com/share/66ebf0ae586e4dd0921b6fbc2aaaf3bf

### Steps to reproduce

1. Create a private git repository for an npm package
2. Add this new package as a dependency to a Gitpod enabled repository using the `github:` protocol helper
```
...
"devDependencies": {
    "private-package": "github:joepurdy/private-npm-package"
}
...
```
3. Run `npm install` from within Gitpod to trigger the "unknown repository" error

### Workspace affected

_No response_

### Expected behavior

Ideally no toast warning would occur in this case since there's no real issue. 

I think where the issue could become thorny is if a user doesn't actually have access to the private repository that is specified as a dependency. In this case the packages would fail to install, but regardless it's not really a problem for Gitpod to be concerned with since lack of access at the user level is the responsibility of whoever manages user access to the associated git repositories.

### Example repository

Here's a snapshot to the demo repo from the Loom recording: https://gitpod.io#snapshot/00ac0dd4-e05b-4e7d-88b8-af19c606ad9a

Note: this should still recreate the toast notification, but you'll also see an error like this in the terminal output:
```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/joepurdy/private-npm-package.git
```

That's expected behavior since you won't have access to the private dependency's source repo. This is what I meant about it not really being a problem for Gitpod to solve for in the event a user lacks the permissions. In that case there's already a clear error from npm about lacking the right access.

### Anything else?

/cc @loujaybee I imagine this might be interesting to the IDE team 😁

### PR DESCRIPTION
**Pull request by jeanp413**
## Related Issue(s)

Fixes #7702

## How to test

1. Open preview env
2. Open this workspace https://github.com/jeanp413/test-gp-bug
3. Run `npm install`
4. Observe NO notification with this message appears `Unknown repository '' Please grant the necessary permissions.`

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#7702*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/gitpod-cli/cmd/credential-helper.go [hunk 1]
```diff
@@ -54,10 +54,13 @@ var credentialHelper = &cobra.Command{
 			fmt.Printf("username=%s\npassword=%s\n", user, token)
 		}()
 
-		repoURL, gitCommand := parseProcessTree()
+		gitCommandData := parseProcessTree()
```
Comment (iQQBot) [inline components/gitpod-cli/cmd/credential-helper.go:57]: maybe use
```go
repoURL, gitCommand, err := parseProcessTree()
``` 
is better?

Comment (jeanp413) [reply components/gitpod-cli/cmd/credential-helper.go:57]: Still learning golang so not sure about it, my feel is that error it's something you should handle when something unexpected goes wrong, here I just wanna check if I'm running a git command against origin remote and if not just do nothing and I didn't like doing `if repoUrl == "" && gitCommand == ""` :smile:

Comment (iQQBot) [reply components/gitpod-cli/cmd/credential-helper.go:57]: Yes you are right, but not getting the right data is a error

Comment (jeanp413) [reply components/gitpod-cli/cmd/credential-helper.go:57]: It is expected that repoURL and gitCommand could be empty as not all git commands are run against remote origin.
How about using the ok idiom (return bool) `repoURL, gitCommand, ok := parseProcessTree()`?

**Comment by akosyakov** [comment]
Should we start adding some unit tests for that?

**Review by filiptronicek — APPROVED** [review]
I will not merge since there are some discussions about the code but functionality wise it's a LGTM!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f9629ddd140e09f66842737f214d1cd7ccbb7f4b</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7735#pullrequestreview-859263049" title="Approved">filiptronicek</a>*

Associated issue: *#7702*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)~~ [filiptronicek]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
