### PR TITLE
[server] bump GitLab API library

### LINKED ISSUE #12970: Impossible to add some GitLab repositories as a Project when you're a maintainer of more than 100 repositories
### Bug description

When you want to add a repository as a new Project in Gitpod, Gitpod first gets the list of all the possible repositories you could add (grouped by account), and then lets you find the repository you want to add via scrolling or searching/filtering.

Unfortunately, in the case of GitLab, we only fetch the first 100 repositories that you could add:

https://github.com/gitpod-io/gitpod/blob/1d52870bfe3dbb675ae0028c2e1d7a441d2a1489/components/server/ee/src/gitlab/gitlab-app-support.ts#L54

This is a problem, because if you want to add a specific repository that is not present in the first 100 repositories returned by GitLab, you will never be able to see it or find it in the Gitpod UI -- thus adding it as a project is totally impossible.

### Steps to reproduce

1. Be a maintainer of more than 100 GitLab repositories
2. Try to create a new project for a repository that is not listed in the first 100 results returned by GitLab

### Workspace affected

_No response_

### Expected behavior

- You should always be able to create a new project for a GitLab repository that you're a maintainer of (even if it's not in the first 100 results from GitLab)

### Example repository

_No response_

### Anything else?

Possible solutions:
- Paginate the GitLab API call in order to fetch more than just the first 100 repositories
- Allow creating projects by manually entering a repository URL

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
PR updates GitLab API library, adds tests to cover changes and verify that the paginated requests now works as expected.

## Related Issue(s)

Fixes #12970

Screen Shot 2022-09-16 at 13 44 56

## How to test
- [x] checked context parser tests for GitLab are still ✅
  - `export GITPOD_TEST_TOKEN_GITLAB='{ "value": "F00....", "scopes":[] }'`
  - `cd components/server && npx mocha --opts mocha.opts './**/gitlab-*.spec.ts' --exclude './node_modules/**'`
- [x] add manual test to cover the `Projects.all` request
  - run `createManyRepos` to create 
- [x] verify that more than 100 projects/repos are found on `/new`
2. verify the check points in comments bellow 

## Release Notes

```release-note
Update GitLab API library, which fixes paginated API requests.
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@AlexTugarev: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/server/src/gitlab/api.ts [hunk 1]
```diff
@@ -87,7 +87,9 @@ export class GitLabApi {
         path: string,
     ): Promise<string | undefined> {
         const projectId = `${org}/${name}`;
-        const result = await this.run<string>(user, (api) => api.RepositoryFiles.showRaw(projectId, path, commitish));
+        const result = await this.run<string>(user, (api) =>
+            api.RepositoryFiles.showRaw(projectId, path, { ref: commitish }),
```
Comment (AlexTugarev) [inline components/server/src/gitlab/api.ts:91]: to be checked

File: components/server/src/gitlab/gitlab-repository-provider.ts [hunk 2]
```diff
@@ -27,7 +27,8 @@ export class GitlabRepositoryProvider implements RepositoryProvider {
         const cloneUrl = response.http_url_to_repo;
         const description = response.default_branch;
         const host = RepoURL.parseRepoUrl(cloneUrl)!.host;
-        const avatarUrl = response.owner?.avatar_url || undefined;
+        // FIXME(at) that seems to be no longer provided here
```
Comment (AlexTugarev) [inline components/server/src/gitlab/gitlab-repository-provider.ts:30]: to be checked, but it seems, it was missing anyways

File: components/server/ee/src/gitlab/gitlab-app-support.ts [hunk 3]
```diff
@@ -51,7 +52,11 @@ export class GitLabAppSupport {
         // we are listing only those projects with access level of maintainers.
         // also cf. https://docs.gitlab.com/ee/api/members.html#valid-access-levels
         //
-        const projectsWithAccess = await api.Projects.all({ min_access_level: "40", perPage: 100 });
+        const projectsWithAccess = await api.Projects.all({
+            min_access_level: "40",
+            perPage: 100,
+            pagination: "keyset",
```
Comment (AlexTugarev) [inline components/server/ee/src/gitlab/gitlab-app-support.ts:58]: Hi @gtsiolis! Would you like to test this change on the preview environment? Maybe you know how to find the 101 repo in the GitLab org/group?

File: components/server/src/gitlab/gitlab-repository-provider.ts (hunk 2 above)
Comment (AlexTugarev) [reply components/server/src/gitlab/gitlab-repository-provider.ts]: resolved

File: components/server/src/gitlab/api.ts (hunk 1 above)
Comment (AlexTugarev) [reply components/server/src/gitlab/api.ts:92]: see gitlab-file-provider.spec.ts

File: components/server/ee/src/gitlab/gitlab-app-support.ts [hunk 4]
```diff
@@ -9,21 +9,7 @@ import { inject, injectable } from "inversify";
 import { TokenProvider } from "../../../src/user/token-provider";
 import { UserDB } from "@gitpod/gitpod-db/lib";
 import { Gitlab } from "@gitbeaker/node";
-import { ProjectSchemaDefault, NamespaceInfoSchemaDefault } from "@gitbeaker/core/dist/types/services/Projects";
-
-// Add missing fields to Gitbeaker's ProjectSchema type
-type ProjectSchema = ProjectSchemaDefault & {
```
Comment (AlexTugarev) [inline components/server/ee/src/gitlab/gitlab-app-support.ts:15]: dupe of GitLab.Project

File: components/server/ee/src/gitlab/gitlab-app-support.ts (hunk 3 above)
Comment (gtsiolis) [reply components/server/ee/src/gitlab/gitlab-app-support.ts:43]: @AlexTugarev I don't have maintainer access to such a long list of repositories to try this but took 10 minutes to create a list of 101 repositories via command line in a reproduction group.

However, I can already find the 101th repository in Gitpod.io, see screenshot below. 💭 

For this preview environment, when I add the GitLab integration I'm stuck in the fetching repositories screen with the following error in console.

```js
Error: Request getProviderRepositoriesForUser failed with message: Response code 405 (Method Not Allowed)
```

| Gitpod.io | This preview environment |
|-|-|
| Screenshot 2022-09-16 at 2 27 13 PM | Screenshot 2022-09-16 at 2 24 35 PM |

Comment (AlexTugarev) [reply components/server/ee/src/gitlab/gitlab-app-support.ts]: @gtsiolis, in the meantime, I was able to create a test script to create ~200 test projects in https://gitlab.com/alex-gp-test-group?page=1 and wrote a unit test for the request which was expected to be broken. not to forget, those tests are not automated, as they require a personal OAuth token in the environ. 

That said, I'd be more than happy if you could retest after next build is deployed to preview. 🙏🏻

Comment (AlexTugarev) [reply components/server/ee/src/gitlab/gitlab-app-support.ts]: I'll make a screenshot to the description as well, once I could verify it myself.

File: components/server/ee/src/gitlab/gitlab-app-support.spec.ts [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+        const result = await this.appSupport.getProviderRepositoriesForUser({
+            user: this.user,
+            provider: {
+                host: "gitlab.com",
+                authProviderId: "Public-GitLab",
+                authProviderType: "GitLab",
+                verified: true,
+            },
+        });
+        expect(result.length).to.be.greaterThan(200);
```
Comment (AlexTugarev) [inline components/server/ee/src/gitlab/gitlab-app-support.spec.ts:66]: better this not-automated test, than nothing.

File: components/server/ee/src/gitlab/gitlab-app-support.ts (hunk 3 above)
Comment (gtsiolis) [reply components/server/ee/src/gitlab/gitlab-app-support.ts]: > ... in the meantime, I was able to create a test script to create ~200 test projects ... 

🙂  

> ... wrote a unit test for the request which was expected to be broken. not to forget, those tests are not automated, as they require a personal OAuth token ...

It could be nice if we could use a dedicated group for such integrations tests, right? Cross-posting a relevant comment from https://github.com/gitpod-io/gitpod/pull/5362#discussion_r695079714 for visibility.

> ... if you could retest after next build is deployed to preview

I'll keep an eye on the build[[1](https://werft.gitpod-dev.com/job/gitpod-build-at-gl.6)].

> I'll make a screenshot to the description as well

Thank you! 🙇

Comment (gtsiolis) [reply components/server/ee/src/gitlab/gitlab-app-support.ts]: @AlexTugarev I tested this again and works as expected. I can see the 101th repository. ✔️

**Review by gtsiolis — APPROVED** [review]
UX LGTM. Approving this but this will need an approval also from `@gitpod-io/engineering-webapp`.

File: components/server/ee/src/gitlab/gitlab-app-support.ts (hunk 3 above)
Comment (AlexTugarev) [reply components/server/ee/src/gitlab/gitlab-app-support.ts]: @gtsiolis, see the updated description. Also, sorry to have you seen the broken state in between. 🤦🏻‍♂️

File: components/server/src/gitlab/api.ts [hunk 6]
```diff
@@ -70,9 +71,12 @@ export class GitLabApi {
...
                 //     }
 
-                return new GitLab.ApiError(`GitLab Request Error: ${error?.description}`, error);
+                return new GitLab.ApiError(
+                    `GitLab Request Error: ${error?.description?.name || JSON.stringify(error?.description)}`,
+                    error,
+                );
             }
-            log.error(`GitLab request error`, error);
+            // log.error(`GitLab request error`, error);
```
Comment (svenefftinge) [inline components/server/src/gitlab/api.ts:79]: nit: can this be entirely deleted?

File: components/server/src/gitlab/api.ts [hunk 7]
```diff
@@ -219,11 +228,11 @@ export namespace GitLab {
...
     }
     // https://docs.gitlab.com/ee/api/users.html#list-current-user-for-normal-users
-    export interface User extends UserSchemaDefault {
+    export interface User extends UserExtendedSchema {
         email: string;
         state: "active" | string;
-        confirmed_at: string | undefined;
-        private_profile: boolean;
+        // confirmed_at: string | undefined;
+        // private_profile: boolean;
```
Comment (svenefftinge) [inline components/server/src/gitlab/api.ts:235]: nit: delete?

**Review by svenefftinge — APPROVED** [review]
I just read through the code, but haven't tested. Adding hold in case this needs more manual testing.

/hold

**Comment by metcalfc** [comment]
We have folks blocked on this for their evaluations. Please merge as soon as possible.

**Comment by AlexTugarev** [comment]
/werft run

Testing the GitLab features to get a sense of current state of GitLab features affected by this PR. 'Merging then, if nothing seems to be broken.
