### PR TITLE
[local-app] gracefully handle invalid token

### LINKED ISSUE #5368: local-app is crashing with old token
### Bug description

We need to detect it and invalidate token.

### Steps to reproduce

```
time="2021-08-25T09:40:19+02:00" level=info msg="writing workspace ssh_config file" ssh_config=/var/folders/5b/dtz20_cs0414cj898m1725pr0000gn/T/gitpod_ssh_config-89628-f8vKrNHDCwDn
time="2021-08-25T09:40:19+02:00" level=warning msg="cannot get workspace" WorkspaceID=aqua-wolverine-r61bvnkw error="jsonrpc2: code 403 message: not allowed"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1583421]

goroutine 10 [running]:
github.com/gitpod-io/local-app/pkg/bastion.(*Bastion).Update(0xc0001e1360, 0xc000332060, 0x17, 0x16a99a0)
        github.com/gitpod-io/local-app/pkg/bastion/bastion.go:259 +0x241
github.com/gitpod-io/local-app/pkg/bastion.(*LocalAppService).ResolveSSHConnection(0xc0000a4d08, 0x182f360, 0xc0003201b0, 0xc0003220f0, 0xc0000a4d08, 0xc0003201b0, 0xc00010dba0)
        github.com/gitpod-io/local-app/pkg/bastion/service.go:68 +0x49
github.com/gitpod-io/gitpod/local-app/api._LocalApp_ResolveSSHConnection_Handler(0x16b35e0, 0xc0000a4d08, 0x182f360, 0xc0003201b0, 0xc00031e1e0, 0x0, 0x182f360, 0xc0003201b0, 0xc000346080, 0x3f)
        github.com/gitpod-io/gitpod/local-app/api@v0.0.0-00010101000000-000000000000/localapp_grpc.pb.go:169 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fefc0, 0x18355b8, 0xc000116240, 0xc000166000, 0xc000268630, 0x1bd64d8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.39.1/server.go:1293 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001fefc0, 0x18355b8, 0xc000116240, 0xc000166000, 0x0)
        google.golang.org/grpc@v1.39.1/server.go:1618 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000037820, 0xc0001fefc0, 0x18355b8, 0xc000116240, 0xc000166000)
        google.golang.org/grpc@v1.39.1/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.39.1/server.go:939 +0x1fd
```

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #5368 by allowing the local app to validate the current token scopes against expected scopes. And if they don't match then invalidate the token and run auth flow again.

I had to move bearer auth into verify callback to return a proper error code during web socket handshake, instead of failing after web socket is established. It allows clients to analyse the bad hahdshake request for unauthorised access.

#### How to test

- Start a workspace: https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com/#github.com/akosyakov/parcel-demo
- Start the local app:
```
# mac
curl -OL https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com/static/bin/gitpod-local-companion-darwin
chmod +x ./gitpod-local-companion-darwin
GITPOD_HOST=https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com ./gitpod-local-companion-darwin --log-level=debug

# linux
# curl -OL https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com/static/bin/gitpod-local-companion-linux
chmod +x ./gitpod-local-companion-linux
GITPOD_HOST=https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com ./gitpod-local-companion-linux --log-level=debug

# windows
# curl -OL https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com/static/bin/gitpod-local-companion-windows.exe
GITPOD_HOST=https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com ./gitpod-local-companion-windows.exe --log-level=debug
```
- check that you went through the auth flow and output looks fine
- restart the app, checks that you don't need to go through the auth flow this time
- go and corrupt the token for https://akosyakov-local-app-is-crashing-5368.staging.gitpod-dev.com in keychain access
- restart the app, you should see the error that token is invalid and go through the auth flow again
- now corrupt tokens in the DB: `update d_b_gitpod_token set scopes = "";`
- restart the app, you should see the error that token is invalid and go through the auth flow again

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **akosyakov** after the PR has been reviewed.

Associated issue: *#5368*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue: *#5368*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5368*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
@csweichel Could you check it again? I rewrote getGitpodTokenScopes to accept the token hash.

File: components/local-app/main.go [hunk 1]
```diff
@@ -101,7 +110,12 @@ func main() {
 					if c.Bool("mock-keyring") {
 						keyring.MockInit()
 					}
-					return run(c.String("gitpod-host"), c.String("ssh_config"), c.Int("api-port"), c.Bool("allow-cors-from-port"), c.Bool("auto-tunnel"), c.String("auth-redirect-url"))
+					logLevel, err := logrus.ParseLevel(c.String("log-level"))
+					if err != nil {
+						logLevel = logrus.InfoLevel
+						logrus.WithError(err).WithField("logLevel", c.String("log-level")).Error("failed to parse log-level")
+					}
+					return run(c.String("gitpod-host"), c.String("ssh_config"), c.Int("api-port"), c.Bool("allow-cors-from-port"), c.Bool("auto-tunnel"), c.String("auth-redirect-url"), logLevel)
```
Comment (csweichel) [inline components/local-app/main.go:118]: nit: In most of our CLI's we introduced a `--verbose` flag which sets the log level to `debug`. What's the use-case to set the log level to something other than `debug` or `info`?

File: components/local-app/main.go [hunk 2]
```diff
@@ -196,23 +186,136 @@ func run(origin, sshConfig string, apiPort int, allowCORSFromPort bool, autoTunn
...
+
+type ErrInvalidGitpodToken struct {
+	cause error
+}
+
+func (e *ErrInvalidGitpodToken) Error() string {
+	return "invalid gitpod token: " + e.cause.Error()
+}
+
+func validateToken(client *gitpod.APIoverJSONRPC, tkn string) error {
```
Comment (csweichel) [inline components/local-app/main.go:293]: I would have expected this function to be part of the `auth` package - and be tested there (e.g. with a Gitpod client mock)

File: components/server/src/server.ts [hunk 3]
```diff
@@ -143,6 +143,17 @@ export class Server<C extends GitpodClient, S extends GitpodServer> {
                     log.warn("Websocket connection attempt with non-matching Origin header: " + info.origin)
                     return callback(false, 403);
                 }
+                if (info.req.url === '/v1') {
+                    try {
+                        await this.bearerAuth.auth(info.req as express.Request)
```
Comment (csweichel) [inline components/server/src/server.ts:148]: Why are we doing authentication in a CSRF guard?

**Review by csweichel — COMMENTED** [review]
Other than a couple of questions and a nit this looks good to me

File: components/local-app/main.go (hunk 1 above)
Comment (akosyakov) [reply components/local-app/main.go:118]: refactored to verbose

File: components/local-app/main.go (hunk 2 above)
Comment (akosyakov) [reply components/local-app/main.go:293]: moved to auth

File: components/server/src/server.ts (hunk 3 above)
Comment (akosyakov) [reply components/server/src/server.ts:148]: I will refactor it.

I moved it to the ws handshake to avoid opening a websocket at all for invalid token and propagate unauthorited error properly clients. Before we will establish the websocket and then close it without rejecting the handshake in the first place.

**Comment by akosyakov** [comment]
@csweichel Could you have a look again please? All comments should be addressed.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 99039cd043fb7f4830c96d1bb45e23c2fa7d53eb</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5369#issuecomment-909016894" title="LGTM">csweichel</a>*

Associated issue: *#5368*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [csweichel]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [csweichel]
- ~~[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)~~ [csweichel]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
