### PR TITLE
[gitpod-protocol] Remove HTTP headers from logs

### LINKED ISSUE #6919: remove logging of bearer token from reconnecting websocket
### Bug description

Right now they are logged as a part of https://github.com/gitpod-io/gitpod/blob/d86242978d0a23efeac7d6c7e5fe6b97d0e69c9f/components/gitpod-protocol/go/reconnecting-ws.go#L221

### Steps to reproduce

See above.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by corneliusludmann**
## Description
This is to avoid leaking bearer tokens in the logs.

/werft no-preview

## Related Issue(s)

Fixes #6919

## How to test

Just check the code changes. Nothing else to do.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue: *#6919*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Yes 💯 thank you for fixing this. 🙏 🏅

Logging headers is bad practice. If we need specific header values, I think we should log them individually.

/approve
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4adf287d2cfdd2c62c9a2980739b8db46d0f30b3</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6925#pullrequestreview-817118783" title="LGTM">jankeromnes</a>*

Associated issue: *#6919*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/gitpod-protocol/go/reconnecting-ws.go [hunk 1]
```diff
@@ -218,7 +218,7 @@ func (rc *ReconnectingWebsocket) connect(ctx context.Context) *WebsocketConnecti
 		if resp != nil {
 			statusCode = resp.StatusCode
 		}
-		rc.log.WithField("url", rc.url).WithField("headers", rc.reqHeader).Info("websocket handshake")
+		rc.log.WithField("url", rc.url).Info("websocket handshake")
```
Comment (akosyakov) [inline components/gitpod-protocol/go/reconnecting-ws.go:221]: I think this completely, since it does not add new info compare to next error message. It is also misleading, websocket handshake is only one part of establishing connection. I am not sure what `websocket handshake` supposed to mean.
