### PR TITLE
[server] don't always throw exception in deleteUser

### LINKED ISSUE #5262: Deleting account returns an error and does not log out the user properly
### Bug description

When a user tried to delete their account from the Account section in Settings the product returns an error in console and does not log out the user properly.

```js
Uncaught (in promise) Error: Request deleteAccount failed with message:
```

### Steps to reproduce

1. Go to [`/account`](https://gitpod.io/account)
2. Click _Delete Account_ button.
3. Type your email to confirm.
4. Click _Delete Account_.

### Expected behavior

The user should not see any error in the console and they should be properly logged out.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Fixes #5262

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#5262*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: afc681ebe5a329e2074dea9647ad3403adea8cae</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5289#issuecomment-902525981" title="LGTM">laushinka</a>*

Associated issue: *#5262*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [laushinka]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by laushinka — APPROVED** [review]

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5289#pullrequestreview-734801532" title="Approved">laushinka</a>*

Associated issue: *#5262*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [laushinka]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Thanks @JanKoehnlein for fixing this and @laushinka for reviewing! 🏓

File: components/server/ee/src/user/user-deletion-service.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export class UserDeletionServiceEE extends UserDeletionService {
         }
 
         await super.deleteUser(id);
-        if (errors) {
+        if (errors.length > 0) {
```
Comment (AlexTugarev) [inline components/server/ee/src/user/user-deletion-service.ts:64]: @JanKoehnlein, actually, after seeing more instances of this issue, I belief it's not a good idea in general to throw an error after `super.deleteUser` is actually done.
This leads to a state, where one's account is locked in a `deleted` state. This definitely requires proper handling in the frontend.

Comment (JanKoehnlein) [reply components/server/ee/src/user/user-deletion-service.ts:64]: I was mostly worried about users that have a GitHub-based subscription. They actually cannot cancel that subscription using our service, so they should get a message. Similar when Chargebee fails any reason. In any case, users wanted to delete their account so I thought it would be OK if that is the state on the Gitpod side. 

But I am all in for proper error propagation to the frontend. Just unsure which actions should be taken/rolled back on the Gitpod side if some of the error conditions are met.

Comment (AlexTugarev) [reply components/server/ee/src/user/user-deletion-service.ts:64]: That's not an easy issue to solve. While error propagation isn't the real adventure, to decide on the loose end is, especially because the account data will be deleted. 
Maybe we should not call `super.deleteUser` if there are issues to cancel subscription. AND propagate an error.
