### PR TITLE
[server] fix GitHub Education API call

### LINKED ISSUE #12203: fetching the GitHub Education API failed with status 401: Unauthorized
### Bug description

In most Gitpod installations (every one except production i.e. https://gitpod.io), we see these errors very frequently in the logs:

```
fetching the GitHub Education API failed with status 401: Unauthorized

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at EligibilityService.<anonymous> (/app/node_modules/@gitpod/server/dist/ee/src/user/eligibility-service.js:88:37)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@gitpod/server/dist/ee/src/user/eligibility-service.js:19:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

We don't think this error is problematic (it's just that checking the GitHub student status fails), however it's very noisy, and often distracts from "real problems" by acting as a "red herring" (i.e. investigate a new bug, check the logs, see this, report it -- but that wasn't the relevant error message).

We should probably fix it in dev to make our lives easier.

### Steps to reproduce

1. Use any Gitpod preview or staging environment
2. Check the server logs

### Workspace affected

_No response_

### Expected behavior

When checking the student status on GitHub fails, we shouldn't be as loud about it (either log a clear, minimal warning, or don't log anything at all).

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
This PR fixes parse errors when the GH Edu API call errors. 

## Related Issue(s)

Fixes #12203

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

File: components/server/ee/src/user/eligibility-service.ts [hunk 1]
```diff
@@ -94,8 +94,9 @@ export class EligibilityService {
                     logCtx,
                     `fetching the GitHub Education API failed with status ${rawResponse.status}: ${rawResponse.statusText}`,
                 );
+                return { student: false, faculty: false };
```
Comment (AlexTugarev) [inline components/server/ee/src/user/eligibility-service.ts:97]: adding the missing return avoids running into parse error.

**Review by svenefftinge — APPROVED** [review]
