### PR TITLE
[#4699] Handle error situations around /headless-logs endpoint

### LINKED ISSUE #4699: /headless-logs: unhandled request on prebuild
### Bug description

Instead of displaying a prebuild's log this error is raised when waiting for a prebuild for https://gitpod.io/#https://github.com/gitpod-io/template-k3s:

```
{"error":"Error: Unhandled request: GET /headless-logs/b64fe93d-a812-4028-af3e-a0c6ec1ab577/\nStack: Error: Unhandled request: GET /headless-logs/b64fe93d-a812-4028-af3e-a0c6ec1ab577/\n    at /app/node_modules/@gitpod/server/dist/src/server.js:163:29\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at /app/node_modules/express/lib/router/index.js:635:15\n    at next (/app/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/app/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at /app/node_modules/express/lib/router/index.js:635:15\n    at next (/app/node_modules/express/lib/router/index.js:260:14)\n    at BearerAuth.<anonymous> (/app/node_modules/@gitpod/server/dist/src/auth/bearer-authenticator.js:77:20)\n    at Generator.throw (<anonymous>)\n    at rejected (/app/node_modules/@gitpod/server/dist/src/auth/bearer-authenticator.js:20:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
```

image

There are two things broken here:
 1. the rendered URL is off
 2. the broken URL leads this exception being displayed

/cc @ghuntley (original reporter)

### Steps to reproduce

 1. https://gitpod.io/#https://github.com/gitpod-io/template-k3s
 2. :boom: 

### Expected behavior

The log of the prebuild should be displayed.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by geropl**
Fixes #4699.

## Test

 1. create and environment variable: https://gpl-4699-headless-log.staging.gitpod-dev.com/workspaces/
   - name: PREBUILD_PARAMS
   - value: 100_1s_1m_success
   - repo: gitpod-io/gitpod
 2. run a prebuild: https://gpl-4699-headless-log.staging.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/gitpod/tree/gpl/test-prebuild
   - notice how logs work

### CODE REVIEW

File: components/server/src/workspace/headless-log-controller.ts [hunk 1]
```diff
@@ -127,6 +127,16 @@ export class HeadlessLogController {
                 res.end();
             }
         }));
+        router.get("/", (req: express.Request, res: express.Response) => {
+            // This is an error case: every request should match the handler above
+            const user = req.user as User;
```
Comment (AlexTugarev) [inline components/server/src/workspace/headless-log-controller.ts:132]: should we test for `User.is(req.user)`? 
unauthorized requests should be blocked, no?

File: components/server/src/workspace/gitpod-server-impl.ts [hunk 2]
```diff
@@ -1183,7 +1183,7 @@ export class GitpodServerImpl<Client extends GitpodClient, Server extends Gitpod
         }
 
         const sources = await this.workspaceLogService.getWorkspaceLogURLs(wsi);
-        if (!sources) {
+        if (!sources || Object.keys(sources.streams).length === 0) {
```
Comment (AlexTugarev) [inline components/server/src/workspace/gitpod-server-impl.ts:1186]:
```suggestion
        if (!sources || typeof sources.streams === "object" && Object.keys(sources.streams).length === 0) {
```

just to prevent the `undefined` case

File: components/gitpod-protocol/src/workspace-instance.ts [hunk 3]
```diff
@@ -27,12 +27,15 @@ export interface WorkspaceInstance {
     stoppedTime?: string;
 
     // ideUrl is the URL at which the workspace is available on the internet
+    // Note: this is nitially empty, filled during starting process!
```
Comment (AlexTugarev) [inline components/gitpod-protocol/src/workspace-instance.ts:30]: IMO this should be an optional attribute then.

**Review by AlexTugarev — APPROVED** [review]
Works as advertised! 👍🏻 

Please have a look a the comments left.

File: components/gitpod-protocol/src/workspace-instance.ts (hunk 3 above)
Comment (geropl) [reply components/gitpod-protocol/src/workspace-instance.ts:30]: Definitely. This variance was a side-effect of the introduction of `ws-manager`, and has been this way ever since. Won't change that in the scope of this PR.
