### PR TITLE
[ws-scheduler] List pods from _all_ namespaces when calculating available resources

### LINKED ISSUE #2341: [ws-scheduler] Race condition during scheduling
### Describe the bug
`ws-scheduler` has two goroutines to do the actual scheduling work. Those can race if either:
 a) the scheduling takes longer
 b) a lot of workspaces are started in the same timeframe

Instead it should have one single goroutine to do the actual scheduling.

### Steps to reproduce
 - start a lot (>100) workspace in a short period of time (<1s)

### Expected behavior
`ws-scheduler` should hum along.

### Example repository
N/A

### PR DESCRIPTION
**Pull request by geropl**
Fixes #2341.

### Test:
 - verify that regular scheduling works: http://gpl-fix-ws-scheduler-race.staging.gitpod-dev.com/#https://github.com/gitpod-io/django-locallibrary-tutorial
 - check the beginning of `ws-scheduler` logs and verify that in the list of messages reading `removed from localBindingCache` pods from other namespaces (especially `kube-system`) are listed as well

### CODE REVIEW

File: components/ee/ws-scheduler/pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -342,8 +342,10 @@ func (s *Scheduler) buildState(ctx context.Context, pod *corev1.Pod) (state *Sta
 		return nil, err
 	}
 
-	// We need to take _all_ pods into account to accurately calculate available RAM per node
-	allPods, podsErr := s.pods.Lister().List(labels.Everything())
+	// We need to take into account _all_ pods in _all_ namespaces to accurately calculate available RAM per node
+	// NOTE: .Pods("") - in contrast to omitting it and calling .Lister().List(...) directly - means:
+	//       List from _all_ namespaces !!!
+	allPods, podsErr := s.pods.Lister().Pods("").List(labels.Everything())
```
Comment (csweichel) [inline components/ee/ws-scheduler/pkg/scheduler/scheduler.go:348]: it would make sense to use `metav1.NamespaceAll` here to clearly communicate that we're asking for all namespaces

**Review by csweichel — APPROVED** [review]
Other than the comment, LGTM

File: components/ee/ws-scheduler/pkg/scheduler/scheduler.go (hunk 1 above)
Comment (geropl) [reply components/ee/ws-scheduler/pkg/scheduler/scheduler.go:348]: Ah, der is a constant for it! Nice.
