### PR TITLE
fixes for task terminals

### LINKED ISSUE #2086: verbose output from gitpod task terminals on attach
Now:
```
gitpod /workspace/contribute.dev $ /.supervisor/supervisor terminal attach -ir e007120c-0454-40b9-95db-eba039816da6
{"message":"enabled JSON logging","serviceContext":{"service":"supervisor","version":""},"severity":"info","time":"2020-10-29T12:16:01Z"}
{"message":"enabled verbose logging","serviceContext":{"service":"supervisor","version":""},"severity":"info","time":"2020-10-29T12:16:01Z"}
 HISTFILE=/workspace/.gitpod/cmd-0 history -r; {

yarn install && yarn build

} && {

yarn start

}

bash: rustc: command not found
bash: /etc/bash_completion.d/cargo: No such file or directory
bash: rustc: command not found
bash: /etc/bash_completion.d/cargo: No such file or directory
gitpod /workspace/contribute.dev $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> 
> yarn install && yarn build
> 
> } && {
> 
> yarn start
> 
> }
```
Compare to production:
```
gitpod /workspace/contribute.dev $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn install && yarn build
> } && {
> yarn start
> }
```

### LINKED ISSUE #2208: [theia] Terminals are opened unreliably on staging
With staging, I have seen a workspace (this repo) where I only got one terminal and now I also got one where the layout was messed up (see picture below, the terminals should be side-by-side). I believe there is some timing issue or so.

Screenshot 2020-11-18 at 16 46 49

### LINKED ISSUE #2265: [prebuild] Running prebuild on repo without task makes it hang
Try: https://gitpod-staging.com/#prebuild/https://github.com/jankeromnes/hugo-gitpod and see how the process hangs.

The `.gitpod.yml` doesn't have an init so prebuild should be a no-op.

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #2086:
  - align shell with current IDE expectations
  - remove unnecessary line delimiters in task commands
- fix #2208: ensure task status order
- always run task terminals for regular workspaces to avoid closing terminals on workspace restart
- redirect from the prebuild to a workspace on the start page only when the prebuild is stopped to avoid opening a workspace without the prebuild
- don't hang the create page if the prebuild is done but not available
- resolved the read/write deadlock for task terminals
- fix #2265: ensure that headless tasks done is reported always

#### How to test

- Start a regular workspace and check task output: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod
- Restart this workspace and check that terminals are not gone.
- Start a prebuild workspace and check task output: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/gitpod
  - regular to test create page: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod
- Check that both terminals history is proper after prebuilt is done.
- Run a prebuild on the repo without init tasks: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#prebuild/https://github.com/jankeromnes/hugo-gitpod
  - regular to test create page: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#https://github.com/jankeromnes/hugo-gitpod
- Run a prebuild on the repo with failing init task: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#prebuild/https://github.com/akosyakov/test-maven-repo/tree/failed_prebuild
  - regular to test create page: http://akosyakov-verbose-output-from-gitpod-2086.staging.gitpod-dev.com/#https://github.com/akosyakov/test-maven-repo/tree/failed_prebuild

### CODE REVIEW

**Comment by svenefftinge** [comment]
I cannot start a workspace on the preview app. 
Screenshot 2020-11-23 at 09 03 33

**Comment by svenefftinge** [comment]
Stopping workspaces doesn't work anymore. I get:
Screenshot 2020-11-23 at 17 09 23

**Comment by svenefftinge** [comment]
But only for this repo. spring-petclinic works well

**Comment by akosyakov** [comment]
I will look into https://github.com/gitpod-io/gitpod/pull/2205#issuecomment-732266073 but I don't think it is related to this PR. cc @csweichel

**Comment by csweichel** [comment]
> I will look into [#2205 (comment)](https://github.com/gitpod-io/gitpod/pull/2205#issuecomment-732266073) but I don't think it is related to this PR. cc @csweichel

Indeed, it looks like this PR is not the cause for the stopping issue.

For future reference: it would be a tremendous help to post the trace along with the screenshot. Jaeger can export the trace JSON, s.t. we still have that information after sweeper removed the preview env.

**Comment by csweichel** [comment]
image

Looks like an infrastructure issue.

**Comment by svenefftinge** [comment]
> For future reference: it would be a tremendous help to post the trace along with the screenshot. Jaeger can export the trace JSON, s.t. we still have that information after sweeper removed the preview env.

Sure! It is not obvious how to do that, though. Can you write down a short how-to somewhere?

**Review by svenefftinge — DISMISSED** [review]
Works much better now :-)

File: components/supervisor/pkg/supervisor/tasks.go [hunk 1]
```diff
@@ -213,7 +210,13 @@ func (tm *tasksManager) Run(ctx context.Context, wg *sync.WaitGroup) {
 		if t.config.Env != nil {
 			openRequest.Env = *t.config.Env
 		}
-		resp, err := tm.terminalService.Open(ctx, openRequest)
+		var ReadTimeout time.Duration
```
Comment (csweichel) [inline components/supervisor/pkg/supervisor/tasks.go:213]:
```suggestion
var readTimeout time.Duration
```

File: components/supervisor/pkg/terminal/service.go [hunk 2]
```diff
@@ -21,10 +22,18 @@ import (
 
 // NewMuxTerminalService creates a new terminal service
 func NewMuxTerminalService(m *Mux) *MuxTerminalService {
+	shell := os.Getenv("SHELL")
+	if shell == "/bin/false" {
```
Comment (csweichel) [inline components/supervisor/pkg/terminal/service.go:26]: Who sets shell to `/bin/false`, i.e. why is this a case that we need to handle?
Maybe a comment that clarifies this case would be handy.

File: components/supervisor/pkg/terminal/service.go [hunk 3]
```diff
@@ -48,15 +58,22 @@ func (srv *MuxTerminalService) RegisterREST(mux *runtime.ServeMux, grpcEndpoint
...
 func (srv *MuxTerminalService) Open(ctx context.Context, req *api.OpenTerminalRequest) (*api.OpenTerminalResponse, error) {
-	cmd := exec.Command(srv.LoginShell[0], srv.LoginShell[1:]...)
+	return srv.OpenWithOptions(ctx, req, TermOptions{
+		ReadTimeout: 5 * time.Second,
+	})
+}
+
+// OpenWithOptions opens a new terminal running the shell with given options
+func (srv *MuxTerminalService) OpenWithOptions(ctx context.Context, req *api.OpenTerminalRequest, options TermOptions) (*api.OpenTerminalResponse, error) {
+	cmd := exec.Command(srv.DefaultShell, "-i")
```
Comment (csweichel) [inline components/supervisor/pkg/terminal/service.go:70]: This makes the assumption that all shells anyone would want to use as `SHELL` support `-i`.
I couldn't find/google prior conventions for the SHELL variable, i.e. if others would include the `-i` in the SHELL command, or add it like we do here.

File: components/supervisor/pkg/terminal/terminal.go [hunk 4]
```diff
@@ -176,11 +196,24 @@ func (l *multiWriterListener) Done() <-chan struct{} {
 	return l.closeChan
 }
 
+type closedTerminalListener struct {
+}
+
+func (closedTerminalListener) Read(p []byte) (n int, err error) {
+	return 0, errors.New("terminal is closed")
```
Comment (csweichel) [inline components/supervisor/pkg/terminal/terminal.go:203]: we're implementing `io.Reader` whose contract mandates we return `io.EOF` in this case.

```
return 0, io.EOF
```

**Review by csweichel — COMMENTED** [review]
Good stuff ... changes work nicely :)

File: components/supervisor/pkg/terminal/service.go (hunk 2 above)
Comment (akosyakov) [reply components/supervisor/pkg/terminal/service.go:26]: I copied it from VS Code but I will revert it till we have a real issue

File: components/supervisor/pkg/terminal/service.go (hunk 3 above)
Comment (akosyakov) [reply components/supervisor/pkg/terminal/service.go:70]: I will drop `-i`

File: components/supervisor/pkg/supervisor/tasks_test.go [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+						GitpodTasks:    gitpodTasks,
+						GitpodHeadless: strconv.FormatBool(test.Headless),
+					},
+				}, terminalService, contentState, &reporter)
+			)
+			taskManager.storeLocation = storeLocation
+			contentState.MarkContentReady(test.Source)
+			var wg sync.WaitGroup
+			wg.Add(1)
+			taskManager.Run(context.Background(), &wg)
```
Comment (csweichel) [inline components/supervisor/pkg/supervisor/tasks_test.go:132]: there's no `wg.Wait()` ... is that intentional?

Comment (akosyakov) [reply components/supervisor/pkg/supervisor/tasks_test.go:132]: run is blocking, but i can add it just to be sure

Comment (csweichel) [reply components/supervisor/pkg/supervisor/tasks_test.go:132]: makes sense. Either `wg.Wait()` or a comment would be handy :)

**Comment by akosyakov** [comment]
There is one known issue for failed prebuilds that they cannot display properly stopping screen. It is because of https://github.com/gitpod-io/gitpod/issues/2274

**Comment by csweichel** [comment]
- ✅ regular workspace
- regular prebuild
  - ✅ logs during prebuild
  - ❌  workspace opens prebuild: workspace started without the prebuild
- regular prebuild create workspace during prebuild:
  - ✅  logs during prebuild
  - ❌  workspace opens prebuild: workspace started without the prebuild
- prebuild without init task (also for its "create workspace during prebuild"):
  - ✅  prebuild runs, workspace starts
  - ❓ workspace has no terminals, is that ok?
  image
- prebuild with failing init task
  - ✅  logs during prebuild
  - ❌  workspace opens prebuild: workspace started without the prebuild
  - ❓ workspace has no terminals, is that ok?
- prebuild with failing init task create workspace during prebuild:
  - ✅  logs during prebuild
  - ❌  workspace opens prebuild: workspace started without the prebuild
  - ❓ workspace has no terminals, is that ok?
- prebuild with failing init task create workspace **after** prebuild:
  - ❌  workspace opens prebuild: workspace started without the prebuild
  - ❓ workspace has no terminals, is that ok?

**Comment by akosyakov** [comment]
@csweichel could you try again please

you were right btw about failing init case, there should be a terminal if we open from such prebuild, since init is not executed then by a regular workspace

**Review by csweichel — APPROVED** [review]
Awesome. Works nicely now!
