### PR TITLE
[server] Wait for image build logs in preparing state

### LINKED ISSUE #14862: [image-builder-mk3] Unable to fetch build logs for build that waited on node scale-up
### Bug description

`image-builder-mk3` is unable to fetch and stream back image build logs from an image build that had to wait for a node to scale up.

`image-builder-mk3` keeps retrying [here](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-mk3/pkg/orchestrator/monitor.go#L396), trying to get the build logs from the workspace supervisor task URL, but keeps timing out during retries (even when the build workspace is eventually running).

The timeout error is:
```
Get \"https://13fd7139-7af3-457d-9002-90212800b042.ws-ephemeral-wout.gitpod.io/_supervisor/v1/status/tasks\": dial tcp 34.79.xxx.xxx:443: i/o timeout
```

Interestingly, later image builds do stream back logs, when they did not have to wait for a node to scale up.

### Steps to reproduce

- Enable the `movedImageBuilder` feature flag for your user
- Ensure the headless node pool has no schedulable nodes (to ensure new image build waits for node scale up)
- Create a new image build: https://gitpod.io/#imagebuild/github.com/gitpod-io/gitpod
- Observe no image build logs are shown in the browser
- Workspace still starts up fine

### Workspace affected

_No response_

### Expected behavior

Image build logs are shown for image builds that waited for node scale up

### Example repository

_No response_

### Anything else?

Recent improvements to `workspace-preview` will make it easy to add a governed workspace single node cluster to a meta single node cluster, cordon the workspace one, and do your related testing.

### PR DESCRIPTION
**Pull request by WVerlaek**
## Description

Fixes image build logs from showing up in the dashboard if the build is delayed.

When a workspace's image build is delayed (due to e.g. waiting for a node to scale up), the workspace instance stays in a `preparing` state, it only moves to `building` once the build is actually running. Previously, the logic would stop retrying for build logs if it's not in a `building` state, this PR changes it to also wait for build logs while in a `preparing` state

## Related Issue(s)

Fixes #14862

## How to test

In a preview environment:
- Cordon the preview environment's node
- Create a new image build (e.g. `https://<your-preview-env>.preview.gitpod-dev.com/#imagebuild/github.com/gitpod-io/gitpod`
- Wait a few minutes (an image build workspace gets created, but gets stuck in a pending state)
- Uncordon the node
- Observe that the image build runs, and logs are shown on the dashboard

## Release Notes

```release-note
Fix image build logs not showing in the dashboard if the build is delayed.
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

File: components/dashboard/debug.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/bin/bash
+# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
+# Licensed under the GNU Affero General Public License (AGPL).
+# See License.AGPL.txt in the project root for license information.
+
+set -Eeuo pipefail
+source /workspace/gitpod/scripts/ws-deploy.sh deployment dashboard
```
Comment (WVerlaek) [inline components/dashboard/debug.sh:7]: added this script as well which was useful in iterating on the dashboard component in a preview environment, the script is also present in `components/server` already

**Review by AlexTugarev — APPROVED** [review]
Thanks! 
That change makes sense.

**Comment by mads-hartmann** [comment]
/hold
CI is not passing so the merge queue is blocked. Adding hold ☺️
