### PR TITLE
[server] ensure that user that has PVC enabled will not force prebuilds into PVC use

### LINKED ISSUE #11769: [PVC] trigger prebuild affected all the users without PVC feature flag enabled
### Bug description

While testing PVC + prebuild, we enable the PVC feature flag internally (without enabling PVC on the project).
image
image

Then force the trigger to prebuild on repos. For example
- gitpod.io/#prebuild/https://gitlab.com/gitpod-io/template-python-flask
- gitpod.io/#prebuild/https://gitlab.com/gitpod-io/template-python-django

After that, all the users open the above repos https://gitlab.com/gitpod-io/template-python-flask, https://gitlab.com/gitpod-io/template-python-django makes the user use the PVC feature as well, which means the PVC and VolumeSnapshot object be created within the cluster. Furthermore, since we internal use the XL pool (PVC size is 50Gi), the normal user can't start the workspace because the user's PVC size is 30Gi which causes the PVC restore failure.

### Steps to reproduce

1. Enable PVC feature flag.
2. Manually retrigger prebuild.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by sagor999**
## Description

ensure that user that has PVC enabled will not force prebuilds to use them on projects that don't have PVC turned on

## Related Issue(s)

Fixes #11769 

## Release Notes

```release-note
none
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/server/ee/src/workspace/workspace-starter.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export class WorkspaceStarterEE extends WorkspaceStarter {
         user: User,
         excludeFeatureFlags: NamedWorkspaceFeatureFlag[],
         ideConfig: IDEConfig,
-        forcePVC: boolean,
+        PVCEnabledForPrebuilds: boolean,
```
Comment (geropl) [inline components/server/ee/src/workspace/workspace-starter.ts:27]: nit: function args are always lower case. So this would be `pvcEnabledForPrebuilds`. :+1:

File: components/server/src/workspace/workspace-starter.ts [hunk 2]
```diff
@@ -828,8 +828,15 @@ export class WorkspaceStarter {
...
-            if (forcePVC === true) {
-                featureFlags = featureFlags.concat(["persistent_volume_claim"]);
+            if (workspace.type === "prebuild") {
+                if (PVCEnabledForPrebuilds === true) {
+                    featureFlags = featureFlags.concat(["persistent_volume_claim"]);
+                } else {
+                    // If PVC is disabled for prebuilds, we need to remove the PVC feature flag.
+                    // This is necessary to ensure if user has PVC enabled on their account, that they
+                    // will not hijack prebuild with PVC and make everyone who use this prebuild to auto enroll into PVC feature.
+                    featureFlags = featureFlags.filter((f) => f !== "persistent_volume_claim");
```
Comment (geropl) [inline components/server/src/workspace/workspace-starter.ts:838]: :+1:

**Review by geropl — APPROVED** [review]
Code LGTM*

/hold

*but holding bc I'd love to see [this nit](https://github.com/gitpod-io/gitpod/pull/12165#discussion_r947488754) fixed. :pray:

File: components/server/src/workspace/workspace-starter.ts (hunk 2 above)
Comment (jenting) [reply components/server/src/workspace/workspace-starter.ts:838]: 💯
