### PR TITLE
[dashboard] fixing redirects

### LINKED ISSUE #16243: Redirect back to /workspaces when selecting a different org when users are viewing project related pages
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16164#discussion_r1094720611, when users are viewing project related pages and select a different org, the dashboard redirects to an error page.

### Proposal

Re-posting from https://github.com/gitpod-io/gitpod/pull/16164#discussion_r1096516815:

> @svenefftinge: It now properly changes to the "unknown project" when switching. It should redirect to /projects or so if no such project exists. But let's do this in a follow up.

| Viewing a project | Selecting a different org |
|-|-|
| Screenshot 2023-02-06 at 5 29 09 PM | Screenshot 2023-02-06 at 5 29 16 PM |

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

Redirects to the right project (and org) for project URLs that don't exist.
Fixes redirect fro /tokens and /tokens/create

## Related Issue(s)

Fixes #16243

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@svenefftinge: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by svenefftinge** [comment]
/werft run with-gce-vm=true recreate-preview=true with-preview=true

File: components/dashboard/src/projects/project-context.tsx [hunk 1]
```diff
@@ -66,9 +77,24 @@ export function useCurrentProject(): Project | undefined {
 
             // Find project matching with slug, otherwise with name
             const project = projects.find((p) => Project.slug(p) === slugs.projectSlug);
+            if (!project && teams) {
```
Comment (selfcontained) [inline components/dashboard/src/projects/project-context.tsx:80]: Should we also check their personal account's projects?

File: components/dashboard/src/projects/project-context.tsx [hunk 2]
```diff
@@ -66,9 +77,24 @@ export function useCurrentProject(): Project | undefined {
...
+                // check other orgs
+                for (const t of teams) {
+                    if (t.id === team?.id) {
+                        continue;
+                    }
+                    const projects = await listAllProjects({ teamId: t.id });
+                    const project = projects.find((p) => Project.slug(p) === slugs.projectSlug);
+                    if (project) {
+                        // redirect to the other org
+                        history.push(location.pathname + "?org=" + t.id);
```
Comment (selfcontained) [inline components/dashboard/src/projects/project-context.tsx:90]: If you're on a project page, and try to switch orgs, because the org selector menu uses the current page as the link, you end up just getting redirected back to the project you were on and the org you were on. 

We can fix this by changing those org selector links to just link to `/workspaces?org=${orgId}` and not try to maintain the current page. Conversation [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1675800615601449).

**Review by selfcontained — CHANGES_REQUESTED** [review]
A couple small comments, and one bug to check out w/ not being able to change orgs from a project page.

**Review by gtsiolis — APPROVED** [review]
UX LGTM.

Holding for addressing requested changed.

/hold

File: components/dashboard/src/projects/project-context.tsx (hunk 2 above)
Comment (gtsiolis) [reply components/dashboard/src/projects/project-context.tsx:90]: This worked fine on the first attempt, redirecting you to the projects (list) of the second org, but after that I now always run into the same issue as described above.

> If you're on a project page, and try to switch orgs, because the org selector menu uses the current page as the link, you end up just getting redirected back to the project you were on and the org you were on.

Nice catch, @selfcontained! ⚾

Comment (svenefftinge) [reply components/dashboard/src/projects/project-context.tsx:90]: So changing the org selector should always navigate to the workspaces list?

Comment (gtsiolis) [reply components/dashboard/src/projects/project-context.tsx:90]: @svenefftinge Redirecting to a default page within the new org selected changes the context or path for the whole page, see https://github.com/gitpod-io/gitpod/issues/16243. ✔️ 

Keeping the user on the project page but updating the navigation context can create a slight confusion on whether the project belongs to the new org selected, as we've moved away from the breadcrumb pattern. ❌
 
We could introduce a breadcrumb line above the page header (project title) but still, updating only the navigation to a new context does not seem much helpful, right? 💡

**Comment by svenefftinge** [comment]
I have addressed all feedback

**Comment by gtsiolis** [comment]
LGTM. Taking a bias for action and merging this—we can open follow-up issues or PRs for any nitpicks.

/unhold

**Comment by gtsiolis** [comment]
@selfcontained Seems like you will have to approve this to get this merged. 🏓

**Review by selfcontained — APPROVED** [review]
Change lgtm - fixes the org switching issue, and checks personal projects as well now.
