### PR TITLE
Remove checkoutLocation from StartWorkspaceReq

### LINKED ISSUE #7370: Source changes not reflected in dashboard overview
### Bug description

Source changes not reflected in dashboard overview

CleanShot 2021-12-27 at 14 23 23
CleanShot 2021-12-27 at 14 23 36
CleanShot 2021-12-27 at 14 23 32

Happened to 2 different workspaces, one older, one brand new.

### Steps to reproduce

I reproduced by simply making changes in a workspace and then checked the dashboard.

### Workspace affected

blue-raccoon-uzfqkexx

### Expected behavior

It's really important that the changes are shown in the column, or that the column is not there (either is fine), since I trusted it and deleted a workspace that unfortunately had changes in it.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR removes the redundant `checkoutLocation` field from the `StartWorkspace` request. Checkout location is a concept that exists on the content initializer, not on the workspace itself.

## Related Issue(s)

Fixes #7370
Related #8888

## How to test
- Create new workspace
- Modify or create a new file
- Stop the workspace
- Navigate to dashboard -> changes are displayed for the workspace
- Start the workspace again
- Stop the workspace
- Navigate to dashboard -> changes should still be displayed for the workspace

## Release Notes

```release-note
Ensure uncommitted changes are displayed in dashboard when workspace was restored from backup
```

### CODE REVIEW

**Comment by Furisto** [comment]
@csweichel I have fixed the outstanding issues.

File: components/ws-manager-api/typescript/src/core_grpc_pb.d.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2021 Gitpod GmbH. All rights reserved.
+ * Copyright (c) 2022 Gitpod GmbH. All rights reserved.
```
Comment (sagor999) [inline components/ws-manager-api/typescript/src/core_grpc_pb.d.ts:2]: I believe we should not be updating copyright year on existing files.

File: components/ws-manager-api/typescript/src/core_grpc_pb.js [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2021 Gitpod GmbH. All rights reserved.
+ * Copyright (c) 2022 Gitpod GmbH. All rights reserved.
```
Comment (sagor999) [inline components/ws-manager-api/typescript/src/core_grpc_pb.js:2]: same here. do not update copyright year on existing file.

File: components/ws-manager-api/typescript/src/core_grpc_pb.d.ts (hunk 1 above)
Comment (csweichel) [reply components/ws-manager-api/typescript/src/core_grpc_pb.d.ts:2]: > I believe we should not be updating copyright year on existing files.

That's 💯 correct.

That said, the auto-generated files will automatically update because they're autogenerated without headers, and the headers are added in afterwards. We could manually correct that, but chances are it will just happen the next time around.

**Review by aledbf — DISMISSED** [review]
LGTM

**Review by sagor999 — DISMISSED** [review]

**Review by easyCZ — APPROVED** [review]
This is a good example where the change could be across multiple PRs.
1. Just proto changes and generated code
2. The updated logic

Change works according to tests specified.

File: components/server/src/workspace/workspace-starter.ts [hunk 3]
```diff
@@ -1317,7 +1316,11 @@ export class WorkspaceStarter {
         const disp = new DisposableCollection();
 
         if (mustHaveBackup) {
-            result.setBackup(new FromBackupInitializer());
+            const backup = new FromBackupInitializer();
+            if (CommitContext.is(context)) {
+                backup.setCheckoutLocation(context.checkoutLocation || "");
```
Comment (geropl) [inline components/server/src/workspace/workspace-starter.ts:1321]: Shouldn't we default to "."? : 🤔

Comment (geropl) [reply components/server/src/workspace/workspace-starter.ts:1321]: Being picky here bc we had an incident after the last change in the multirepo PR

Comment (geropl) [reply components/server/src/workspace/workspace-starter.ts:1321]: > Shouldn't we default to "."?

Also in all cases, even if not a `CommitContext`?

**Comment by csweichel** [comment]
had to rebase. @easyCZ @sagor999 @aledbf could you re-approve please?

**Review by easyCZ — APPROVED** [review]

File: components/server/src/workspace/workspace-starter.ts (hunk 3 above)
Comment (geropl) [reply components/server/src/workspace/workspace-starter.ts:1321]: @csweichel Could you double-check here?

**Review by sagor999 — APPROVED** [review]

**Review by geropl — APPROVED** [review]
