### PR TITLE
[server, dashboard] Fix usage and parsing of ws.ontextURL

### LINKED ISSUE #8097: Workspace list stays blank when displaying `git` contextURLs
Example

image

/cc @jankeromnes

### PR DESCRIPTION
**Pull request by geropl**
## Description
 1. Never fail when trying to parse `contextURL`
 2. prefer `normalizedContextURL` if present
 3. if `normalizedContextURL` is not present, try to parse it from `contextURL`
 3. ~handle broken "git@github:" contextURLs in the DB (@jankeromnes )~ Done with #8100

## Related Issue(s)

Fixes #8097

## Release Notes

```release-note
fix dashboard contextURL handling
```

### CODE REVIEW

File: components/gitpod-protocol/src/context-url.ts [hunk 1]
```diff
@@ -4,41 +4,88 @@
...
+      const u = removePrefixes(ws.contextURL);
+      if (u) {
+        return u;
+      }
+    } catch (err) {
+      console.error(err);
+    }
+
+    return undefined;
+  }
```
Comment (jankeromnes) [inline components/gitpod-protocol/src/context-url.ts:57]: I agree that in most cases we should prefer `ws.context.normalizedContextURL`. However, isn't it a little overkill to have two different methods, `getNormalized` and `getNormalizedURL`?

I think I would prefer having just `getNormalizedURL` to keep this protocol helper as simple as possible. _(Side note: I find the function name `getNormalized(workspace)` a little bit ambiguous, and had to read the code to understand what it does.)_

File: components/dashboard/src/start/StartWorkspace.tsx [hunk 2]
```diff
@@ -226,9 +226,9 @@ export default class StartWorkspace extends React.Component<StartWorkspaceProps,
 
     // Successfully stopped and headless: the prebuild is done, let's try to use it!
     if (!error && workspaceInstance.status.phase === 'stopped' && this.state.workspace?.type !== 'regular') {
-      const contextURL = ContextURL.parseToURL(this.state.workspace?.contextURL);
+      const contextURL = ContextURL.getNormalized(this.state.workspace, false);
```
Comment (jankeromnes) [inline components/dashboard/src/start/StartWorkspace.tsx:229]: Shouldn't this actually "fall back to raw" when there is no normalizedContextURL? 🤔

Could also be simplified:

```ts
this.redirectTo('/' + (this.state.workspace?.context?.normalizedContextURL || this.state.workspace?.contextURL)
```

**Comment by akosyakov** [comment]
Maybe also update all places in the dashboard where  `workspace.contextUrl` as user facing is used with this new method.

File: components/dashboard/src/admin/WorkspaceDetail.tsx [hunk 3]
```diff
@@ -63,7 +63,7 @@ export default function WorkspaceDetail(props: { workspace: WorkspaceAndInstance
                 <div className="flex w-full mt-6">
                     <Property name="Created">{moment(workspace.workspaceCreationTime).format('MMM D, YYYY')}</Property>
                     <Property name="Last Start">{moment(workspace.instanceCreationTime).fromNow()}</Property>
-                    <Property name="Context"><a className="text-blue-400 dark:text-blue-600 hover:text-blue-600 dark:hover:text-blue-400" href={ContextURL.parseToURL(workspace.contextURL)?.toString()}>{workspace.context.title}</a></Property>
+                    <Property name="Context"><a className="text-blue-400 dark:text-blue-600 hover:text-blue-600 dark:hover:text-blue-400" href={ContextURL.getNormalized(workspace)}>{workspace.context.title}</a></Property>
```
[the remark this answers is not in the document]
Comment (geropl) [reply components/dashboard/src/admin/WorkspaceDetail.tsx:66]: IMO the expectation here is to go the context, not open the workspace.

File: components/gitpod-protocol/src/context-url.ts [hunk 4]
```diff
@@ -4,41 +4,88 @@
...
+import { Workspace } from ".";
+
 export namespace ContextURL {
   export const INCREMENTAL_PREBUILD_PREFIX = "incremental-prebuild";
   export const PREBUILD_PREFIX = "prebuild";
   export const IMAGEBUILD_PREFIX = "imagebuild";
+  export const SNAPSHOT_PREFIX = "snapshot";
   export const REFERRER_PREFIX = 'referrer:';
 
+  export function getNormalized(ws: Pick<Workspace, "context" | "contextURL"> | undefined, fallbackToRaw: boolean = true): string | undefined {
```
[the remark this answers is not in the document]
Comment (geropl) [reply components/gitpod-protocol/src/context-url.ts:16]: Agreed. The motivation here was to make no external changes at all to minimize the PR surface. But will change now that we have more time to polish this.

File: components/gitpod-protocol/src/context-url.ts (hunk 1 above)
Comment (geropl) [reply components/gitpod-protocol/src/context-url.ts:57]: Same answer as here: https://github.com/gitpod-io/gitpod/pull/8099#discussion_r801868556

File: components/dashboard/src/start/StartWorkspace.tsx (hunk 2 above)
Comment (geropl) [reply components/dashboard/src/start/StartWorkspace.tsx:229]: I don't think so: In case the workspace was a prebuild, we now want to start a fresh workspace on it's context and leverage it (cmp. comment 2 lines above).

**Comment by geropl** [comment]
> Maybe also update all places in the dashboard where workspace.contextUrl as user facing is used with this new method.

@akosyakov Excellent point, will do.

File: components/dashboard/src/start/CreateWorkspace.tsx [hunk 5]
```diff
@@ -163,14 +163,17 @@ export default class CreateWorkspace extends React.Component<CreateWorkspaceProp
...
-            {result?.existingWorkspaces?.map(w =>
-              <a href={w.latestInstance?.ideUrl || gitpodHostUrl.with({ pathname: '/start/', hash: '#' + w.latestInstance?.workspaceId }).toString()} className="rounded-xl group hover:bg-gray-100 dark:hover:bg-gray-800 flex p-3 my-1">
-                <div className="w-full">
-                  <p className="text-base text-black dark:text-gray-100 font-bold">{w.workspace.id}</p>
-                  <p className="truncate" title={w.workspace.contextURL}>{w.workspace.contextURL}</p>
-                </div>
-              </a>
-            )}
+            {result?.existingWorkspaces?.map(w => {
+              const normalizedContextUrl = ContextURL.getNormalizedURL(w.workspace)?.toString() || "undefined";
```
Comment (geropl) [inline components/dashboard/src/start/CreateWorkspace.tsx:167]: Note: This is one of the places where I was not 100% sure if we really want the `normalizedContextUrl`, but ultimately think we should always display it (except for debugging purposed in `/admin`, maybe).

**Comment by geropl** [comment]
> One is: Changing the protocol API risks breaking downstream clients, right? Do we know if any other code than the dashboard relies on ContextURL.parseToURL?

The only real client here is dashboard. :+1: The Gitpod plugin for vscode server also uses parts from `gitpod-protocol`, but 1) they do not use this, and 2) they import during build, not runtime, so their build would fail and they'd have to adjust.

Most importantly, maybe, 3): We should not consider `gitpod-protocol` to be public API. It's 99% the intersection of `dashboard` and `server` for convenience sake. And hopefully replaced with something more stable, soon. :slightly_smiling_face:

File: components/dashboard/src/admin/WorkspacesSearch.tsx [hunk 6]
```diff
@@ -134,6 +134,7 @@ function WorkspaceEntry(p: { ws: WorkspaceAndInstance }) {
             <div className="flex flex-col w-5/12 self-center truncate">
                 <div className="text-gray-500 overflow-ellipsis truncate">{p.ws.description}</div>
                 <div className="text-sm text-gray-400 overflow-ellipsis truncate">{p.ws.contextURL}</div>
```
Comment (JanKoehnlein) [inline components/dashboard/src/admin/WorkspacesSearch.tsx:136]: Should we get rid of this div?

**Review by JanKoehnlein — COMMENTED** [review]
LGTM apart from the duplicate div

File: components/dashboard/src/admin/WorkspacesSearch.tsx (hunk 6 above)
Comment (geropl) [reply components/dashboard/src/admin/WorkspacesSearch.tsx]: @JanKoehnlein done.

**Review by JanKoehnlein — APPROVED** [review]
Supi

**Comment by akosyakov** [comment]
@geropl It will be cool to add a warning comment here: https://github.com/gitpod-io/gitpod/blob/95592d00d8dcce49539d39c68c22ac980d9581c6/components/gitpod-protocol/src/protocol.ts#L413
