### PR TITLE
[ws-daemon] Properly handle mark unmount

### LINKED ISSUE #5689: Workspaces falsely reports "last backup failed: workspace does not exist. Please contact support if you need the workspace data."
### Bug description

On workspace timeout, the users sees `last backup failed: workspace does not exist. Please contact support if you need the workspace data.`.
But on checking, the backup is there, and also re-produced on startup.

Exmaples:
 - fuchsia-spider-384e445r (13.09., around 13:20 CEST)
 - black-sheep-xvsk5brx (14.09., around 09:05 CEST)

Internal slack discussion: https://gitpod.slack.com/archives/C01KGM9AW4W/p1631539665230200

### Steps to reproduce

Have a workspace time out (often enough?)

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR moves the mark unmount fallback back to ws-daemon. Prior to this change we'd try and finalise workspace content even before the pod was stopped. During content finalisation we'd try and unmount the mark mount that might have been propagated to ws-daemon during a restart. If that happened, the pod would never actually stop - hence we'd try to finalise even if the pod was not stopped yet.

This change pushes all this mark mount business back into ws-dameon using the `dispatch` mechanism. If a pod lingers around for longer than its termination grace period, we'll try and unmount the mark mount, eventually causing the pod to stop.

## Related Issue(s)

Fixes #5689

## How to test
1. Start a workspace
2. Restart ws-daemon
3. Stop the workspace
4. The workspace should have stopped just fine and the `gitpod_ws_daemon_markunmountfallback_active_total` metric on ws-daemon should have incremented by one.

## Release Notes

```release-note
[workspace] Make the workspace stopping mechanism more deterministic
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5689*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-daemon/pkg/daemon/markunmount.go [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+}
+
+// WorkspaceUpdated gets called when a workspace pod is updated. For containers being deleted, we'll check
+// if they're still running after their terminationGracePeriod and if Kubernetes still knows about them.
+func (c *MarkUnmountFallback) WorkspaceUpdated(ctx context.Context, ws *dispatch.Workspace) error {
+	if ws.Pod.DeletionTimestamp == nil {
+		return nil
+	}
+
+	c.mu.Lock()
```
Comment (geropl) [inline components/ws-daemon/pkg/daemon/markunmount.go:80]: What about
``
func(){
  c.mu.Lock()
  defer c.mu.Lock()
  ...
}()
```
as a pattern to indicate we really wan tto releace `c.mu`?

File: components/ws-manager/pkg/manager/monitor.go [hunk 2]
```diff
@@ -363,22 +363,9 @@ func actOnPodEvent(ctx context.Context, m actingManager, status *api.WorkspaceSt
 		_, gone := wso.Pod.Annotations[wsk8s.ContainerIsGoneAnnotation]
 
 		if terminated || gone {
```
Comment (geropl) [inline components/ws-manager/pkg/manager/monitor.go:365]: :heart:

**Comment by geropl** [comment]
I might mix this up, but: This is basically the mechanism we had in place before the "stuck in stopping" weeks, just with "unmountMarkMount" instead of `kubectl delete pod .. --force`, right?
But wasn't the problem with this approach that it is already too late? E.g., containerd already tried to remove the container, failed, and the workspace is in a state where retries won't help?
Or is it that we now delete the mark mount in all scenarios, that when containerd re-tries to delete the pod it succeeds?

Just trying to completely understand this :thinking:

File: components/ws-daemon/pkg/daemon/markunmount.go (hunk 1 above)
Comment (csweichel) [reply components/ws-daemon/pkg/daemon/markunmount.go:80]: Indeed we could write it that way. In this instance I found the `func` wrap too much considering it's just one line inbetween. A matter of taste I reckon :)

**Comment by csweichel** [comment]
> I might mix this up, but: This is basically the mechanism we had in place before the "stuck in stopping" weeks, just with "unmountMarkMount" instead of `kubectl delete pod .. --force`, right? 

Indeed, the mechanism is the same. Actually I went back in the Git history and pulled out the containerd workaround code :) 

> But wasn't the problem with this approach that it is already too late? E.g., containerd already tried to remove the container, failed, and the workspace is in a state where retries won't help? 

The key difference between then and now is that containerd behaves differently in this situation. It continuously tries to unmount the root filesystem, and eventually (once this mechanism has kicked in) succeeds.

> Or is it that we now delete the mark mount in all scenarios, that when containerd re-tries to delete the pod it succeeds?

💯

File: components/ws-daemon/pkg/daemon/markunmount.go (hunk 1 above)
Comment (csweichel) [reply components/ws-daemon/pkg/daemon/markunmount.go:80]: I should have paid more attention as to where that comment is located 🤦 
Will update accordingly

**Review by geropl — APPROVED** [review]
Not sure this helps, but: LGTM :upside_down_face:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7e8e635de31c41d0b4a65276bdb33ec9ff0d6665</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5897#pullrequestreview-765555306" title="Approved">geropl</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5689*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by aledbf** [comment]
@csweichel I see two things with this change:
- stopping workspaces takes more time (UI)
- the counter `gitpod_ws_daemon_markunmountfallback_active_total{successful="true"}` increases in two

**Comment by csweichel** [comment]
> @csweichel I see two things with this change:
> - stopping workspaces takes more time (UI)

That makes sense as we now wait for containerd to realise that the rootfs was unmounted

> - the counter `gitpod_ws_daemon_markunmountfallback_active_total{successful="true"}` increases in two

Did it increment by two for one workspace stop?

**Comment by aledbf** [comment]
> Did it increment by two for one workspace stop?

Yes

**Comment by csweichel** [comment]
Testing this I saw a single increase only. Beware that preview environments have a single ghost running as well, whose stop would be affected by this behaviour also.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7b03f9fcb851847126a83209fa202093976f1dde</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5897#issuecomment-930114287" title="Approved">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5897#pullrequestreview-765555306" title="Approved">geropl</a>*

Associated issue: *#5689*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
