### PR TITLE
Fix prebuild open

### LINKED ISSUE #14017: Branch not checked out in prebuild
### Bug description

I'm running into an issue where starting a prebuild with the "New Workspace (with this prebuild)" button is not checking out the branch.  Looking at the code, this is intentional:
https://github.com/gitpod-io/gitpod/blob/4c6b2246a1892129a938d38d6da21f6a8a24d9c2/components/server/ee/src/workspace/workspace-factory.ts#L375-L385

This makes sense, except that I'm using the prebuild for the latest commit on this branch. Would it be possible to checkout the branch in this case?

### Steps to reproduce

- Push new commit to branch w/ prebuilds enabled
- Navigate to Prebuilds tab in the project
- Select latest prebuild and start a new workspace

### Workspace affected

_No response_

### Expected behavior

Opening a prebuild for the latest commit on a branch should checkout the branch.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nVitius**
## Description
Made this PR in an effort to address some issues I ran into with prebuilds.
I don't know how to test the changes I made in `workspace-factory.ts`. The original pull request that had changes to that block of code (#13768) didn't have any unit tests, so I wasn't sure where to add some.

## Related Issue(s)

Fixes #14017

## How to test

- Create new prebuild
- Open workspace from either the branches tab or the specific prebuild page
- Prebuild should load correctly and the branch should be checked out in git

## Release Notes

```release-note
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@nVitius: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by nVitius** [comment]
@jankeromnes Pinging you as you're the author of the PR that originally implemented this feature.

**Comment by jankeromnes** [comment]
Hi @nVitius! 👋 Wow, many thanks for this contribution 👀 I'm happy to take a look today and help move this forward. ⏩

I see that you're already aware that there was a different bug https://github.com/gitpod-io/gitpod/issues/13991, where the original Git context (branch, commit) of the Prebuild was being kept in place, instead of being updated to whichever Git context is mandated by the context URL (e.g. new branch, new commit...)

However, you're probably right that this might be different and related to the new [bit of code](https://github.com/gitpod-io/gitpod/blob/4c6b2246a1892129a938d38d6da21f6a8a24d9c2/components/server/ee/src/workspace/workspace-factory.ts#L375-L385) that I don't fully understand yet.

I'll start by triggering a CI build for your PR (so that we can test your changes) and by trying to reproduce your specific issue.

/werft run

**Comment by jankeromnes** [comment]
Note: The CI says that the build failed, but I notice that it actually started two builds:

- https://werft.gitpod-dev.com/job/gitpod-build-fix-prebuild-open.0 which failed because it cannot find the commit in https://github.com/gitpod-io/gitpod (which makes sense, because this PR comes from a fork)

- https://werft.gitpod-dev.com/job/gitpod-build-fix-prebuild-open-fork.0 which is still in progress

I guess this is a CI bug, but we can simply ignore the first build and focus exclusively on the second.

File: components/server/ee/src/workspace/workspace-factory.ts [hunk 1]
```diff
@@ -373,15 +373,22 @@ export class WorkspaceFactoryEE extends WorkspaceFactory {
             }
 
             if (OpenPrebuildContext.is(context.originalContext)) {
+                if (CommitContext.is(buildWorkspace.context)) {
+                    if (
+                        CommitContext.is(context.originalContext) &&
+                        CommitContext.computeHash(context.originalContext) !==
+                            CommitContext.computeHash(buildWorkspace.context)
+                    ) {
+                        // If the current context has a newer/different commit hash than the prebuild
```
Comment (jankeromnes) [inline components/server/ee/src/workspace/workspace-factory.ts:382]: Thanks for updating this comment! At first glance, this change looks like it could "fix" the situation when prebuild commit == branch HEAD.

While this is definitely an improvement over the status quo, it does leave the cases with prebuild commit != branch HEAD with an awkward non-branch checkout.

I wonder if a (follow-up) more general fix could be possible, e.g. by making the workspace Git initializer respect _both_ `revision` _and_ `branch`, such that you could check out a branch @ an earlier HEAD. 🤔 But this would probably need further discussion, and thus warrant a follow-up issue.

Meanwhile, let's wait for the (correct) CI build to finish so that we can confirm & merge this fix. 🙌

Comment (nVitius) [reply components/server/ee/src/workspace/workspace-factory.ts:382]: > While this is definitely an improvement over the status quo, it does leave the cases with prebuild commit != branch HEAD with an awkward non-branch checkout.

I think this makes sense though. As an example: in my project I'm using prebuilds to compile my scala codebase so that when the workspace opens I can run my project without having to compile anything. It saves me around 10 minutes per workspace. If I were to try running a workspace on an older prebuild but the latest code was checked out instead, my process to run my scala project would automatically start compiling everything.

I guess this brings up an interesting question though: what's the reasoning for allowing old prebuilds to be used at all? What's the use case?

Comment (nVitius) [reply components/server/ee/src/workspace/workspace-factory.ts:382]: Also, I don't think it's possible to checkout a branch at an earlier commit. The branch is just a reference to a single commit. I suppose it would be possible to reset the branch (i.e. like `git reset <commit> --hard`).

Like you mentioned though, that's all probably a bigger discussion.

Comment (jankeromnes) [reply components/server/ee/src/workspace/workspace-factory.ts:382]: > I guess this brings up an interesting question though: what's the reasoning for allowing old prebuilds to be used at all? What's the use case?

What you mentioned before this about saving 10 minutes by starting from a Prebuild that is already finished is exactly the use case. This can be a life saver, e.g. for projects with very long build times, or with a high frequency of new commits being merged all the time.

FYI, there is another feature that is upcoming: A `Use Last Successful Prebuild` button right next to the `Skip Prebuild` button in the `Prebuild in Progress` screen. This would also allow you to save a lot of time when you start a workspace while a prebuild is still running.

> Also, I don't think it's possible to checkout a branch at an earlier commit. The branch is just a reference to a single commit. I suppose it would be possible to reset the branch (i.e. like `git reset <commit> --hard`).

Yes, I was implying that you'd end up with a local branch, that has the same name as the upstream branch, but is hard-reset to the specified commit.

I.e. it would not be in "detached HEAD" state, as is currently the case when you open a Prebuild directly, but instead it would keep the desired branch name (just at an earlier commit).

Instead of showing:

Screenshot 2022-10-21 at 10 44 55

It would show:

Screenshot 2022-10-21 at 10 45 14

And `git status` would say `Your branch is behind 'origin/fix_prebuild_open' by 1 commit`

**Comment by jankeromnes** [comment]
Okay, here is a preview environment that actually works (sorry for the CI troubles, and thanks @vulkoingim for the help!)

- CI build: https://werft.gitpod-dev.com/job/gitpod-build-fix-prebuild-open.2
- Preview URL: https://fix-prebuild-open.preview.gitpod-dev.com/workspaces

File: components/server/ee/src/workspace/workspace-factory.ts [hunk 2]
```diff
@@ -373,15 +373,22 @@ export class WorkspaceFactoryEE extends WorkspaceFactory {
             }
 
             if (OpenPrebuildContext.is(context.originalContext)) {
+                if (CommitContext.is(buildWorkspace.context)) {
+                    if (
+                        CommitContext.is(context.originalContext) &&
+                        CommitContext.computeHash(context.originalContext) !==
+                            CommitContext.computeHash(buildWorkspace.context)
```
[the remark this answers is not in the document]
Comment (jankeromnes) [reply components/server/ee/src/workspace/workspace-factory.ts:380]: Also, on a side note, would you be okay with using a single `if` statement with 3 conditions, instead of two nested `if` blocks? (But I'm aware that's mostly personal preference, so please feel free to disregard this suggestion.)

**Review by jankeromnes — APPROVED** [review]
Tested and works like a charm! ✨ Many thanks for this impressive contribution. 🎯 I'm happy that I got to better understand what this code does / what its consequences are.

Adding a temporary hold for the merge-bot while we figure out the CLA. Have we already been in touch about this? If not I'm happy to help resolve this.

**Comment by jankeromnes** [comment]
Actually adding the hold (I forgot):

/hold

File: components/server/ee/src/workspace/workspace-factory.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (nVitius) [reply components/server/ee/src/workspace/workspace-factory.ts:380]: I wanted to make sure that the original logic was still available in the case that `CommitContext.is(context.originalContext)` was not true.

I wasn't sure that `originalContext` would always be a `CommitContext` and didn't want to break anything since there weren't specific unit tests for that block.

If you think it looks good, I can update it.

[the remark this answers is not in the document]
Comment (nVitius) [reply components/server/ee/src/workspace/workspace-factory.ts:380]: > Interesting that you're using `CommitContext.computeHash` here instead of using `context.originalContext.revision` directly.

I saw it being used elsewhere when reading through some code and it made sense... I hadn't looked at the Interface for `CommitContext` too closely nor the definition for `computeHash`. Makse sense to me to use `revision` instead. Let me know what you think and I can make that change.

**Comment by nVitius** [comment]
> Adding a temporary hold for the merge-bot while we figure out the CLA. Have we already been in touch about this? If not I'm happy to help resolve this.

Haven't received anything about the CLA. Let me know what I need to do that. I'm also on the Discord server for Gitpod if it makes it easier to coordinate that.

**Comment by jankeromnes** [comment]
> Haven't received anything about the CLA. Let me know what I need to do that. I'm also on the Discord server for Gitpod if it makes it easier to coordinate that.

Sure! I've asked internally, and it looks like we'd need you to sign the following form:

https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112

Could you please take a look when you have some time, and sign it if it looks good to you? Please do let me know if you have any questions about this.

**Comment by nVitius** [comment]
@jankeromnes Thanks for the link. I signed the CLA.

**Comment by jankeromnes** [comment]
That's great, many thanks @nVitius! The next step is for @meysholdt to counter-sign and store the CLA, and then this should be good to go. 🚀

Let's also give this PR a green build (so that the merge bot is happy) -- we've already tested this PR in a custom build, so this one doesn't need a preview:

/werft run

**Comment by meysholdt** [comment]
hey @nVitius, thank you for signing the CLA!

**Comment by jankeromnes** [comment]
Congratulations on your first contribution to Gitpod @nVitius! 🎉 🎉 🎉

And thanks again for going all the way from noticing the bug, to undertanding the code, to fixing the bug, seemingly without any help. 🙏 🤯

**Comment by nVitius** [comment]
Thanks, @jankeromnes. Happy I could help.
