### PR TITLE
fix(workspace): force-stop workspaces stuck in a bad state

### LINKED ISSUE #5016: Please force-stop workspace instances that are "stuck" in a bad state
Following today's incident: https://github.com/gitpod-io/gitpod/issues/5005 a few workspaces and prebuilds got stuck in a bad state.

Specifically, they have a workspace instance stuck in `phase = 'preparing'`, even though no build is in progress (anymore) -- and they have remained in this "temporary" state for several hours at least.

It would be great to forcefully stop them again, so that they can be restarted, e.g. from an earlier backup.

### PR DESCRIPTION
**Pull request by MrSimonEmms**
fixes #5016

This was tested by scaling the ws-manager to 0 (`kubectl scale deployment --replicas=0 ws-manager`) and then creating a new workspace. After the elapsed time (suggest editing the ConfigMap so not waiting 2 hours) when failing to start the workspace you'll see something like this:

image

Things to note:
- the timeouts for a workspace stuck in the state are 2 hours for unknown and preparing. This may need amending
- the `setInterval` does not kill any previous runs. There are 60 seconds between runs which _SHOULD_ be enough, but this may need adjusting
- any errors in the `setInterval` are logged. Suggest adding an alert (or at least adding to Prometheus)

Future improvements:
- improve the UX/UI so that it gives a more useful/descriptive message to the user with the fact there's been an error starting the workspace
- improve logging so that a pattern can be found in failing workspaces

Happy to demo to anyone who wants to see it, and to check it meets the needs of the ticket

### CODE REVIEW

File: components/ws-manager-bridge/src/meta-instance-controller.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+    protected async checkAndStopWorkspaces() {
+        const instances = await this.workspaceDB.findRunningInstancesWithWorkspaces(this.config.installation);
+
+        await Promise.all(instances.map(async (instance: RunningWorkspaceInfo) => {
+            const creationTime = new Date(instance.latestInstance.creationTime).getTime();
+            const preparingKillTime = creationTime + (this.config.timeouts.preparingPhaseSeconds * 1000);
+            const unknownKillTime = creationTime + (this.config.timeouts.unknownPhaseSeconds * 1000);
+            const exceededPreparingTime = Date.now() >= preparingKillTime;
+            const exceededUnknown = Date.now() >= unknownKillTime;
```
Comment (MrSimonEmms) [inline components/ws-manager-bridge/src/meta-instance-controller.ts:33]: add `Time` to var

File: components/ws-manager-bridge/src/meta-instance-controller.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+                await this.workspaceDB.storeInstance(instance.latestInstance);
+                await this.messagebus.notifyOnInstanceUpdate({}, instance.workspace.ownerId, instance.latestInstance);
+            }
+        }));
+    }
+
+    public start() {
+        setInterval(() => {
+            // We don't need to wait for this to resolve as it won't resolve until all intervals finished
+            this.checkAndStopWorkspaces();
```
Comment (MrSimonEmms) [inline components/ws-manager-bridge/src/meta-instance-controller.ts:56]: Put in `try/catch` and log the error

File: components/ws-manager-bridge/src/meta-instance-controller.ts [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+    @inject(MessageBusIntegration)
+    protected readonly messagebus: MessageBusIntegration;
+
+    @inject(WorkspaceDB)
+    protected readonly workspaceDB: WorkspaceDB;
+
+    protected async checkAndStopWorkspaces() {
+        const instances = await this.workspaceDB.findRunningInstancesWithWorkspaces(this.config.installation);
+
+        await Promise.all(instances.map(async (instance: RunningWorkspaceInfo) => {
```
Comment (MrSimonEmms) [inline components/ws-manager-bridge/src/meta-instance-controller.ts:28]: Use `Promise.allSettled`

File: chart/templates/ws-manager-bridge-configmap.yaml [hunk 4]
```diff
@@ -25,6 +25,11 @@ data:
           "host": "localhost",
           "port": "8080"
         },
+        "timeouts": {
+          "metaInstanceCheckIntervalSeconds": 60,
+          "preparingPhaseSeconds": 7200,
+          "unknownPhaseSeconds": 7200
```
Comment (csweichel) [inline chart/templates/ws-manager-bridge-configmap.yaml:31]: should be 10min (600 seconds).
We don't expect workspaces to be in unknown for longer than a few seconds really.

Comment (MrSimonEmms) [reply chart/templates/ws-manager-bridge-configmap.yaml:31]: Ok, I'll change

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 6959bff2c7695c390cf3398e182c7a60daf3ce9e</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5055#issuecomment-894191549" title="LGTM">csweichel</a>*

Associated issue: *#5016*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [csweichel]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
