### PR TITLE
[protocol] connection: buffer messages until reconnect

### LINKED ISSUE #5042: [dashboard] Gracefully handle connection disposal
### Bug description

Loading a workspace took very long time, at the end I got this:
image

### Steps to reproduce

It happened only once; But I've never seen it before.
I was able to open the URL in a new tab and it worked as expected.

This is the URL:
https://gitpod.io/#DP_PROJECT_NAME=feeds_ex,DP_ISSUE_FORK=feeds_ex-3025848,DP_ISSUE_BRANCH=3025848-context-examples-with-code,DP_PROJECT_TYPE=project_module,DP_MODULE_VERSION=8.x-1.x,DP_CORE_VERSION=9.2.0,DP_PATCH_FILE=,DP_INSTALL_PROFILE=standard/https://github.com/shaal/drupalpod

### Expected behavior

It would be awesome to know what is going on while it's happening, why a workspace takes long, what part of it got stuck, is it something I did wrong, or a glitch in the system. I'm just happy it only happened once :)

### Example repository

https://gitpod.io/#DP_PROJECT_NAME=feeds_ex,DP_ISSUE_FORK=feeds_ex-3025848,DP_ISSUE_BRANCH=3025848-context-examples-with-code,DP_PROJECT_TYPE=project_module,DP_MODULE_VERSION=8.x-1.x,DP_CORE_VERSION=9.2.0,DP_PATCH_FILE=,DP_INSTALL_PROFILE=standard/https://github.com/shaal/drupalpod

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by geropl**
## Description
This avoids Error("Connection got disposed") errors which gobble up to the frontend and block users. Also, it makes the frontend's websocket connection more resilient in general: Instead of dropping calls, those are buffered and re-issued once the connection is reestablished.

## Related Issue(s)

Fixes #5042

### Login to preview env
1. go [here](https://gpl-5042-conn-disposed.staging.gitpod-dev.com/workspaces/) and login
2. note how you're re-directed on successful login with GitHub/GitLab

### Start a workspace
1. open devtools (console and network)
1. start [any workspace](https://gpl-5042-conn-disposed.staging.gitpod-dev.com/#https://github.com/gitpod-io/template-typescript-node)
2. note how websocket connections work and open as expected

### View build logs
1. open a context that requires an image build
2. wait until you see the log appearing
3. terminate the websocket connection (by killing `server`)
4. notice how the logs re-start scrolling automatically once server and the websocket connection is up-and-running again

## Release Notes

```release-note
improve websocket reconnection handling in the frontend
```

 - [x] /werft with-clean-slate-deployment

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#5042*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
@akosyakov I'm not 100% sure that this is worth the effort (code complexity, potential fallout), but her it is :shrug:  :wink:

File: components/gitpod-protocol/src/messaging/browser/connection.ts [hunk 1]
```diff
@@ -91,3 +98,162 @@ export class WebSocketConnectionProvider {
...
+        this.buffer = [];
+        for (const msg of buffer) {
+            this.write(msg);
+        }
+        this.logger.info(`flushed buffer (${this.buffer.length})`)
+    }
+
+    protected bufferMsg(msg: any) {
+        this.buffer.push(msg);
+        this.logger.info(`buffered message (${this.buffer.length})`);
```
Comment (akosyakov) [inline components/gitpod-protocol/src/messaging/browser/connection.ts:185]: Should log level be info?

**Comment by akosyakov** [comment]
/lgtm
@geropl I tested and everything seems to work.

/hold
see comment about logs, maybe they should be of debug level?

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4acb2df23463a7bb5300d92035b349b5eefa590d</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5787#issuecomment-925618026" title="LGTM">akosyakov</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#5042*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

File: components/gitpod-protocol/src/messaging/browser/connection.ts (hunk 1 above)
Comment (geropl) [reply components/gitpod-protocol/src/messaging/browser/connection.ts]: I uncommented those statements as the `ConsoleLogger` had no `debug` level.

**Comment by geropl** [comment]
> see comment about logs, maybe they should be of debug level?

@akosyakov commented out log statements

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 3a3881a7325f6905ed44f26ee3f7f7430ae27ecc</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5787#issuecomment-928949964" title="LGTM">akosyakov</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#5042*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
/unhold

@geropl I think you need add approve label to merge it.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5787#issuecomment-928949964" title="LGTM">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5787#issuecomment-928950759" title="Approved">geropl</a>*

Associated issue: *#5042*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [geropl]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
