### PR TITLE
Remove free text search on contextURL

### LINKED ISSUE #8453: Change "Search workspaces" to "Enter workspace ID" and disable contextURL search.
Workspace ID search returns quite fast, and searches usually do use the workspace IDs. 
Therefore we will only allow workspace ID searches and disable the free text search.

### LINKED ISSUE #8454: Fix search input to trim whitespace in all searches
Searches with whitespaces (can happen when copy-pasting) would fail.

### PR DESCRIPTION
**Pull request by laushinka**
## Description
This change disables the free text search, and encourages searching on workspace IDs.  
It's a minimum change for now - there will be follow-up tasks to improve the search[[1](https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1050875763)][[2](https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1054716890)].
It also includes drive-by changes of removing whitespace from searches[[1](https://github.com/gitpod-io/gitpod/issues/8454)].

Screenshot 2022-03-02 at 00 54 02

## Related Issue(s)

Fixes #8453
Fixes #8454 

## How to test
1. Go to https://lm-search-ws-8453.staging.gitpod-dev.com/admin/workspaces
2. Search part of a contextURL - it should not work.

## Release Notes

```release-note
Free text search on workspace admin dashboard is not enabled anymore.
```

### CODE REVIEW

File: components/dashboard/src/admin/WorkspacesSearch.tsx [hunk 1]
```diff
@@ -68,27 +68,19 @@ export function WorkspaceSearch(props: Props) {
...
-            } else if (matchesNewWorkspaceIdExactly(searchTerm)) {
-                query.workspaceId = searchTerm;
-            }
-            if (query.workspaceId || query.instanceId || query.instanceIdOrWorkspaceId) {
-                searchTerm = undefined;
+            const query: AdminGetWorkspacesQuery = {};
+            if (matchesInstanceIdOrLegacyWorkspaceIdExactly(queryTerm)) {
+                query.instanceIdOrWorkspaceId = queryTerm;
+            } else if (matchesNewWorkspaceIdExactly(queryTerm)) {
+                query.workspaceId = queryTerm;
```
Comment (laushinka) [inline components/dashboard/src/admin/WorkspacesSearch.tsx:75]: @geropl What was the case before where we would populate `query.instanceId`?

Comment (geropl) [reply components/dashboard/src/admin/WorkspacesSearch.tsx:75]: @laushinka Not sure I understand your question? IMO we never were able to reliably fill `instanceId` (because `workspaceId`s always looked identical).

File: components/dashboard/src/admin/WorkspacesSearch.tsx [hunk 2]
```diff
@@ -104,7 +96,9 @@ export function WorkspaceSearch(props: Props) {
                             <path fillRule="evenodd" clipRule="evenodd" d="M6 2a4 4 0 100 8 4 4 0 000-8zM0 6a6 6 0 1110.89 3.477l4.817 4.816a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 010 6z" fill="#A8A29E" />
                         </svg>
                     </div>
-                    <input type="search" placeholder="Search Workspaces" onKeyDown={(ke) => ke.key === 'Enter' && search() } onChange={(v) => { setQueryTerm(v.target.value) }} />
+                    <input type="search" placeholder="Search Workspace IDs or Instance IDs" style={{width: "20rem"}}
```
Comment (gtsiolis) [inline components/dashboard/src/admin/WorkspacesSearch.tsx:99]: **question**: Shall we go with one of these here based on https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1055427520? Cc @geropl

File: components/dashboard/src/admin/WorkspacesSearch.tsx (hunk 1 above)
Comment (laushinka) [reply components/dashboard/src/admin/WorkspacesSearch.tsx:75]: > Maybe `instanceId` was added with the previous change that introduced this "interpretation" of user input, to pave the way for a explicit choice (dropdown).

Makes sense!

**Comment by laushinka** [comment]
Thank you for taking a look @geropl @gtsiolis 🙏🏽 It's now ready for actual review (not a draft anymore).

**Review by gtsiolis — APPROVED** [review]
Thanks, @laushinka!

Regarding the input placeholder question in https://github.com/gitpod-io/gitpod/pull/8503#discussion_r817490980:

I think @geropl was only suggesting to go with the `workspaceId` option instead of the `instanceId` as described in https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1055424756 but sounds ok to keep the friendlier placeholder.

File: components/dashboard/src/admin/WorkspacesSearch.tsx [hunk 3]
```diff
@@ -104,7 +96,9 @@ export function WorkspaceSearch(props: Props) {
                             <path fillRule="evenodd" clipRule="evenodd" d="M6 2a4 4 0 100 8 4 4 0 000-8zM0 6a6 6 0 1110.89 3.477l4.817 4.816a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 010 6z" fill="#A8A29E" />
                         </svg>
                     </div>
-                    <input type="search" placeholder="Search Workspaces" onKeyDown={(ke) => ke.key === 'Enter' && search() } onChange={(v) => { setQueryTerm(v.target.value) }} />
+                    <input type="search" placeholder="Search Workspace IDs"
+                        onKeyDown={(ke) => ke.key === 'Enter' && search() }
+                        onChange={(v) => { setQueryTerm((v.target.value).trim()) }} />
                 </div>
                 <button disabled={searching} onClick={search}>Search</button>
```
[the remark this answers is not in the document]
Comment (laushinka) [reply components/dashboard/src/admin/WorkspacesSearch.tsx:103]: *thinking* When there is no button, would the expectation be that the search result gets updated with every key change? Or would the user be expected to hit Enter?

File: components/dashboard/src/admin/WorkspacesSearch.tsx [hunk 4]
```diff
@@ -104,7 +96,9 @@ export function WorkspaceSearch(props: Props) {
                             <path fillRule="evenodd" clipRule="evenodd" d="M6 2a4 4 0 100 8 4 4 0 000-8zM0 6a6 6 0 1110.89 3.477l4.817 4.816a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 010 6z" fill="#A8A29E" />
                         </svg>
                     </div>
-                    <input type="search" placeholder="Search Workspaces" onKeyDown={(ke) => ke.key === 'Enter' && search() } onChange={(v) => { setQueryTerm(v.target.value) }} />
+                    <input type="search" placeholder="Search Workspace IDs"
```
[the remark this answers is not in the document]
Comment (laushinka) [reply components/dashboard/src/admin/WorkspacesSearch.tsx:99]: > We also scarcely reference the term workspace or instance `ID` in our docs.

Initially I thought that Admins surely know that those are workspace IDs, but I realize that that was my biased assumption and the fact that we don't reference the term `ID` anywhere makes me see your point.
Let's see how this goes - especially when self-hosted users give us feedback, and yes we can improve this anytime. 🙏🏽

File: components/dashboard/src/admin/WorkspacesSearch.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (gtsiolis) [reply components/dashboard/src/admin/WorkspacesSearch.tsx:103]: **thought**: There are cases where searching or filtering on key change is valid and useful like projects or members which usually are a finite and small data set. However, it sounds optimal to _not_ search on key change when filtering large datasets like instance users, workspaces, etc but require enter to perform the search. 💭 

Thinking out loud, we added the search button back in https://github.com/gitpod-io/gitpod/pull/3723 because we require the enter key to perform a search here but seems harmless to drop the button. Your call, feel free to move this discussion in a follow up issue. 🏓

**Review by geropl — APPROVED** [review]
Code LGTM and tested: works and looks nice! :+1:
