### PR TITLE
White list `GITPOD_IMAGE_AUTH` env var name

### LINKED ISSUE #19574: Unable to set GITPOD_IMAGE_AUTH environment variable
### Bug description

When attempting to configure private Docker images in Gitpod following the documented instructions at https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image, I encounter an error message.
 
Despite the documentation stating that credentials can be provided by setting `GITPOD_IMAGE_AUTH` as a repository-level environment variable, I receive a __"Repository: Error: Variable name with prefix 'GITPOD_' is reserved"_ error when attempting to do so. Additionally, trying to set this variable at the user level results in a __"User: Name with prefix 'GITPOD_' is reserved"_ error.

### Steps to reproduce

Go to Gitpod's Dashboard and try to set `GITPOD_IMAGE_AUTH` as a repository-level environment variable.

### Workspace affected

_No response_

### Expected behavior

Be able to set `GITPOD_IMAGE_AUTH` as a repository-level environment variable.

### Example repository

_No response_

### Anything else?

Not sure but maybe was introduced by https://github.com/gitpod-io/gitpod/pull/19547 ?

### PR DESCRIPTION
**Pull request by mustard-mh**
## Related Issue(s)

Fixes #19574

## How to test

https://hw-fix-env.preview.gitpod-dev.com/workspaces

- It can't create env var (on user settings or repo settings) with prefixed naming `GITPOD_`
- Except `GITPOD_IMAGE_AUTH` as it's documented [here](https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image)
- Search document repo if there's another other prefixed `GITPOD_` env is documented (I did it, seems only this one)

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - hw-fix-env</li>
	<li><b>🔗 URL</b> - <a href="https://hw-fix-env.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-env.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - hw-fix-env-gha.23933</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-hw-fix-env%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

File: components/gitpod-protocol/src/protocol.ts [hunk 1]
```diff
@@ -297,6 +297,8 @@ export namespace UserEnvVar {
     const WILDCARD_SHARP = "#"; // TODO(gpl) Where does this come from? Bc we have/had patterns as part of URLs somewhere, maybe...?
     const MIN_PATTERN_SEGMENTS = 2;
 
+    export const WhiteListFromReserved = ["GITPOD_IMAGE_AUTH"];
```
Comment (jeanp413) [inline components/gitpod-protocol/src/protocol.ts:300]: A link to the doc to know why this is required would be useful

**Review by jeanp413 — APPROVED** [review]
