### PR TITLE
[usage] Test for and fix negative credits in GenerateUsageReport

### LINKED ISSUE #12064: Negative credits in usage list view
Something is wrong with the minutes -> credits computation.

Screenshot 2022-08-11 at 12 42 04

### PR DESCRIPTION
**Pull request by geropl**
## Description
There was a disconnect between when we determined `now`, and when we used it in combination with start-/stopTimes that - based on runtime behavior - _could_ lead to negative usage being calculated.

## Related Issue(s)

Fixes #12064 

### Run unit tests
 - [open a workspace](https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/12178)
 - `leeway build components/usage:init-testdb && (cd components/usage && go test -v ./...)`

### Manual test
I did not manage to provoke this situation in preview envs, mainly due to data volume I guess.
It's still worth testing that usage still works as expected: 
 - signup
 - create a team starting with `Gitpod-...`
 - import a project
 - start a workspace on that project
 - go to the usage view and notice the correct usage being displayed

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [x] /werft with-payment

### CODE REVIEW

**Comment by geropl** [comment]
/werft run

:crossed_fingers: npmjs.org...

File: components/usage/pkg/apiv1/usage_test.go [hunk 1]
```diff
@@ -297,8 +299,132 @@ func TestReportGenerator_GenerateUsageReport(t *testing.T) {
 
 	require.Equal(t, nowFunc(), report.GenerationTime)
 	require.Equal(t, startOfMay, report.From)
-	require.Equal(t, startOfJune, report.To)
+	// require.Equal(t, startOfJune, report.To) TODO(gpl) This is not true anymore - does it really make sense to test for it?
```
Comment (jankeromnes) [inline components/usage/pkg/apiv1/usage_test.go:302]: Hmm, you're right. If we're looking at the usage from May to June, and `now` is some time in May, then `to` should be equal to `now` (and not `startOfJune`, which would only be the case if `now` is some time in June or later).

File: components/usage/pkg/apiv1/usage_test.go [hunk 2]
```diff
@@ -297,8 +299,132 @@ func TestReportGenerator_GenerateUsageReport(t *testing.T) {
...
+				// 	{
+				// 		InstanceID: instanceID,
+				// 		AttributionID: db.NewTeamAttributionID(teamID.String()),
+				// 		StartedAt: Timestamp("2022-08-17T09:40:53.115Z").Time(),
+				// 		StoppedAt: sql.NullTime{ Time: Timestamp("2022-08-17T09:43:04.874Z").Time(), Valid: true },
+				// 		WorkspaceClass: "default",
+				// 		CreditsUsed: 3.0,
+				// 	},
+				// },
+			},
```
Comment (jankeromnes) [inline components/usage/pkg/apiv1/usage_test.go:360]: No expectation here? 🤔

File: components/usage/pkg/apiv1/usage-report.go [hunk 3]
```diff
@@ -44,11 +47,21 @@ type ReportGenerator struct {
...
 
-func (g *ReportGenerator) GenerateUsageReport(ctx context.Context, from, to time.Time) (UsageReport, error) {
+func (g *ReportGenerator) GenerateUsageReport(ctx context.Context, from, to time.Time) (*UsageReport, error) {
 	now := g.nowFunc().UTC()
-	log.Infof("Gathering usage data from %s to %s", from, to)
 
-	report := UsageReport{
+	// Sanity check: from <= now
+	if now.Before(from) {
+		return nil, status.Errorf(codes.InvalidArgument, "Now must be before from")
```
Comment (jankeromnes) [inline components/usage/pkg/apiv1/usage-report.go:55]: Error message is wrong:

```suggestion
		return nil, status.Errorf(codes.InvalidArgument, "Now must be after from")
```

File: components/usage/pkg/apiv1/usage_test.go (hunk 2 above)
Comment (geropl) [reply components/usage/pkg/apiv1/usage_test.go:360]: Yes, can make can more explicit with: `usageRecords: nil`. :+1:

**Comment by jankeromnes** [comment]
Note: I've added the Werft flag `with-payment`, which triggered a new build. My intent is to test the credit-counting behavior (i.e. start workspaces in various billing states, then double-check how many credits we've reported to Stripe).

File: components/usage/pkg/apiv1/usage_test.go (hunk 1 above)
Comment (geropl) [reply components/usage/pkg/apiv1/usage_test.go:302]: There are other potential solutions, but this was the least invasive - and seems to be in line with what we expect at other places. Happy to turn this one around when Milan/Andrew come back (and do better filtering on the instances we retrieve, for example) - as long as the test passes! :wink:

**Review by jankeromnes — APPROVED** [review]
Code looks good to me, test works, and I've also tested the credit-counting/reporting behavior with a few instances. Works great!

/hold

**Comment by geropl** [comment]
/unhold

Handled review comments, so good to go! :racehorse:
