### PR TITLE
Immediately redirect to www.gitpod.io for any website slugs.

### LINKED ISSUE #5452: [Dashboard] Make www.gitpod.io redirect work for logged out users
### Bug description

If a user is NOT logged in then:

- `https://gitpod.io/chat` does not redirect to `https://www.gitpod.io/chat`

Same for any 404.

When the user is logged in 404's redirect to the website.

### Steps to reproduce

As above

### Expected behavior

`https://gitpod.io` always redirects to `https://www.gitpod.io/` if 404

### Example repository

_No response_

### Anything else?

💭 As this involves our authentication page - discuss threat model in `#security` before merging.

### PR DESCRIPTION
**Pull request by svenefftinge**
fixes #5452

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **svenefftinge** after the PR has been reviewed.

Associated issue: *#5452*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ghuntley** [comment]
Thanks for fixing this particular paper cut that has been very frustrating 🧡

File: components/dashboard/src/App.tsx [hunk 1]
```diff
@@ -53,6 +53,15 @@ function isGitpodIo() {
     return window.location.hostname === 'gitpod.io' || window.location.hostname === 'gitpod-staging.com' || window.location.hostname.endsWith('gitpod-dev.com') || window.location.hostname.endsWith('gitpod-io-dev.com')
 }
 
+function isWebsiteSlug(pathName: string) {
+    const slugs = ['chat', 'features', 'screencasts', 'blog', 'docs', 'changelog', 'pricing', 'self-hosted', 'gitpod-vs-github-codespaces', 'support', 'about', 'careers', 'contact', 'media-kit', 'imprint', 'terms', 'privacy']
+    return slugs.some(slug => pathName.startsWith('/' + slug + '/'));
```
Comment (gtsiolis) [inline components/dashboard/src/App.tsx:58]: **issue**: Should we also redirect URLs without a trailing `/`? For example, [`/changelog/`](https://se-website-redirect.staging.gitpod-dev.com/changelog/) v. [`/changelog`](https://se-website-redirect.staging.gitpod-dev.com/changelog).

**Review by gtsiolis — APPROVED** [review]
LGTM! Approving to unblock merging this but holding for one minor comment which could be resolved in a follow up issue. 🏀 

/hold

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5531#pullrequestreview-747017198" title="Approved">gtsiolis</a>*

Associated issue: *#5452*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [gtsiolis]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f5730f903d6c8d322b963bcb597c1c5542cb0a68</details>

File: components/dashboard/src/App.tsx (hunk 1 above)
Comment (ghuntley) [reply components/dashboard/src/App.tsx:58]: **change:** add /values as well please 🧡

[Copying/pasting the link](https://news.ycombinator.com/item?id=28432300) from notion is getting old.

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by gtsiolis** [comment]
Works like a charm! 🔮 

Removing hold!

**Comment by gtsiolis** [comment]
Noticed that when having a team name that matches these URLs we also redirect to the website instead of `/values/projects` which could be minor since a) we only link to `/team-name/projects` and b) could be resolved with https://github.com/gitpod-io/gitpod/issues/5465. Cc @svenefftinge 

For example, try creating team `values` and visiting `https://gitpod.io/values` as a logged in user.
