### PR TITLE
[gitpod-protocol] handle host:port:token for getGitpodImageAuth

### LINKED ISSUE #16237: Please support private Docker registries with a non-default port
### Bug description

Today in Gitpod, you can use private Docker images by specifying a `GITPOD_IMAGE_AUTH` Project-level variable as described in:

https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image

Unfortunately, since `:` was used as a separator, you cannot specify Docker registries with non-default ports, i.e.:

- Specifying `registry.example.com` works ✅
  - (`GITPOD_IMAGE_AUTH="registry.example.com:Zm9vOmJhcg=="` is properly recognized 👍)

- Specifying `registry.example.com:1337` doesn't work ❌
  - (`GITPOD_IMAGE_AUTH="registry.example.com:1337:Zm9vOmJhcg=="` is ignored due to the double `:` 😖)

### Steps to reproduce

1. Try to specify a private Docker registry using a non-default port (like `registry.example.com:1337`)

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

The following code ignores any value of `GITPOD_IMAGE_AUTH` that doesn't have exactly one `:` character:

https://github.com/gitpod-io/gitpod/blob/508148b8366804d0bb0a43316b44df7b83abc72a/components/server/src/workspace/workspace-starter.ts#L695-L699

**Suggestion**: Maybe, it could instead split on the _last_ occurrence of a `:`, and allow 0 or 1 `:` to be present in the Docker registry hostname ? (Or, maybe it could allow a base64-encoded Docker registry hostname?)

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Be able to consume GITPOD_IMAGE_AUTH, where it is `host:<token>` or `host:port:<token>`.

## Related Issue(s)

Fixes #16237
Fixes CLC-1364

## How to test

See unit tests

[Preview](https://kylos101-s2pzmioah6s.preview.gitpod-dev.com/workspaces)

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by geropl — CHANGES_REQUESTED** [review]
@kylos101 We have at least two other places where we parse this forward, which we need to adjust as well.

IIRC it was in proxy.go (image-builder-bob), and maybe even somewhere else - maybe around docker-up? :thinking: 

I can pull out the references on Monday - or you try to ask cline :wink:

File: components/gitpod-protocol/src/protocol.ts [hunk 1]
```diff
@@ -293,11 +293,25 @@ export namespace EnvVar {
             return res;
         }
 
-        (imageAuth.value || "")
-            .split(",")
-            .map((e) => e.trim().split(":"))
-            .filter((e) => e.length == 2)
-            .forEach((e) => res.set(e[0], e[1]));
+        (imageAuth.value || "").split(",").forEach((entry) => {
```
Comment (geropl) [inline components/gitpod-protocol/src/protocol.ts:296]: Somehow it's very hard for me to understand the new implementation, while the old I could grok in an instant.

Does it really need that many lines? And if the answer is really yes: We should probably have a separate (in-function?) "parse" method.

Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts]: I introduced an inline function and reduced lines of code in c0be79f32f0bd5066843e5df19a4bbb81e2f8aa8.

You'll notice a truthiness check on all parts, this is to ensure we're not working with junk. I could remove it, but that'll cause tests to fail like so:

image

LMKWYT? I'll move onto checking other components now.

**Comment by kylos101** [comment]
> @kylos101 We have at least two other places where we parse this forward, which we need to adjust as well.
> 
> IIRC it was in proxy.go (image-builder-bob), and maybe even somewhere else - maybe around docker-up? 🤔
> 
> I can pull out the references on Monday - or you try to ask cline 😉

Thanks again for the tip, @geropl!

It seems supervisor [here](https://github.com/gitpod-io/gitpod/blob/c0be79f32f0bd5066843e5df19a4bbb81e2f8aa8/components/supervisor/pkg/supervisor/docker.go#L316), image-builder-bob [here](https://github.com/gitpod-io/gitpod/blob/c0be79f32f0bd5066843e5df19a4bbb81e2f8aa8/components/image-builder-bob/pkg/proxy/auth.go#L98-L104) and [here](https://github.com/gitpod-io/gitpod/blob/c0be79f32f0bd5066843e5df19a4bbb81e2f8aa8/components/image-builder-bob/pkg/proxy/auth.go#L56), and image-builder-mk3 [here](https://github.com/gitpod-io/gitpod/blob/c0be79f32f0bd5066843e5df19a4bbb81e2f8aa8/components/image-builder-mk3/pkg/auth/auth.go#L385-L389) are impacted, too.

**Comment by kylos101** [comment]
Related to https://github.com/gitpod-io/gitpod/pull/20586

File: components/gitpod-protocol/src/protocol.ts [hunk 2]
```diff
@@ -293,11 +293,24 @@ export namespace EnvVar {
...
         }
 
+        // Returns a host value, which can include port, if token also has length.
+        const getHost = (parts: string[]): string => {
+            if (parts.length === 2 && parts[0] && parts[1]) {
+                return parts[0];
+            } else if (parts.length === 3 && parts[0] && parts[1] && parts[2]) {
+                return `${parts[0]}:${parts[1]}`;
+            }
+            return "";
```
Comment (geropl) [inline components/gitpod-protocol/src/protocol.ts:303]: In TS, `undefined´ takes the role of "" in Go. Why not stick to that convention.

File: components/gitpod-protocol/src/protocol.ts [hunk 3]
```diff
@@ -293,11 +293,24 @@ export namespace EnvVar {
             return res;
         }
 
+        // Returns a host value, which can include port, if token also has length.
+        const getHost = (parts: string[]): string => {
+            if (parts.length === 2 && parts[0] && parts[1]) {
+                return parts[0];
+            } else if (parts.length === 3 && parts[0] && parts[1] && parts[2]) {
```
Comment (geropl) [inline components/gitpod-protocol/src/protocol.ts:300]: The invariant that no part may be empty can be stuffed into a single line at the top of the function.

File: components/gitpod-protocol/src/protocol.ts [hunk 4]
```diff
@@ -293,11 +293,24 @@ export namespace EnvVar {
...
+        };
+
         (imageAuth.value || "")
             .split(",")
             .map((e) => e.trim().split(":"))
-            .filter((e) => e.length == 2)
-            .forEach((e) => res.set(e[0], e[1]));
+            .forEach((parts) => {
+                const host = getHost(parts);
+                host !== "" ? res.set(host, parts[parts.length - 1]) : null;
```
Comment (geropl) [inline components/gitpod-protocol/src/protocol.ts:311]: We are breaking the abstraction of `getHost` here, because we are not only needing the host, but the auth/password part as well.
(This surfaces in that we access part by index, without prior checking that the length >= 1 - in this function).

One way to solve is by having naming the function to `parse` and have it return `{ host: string, auth: string } | undefined`, and calling if like this:

```
const parsed = parse(parts);
if (parsed) {
    res.set(parsed.host, parsed.auth);
}
```

File: components/gitpod-protocol/src/protocol.ts (hunk 3 above)
Comment (geropl) [reply components/gitpod-protocol/src/protocol.ts:300]: Also, not entirely sure where we guard again this parttern: `" centeredKey : centeredValue "`, so it should probably check `if (parts.some(e => e.trim() === "")) { return undefined }`

File: components/image-builder-bob/pkg/proxy/auth.go [hunk 5]
```diff
@@ -53,21 +53,30 @@ func (a MapAuthorizer) Authorize(host string) (user, pass string, err error) {
 	}()
 
 	// Strip any port from the host if present
-	host = strings.Split(host, ":")[0]
+	hostSlice := strings.Split(host, ":")
```
Comment (geropl) [inline components/image-builder-bob/pkg/proxy/auth.go:56]: This code would benefit from:
 - an explicit `parse` function
 - re-using the existing terms [hostname](https://developer.mozilla.org/en-US/docs/Web/API/Location/hostname) and [host](https://developer.mozilla.org/en-US/docs/Web/API/Location/host) not only in this code, but also all downstream functions

File: components/image-builder-mk3/pkg/auth/auth.go [hunk 6]
```diff
@@ -383,9 +383,11 @@ func (a AllowedAuthFor) additionalAuth(domain string) *Authentication {
 	dec, err := base64.StdEncoding.DecodeString(ath)
 	if err == nil {
 		segs := strings.Split(string(dec), ":")
-		if len(segs) > 1 {
-			res.Username = segs[0]
-			res.Password = strings.Join(segs[1:], ":")
+		numSegs := len(segs)
+
+		if numSegs > 1 {
+			res.Username = strings.Join(segs[:numSegs-1], ":")
```
Comment (geropl) [inline components/image-builder-mk3/pkg/auth/auth.go:389]: :nice:

File: components/image-builder-bob/pkg/proxy/auth.go [hunk 7]
```diff
@@ -53,21 +53,30 @@ func (a MapAuthorizer) Authorize(host string) (user, pass string, err error) {
...
+	portStrippedHost := hostSlice[0]
+	var port string
+	if len(hostSlice) > 1 {
+		port = hostSlice[1]
+	}
 
 	explicitHostMatcher := func() (authConfig, bool) {
```
Comment (geropl) [inline components/image-builder-bob/pkg/proxy/auth.go:63]: @kylos101 I'm not exactly sure how this matcher is used/what header we use to distinguish this. Did you check what we feed into the matcher: is it hostname or host?

If it's a header, I could also imagine that we may want to at least fall back to/maybe just use the _less specific_ version, just for the sake of interoperability... :thinking: Happy to sync here.

**Comment by geropl** [comment]
@kylos101 Left a bunch of comments with the intention to not to block or nitpick, but aim for leaving all these code pieces (that are already in a bad spot because of these cross-component dependencies) in a better spot than before.
In that regard, especially **loving** the push for tests here! :orange_heart: :pray:

File: components/gitpod-protocol/src/protocol.ts (hunk 4 above)
Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts:311]: Much cleaner, thank you for the suggestion! I had forgotten about this syntax: `{ host: string, auth: string } | undefined`

File: components/gitpod-protocol/src/protocol.ts (hunk 3 above)
Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts]: Fixed in d444551a4b93038190b9d035a5c3eea3545bfb55

File: components/gitpod-protocol/src/protocol.ts (hunk 2 above)
Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts]: Fixed in d444551a4b93038190b9d035a5c3eea3545bfb55

File: components/gitpod-protocol/src/protocol.ts (hunk 4 above)
Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts]: Fixed in d444551a4b93038190b9d035a5c3eea3545bfb55

File: components/gitpod-protocol/src/protocol.ts (hunk 3 above)
Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts]: TIL about `some` function!

File: components/image-builder-bob/pkg/proxy/auth.go (hunk 7 above)
Comment (kylos101) [reply components/image-builder-bob/pkg/proxy/auth.go:63]: > I'm not exactly sure how this matcher is used/what header we use to distinguish this.

I'll explore in a moment. My understanding follows.

> Did you check what we feed into the matcher: is it hostname or host?

The function names denote host, which can include port. I say this because when inspecting my config.json after doing a Docker Login for a private repo where the underlying registry lived on localhost:5000 (a Caddy passthrough to Docker Hub), I saw exactly that (localhost:5000 for the credential), rather than just the hostname (localhost).

> host = strings.Split(host, ":")[0]

@geropl do you know why port was being dropped here? This was introduced a few months back, but I lack context on why port was a factor (at least, I couldn't find any).

Comment (kylos101) [reply components/image-builder-bob/pkg/proxy/auth.go:63]: I'm not sure why dropping the port was introduced here:
https://github.com/gitpod-io/gitpod/pull/20586/files#diff-0d8d6971f60ba51f4062480bcf497c8a7ce5ea2493526659fc39e7955cc6b03cR56

Do you know? That is what led me to what we have now - where we drop port 443 - but keep others.

I'll test with port 5000, it's possible I am wrong, and that this should always be hostname. Thank you for sharing the [references](https://github.com/gitpod-io/gitpod/pull/20806/files#r2084266691) to the naming distinction!

File: components/gitpod-protocol/src/protocol.ts [hunk 8]
```diff
@@ -293,11 +293,33 @@ export namespace EnvVar {
...
+        };
+
         (imageAuth.value || "")
             .split(",")
-            .map((e) => e.trim().split(":"))
-            .filter((e) => e.length == 2)
-            .forEach((e) => res.set(e[0], e[1]));
+            .map((e) =>
+                e
+                    .trim()
```
[the remark this answers is not in the document]
Comment (kylos101) [reply components/gitpod-protocol/src/protocol.ts]: 🤦 yes. Fixed in 60fe995db79e6382152c387845f38fab40124af6

Reads better now, too.

File: components/image-builder-bob/pkg/proxy/auth.go (hunk 7 above)
Comment (geropl) [reply components/image-builder-bob/pkg/proxy/auth.go:63]: Sorry for the confusion! What I was after with the comment are two things:
 - nameing the variables "hostname" instead of "portStrippedHost"
 - (potentially) extracting all this code into a "parse" function that returns two values: "host" and "hostname"
 - and most importantly: Try to understand where in the client request "host" (the input var) is coming from
   - turns out to be [this code](https://github.com/containerd/containerd/blob/v1.6.36/remotes/docker/authorizer.go#L121): So "host" is the value of the host header - which can be a lot. [Definition says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Host):
 > The HTTP Host [request header](https://developer.mozilla.org/en-US/docs/Glossary/Request_header) specifies the host and port number of the server to which the request is being sent.
> If no port is included, the default port for the service requested is implied (e.g., 443 for an HTTPS URL, and 80 for an HTTP URL).

**Review by geropl — APPROVED** [review]
Rubber stamping your PR :white_check_mark:

**Comment by geropl** [comment]
Merging after we did extensive testing: https://linear.app/gitpod/issue/CLC-1364/image-pull-does-not-work-with-hostporttoken#comment-cbc77632
