### PR TITLE
[server] Correctly record client IP for analytics purposes 

### LINKED ISSUE #15600: Track client IP in for analytics
### Bug description

We are depending on the (masked) client IP for the creation of a daily changing fingerprint in order to identify users without cookies and map website activity to web app activity, see [this PR](https://github.com/gitpod-io/gitpod/pull/14978#issuecomment-1362748733). The obtained IPs tracked here belong to some Google data center, not the client and a first attempt to fix did not address this issue, see [this PR](https://github.com/gitpod-io/gitpod/pull/15356).

### Steps to reproduce

Cannot be reproduced in developer environment as the bug arises from the architecture in production. There are (at least) two ways to get some context on this issue

- check the IPs in production is [these logs](https://github.com/gitpod-io/gitpod/pull/15356#pullrequestreview-1219305190)
- Query identify calls (they use the client's masked IP), e.g. of yourself, in BigQuery with the query below

Also, you can find more analysis on the issue in this [data task](https://www.notion.so/gitpod/Complete-Cookieless-Tracking-69c9ca21f7444b528a8f96479b66e09a#58faf5c4175c419a8d674d1729cacef9).

Query for identify calls:
```
select
    user_id,
    timestamp,
    context_ip
from production_trusted.identifies
where user_id = '<your Gitpod user ID>' --insert your own user_id here
and context_ip is not null
order by timestamp desc
limit 10
```

### Workspace affected

_No response_

### Expected behavior

Instead of IPs that seem to belong to some proxy, we are expecting to obtain the true client IP in `express-util.ts`'s `clientIp` function.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andrew-farries**
## Description

Use a new `X-Real-IP` header for cookieless tracking rather than relying on the `X-Forwarded-For` header that the GCP loadbalancer sets by default. The `X-Forwarded-For` header is truncated by Caddy [[1](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults)], removing the true client IP and leaving just the IP of the GCP LB.

By defining a new custom header at the LB and setting it to the client IP, we ensure that Caddy forwards it to `server` without modification.

If we decide to go ahead with this approach we need to configure the `X-Real-IP` header on the production loadbalancer just as has already been done for the staging loadbalancer.

## Related Issue(s)
Fixes #15600

## How to test

* Take the image of `server` built on this branch and use it to update the `image` of the `server` deployment in staging.
* Change `server`'s log level to `debug`:
```bash
kubectl get pods | rg '^server' | awk '{ print $1 }' | xargs -I@ kubectl exec @ -c server -- curl -H "Content-Type: application/json" localhost:6060/debug/logging -d '{"level": "debug"}'
```
* Open a browser and visit https://gitpod-staging.com/workspaces.
* Server logs should contain the (masked) client IP address when the websocket connection was established:
```
{"component":"server","severity":"DEBUG","time":"2023-01-13T12:38:40.354Z","message":"masked wss client IP","payload":{"maskedClientIp":"185.118.207.0"}}
```

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

File: components/server/src/express-util.ts [hunk 1]
```diff
@@ -171,11 +171,9 @@ export const takeFirst = (h: string | string[] | undefined): string | undefined
 };
 
 export function clientIp(req: express.Request): string | undefined {
-    const forwardedFor = takeFirst(req.headers["x-forwarded-for"]);
-    if (!forwardedFor) {
+    const clientIp = takeFirst(req.headers["x-client-ip-for-analytics"]);
```
Comment (AlexTugarev) [inline components/server/src/express-util.ts:174]: Is there a way to fix https://github.com/gitpod-io/gitpod/blob/dd0826cc0d3432a6b601c86760387ce0afc01038/components/proxy/conf/Caddyfile#L71

As it's seems to have the same value as `x-forwarded-for`.

Maybe we can use `x-real-ip` instead of `x-client-ip-for-analytics` in general?

Comment (andrew-farries) [reply components/server/src/express-util.ts]: Yes, let's do this as we discussed.

https://github.com/gitpod-io/gitpod/pull/15752 will stop setting `X-Real-IP` in Caddy so that we can set it at the LB instead.

Once that is live we can deploy this change to start reading from the `X-Real-IP` header.

**Comment by andrew-farries** [comment]
Removed `hold` now that https://github.com/gitpod-io/gitpod/pull/15752 has been merged.

**Review by geropl — APPROVED** [review]
LGTM!
