### PR TITLE
[dashboard] Fix email notifications checkbox

### LINKED ISSUE #4755: changes to email notifications in the dashboard are not displayed correctly
### Bug description

Changes to the notifications checkboxes are not displayed. Only once I refresh the page I can see the changes. 

### Steps to reproduce

Go to https://gitpod.io/notifications

Edit the checkboxes

Refresh the page

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by corneliusludmann**
Fixes #4755

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4870#" title="Author self-approved">corneliusludmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by corneliusludmann** [comment]
Used the `useState`/`useRef` pattern here. If you have an idea for a better implementation, please let me know.

File: components/dashboard/src/settings/Notifications.tsx [hunk 1]
```diff
@@ -13,47 +13,63 @@ import settingsMenu from "./settings-menu";
 
 export default function Notifications() {
     const { user, setUser } = useContext(UserContext);
-    const isTransactionalMail = !user?.additionalData?.emailNotificationSettings?.disallowTransactionalEmails;
-    const toggleTransactionalMail = async ()=>{
+
+    const [isTransactionalMail, _setTransactionMail] = useState(!user?.additionalData?.emailNotificationSettings?.disallowTransactionalEmails);
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Notifications.tsx:17]: `_setTransactionMail` -> `setTransactionMail`

File: components/dashboard/src/settings/Notifications.tsx [hunk 2]
```diff
@@ -13,47 +13,63 @@ import settingsMenu from "./settings-menu";
...
+    const isTransactionalMailRef = useRef(isTransactionalMail);
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Notifications.tsx:18]: please, just remove the `isTransactionalMailRef`

File: components/dashboard/src/settings/Notifications.tsx [hunk 3]
```diff
@@ -13,47 +13,63 @@ import settingsMenu from "./settings-menu";
...
+    const setTransactionMail = (data: boolean) => {
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Notifications.tsx:19]: same

File: components/dashboard/src/settings/Notifications.tsx [hunk 4]
```diff
@@ -13,47 +13,63 @@ import settingsMenu from "./settings-menu";
...
+
+    const toggleTransactionalMail = async () => {
         if (user) {
             user.additionalData = {
                 ... {
-                    ... user.additionalData,
+                    ...user.additionalData,
                     emailNotificationSettings: {
-                        ... user.additionalData?.emailNotificationSettings,
-                        disallowTransactionalEmails: !!isTransactionalMail
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Notifications.tsx:24]: why removing? I thought this would ensure `boolean` type

File: components/dashboard/src/settings/Notifications.tsx [hunk 5]
```diff
@@ -13,47 +13,63 @@ import settingsMenu from "./settings-menu";
...
+                        ...user.additionalData?.emailNotificationSettings,
+                        disallowTransactionalEmails: isTransactionalMail
                     }
                 }
             }
             await getGitpodService().server.updateLoggedInUser({
                 additionalData: user.additionalData
             });
             setUser(user);
+            setTransactionMail(!isTransactionalMail);
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Notifications.tsx:39]: that is the missing bit to solve the underlying issue

File: components/dashboard/src/settings/Notifications.tsx [hunk 6]
```diff
@@ -13,47 +13,63 @@ import settingsMenu from "./settings-menu";
...
         }
     };
-    const isMarketingMail = !!user?.allowsMarketingCommunication;
-    const toggleMarketingMail = async ()=> {
+
+    const [isMarketingMail, _setMarketingMail] = useState(!!user?.allowsMarketingCommunication);
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Notifications.tsx:43]: same as above

**Review by AlexTugarev — COMMENTED** [review]
`useState` should solve the issue.

File: components/dashboard/src/settings/Notifications.tsx (hunk 2 above)
Comment (corneliusludmann) [reply components/dashboard/src/settings/Notifications.tsx]: I don't understand why it's not needed here even though it's accessed from inside an event handler but it works. Thanks. :+1:

File: components/dashboard/src/settings/Notifications.tsx (hunk 4 above)
Comment (corneliusludmann) [reply components/dashboard/src/settings/Notifications.tsx:24]: `isTransactionalMail` is actually boolean. There is no need for `!!`, is there?

**Review by AlexTugarev — APPROVED** [review]
Works nicely!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4c3778583f7ecc44ff318ee528a4c4a5085986bf</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4870#pullrequestreview-710370463" title="Approved">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4870#" title="Author self-approved">corneliusludmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev,corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
