### PR TITLE
Don't try to connect to opened ports

### LINKED ISSUE #7313: Connection lost & workspace needs to be reloaded when debugging theme / extension after a certain time
### Bug description

I have 2 workspaces in which I work on either a theme or a VS Code extension - both of these and only these workspaces are randomly disconnected after a certain random time - sometimes it's a few minutes, sometimes it's 20 minutes. I was finally able to get some log data of the console before the window was reloaded.

### Steps to reproduce

You could reproduce when working on a theme or any VS Code extension I assume - that's where I reproduced.

You can fork & test with my theme - https://github.com/Foxhoundn/synthax-code-theme
Or you can try forking our extension, but bear in mind this is a huge project and will require additional steps to set up - https://github.com/qoretechnologies/qorus-vscode

After a certain time working with the other window open (when Run & Debug is running), the workspace disconnects - here are some of the logs

```
 WARN Error: Aborted onWillSaveTextDocument-event after 1750ms
    at mainThreadSaveParticipant.ts:39
mainThreadExtensionService.ts:63 [[object Object]]Cannot find target e2c95a853c53a07a40ef9bbf
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 Error: Cannot find target e2c95a853c53a07a40ef9bbf
	at t.SessionManager.createNewChildSession (/ide/extensions/ms-vscode.js-debug/src/extension.js:2)
	at /ide/extensions/ms-vscode.js-debug/src/extension.js:2
	at Server.<anonymous> (/ide/extensions/ms-vscode.js-debug/src/extension.js:2)
	at Server.emit (/events.js:315)
	at TCP.onconnection (/net.js:1560)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
mainThreadExtensionService.ts:63 [[object Object]]Cannot find target e2c95a853c53a07a40ef9bbf
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 Error: Cannot find target e2c95a853c53a07a40ef9bbf
	at t.SessionManager.createNewChildSession (/ide/extensions/ms-vscode.js-debug/src/extension.js:2)
	at /ide/extensions/ms-vscode.js-debug/src/extension.js:2
	at Server.<anonymous> (/ide/extensions/ms-vscode.js-debug/src/extension.js:2)
	at Server.emit (/events.js:315)
	at TCP.onconnection (/net.js:1560)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'text' of undefined
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'text' of undefined	at /home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17:66873	at Object.t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17:67000)	at t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17:75159)	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at P.$acceptDirtyStateChanged (/ide/out/vs/server/remoteExtensionHostProcess.js:95:71823)	at t._doInvokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99:13802)	at t._invokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99:13486)	at t._receiveRequest (/ide/out/vs/server/remoteExtensionHostProcess.js:99:12148)	at t._receiveOneMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:99:10826)	at /ide/out/vs/server/remoteExtensionHostProcess.js:99:8922	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74:18942)	at /ide/out/vs/server/remoteExtensionHostProcess.js:114:34341	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74:18942)	at n._receiveMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:74:23523)	at /ide/out/vs/server/remoteExtensionHostProcess.js:74:21057	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at w.acceptChunk (/ide/out/vs/server/remoteExtensionHostProcess.js:74:15770)	at /ide/out/vs/server/remoteExtensionHostProcess.js:74:14900	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at s._processReadQueue (/ide/out/vs/server/remoteExtensionHostProcess.js:114:21295)
I @ console.ts:137
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'text' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'text' of undefined
	at /home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17
	at Object.t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17)
	at t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17)
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at P.$acceptDirtyStateChanged (/ide/out/vs/server/remoteExtensionHostProcess.js:95)
	at t._doInvokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at t._invokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at t._receiveRequest (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at t._receiveOneMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:99
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:114
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at n._receiveMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:74
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at w.acceptChunk (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:74
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at s._processReadQueue (/ide/out/vs/server/remoteExtensionHostProcess.js:114)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'text' of undefined
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'text' of undefined	at /home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17:66873	at Object.t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17:67000)	at t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17:75159)	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at P.$acceptDirtyStateChanged (/ide/out/vs/server/remoteExtensionHostProcess.js:95:71823)	at P.$acceptModelSaved (/ide/out/vs/server/remoteExtensionHostProcess.js:95:71566)	at t._doInvokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99:13802)	at t._invokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99:13486)	at t._receiveRequest (/ide/out/vs/server/remoteExtensionHostProcess.js:99:12148)	at t._receiveOneMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:99:10826)	at /ide/out/vs/server/remoteExtensionHostProcess.js:99:8922	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74:18942)	at /ide/out/vs/server/remoteExtensionHostProcess.js:114:34341	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74:18942)	at n._receiveMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:74:23523)	at /ide/out/vs/server/remoteExtensionHostProcess.js:74:21057	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at w.acceptChunk (/ide/out/vs/server/remoteExtensionHostProcess.js:74:15770)	at /ide/out/vs/server/remoteExtensionHostProcess.js:74:14900	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66:1712)	at s._processReadQueue (/ide/out/vs/server/remoteExtensionHostProcess.js:114:21295)
I @ console.ts:137
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'text' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'text' of undefined
	at /home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17
	at Object.t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17)
	at t.default (/home/gitpod/.vscode-remote/extensions/tabnine.tabnine-vscode-3.5.11/out/extension.js:17)
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at P.$acceptDirtyStateChanged (/ide/out/vs/server/remoteExtensionHostProcess.js:95)
	at P.$acceptModelSaved (/ide/out/vs/server/remoteExtensionHostProcess.js:95)
	at t._doInvokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at t._invokeHandler (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at t._receiveRequest (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at t._receiveOneMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:99)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:99
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:114
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at r.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at n._receiveMessage (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:74
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at w.acceptChunk (/ide/out/vs/server/remoteExtensionHostProcess.js:74)
	at /ide/out/vs/server/remoteExtensionHostProcess.js:74
	at u.fire (/ide/out/vs/server/remoteExtensionHostProcess.js:66)
	at s._processReadQueue (/ide/out/vs/server/remoteExtensionHostProcess.js:114)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
mainThreadExtensionService.ts:63 [[object Object]]Cannot find target e2c95a853c53a07a40ef9bbf
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 Error: Cannot find target e2c95a853c53a07a40ef9bbf
	at t.SessionManager.createNewChildSession (/ide/extensions/ms-vscode.js-debug/src/extension.js:2)
	at /ide/extensions/ms-vscode.js-debug/src/extension.js:2
	at Server.<anonymous> (/ide/extensions/ms-vscode.js-debug/src/extension.js:2)
	at Server.emit (/events.js:315)
	at TCP.onconnection (/net.js:1560)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
5errors.ts:160 Uncaught (in promise) Canceled: Canceled
    at y (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:8:1157)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1736:2563
    at l.fire (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:1712)
    at M.cancel (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15007)
    at S.cancel (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15548)
    at S.dispose (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15603)
    at p (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:578:33730)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:578:34817
    at l.fire (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:1712)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:555:31586
y @ errors.ts:160
(anonymous) @ searchService.ts:163
fire @ event.ts:577
cancel @ cancellation.ts:69
cancel @ cancellation.ts:124
dispose @ cancellation.ts:130
p @ pickerQuickAccess.ts:120
(anonymous) @ pickerQuickAccess.ts:269
fire @ event.ts:577
(anonymous) @ quickInput.ts:745
fire @ event.ts:577
onValueChange @ inputBox.ts:527
(anonymous) @ inputBox.ts:219
await in (anonymous) (async)
(anonymous) @ pickerQuickAccess.ts:269
fire @ event.ts:577
(anonymous) @ quickInput.ts:745
fire @ event.ts:577
onValueChange @ inputBox.ts:527
(anonymous) @ inputBox.ts:219
2errors.ts:160 Uncaught (in promise) Canceled: Canceled
    at y (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:8:1157)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1736:2563
    at l.fire (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:1712)
    at M.cancel (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15007)
    at S.cancel (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15548)
    at l.fire (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:1732)
    at M.cancel (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15007)
    at S.cancel (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:15548)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:584:32698
    at l.fire (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:1712)
y @ errors.ts:160
(anonymous) @ searchService.ts:163
fire @ event.ts:577
cancel @ cancellation.ts:69
cancel @ cancellation.ts:124
fire @ event.ts:579
cancel @ cancellation.ts:69
cancel @ cancellation.ts:124
(anonymous) @ quickAccess.ts:139
fire @ event.ts:577
didHide @ quickInput.ts:311
hide @ quickInput.ts:1697
(anonymous) @ quickInput.ts:1309
fire @ event.ts:577
(anonymous) @ dom.ts:986
await in (anonymous) (async)
(anonymous) @ pickerQuickAccess.ts:269
fire @ event.ts:577
(anonymous) @ quickInput.ts:745
fire @ event.ts:577
onValueChange @ inputBox.ts:527
(anonymous) @ inputBox.ts:219
log.ts:301  INFO [remote-connection][ExtensionHost][bdb08…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
log.ts:313   ERR CloseEvent
log.ts:301  INFO [remote-connection][ExtensionHost][bdb08…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:301  INFO [remote-connection][ExtensionHost][bdb08…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][bdb08…][reconnect] connecting to black-marmoset-d720tsvs.ws-eu23.gitpod.io:443...
log.ts:313   ERR [remote-connection][ExtensionHost][bdb08…][reconnect][black-marmoset-d720tsvs.ws-eu23.gitpod.io:443] received error control message when negotiating connection. Error:
log.ts:313   ERR Error: Connection error: Unknown reconnection token (seen before)
    at W (remoteAgentConnection.ts:743)
    at remoteAgentConnection.ts:325
    at l.fire (event.ts:577)
    at o.fire (ipc.net.ts:638)
    at u._receiveMessage (ipc.net.ts:964)
    at ipc.net.ts:899
    at l.fire (event.ts:577)
    at r.acceptChunk (ipc.net.ts:382)
    at ipc.net.ts:338
    at browserSocketFactory.ts:230
log.ts:313   ERR [remote-connection][ExtensionHost][bdb08…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
log.ts:313   ERR Error: Connection error: Unknown reconnection token (seen before)
    at W (remoteAgentConnection.ts:743)
    at remoteAgentConnection.ts:325
    at l.fire (event.ts:577)
    at o.fire (ipc.net.ts:638)
    at u._receiveMessage (ipc.net.ts:964)
    at ipc.net.ts:899
    at l.fire (event.ts:577)
    at r.acceptChunk (ipc.net.ts:382)
    at ipc.net.ts:338
    at browserSocketFactory.ts:230
abstractExtensionService.ts:644 Extension host (Remote) terminated unexpectedly. Code: 0, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:644
await in _onExtensionHostCrashed (async)
_beginReconnecting @ remoteAgentConnection.ts:594
(anonymous) @ remoteAgentConnection.ts:572
fire @ event.ts:577
fire @ ipc.net.ts:638
(anonymous) @ ipc.net.ts:832
n @ browserSocketFactory.ts:238
fire @ event.ts:577
(anonymous) @ browserSocketFactory.ts:174
e._callEventListener @ reconnecting-websocket-mjs.js:555
(anonymous) @ reconnecting-websocket-mjs.js:195
_handleClose @ reconnecting-websocket-mjs.js:195
5errors.ts:160 Uncaught (in promise) Canceled: Canceled
    at Object.y [as canceled] (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:8:1157)
    at h._remoteCall (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1535:13193)
    at Proxy.x.<computed>.A.charCodeAt.x.<computed> (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1535:9588)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1528:2495
    at l.fire (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:69:1712)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:571:43727
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:17:30315
    at Object.dispose (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:9:7058)
    at n.dispose (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1528:2647)
    at Xr.dispose (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:1586:6178)
y @ errors.ts:160
_remoteCall @ rpcProtocol.ts:477
x.<computed>.A.charCodeAt.x.<computed> @ rpcProtocol.ts:252
(anonymous) @ mainThreadLanguageFeatures.ts:56
fire @ event.ts:577
(anonymous) @ languageConfigurationRegistry.ts:198
(anonymous) @ lifecycle.ts:170
(anonymous) @ functional.ts:17
dispose @ mainThreadLanguageFeatures.ts:68
dispose @ extensionHostManager.ts:182
_onExtensionHostCrashed @ abstractExtensionService.ts:650
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:636
(anonymous) @ abstractExtensionService.ts:626
fire @ event.ts:577
_onExtHostConnectionLost @ remoteExtensionHost.ts:209
(anonymous) @ remoteExtensionHost.ts:137
fire @ event.ts:577
fire @ ipc.net.ts:638
acceptDisconnect @ ipc.net.ts:922
F @ remoteAgentConnection.ts:732
_gotoPermanentFailure @ remoteAgentConnection.ts:687
(anonymous) @ remoteAgentConnection.ts:522
triggerPermanentFailure @ remoteAgentConnection.ts:522
_runReconnectingLoop @ remoteAgentConnection.ts:643
await in _runReconnectingLoop (async)
_beginReconnecting @ remoteAgentConnection.ts:594
(anonymous) @ remoteAgentConnection.ts:572
fire @ event.ts:577
fire @ ipc.net.ts:638
(anonymous) @ ipc.net.ts:832
n @ browserSocketFactory.ts:238
fire @ event.ts:577
(anonymous) @ browserSocketFactory.ts:174
e._callEventListener @ reconnecting-websocket-mjs.js:555
(anonymous) @ reconnecting-websocket-mjs.js:195
_handleClose @ reconnecting-websocket-mjs.js:195
search.ts:460 Uncaught (in promise) Error: Canceled
    at L (search.ts:468)
    at searchService.ts:237
    at async searchService.ts:142
    at async cacheState.ts:71
D @ search.ts:460
L @ search.ts:468
(anonymous) @ searchService.ts:237
await in (anonymous) (async)
load @ cacheState.ts:82
createFileQueryCache @ anythingQuickAccess.ts:495
set @ anythingQuickAccess.ts:117
provide @ anythingQuickAccess.ts:210
doShowOrPick @ quickAccess.ts:132
show @ quickAccess.ts:40
handler @ quickAccessActions.ts:138
w.handler @ commands.ts:90
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
_doDispatch @ abstractKeybindingService.ts:296
_dispatch @ abstractKeybindingService.ts:187
(anonymous) @ keybindingService.ts:261
DevTools failed to load source map: Could not load content for https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/node_modules/vscode-textmate/release/main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/node_modules/xterm/lib/xterm.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/node_modules/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/node_modules/xterm-addon-search/lib/xterm-addon-search.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/node_modules/@gitpod/local-app-api-grpcweb/lib/localapp.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
log.ts:313   ERR Canceled: Canceled
    at Object.y [as canceled] (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:8:1157)
    at Object.call (https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:85:1927)
    at https://blobserve.ws-eu23.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-0d1e8cc5dcc8ccb38efcc2cd6404316b6e7bf4e9/__files__/out/vs/workbench/workbench.web.api.js:85:7223
```

I also have screenshots if for whatever reason you'd need those.

### Workspace affected

black-marmoset-d720tsvs

### Expected behavior

Connection should not be terminated.

### Example repository

https://github.com/qoretechnologies/qorus-vscode

### Anything else?

Only happens when Run & Debug is running (theme or extension) and the 2nd code tab is opened.

### LINKED ISSUE #7628: Unexpected connections to processes listening on localhost
### Bug description

When opening a TCP socket on `127.0.0.1`, some local process establishes a connection to it every second (source is 127.0.0.1, random port). This causes issues e.g. with PySpark, which opens a socket and complains about bad data being sent to it. The same problem does not occur when listening to `0.0.0.0` or e.g. `127.0.0.2`.

I've also noticed that when listening on `127.0.0.1`, then `supervisor` starts listening on the same port, but on the local tap interface, and would like to understand why.

### Steps to reproduce

Start a process that listens on `127.0.0.1` (port 12989 here is a random port), e.g. using `socat`:
```
socat -d -d TCP4-LISTEN:12989,bind=127.0.0.1,reuseaddr,keepalive,fork STDOUT
```
Socat will print something to the screen every time a connection is established.

To verify that this interferes with `pyspark`, run the PySpark shell `pyspark`. PySpark in local mode will open up a socket on `127.0.0.1` and a random port. You will see a stream of messages:
```
ValueError: The value of the provided token to the AccumulatorServer is not correct.
```

Verify that `supervisor` starts listening, e.g. using `netstat`:
```
netstat -tulpn
```

### Workspace affected

_No response_

### Expected behavior

I expect the socket to receive no connections

### Example repository

The issue can be reproduced on any workspace. I created a workspace that has PySpark, socat and netstat installed for easy verification here: https://gitpod.io/#https://github.com/JonMerlevede/gitpodissue.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

With the current approach (calling `net.DialTimeout`) it causes exceptions to be thrown continuously in the vscode-js-debug extension when debugging, internally it creates a tcp server and then extension host connects to it, this connection should only happen once as it's tracked internally, after some time this exceptions make the the extension host crash.

## Related Issue(s)

Fixes #7313
Fixes #7628

## How to test

1. Open https://github.com/Foxhoundn/synthax-code-theme in a prev env
2. Press f5 to start debugging
3. Open dev tools on main window and observe in console there are no errors of this type
```
workbench.web.api.js:1923 Error: Cannot find target c0f0b7985e02a5dd08c2a37e
	at t.SessionManager.createNewChildSession (/ide/extensions/ms-vscode.js-debug/src/extension.js:2:1344943)
	at /ide/extensions/ms-vscode.js-debug/src/extension.js:2:1342437
	at Server.<anonymous> (/ide/extensions/ms-vscode.js-debug/src/extension.js:2:1342653)
	at Server.emit (/events.js:315:20)
	at TCP.onconnection (/net.js:1560:8)
```

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#7313*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#7313*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#7313*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
@aledbf can you review please :pray:
You mentioned to keep the `isLocalPortOpen` function but that would imply calling `readNetTCPFile` twice and duplicating some logic from `updateState`.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 150f914acf2ad5ee629eb96bf0ac75e6998ec1dc</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7534#issuecomment-1013902778" title="Approved">aledbf</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#7313*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by aledbf — APPROVED** [review]
LGTM

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7534#issuecomment-1013902778" title="Approved">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7534#issuecomment-1013909375" title="Approved">jeanp413</a>*

Associated issue: *#7313*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [jeanp413]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/supervisor/pkg/ports/ports.go [hunk 1]
```diff
@@ -289,6 +259,12 @@ func (pm *Manager) updateState(ctx context.Context, exposed []ExposedPort, serve
 	if served != nil {
 		servedMap := make(map[uint32]ServedPort)
 		for _, port := range served {
+			if port.Address.String() == workspaceIPAdress {
```
Comment (iQQBot) [inline components/supervisor/pkg/ports/ports.go:262]: If we listen on this IP address(10.0.2.100), the port view doesn't detect

Comment (jeanp413) [reply components/supervisor/pkg/ports/ports.go:262]: Good catch, created https://github.com/gitpod-io/gitpod/pull/7631
