### PR TITLE
[UBP] Pagination and UI fixes

### LINKED ISSUE #11285: [UBP] Team usage view - Iterate based on designs
Following up from recent PR #11257 - (screenshot 👇 ) 

| current | [latest figma designs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1274%3A8041) 🥯 |
| ------- | -------- |
| Screenshot 2022-07-11 at 15 29 00 | usage-2022-07-18 |

#### Column changes 
- [x] 1. **Type**: "Workspace" or "Prebuild" no colors 
- [x] 2. **Class**: "standard" or "large" lowercase class names
- [x] 3. **Usage**: (instead of Amount) values in minutes for workspaces
- [x] 4. **Credits**: show icon in heading, values should have 1 decimal point (unless that's difficult)
5. **Time**: with avatar (user) for workspaces, same-size blank for prebuilds (will do this in a separate PR)

#### Other changes 
- [x]  Navigation - move “Usage” link up to team tabs
- [x] Pagination - when usage data exceeds 100 sessions

From discussion with @gtsiolis ([notes](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#46017a84b86d48e0b1d1414d42dac840) - internal)

### LINKED ISSUE #11483: Add pagination or infinite scroll support
### Problem to solve

Pagination. 📄 

### Proposal

:a: **Pagination** breaks up content into multiple pages.
:b: **Infinite scroll** helps users parse a large number of items. Infinite scroll is also suitable when the list updates frequently and there are no sorting or filtering options.

Cc @laushinka @jldec because of our recent discussion related to pagination.

### Designs

| Pagination (Simple) | Pagination (Complex) | 
|-|-|
| Simple | Complex |

| Infinite Scroll (Simple) | Infinite Scroll (Loading) | Infinite Scroll (Showing All) |
|-|-|-|
| InfiniteScrollSimple | InfiniteScrollPage | InfiniteScrollAll |

See [design specs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1326%3A3573).

### PR DESCRIPTION
**Pull request by laushinka**
## Description
Among other UI fixes, this PR:
- adds pagination
- moves the Usage tab outside of settings
- uses actual data from the API ([except for the usage period](https://github.com/gitpod-io/gitpod/pull/11481#issuecomment-1190553173))

Screenshot 2022-07-20 at 19 09 27

## Related Issue(s)

Fixes #11483
Fixes #11285

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@laushinka: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
This PR does not yet:
- show the user avatar for workspaces 
- show the real usage period

File: components/gitpod-protocol/src/usage.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export interface BillableSession {
 
     workspaceType: BillableWorkspaceType;
 
-    // "standard" or "XL"
+    // "standard" or "large"
```
Comment (easyCZ) [inline components/gitpod-protocol/src/usage.ts:23]: We should drop this comment, as it's not accurate. For our use-cases, the class is just a string and we don't necessarily know much more about the meaning of it - for self-hosted it may even be entirely different workspaceClasses

Comment (laushinka) [reply components/gitpod-protocol/src/usage.ts:23]: Ah, I see. Because the classes are determined by the workspace team?

Comment (easyCZ) [reply components/gitpod-protocol/src/usage.ts:23]: In part, but in general the idea behind classes is that for self-hosted, you should be able to customize (and name) them for the needs of each installation. Some may need Data Science workloads, some just tiny workspaces and we don't really know ahead of time what it will be

Comment (laushinka) [reply components/gitpod-protocol/src/usage.ts:23]: > for self-hosted, you should be able to customize (and name) them

Good point!

**Review by easyCZ — APPROVED** [review]
Code-wise LGTM. Adding hold for @jldec as he's a reviewer too.

/hold

**Review by jldec — APPROVED** [review]
Thanks Laurie - this is a great step forward - let's merge this - it will be good to see real usage data. (leaving hold in case you are still working on TS errors)

**Comment by laushinka** [comment]
> Thanks Laurie - this is a great step forward - let's merge this - it will be good to see real usage data. (leaving hold in case you are still working on TS errors)

Thanks! It's green now so I will unhold. Also thank you @gtsiolis for the quick UI sync-fixes 🔥

/unhold

**Comment by jldec** [comment]
@gtsiolis - since you're working on followup design polish I had some suggestions:

- remove extra heading above the list (takes up valuable real estate)
- move existing description up
- small polish on sidebar - heading bold, values not-bold, 
- "Total usage" instead of "Monthly usage" as discussed (and don't repeat the word "total" before credits)

Screenshot 2022-07-21 at 11 45 08

**Comment by gtsiolis** [comment]
Woohoo! UBP is getting real. ✨ 

[De rien](https://en.wiktionary.org/wiki/de_rien), @laushinka!

Agree with all your points, @jldec, except for probably removing the section heading before updating the sidebar, which could confuse users of what exactly they are looking at. However, I'd be up for trying that and seeing in action if the heading is really helpful.

To help demonstrate the issue here, let me add below some screenshot of how this page would look like a) with both a better sidebar and section heading, b) just the better sidebar, and c) no better sidebar and no heading.

I've also opened a few follow-up issues to keep track of some UX issues in this page, see https://github.com/gitpod-io/gitpod/issues/11526, https://github.com/gitpod-io/gitpod/issues/11527, and https://github.com/gitpod-io/gitpod/issues/11528.

| A | B | C |
|-|-|-|
| Usage | Usage-1 | Usage-2 |

**Comment by jldec** [comment]
@gtsiolis I don't see value in in the extra heading
(it steals vertical space from the list - we have a lot of chrome already) 

I find the bold black summary element in the sidebar a bit distracting so prefer C for that reason.

Could we please label the total usage element "Total Usage" (not "Monthly Usage") and use "Credits" as the units next to the value (instead of "Total Credits".)

cc: @laushinka

**Comment by gtsiolis** [comment]
> I don't see value in the extra heading - It steals vertical space from the list

@jldec Fair point. Up for removing it and see how it feels. 🤝 

> I find the bold black summary element in the sidebar a bit distracting so prefer option C for that reason.

@jldec Thanks for the feedback! Let's go with C and change back if needed. I may also attempt to create a version that's not so bold using black background, but a more grayish background. 🤝 

> Could we please label the total usage element "Total Usage" (not "Monthly Usage") and use "Credits" as the units next to the value (instead of "Total Credits".)

@jldec This is already changed in https://github.com/gitpod-io/gitpod/issues/11526.

**Comment by gtsiolis** [comment]
One more note regarding dropping the heavier black-colored active elements in the left sidebar is that we would need to pay closer attention to the UX changes so that the visual balance remains good as originally seen in the design specs. Otherwise, everything will collapse together in dense-information pages like the usage page.

The heavier black-colored elements were also added to provide the necessary visual balance, but also information hierarchy required when using fewer borders in the user interface, see also https://github.com/gitpod-io/gitpod/issues/7932#issuecomment-1026269854.

To demonstrate this better:

| BEFORE | AFTER | What's on production |
|-|-|-|
| Sidebar-1 | Sidebar | Sidebar3 |

From https://github.com/gitpod-io/gitpod/pull/11481#issuecomment-1191591423:
>  I may also attempt to create a version that's not so bold using black background, but a more grayish background. 🤝

| BEFORE | AFTER | What's on production |
|-|-|-|
| Usage | Usage-1 | Screenshot 2022-07-21 at 6 31 03 PM (2) |

**Comment by jldec** [comment]
Clarifying a little more - I think the black box draws attention (because of its size) in a way that makes it look like a heading (for the page) instead of a section element.
