### PR TITLE
fix(gitpod-cli): ports list safe access to exposed url

### LINKED ISSUE #11990: Segmentation fault when running "gp ports list" in a task command
### Bug description

I started a workspace with two simple tasks :

```yaml
tasks:
  # Console for the user with a welcome message
  - name: Console
    command: |
      sleep 10
      echo "========================================"
      echo "Welcome to this repository ! Hugo server should start automatically and show both drafts and future posts, see below for the URL."
      gp ports list
      echo "========================================"
  # Dedicated terminal to display the logs
  - name: Logs
    command: |
      hugo serve --buildDrafts --buildFuture
    openMode: split-right

```

When opening gitpod I see a segmentation fault in the first console, when running "gp ports list" :

```bash
HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> echo "========================================"
> echo "Welcome to this repository ! Hugo server should start automatically and show both drafts and future posts, see below for the URL."
> gp ports list
> echo "========================================"
> 
> }
========================================
Welcome to this repository ! Hugo server should start automatically and show both drafts and future posts, see below for the URL.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x95560e]

goroutine 1 [running]:
github.com/gitpod-io/gitpod/gitpod-cli/cmd.glob..func11(0xf70c80, {0xa9a3e2, 0x0, 0x0})
        /tmp/build/components-gitpod-cli--app.6b8796aa57fed8a61e36573e2558f89f4aa872c2/cmd/ports-list.go:86 +0x3ae
github.com/spf13/cobra.(*Command).execute(0xf70c80, {0xfb1318, 0x0, 0x0})
        /home/gitpod/go-packages/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xf70780)
        /home/gitpod/go-packages/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/gitpod/go-packages/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/gitpod-io/gitpod/gitpod-cli/cmd.Execute()
        /tmp/build/components-gitpod-cli--app.6b8796aa57fed8a61e36573e2558f89f4aa872c2/cmd/root.go:35 +0x325
main.main()
        /tmp/build/components-gitpod-cli--app.6b8796aa57fed8a61e36573e2558f89f4aa872c2/main.go:12 +0x17
========================================
```

Trying to run the command manually after the workspace as fully setup is OK : 
```bash
gitpod /workspace/information-platform (master) $ gp ports list
| PORT |     STATUS     |                                URL                                 | NAME & DESCRIPTION |
|------|----------------|--------------------------------------------------------------------|--------------------|
| 1313 | open (private) | https://1313-[REDACTED].ws-eu59.gitpod.io | hugo-server        |
```

### Steps to reproduce

My .gitpod.io file is very basic. 

```yaml
tasks:
  # Console for the user with a welcome message
  - name: Console
    command: |
      sleep 10
      echo "========================================"
      echo "Welcome to this repository ! Hugo server should start automatically and show both drafts and future posts, see below for the URL."
      gp ports list
      echo "========================================"
  # Dedicated terminal to display the logs
  - name: Logs
    command: |
      hugo serve --buildDrafts --buildFuture
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    name: hugo-server
    onOpen: open-browser

```

### Workspace affected

_No response_

### Expected behavior

The gp ports list command should display the open ports

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andreafalzetti**
## Description
This PR fix safe access to `port.Exposed.*` for both `Url` and `Visibility`.

Also, I've refactored the existing logic to determine the status, to be more readable and to follow the [vscode implementation](https://github.com/gitpod-io/openvscode-server/blob/gp-code/main/extensions/gitpod-shared/src/workspacePort.ts#L116-L140)

```
 gp ports list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x97c5ae]

goroutine 1 [running]:
github.com/gitpod-io/gitpod/gitpod-cli/cmd.glob..func12(0xfb5fe0, {0xac9654, 0x0, 0x0})
        github.com/gitpod-io/gitpod/gitpod-cli/cmd/ports-list.go:86 +0x3ae
github.com/spf13/cobra.(*Command).execute(0xfb5fe0, {0xff6aa8, 0x0, 0x0})
        github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xfb5ae0)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/gitpod-io/gitpod/gitpod-cli/cmd.Execute()
        github.com/gitpod-io/gitpod/gitpod-cli/cmd/root.go:35 +0x325
main.main()
        github.com/gitpod-io/gitpod/gitpod-cli/main.go:12 +0x17
```

## Related Issue(s)

Fixes #11990

## How to test
1. Start a workspace with https://afalz-fix-5d5a7c82e6.preview.gitpod-dev.com/#https://github.com/gitpod-io/empty
2. Run `gp ports list` and observe nothing is resulted (actually port 3000 is already displayed as non-served by default for some reason)
3. Run `curl lama.sh | sh -s — —port 3001` 
4. Run `gp ports list` and observe port 3001 being `open (private)`
5. Run `gp ports visibility 3001:public`, then run `gp ports list` and observe port 3001 being open (public)

## Release Notes

```release-note
Bugfix for gitpod CLI: avoid failure on `ports list` when port is not exposed
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by felladrin** [comment]
ℹ️ I'm reviewing it now!

File: components/gitpod-cli/cmd/ports-list.go [hunk 1]
```diff
@@ -48,21 +48,40 @@ var listPortsCmd = &cobra.Command{
...
 					status = "failed to expose"
 					statusColor = tablewriter.FgRedColor
 				} else {
 					status = "detecting..."
 					statusColor = tablewriter.FgYellowColor
 				}
-			} else if port.Served {
-				status = "open (" + port.Exposed.Visibility.String() + ")"
-				if port.Exposed.Visibility == supervisor.PortVisibility_public {
+			} else {
```
Comment (felladrin) [inline components/gitpod-cli/cmd/ports-list.go:70]: _Suggestion_: How about saving some processing by reducing the checks?
Currently, it will run between 4 and 8 checks. If you change it, it will run from 2 to 4 checks:

```
			} else if port.Tunneled != nil {
				if port.Tunneled.Visibility == supervisor.TunnelVisiblity(supervisor.TunnelVisiblity_value["network"]) {
					status = "open on all interfaces"
					statusColor = tablewriter.FgHiGreenColor
				} else if port.Tunneled.Visibility == supervisor.TunnelVisiblity(supervisor.TunnelVisiblity_value["host"]) {
					status = "open on localhost"
					statusColor = tablewriter.FgHiGreenColor
				}
			} else if port.Exposed != nil {
				if port.Exposed.Visibility == supervisor.PortVisibility_public {
					status = "open (public)"
					statusColor = tablewriter.FgHiGreenColor
				} else if port.Exposed.Visibility == supervisor.PortVisibility_private {
					status = "open (private)"
					statusColor = tablewriter.FgHiCyanColor
				}
			}
```

**Review by felladrin — COMMENTED** [review]
Working as described! ✅ 

image

**Review by felladrin — APPROVED** [review]

File: components/gitpod-cli/cmd/ports-list.go (hunk 1 above)
Comment (andreafalzetti) [reply components/gitpod-cli/cmd/ports-list.go]: thanks for the feedback, @felladrin :) I've integrated the suggestion
