### PR TITLE
fix #3847: reconnect ws to server in iframe

### LINKED ISSUE #3847: [dashboard] Websocket is not reconnectable in iframe
### Bug description

When not being logged in to Gitpod and trying to access a URL of a running workspace you will see the login page, but after signing in with OAuth you will stay on the login page. 

### Steps to reproduce

1. Start a workspace and copy it's URL
2. open a clean browser session (where you are not logged in at that time) and try to access the workspace URL
3. try to login

### Expected behavior

After a successful login, you would be able to access your workspace from a clean browser session.

### Example repository

_No response_

### Details

* When not being logged in to Gitpod and trying to access a URL of a running workspace the websocket is created in the supervisor frontend instead of the regular dashboard parts.
* Supervisors frontend is not prepared for reconnecting websockets (`Websocket reconnect not possible` is logged)
* Also it seems there were related changes merged to `gitpod-protocol` in the meantime which needs to be considered.

### Workaround

* forcibly reload the browser tab (with the workspace URL) after the login in order to recreate the websocket connection

/cc. @akosyakov

### PR DESCRIPTION
**Pull request by akosyakov**
Try to login on gitpod.io and workspace location without any credentials stored in the browser.

### CODE REVIEW

File: components/gitpod-protocol/src/messaging/browser/connection.ts [hunk 1]
```diff
@@ -26,14 +27,17 @@ export class WebSocketConnectionProvider {
     createProxy<T extends object>(path: string | Promise<string>, target?: object, options?: WebSocketOptions): JsonRpcProxy<T> {
         const factory = new JsonRpcProxyFactory<T>(target);
         const startListening = (path: string) => {
-            this.listen({
-                    path,
-                    onConnection: c => factory.listen(c)
-                },
+            const socket = this.listen({
```
Comment (AlexTugarev) [inline components/gitpod-protocol/src/messaging/browser/connection.ts:30]: `createProxy2` 👇🏻  can be removed then 🙏🏻

**Review by AlexTugarev — APPROVED** [review]
Works nicely! Thanks @akosyakov !
