### PR TITLE
[dashboard/code] Produce timing data for workspace startup

### LINKED ISSUE #4863: [enhancement] More insight into the UX-perspective on workspace startup
Historically we have mostly been looking at backend metrics when it comes to workspace startup(/failure) rates. Also, we have not been very good at separating "user/input errors" (where we're missing sanity checks, better feedback, general UX improvements) and "backend issues" (bugs, but also problems we have with some rare kubernetes/cloud provider condition): Both get spilled into the frontend nearly unfiltered.

This has two implications:
 - we're leaving users with little to no clue what went wrong - and if they can do sth to "make it work" for them
 - more often then we'd like to we learn about incidents from our users before alerts show them: experience shows that a lot of problems show in the "frontend" way before they pile up in the "backend" where our existing alerts catch them

To get a bit more insight how big this is of an issue, and if and how we can improve on it, we should start reporting and collecting measurements **in the frontend** on:
 - the steps a workspace startup is going through ("pages rendered"?)
 - timing for those steps
 - if workspace startup fails: record the error message we display to the user
 
 This should not be too complicated at first, but help to get a rough understanding on how much and what is going wrong.
 It also opens the doors for further improvements on:
 - UX improvements: show nicer error messages, plus hints on how to resolve common problems ("cannot parse Dockerfile", etc.)
 - eventually set up alerts on error rates to learn about incidents as early as our users
 
 @csweichel Suggested using some recently added segment integration for this

### PR DESCRIPTION
**Pull request by csweichel**
This PR produces analytics events from the frontend to track the speed and reliability of workspace starts. E.g.

```
{"payload":{"userId":"1c23ee48-4c56-4684-831e-cca71711a36b","event":"workspace-started","properties":{"workspaceId":"brown-leopon-tndxsxj3","instanceId":"7ed1f664-8af1-4ea0-8f4a-10178f925a79","contextURL":"https://github.com/gitpod-io/template-typescript-node","usesPrebuild":false}},"component":"server","severity":"DEBUG","time":"2021-07-22T09:30:16.571Z","environment":"devstaging","region":"europe-west1","message":"analytics track"}
{"payload":{"userId":"1c23ee48-4c56-4684-831e-cca71711a36b","event":"status_rendered","properties":{"workspaceId":"brown-leopon-tndxsxj3","phase":"creating"}},"component":"server","severity":"DEBUG","time":"2021-07-22T09:30:17.901Z","environment":"devstaging","region":"europe-west1","message":"analytics track"}
{"payload":{"userId":"1c23ee48-4c56-4684-831e-cca71711a36b","event":"status_rendered","properties":{"workspaceId":"brown-leopon-tndxsxj3","phase":"initializing"}},"component":"server","severity":"DEBUG","time":"2021-07-22T09:30:29.593Z","environment":"devstaging","region":"europe-west1","message":"analytics track"}
{"payload":{"userId":"1c23ee48-4c56-4684-831e-cca71711a36b","event":"status_rendered","properties":{"workspaceId":"brown-leopon-tndxsxj3","phase":"running"}},"component":"server","severity":"DEBUG","time":"2021-07-22T09:30:40.577Z","environment":"devstaging","region":"europe-west1","message":"analytics track"}
{"payload":{"userId":"1c23ee48-4c56-4684-831e-cca71711a36b","event":"status_rendered","properties":{"workspaceId":"brown-leopon-tndxsxj3","phase":"vsc_opened"}},"component":"server","severity":"DEBUG","time":"2021-07-22T09:30:45.054Z","environment":"devstaging","region":"europe-west1","message":"analytics track"}
```

Corresponding code PR: https://github.com/gitpod-io/vscode/pull/21
@akosyakov what's the usual path here? Merge the PR in vscode and then update the commit in this one?

Caveat: we'll possibly receive multiple `vsc_opened` events, namely whenever the user opens the IDE, e.g. reloads the window or opens another one.

fixes #4863 

/werft analytics=log

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4907#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **svenefftinge** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @svenefftinge` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [csweichel]
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
/hold

@akosyakov I want to make sure you get a chance to have a look at this change. Hence I'm holding the merge.

**Comment by akosyakov** [comment]
> @akosyakov what's the usual path here? Merge the PR in vscode and then update the commit in this one?

Usually yes, but we did not merge yet https://github.com/gitpod-io/gitpod/pull/4807 which points to gp-code. Main state sits in https://github.com/gitpod-io/vscode/tree/gp-code-1.57.1

**Comment by akosyakov** [comment]
I think you can do it in the supervisor instead of VS Code: https://github.com/gitpod-io/gitpod/blob/99885b4eb5867a9a83212d590704d2a014407a1d/components/supervisor/frontend/src/index.ts#L137

If ideService.state is ready, it means that IDE was rendered.

**Comment by akosyakov** [comment]
Could we also capture a reason why starting IDE failed. There is another state on ideServices.failureCause.

**Comment by csweichel** [comment]
@akosyakov thank you for the feedback. I'll move the write to the supervisor frontend, and also capture the failure reason.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4907#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **svenefftinge** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @svenefftinge` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
This is how the happy path looks like now:

image

File: components/supervisor/frontend/src/index.ts [hunk 1]
```diff
@@ -137,6 +137,15 @@ const loadingIDE = new Promise(resolve => window.addEventListener('DOMContentLoa
     ideService.onDidChange(() => {
         updateLoadingState();
         updateCurrentFrame();
+
+        window.gitpod.service.server.trackEvent({
+            event: "status_rendered",
+            properties: {
+                workspaceId: gitpodServiceClient.info.latestInstance?.workspaceId,
+                phase: `ide-${ideService.state}`,
+                error: ideService.failureCause?.message,
```
Comment (akosyakov) [inline components/supervisor/frontend/src/index.ts:146]: there is also can be `ideService.failureCause?.stack` it would be interesting to capture it

**Review by jakobhero — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 080c71bce25fb16fe4695f25f9864f048b1fe5c2</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4907#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4907#pullrequestreview-714643536" title="Approved">jakobhero</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **svenefftinge** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @svenefftinge` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4907#issuecomment-886582747" title="LGTM">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4907#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4907#pullrequestreview-714643536" title="Approved">jakobhero</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
