### PR TITLE
[code] add missing web deps

### LINKED ISSUE #3874: unable to open files i get a string that says [object event]
### Bug description

similar problem to this 
https://crimson-tuna-hpo667r4.ws-eu03.gitpod.io/

### Steps to reproduce

still new in coding  and learning new skills 

### Expected behavior

_No response_

### Example repository

https://crimson-tuna-hpo667r4.ws-eu03.gitpod.io/

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #3874: web part were built with filter for native deps, not web and removed jschardet. This dep is used sometimes.

Change in Gitpod Code: https://github.com/gitpod-io/vscode/commit/9701055e7471b4d2edf281cbdb479bbb57f78e8c

#### How to test

- Start a workspace.
- Check jschardet is there, it should be on this path: node_modules/jschardet/dist/jschardet.min.js

### CODE REVIEW

File: components/ide/code/startup.sh [hunk 1]
```diff
@@ -31,4 +31,4 @@ export USER=gitpod
 [ -s ~/.nvm/nvm-lazy.sh ] && source ~/.nvm/nvm-lazy.sh
 
 cd /ide
-exec /ide/node/bin/gitpod-node --inspect=0 ./out/gitpod.js $*
\ No newline at end of file
+exec /ide/node/bin/gitpod-node ./out/gitpod.js $*
```
Comment (akosyakov) [inline components/ide/code/startup.sh:34]: it is a clean up

**Comment by jankeromnes** [comment]
Taking a look. 👀

File: components/ide/code/startup.sh (hunk 1 above)
Comment (akosyakov) [reply components/ide/code/startup.sh:34]: it is confusing, a user sees some port exposed when he does not start anything. I think it is better not to do it.

**Review by jankeromnes — APPROVED** [review]
Looks good to me, and works as advertised. Thanks!

Screenshot 2021-04-22 at 16 52 21
