### PR TITLE
Don't mark prebuilds with failing tasks unavailable

### LINKED ISSUE #4964: Don't abort prebuild if task failed
Task failure means something potentially wrong with user code base. Aborting a prebuild in such case means that a user has to wait all over to see the same error.

Also from Sven:
We’d need to also stop executing follow up task.

### PR DESCRIPTION
**Pull request by csweichel**
This PR correctly marks prebuilds with a failed headless task as available, and updates ws-manager to not spuriously add the `failed` condition if the headless task fails.

fixes #4964

### How to test
1. Run a prebuild with a failing headless task, e.g. https://csweichel-don-t-abort-prebuild-4964.staging.gitpod-dev.com#https://github.com/csweichel/test-repo/tree/task-failure
2. Check the database and find the prebuild marked as available

image

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4975#" title="Author self-approved">csweichel</a>*

Associated issue: *#4964*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-manager/pkg/manager/status.go [hunk 1]
```diff
@@ -570,6 +570,10 @@ func (m *Manager) extractStatusFromPod(result *api.WorkspaceStatus, wso workspac
 func extractFailure(wso workspaceObjects) (string, *api.WorkspacePhase) {
 	pod := wso.Pod
 
+	if pod.Name == "prebuild-60116ccc-1593-41f5-880e-6c4010dc4d1d" {
+		fmt.Println()
```
Comment (geropl) [inline components/ws-manager/pkg/manager/status.go:574]: Debug leftover?

File: components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.json [hunk 2]
```diff
@@ -0,0 +1,1223 @@
...
+                      ".": {},
+                      "f:name": {},
+                      "f:value": {}
+                    },
+                    "k:{\"name\":\"GITPOD_GIT_USER_EMAIL\"}": {
+                      ".": {},
+                      "f:name": {},
+                      "f:value": {}
+                    },
+                    "k:{\"name\":\"GITPOD_GIT_USER_NAME\"}": {
```
Comment (geropl) [inline components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.json:133]: Can we somehow get rid of this inline schemas in test data? :thinking:

File: components/ws-manager/pkg/manager/status.go (hunk 1 above)
Comment (csweichel) [reply components/ws-manager/pkg/manager/status.go:574]: oops. Yes it is. Will remove

File: components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.json (hunk 2 above)
Comment (csweichel) [reply components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.json:133]: or in Kubernetes in general :D 

I'm not sure what the effect would be if we removed this. Probably none.

**Comment by csweichel** [comment]
@geropl debug leftover is removed. Please have another look

**Review by geropl — APPROVED** [review]
Code LGTM, tested and worked :+1:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 633a975dcfd6b697616f5278363f392b12b1f86c</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4975#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4975#pullrequestreview-717798064" title="Approved">geropl</a>*

Associated issue: *#4964*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [csweichel,geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
