### PR TITLE
Fix intermittent integration test failures

### LINKED ISSUE #5413: [test] TestBackup integration test fails
### Bug description

This is NOT a false positive, the backup doesn't actually succeed:
```JSON
{"instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"debug","message":"created temp file for workspace backup upload","serviceContext":{"service":"ws-daemon","version":""},"severity":"DEBUG","size":1536,"time":"2021-08-27T07:27:23Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"open /tmp/wsbkp-d2810fa4-3f27-4fc8-b2d8-6217d4114061-414450780.tar: no such file or directory","instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"error","message":"op failed","op":"upload layer","serviceContext":{"service":"ws-daemon","version":""},"severity":"ERROR","time":"2021-08-27T07:27:23Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
{"backoff":"1s","instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"debug","message":"retrying op after backoff","op":"upload layer","serviceContext":{"service":"ws-daemon","version":""},"severity":"DEBUG","time":"2021-08-27T07:27:23Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"open /tmp/wsbkp-d2810fa4-3f27-4fc8-b2d8-6217d4114061-414450780.tar: no such file or directory","instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"error","message":"op failed","op":"upload layer","serviceContext":{"service":"ws-daemon","version":""},"severity":"ERROR","time":"2021-08-27T07:27:24Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
{"backoff":"2s","instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"debug","message":"retrying op after backoff","op":"upload layer","serviceContext":{"service":"ws-daemon","version":""},"severity":"DEBUG","time":"2021-08-27T07:27:24Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"open /tmp/wsbkp-d2810fa4-3f27-4fc8-b2d8-6217d4114061-414450780.tar: no such file or directory","instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"error","message":"op failed","op":"upload layer","serviceContext":{"service":"ws-daemon","version":""},"severity":"ERROR","time":"2021-08-27T07:27:26Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"cannot upload workspace content:\n    github.com/gitpod-io/gitpod/ws-daemon/pkg/content.(*WorkspaceService).uploadWorkspaceContent\n        github.com/gitpod-io/gitpod/ws-daemon/pkg/content/service.go:493\n  - open /tmp/wsbkp-d2810fa4-3f27-4fc8-b2d8-6217d4114061-414450780.tar: no such file or directory","instanceId":"d2810fa4-3f27-4fc8-b2d8-6217d4114061","level":"error","message":"final backup failed","serviceContext":{"service":"ws-daemon","version":""},"severity":"ERROR","time":"2021-08-27T07:27:26Z","userId":"builtin-user-workspace-probe-0000000","workspaceId":"aqua-hamster-kws18kc8"}
```

### Steps to reproduce

In a core-dev context:
```bash
cd test
go test -v -run TestBackup ./...
```

### Expected behavior

The test should succeed

### Example repository

_No response_

### Anything else?

Requires the changes of https://github.com/gitpod-io/gitpod/pull/5407 to be merged before the test even gets this far.

### PR DESCRIPTION
**Pull request by rl-gitpod**
## Description
2 [minor](https://github.com/gitpod-io/gitpod/commit/a49bd32164aef08f3a8418d0f5d5579676d007d2) changes [here](https://github.com/gitpod-io/gitpod/commit/581d77998bea70e6dab982bedb7ce0b3d63da61b).
The most impactful is the ws-proxy [change](https://github.com/gitpod-io/gitpod/commit/b9f2dadea1a26a6f50542a2f9d852219079233de) where an active workspace could be deleted from the cache by the stop event of the same workspace id. This can happen in integration testing or via the API, but the UI would prevent this happening in user-land as it waits for the stopped event before allowing another start.

## Related Issue(s)

Fixes #5413 

## How to test
Run the 'TestBackup' test:

`go test -count=1 -v -run TestBackup ./...
`

Prior to these changes it will intermittently fail, but if run multiple times in succession it would fail more 'reliably'.
Now, the following repeated test will succeed:

`for i in $(seq 1 10); do go test -count=1 -v -run TestBackup ./...; done
`
## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **rl-gitpod** after the PR has been reviewed.

Associated issue: *#5413*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 1]
```diff
@@ -400,6 +403,18 @@ func (c *workspaceInfoCache) Insert(info *WorkspaceInfo) {
...
 
 func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
+	existing := c.infos[info.WorkspaceID]
+	if existing != nil {
+		// Do not insert if the current workspace is newer
+		// This works around issues when a workspace is deleted then restarted in quick succession
+		// and the stopping event occurs after the replocement pod is started
+		if existing.StartedAt != nil && info.StartedAt != nil {
+			if existing.StartedAt.AsTime().After(info.StartedAt.AsTime()) {
+				log.WithField("workspaceID", existing.WorkspaceID).Info("ignoring insert of older workspace")
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:413]:
```suggestion
				log.WithField("workspaceID", existing.WorkspaceID).Debug("ignoring insert of older workspace")
```

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 2]
```diff
@@ -413,14 +428,23 @@ func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
 	}
 }
 
-func (c *workspaceInfoCache) Delete(workspaceID string) {
+func (c *workspaceInfoCache) Delete(workspaceID string, startedAt *timestamppb.Timestamp) {
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:431]:
```suggestion
func (c *workspaceInfoCache) Delete(workspaceID string, startedAt *time.Time) {
```

Comment (rl-gitpod) [reply components/ws-proxy/pkg/proxy/infoprovider.go]: +1
Switched to time.Time throughout

**Comment by rl-gitpod** [comment]
/hold

Refactoring to use instance id and adding tests

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **rl-gitpod** after the PR has been reviewed.

Associated issue: *#5413*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **rl-gitpod** after the PR has been reviewed.

Associated issue: *#5413*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **rl-gitpod** after the PR has been reviewed.

Associated issue: *#5413*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: test/tests/workspace/content_test.go [hunk 3]
```diff
@@ -146,3 +146,9 @@ func TestMissingBackup(t *testing.T) {
 		})
 	}
 }
+
+
+var (
+	// TODO(rl): do not use a hard-coded tag, generate?
+	ideOpt = integration.WithIDEImage("eu.gcr.io/gitpod-core-dev/build/ide/code:commit-ff263e14024f00d0ed78386b4417dfa6bcd4ae2f")
```
[the remark this answers is not in the document]
Comment (rl-gitpod) [reply test/tests/workspace/content_test.go]: Thanks for the prompt... I recalled @akosyakov mentioning that the IDE config was separated from the server config which turned out to be the root cause. 

The integration tests now mirror that change.

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 4]
```diff
@@ -400,7 +402,24 @@ func (c *workspaceInfoCache) Insert(info *WorkspaceInfo) {
...
 
 func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
-	c.infos[info.WorkspaceID] = info
+	existingInfos := c.infos[info.WorkspaceID]
+	// Only insert if this is a new instance
+	mustAppend := true
+	for i, existingInfo := range existingInfos {
+		if existingInfo.InstanceID == info.InstanceID {
+			c.infos[info.WorkspaceID][i] = info
+			log.WithField("info", info).Debug("ignoring insert of existing instance for workspace")
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:411]: nit: this log statement will be very verbose in prod

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 5]
```diff
@@ -400,7 +402,24 @@ func (c *workspaceInfoCache) Insert(info *WorkspaceInfo) {
 }
 
 func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
-	c.infos[info.WorkspaceID] = info
+	existingInfos := c.infos[info.WorkspaceID]
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:405]: if `c.infos` were a `map[string]map[string]*WorkspaceInfo` the code below could be simplified to
```Go
existingInfos, ok := c.infos[info.WorkspaceID]
if !ok {
    existingInfos = make(map[string]*WorkspaceInfo)
}
existingInfos[info.InstanceID] = info
c.infos[info.WorkspaceID] = existingInfos
```

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 6]
```diff
@@ -413,25 +432,69 @@ func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
...
 	}
-	delete(c.coordsByPublicPort, info.IDEPublicPort)
-	delete(c.infos, workspaceID)
+
+	// Keep only the active instances and public port(s) for the workspace id
+	activeInfos := []*WorkspaceInfo{}
+	activePublicPorts := make(map[string]interface{})
+	var instanceIDEPublicPort string
+	for _, info := range infos {
+		if info.InstanceID != instanceID {
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:449]: nit: `if` statements with an `else` clause should have the non-negated case, otherwise you have to mentally double-negate to understand the clause.

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 7]
```diff
@@ -413,25 +432,69 @@ func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
...
+			activeInfos = append(activeInfos, info)
+			activePublicPorts[info.IDEPublicPort] = true
+		} else {
+			instanceIDEPublicPort = info.IDEPublicPort
+		}
+	}
+
+	if len(activeInfos) == 0 {
+		log.WithField("workspaceID", workspaceID).WithField("instanceID", instanceID).Debug("deleting all instances for workspace")
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:458]: I reckon the log statements in here would be rather verbose in prod

File: components/ws-proxy/pkg/proxy/infoprovider.go [hunk 8]
```diff
@@ -413,25 +432,69 @@ func (c *workspaceInfoCache) doInsert(info *WorkspaceInfo) {
...
-	if !present || info == nil {
+	infos, present := c.infos[workspaceID]
+	if !present || infos == nil {
 		return
 	}
-	delete(c.coordsByPublicPort, info.IDEPublicPort)
-	delete(c.infos, workspaceID)
+
+	// Keep only the active instances and public port(s) for the workspace id
+	activeInfos := []*WorkspaceInfo{}
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider.go:445]: with the `map` design outlined above this simplifies to:

```Go
var instanceIDEPublicPort string
if nfo, ok := infos[instanceID]; ok {
    delete(infos, instanceID)
    instanceIDEPublicPort = info.IDEPublicPort
}

if len(infos) == 0 {
    delete(c.infos, workspaceID)
} else {
    c.infos[workspaceID] = info
}
```

File: components/ws-proxy/pkg/proxy/infoprovider_test.go [hunk 9]
```diff
@@ -177,6 +176,758 @@ func TestRemoteInfoProvider(t *testing.T) {
 
 }
 
+func Test_workspaceInfoCache_Insert(t *testing.T) {
```
Comment (csweichel) [inline components/ws-proxy/pkg/proxy/infoprovider_test.go:179]: 🙏 thanks for the tests

File: test/pkg/integration/workspace.go [hunk 10]
```diff
@@ -127,14 +128,20 @@ func LaunchWorkspaceDirectly(it *Test, opts ...LaunchWorkspaceDirectlyOpt) (res
...
 	if ideImage == "" {
-		cfg, err := it.GetServerConfig()
+		cfg, err := it.GetServerIDEConfig()
 		if err != nil {
-			it.t.Fatalf("cannot find server config: %q", err)
+			it.t.Fatalf("cannot find server IDE config: %q", err)
+		}
+		ideImage = cfg.IDEImageAliases.Code
+		if ideImage == "" {
+			it.t.Fatalf("cannot start workspaces without an IDE image (required by resolver)")
```
Comment (csweichel) [inline test/pkg/integration/workspace.go:143]: which resolver does this refer to?

**Comment by csweichel** [comment]
imho the changes could go in like this, but I believe there's a chance to simplify things a little

File: components/ws-proxy/pkg/proxy/infoprovider.go (hunk 4 above)
Comment (rl-gitpod) [reply components/ws-proxy/pkg/proxy/infoprovider.go]: It is debug, but I'd left it for testing purposes - removed

File: test/pkg/integration/workspace.go (hunk 10 above)
Comment (rl-gitpod) [reply test/pkg/integration/workspace.go]: registry-facade - error message updated to reflect

File: components/ws-proxy/pkg/proxy/infoprovider.go (hunk 7 above)
Comment (rl-gitpod) [reply components/ws-proxy/pkg/proxy/infoprovider.go]: Ditto on the testing - removed

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f97190d139ec78a38c579290c1374481b849e556</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5617#issuecomment-925121343" title="LGTM">csweichel</a>*

Associated issue: *#5413*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [csweichel]
- ~~[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)~~ [csweichel]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [csweichel]
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
