### PR TITLE
[pvc] add init container to workspace to chown pvc mount folder

### LINKED ISSUE #14003: [pvc] `/workspace` directory is owned by `nobody`
### Bug description

/workspace directory is owned by nobody

### Steps to reproduce

On a workspace with PVC enabled, the `/workspace` directory is owned by `nobody`:
```
$ ls -al /
...
drwxrwsr-x  13 nobody gitpod  4096 Oct 19 13:13 workspace
```

This prevents e.g. the root user from making a new directory inside `/workspace` (but it's fine when done from the `gitpod` user):
```shell
$ sudo mkdir -p /workspace/directory
mkdir: cannot create directory ‘/workspace/directory’: Permission denied

```

With pvc disabled, it's owned by `gitpod`:

```
$ ls -al /
...
drwxr-xr-x   7 gitpod gitpod   98 Oct 19 13:41 workspace
```

### Workspace affected

_No response_

### Expected behavior

The prebuild workspace should be up and running.

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by sagor999**
## Description

Adds init container when using PVC to ensure that PVC mounted folder has proper permissions (k8s mounts folder as root)

## Related Issue(s)

Fixes #14003 

## How to test

Enable PVC
Open workspace. 
`ls -la /` and verify that `/workspace` is owned by `gitpod:gitpod` now.

## Release Notes

```release-note
none
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by csweichel** [comment]
What does that do to workspace startup time?
What alternatives to an init container exist?
How would that work in an airgapped environment?

**Comment by sagor999** [comment]
>What does that do to workspace startup time?

nothing. It executes almost instantenous (<1s), with only exception is a first image pull, which is fast since image is small and I believe we pack it into image for k3s as well.

>What alternatives to an init container exist?

none that I can think of. :( 
I guess it might be possible to do the same from workspace container itself? But when I tried to do same from even ring0, I would get permission denied, since workspace container does not run with actual root (AFAIK), yet k8s mounts that folder as root.

>How would that work in an airgapped environment?

I presume we need to ensure we pack busybox image for airgapped envs. Do you have a better image that I can use? :thinking: I was looking for anything similar that we already use and could not find anything.

@csweichel

File: components/ws-manager/pkg/manager/create.go [hunk 1]
```diff
@@ -592,6 +592,21 @@ func (m *Manager) createDefiniteWorkspacePod(startContext *startWorkspaceContext
 			gitpodGUID := int64(133332)
 			pod.Spec.SecurityContext.FSGroup = &gitpodGUID
 
+			// add init container to chown workspace subpath, so that it is owned by gitpod user (there is no k8s native way of doing this as of right now)
+			pod.Spec.InitContainers = append(pod.Spec.InitContainers, corev1.Container{
```
Comment (utam0k) [inline components/ws-manager/pkg/manager/create.go:596]: Sorry if this question is too beginner, but why do we need to use InitContainer instead of a normal container?

**Comment by utam0k** [comment]
> What alternatives to an init container exist?

How about using the IWS from ring0?

File: components/ws-manager/pkg/manager/create.go (hunk 1 above)
Comment (sagor999) [reply components/ws-manager/pkg/manager/create.go:596]: @utam0k we only need to do chown at container startup, and it ensures it runs before our workspace container. if we do as normal container, then both containers would start at the same time.

**Comment by sagor999** [comment]
>How about using the IWS from ring0?

IWS runs in ws-daemon right? ws-daemon does not have access to PVC. Only workspace container mounts it.

**Comment by utam0k** [comment]
> IWS runs in ws-daemon right? ws-daemon does not have access to PVC. Only workspace container mounts it.

I completely forgot about it :sob:

**Comment by jenting** [comment]
> I presume we need to ensure we pack busybox image for airgapped envs. Do you have a better image that I can use? 🤔 I was looking for anything similar that we already use and could not find anything.

We could build our own container image with chown.

Question: does ws-manager container image contains the chown binary?

**Comment by sagor999** [comment]
>Question: does ws-manager container image contains the chown binary?

I would be hesitant on trying to add wsmanager image into workspace pod. It feels potentially unsafe somehow. :thinking:

**Comment by csweichel** [comment]
IWS could indeed be a way to do this. Although it runs on the node, we call IWS from ring0 (e.g. `PrepareForUserNS`) where we could also correct the path. 

Also, we assemble a new filesystem layout in ring1 which might give us the opportunity to fix this.

**Comment by csweichel** [comment]
Depending on what this issue is blocking, we could also consider merging the change and look for a simpler solution immediately afterwards to remove the init container.

**Comment by sagor999** [comment]
@csweichel it blocks roll out of PVC to end users. (as without this fix some workspaces might become broken due to permission issue on /workspace folder).

**Comment by kylos101** [comment]
> Depending on what this issue is blocking, we could also consider merging the change and look for a simpler solution immediately afterwards to remove the init container.

@csweichel leaving this PR unmerged blocks our ability to continue the rollout for PVC with regular workspaces. The feedback in #14003 indicates without this fix, it could break user workflows (there's a workaround, but we'd prefer to avoid needing it).

My preference would be to ship this as is, assuming init-container failures result in a failed workspace start that:
1. we clearly log
2. which the user can see as a failed workspace start

Why? That'll give us a chance to focus on learning from a gradual rollout, which could include alternate designs (removing the init container, for example). 

@sagor999 if the `init-container` fails, what is the user experience like when starting the workspace? Do we log the error?

**Comment by sagor999** [comment]
I am not sure how that init container can fail... 
but if it would, it would result in workspace pod failing, which would show an error to user, something like "failed to start workspace".

**Review by jenting — APPROVED** [review]
> Depending on what this issue is blocking, we could also consider merging the change and look for a simpler solution immediately afterwards to remove the init container.

My preference is not to block this, LGTM.

**Comment by utam0k** [comment]
@sagor999 @csweichel @jenting 
`chown` is costly in terms of performance. I am concerned that this aspect has been verified.
Can we consider mounting to shiftfs instead of chown? It is just an idea.

**Comment by sagor999** [comment]
@utam0k it only chowns folder, it is not recursive. so it should be very cheap. or am I wrong?

**Comment by utam0k** [comment]
@sagor999 Oh, I missed. You are right
>  it is not recursive.
