### PR TITLE
[installer] set the ServiceType as LB for ws-proxy

### LINKED ISSUE #7734: [installer] Add support for Ingress traffic in cloud providers
### Bug description

The installer uses services `type=ClusterIP`. In particular for workspace clusters we need to use `type=LoadBalancer`, using standard ports 80 and 443. If we could also add support for additional annotations it would be ideal.

The goal here is to reduce the need for post-processing.

### Steps to reproduce

-

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nandajavarma**
## Description

Currently, the type of the service created for `ws-proxy` is `ClusterIP` by default. When setting up in cloud in just the `Workspace` installation, this creates a requirement for having to post process the YAML to change the type to `LoadBalancer`. With this PR, the default value of `ws-proxy` service type is set as `LoadBalancer` when the installation is of the kind `Workspace`

## Related Issue(s)

Fixes #7734

## How to test

Set the value of `kind` in config file `Workspace`. Run the render command, `installer render --config gitpod.config.yaml > gitpod.yaml`. This will render `Service` definition of the app `ws-proxy` as type `LoadBalancer`

## Release Notes

```release-note
NONE
```

## Documentation

No

### CODE REVIEW

File: install/installer/pkg/components/ws-proxy/objects.go [hunk 1]
```diff
@@ -14,23 +17,33 @@ var Objects = common.CompositeRenderFunc(
...
+				ContainerPort: SSHTargetPort,
+				ServicePort:   SSHServicePort,
+			},
+		}
+		return common.GenerateService(Component, ports, func(service *corev1.Service) {
+			// In the case of Workspace only setup, `ws-proxy` service is the entrypoint
+			// Hence we use LoadBalancer type for the service
+			if cfg.Config.Kind == config.InstallationWorkspace {
+				service.Spec.Type = corev1.ServiceTypeLoadBalancer
+				service.Annotations["cloud.google.com/neg"] = `{"exposed_ports": {"80":{},"443": {}}}`
```
Comment (princerachit) [inline install/installer/pkg/components/ws-proxy/objects.go:44]: Do we need to hardcode google specific annotations here?

Comment (MrSimonEmms) [reply install/installer/pkg/components/ws-proxy/objects.go:44]: These annotations have been hardcoded for some time on the basis that a) they're ignored if not used and b) we don't really have an effective (and non-verbose) way of adding custom annotations to services. Elsewhere, there's also an annotation for `external-dns` with the same thinking

File: install/installer/README.md [hunk 2]
```diff
@@ -163,12 +163,21 @@ yq eval-all --inplace \
   gitpod.yaml
 ```
 
+Similarly, if you are doing a `Workspace` only install (specifying `Workspace`
+as the kind in config) you might want to change the service type of `ws-proxy` to `ClusterIP`
+instead of the default `LoadBalancer`. You can post-process the yaml to change that.
```
Comment (MrSimonEmms) [inline install/installer/README.md:168]: nit: `YAML`, not `yaml`

Comment (nandajavarma) [reply install/installer/README.md]: done!

**Review by princerachit — APPROVED** [review]
I did not test the changes but code lgtm

File: install/installer/README.md [hunk 3]
```diff
@@ -163,12 +163,21 @@ yq eval-all --inplace \
...
 
+Similarly, if you are doing a `Workspace` only install (specifying `Workspace`
+as the kind in config) you might want to change the service type of `ws-proxy` to `ClusterIP`
+instead of the default `LoadBalancer`. You can post-process the YAML to change that.
+
+```shell
+yq eval-all --inplace \
+  '(select(.kind == "Service" and .metadata.name == "ws-proxy") | .spec.type) |= "ClusterIP"' \
+  gitpod.yaml
+```
```
Comment (corneliusludmann) [inline install/installer/README.md:174]: Off-topic: Do we have already an issue to get rid of this post-processing step and having a config value for the service type?

Comment (nandajavarma) [reply install/installer/README.md:174]: @corneliusludmann there is no such issue open specifically for making the service type configurable. I guess the question is do we plan on making this configurable, since our thought process [was to not make it configurable.](https://github.com/gitpod-io/gitpod/pull/7280)

Comment (corneliusludmann) [reply install/installer/README.md:174]: I'm glad you brought that up. :rocket: Indeed, we decided like this in the past. However, 2 things have changed since then:
- We introduced the `experimental` section. Everything that we won't support for some reason but need internally for SaaS should go there. We shouldn't need to rely on post-processing.
- Since our official supported installation path will be the KOTS installation, we are a little more relaxed about the config surface.

What do you think, @MrSimonEmms?

Comment (nandajavarma) [reply install/installer/README.md:174]: Sorry for the inactivity on this issue. I have created[ this issue ](https://github.com/gitpod-io/gitpod/issues/8838) to track this requirement. Shall we merge this PR and continue the work there?

**Review by princerachit — APPROVED** [review]
code changes lgtm. did not test this though

**Comment by Furisto** [comment]
Hey @MrSimonEmms, if I understood correctly you agree with the changes in this PR. If so, can you please approve it?

**Review by MrSimonEmms — APPROVED** [review]
LGTM
