### PR TITLE
[pvc] fix prebuilds when using pvc

### LINKED ISSUE #12464: [PVC] Open workspace from prebuild PVC, no message This task ran as a workspace prebuild on CLI
### Bug description

[PVC] Open workspace from prebuild PVC, no message `This task ran as a workspace prebuild` on CLI

### Steps to reproduce

- Prebuild + PVC
- The user account with PVC
- The user open the workspace from prebuild

### Workspace affected

_No response_

### Expected behavior

We should see the message `This task ran as a workspace prebuild` in workspace CLI when we open from prebuild. After that, we could know whether the workspace open from prebuild or not.

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by sagor999**
## Description

First, kudos to @jenting for catching this issue. :heart: 
What was happening is actually when using pvc and prebuilds, it would not know that workspace was open from prebuild, rendering prebuild useless (as it would do all the work that prebuild already done).
This PR fixes this. 

## Related Issue(s)

Fixes #12464 

## How to test

Open regular workspace
Open PVC regular workspace
Open regular prebuild
Open PVC prebuild

## Release Notes

```release-note
none
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/content-service/pkg/layer/provider.go [hunk 1]
```diff
@@ -508,13 +529,16 @@ git log --pretty=%H -n 1 > /.workspace/prestophookdata/git_log_2.txt
...
+var pvcEnabledFile = `PVC`
+
 // version of this function for persistent volume claim feature
 // we cannot use /workspace folder as when mounting /workspace folder through PVC
 // it will mask anything that was in container layer, hence we are using /.workspace instead here
 func contentDescriptorToLayerPVC(cdesc []byte) (*Layer, error) {
 	layers := []fileInLayer{
 		{&tar.Header{Typeflag: tar.TypeDir, Name: "/.workspace", Uid: initializer.GitpodUID, Gid: initializer.GitpodGID, Mode: 0755}, nil},
 		{&tar.Header{Typeflag: tar.TypeDir, Name: "/.workspace/.gitpod", Uid: initializer.GitpodUID, Gid: initializer.GitpodGID, Mode: 0755}, nil},
+		{&tar.Header{Typeflag: tar.TypeReg, Name: "/.workspace/.gitpod/pvc", Uid: 0, Gid: 0, Mode: 0775, Size: int64(len(pvcEnabledFile))}, []byte(pvcEnabledFile)},
```
Comment (sagor999) [inline components/content-service/pkg/layer/provider.go:541]: this allows us to reliably check in supervisor if workspace is using pvc or not, instead of relying on content.json being present, which is not the case everytime (restoring from prebuild will not generate any content.json for example).

File: components/content-service/pkg/layer/provider.go [hunk 2]
```diff
@@ -523,6 +547,22 @@ func contentDescriptorToLayerPVC(cdesc []byte) (*Layer, error) {
...
+	}
+	ctnt, err := json.Marshal(msg)
+	if err != nil {
+		return nil, err
+	}
+
+	return layerFromContent(
+		fileInLayer{&tar.Header{Typeflag: tar.TypeDir, Name: "/.workspace", Uid: initializer.GitpodUID, Gid: initializer.GitpodGID, Mode: 0755}, nil},
+		fileInLayer{&tar.Header{Typeflag: tar.TypeDir, Name: "/.workspace/.gitpod", Uid: initializer.GitpodUID, Gid: initializer.GitpodGID, Mode: 0755}, nil},
+		fileInLayer{&tar.Header{Typeflag: tar.TypeReg, Name: "/.workspace/.gitpod/ready", Uid: initializer.GitpodUID, Gid: initializer.GitpodGID, Mode: 0755, Size: int64(len(ctnt))}, []byte(ctnt)},
```
Comment (sagor999) [inline components/content-service/pkg/layer/provider.go:562]: this allows us to place ready file. 
why we cannot use `/workspace` folder? because when using pvc that folder is masked by pvc. 
also, on top of that, when restoring from prebuild for example, prebuild volume snapshot will contain ready file in there from the time when prebuild was generated. 
so this allows us to completely separate pvc and non pvc approach.

File: components/supervisor/pkg/supervisor/supervisor.go [hunk 3]
```diff
@@ -1327,9 +1327,10 @@ func startContentInit(ctx context.Context, cfg *Config, wg *sync.WaitGroup, cst
 
 	fn := "/workspace/.gitpod/content.json"
 	fnReady := "/workspace/.gitpod/ready"
-	if _, err := os.Stat("/.workspace/.gitpod/content.json"); !os.IsNotExist(err) {
+	if _, err := os.Stat("/.workspace/.gitpod/pvc"); !os.IsNotExist(err) {
 		fn = "/.workspace/.gitpod/content.json"
-		log.Info("Detected content.json in /.workspace folder, assuming PVC feature enabled")
+		fnReady = "/.workspace/.gitpod/ready"
```
Comment (sagor999) [inline components/supervisor/pkg/supervisor/supervisor.go:1332]: we need to wait for ready file that comes from PVC layer, we should not use ready file that comes from `/workspace` since that file will be backed up into volume snapshot when it is created from pvc.
so this makes a clear separation between pvc and non-pvc code path.

**Comment by sagor999** [comment]
@kylos101 due to necessary refactor in supervisor, once IDE rolls it out, PVC feature will become broken in prod until we roll out new workspace cluster. So we can still start dog fooding PVC at workspace team level, but will need to stop once IDE deploys this change, and we will need to deploy new cluster.

File: components/content-service/pkg/layer/provider.go [hunk 4]
```diff
@@ -287,8 +295,12 @@ func (s *Provider) GetContentLayerPVC(ctx context.Context, owner, workspaceID st
 			if err != nil {
 				return nil, nil, err
 			}
+			layerReady, err := workspaceReadyLayerPVC(csapi.WorkspaceInitFromOther)
```
Comment (jenting) [inline components/content-service/pkg/layer/provider.go:298]: To be honest, I don't know what is the correct `WorkspaceInitSource` for the snapshot.

**Review by jenting — COMMENTED** [review]
I have verified it, it works like a charm.

File: components/content-service/pkg/layer/provider.go (hunk 4 above)
Comment (jenting) [reply components/content-service/pkg/layer/provider.go:298]: I test the snapshot without the PVC feature flag. The content within `read` file is `{"source":"from-backup"}`.

Comment (sagor999) [reply components/content-service/pkg/layer/provider.go]: I don't think it matters that much if it is from backup or from other, but for consistency, updated to match. :heart:

**Review by jenting — APPROVED** [review]

**Comment by jenting** [comment]
The werft finally happy now.

**Review by akosyakov — APPROVED** [review]
lgtm, i have not tried, rely on @pavel review

it seems that changes to supervisor are backward compatible

/hold

unhold when you comfortable to merge
