### PR TITLE
[image-builder] fixes forcing tags does not work

### LINKED ISSUE #7053: [image-builder] Forcing tags does not work
the bob-proxy forces the tag of the base-ref and target-ref by [rewriting the downstream manifest URL.](https://github.com/gitpod-io/gitpod/blob/b6c0295c4a7191d9b9cdfd0f99123c2d1b9cb12a/components/image-builder-bob/pkg/proxy/proxy.go#L70-L75) The intention is to limit the access users have to the images in the respective repositories.

This fails if one tries to access a multi-platform image, e.g. `golang:latest`.

### Steps to reproduce
```bash
# run bob proxy
cd components/image-builder-bob
go run main.go proxy --base-ref golang:latest --target-ref localhost:5000/target:test --auth {}

## in a new terminal
# install buildkit
cd /tmp
curl -OL https://github.com/moby/buildkit/releases/download/v0.9.0/buildkit-v0.9.0.linux-amd64.tar.gz
tar xzfv buildkit-v0.9.0.linux-amd64.tar.gz
sudo mv bin/* /usr/bin

# build bob and run it
cd /workspace/gitpod/components/image-builder-bob
go install

# Run bob. If the push to the target does not work, that's expected (unless you run a registry on that port).
# However, the pull fails already.
BOB_BASE_REF=localhost:8080/base:latest BOB_TARGET_REF=localhost:5000/target:latest sudo -E $(which bob) build
```

A more direct way to debug this is using the OCI tool:
```bash
# install oci-tool
go install github.com/csweichel/oci-tool@latest

# pull from bob proxy
oci-tool fetch --insecure manifest --platform linux-amd64 localhost:8080/base:latest
```
The returned manifest will be empty rather than the actual manifest.

## Possible solutions:
1. we could abandon the "tag forcing", and specify it when parametrising bob akin to what we're doing for digests already.
2. we could find out how to make this tag forcing work, which would likely work [for digests](https://github.com/gitpod-io/gitpod/pull/7052), too.

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

Fixes forcing tags does not work

## Related Issue(s)

Fixes #7053

## How to test

```c
// golang:latest
https://iqqbot-image-builder-forcing-tags-7053.staging.gitpod-dev.com/#/https://github.com/iQQBot/test.test
// golang@sha256:d9d5bd5c0b80ffc3b4e7fb1dd8d59228e4eac009234f3b9eb049f21ccd5f8370
https://iqqbot-image-builder-forcing-tags-7053.staging.gitpod-dev.com/#/https://github.com/iQQBot/test.test/tree/dig
// golang
https://iqqbot-image-builder-forcing-tags-7053.staging.gitpod-dev.com/#/https://github.com/iQQBot/test.test/tree/golang
// golang:1.17.0
https://iqqbot-image-builder-forcing-tags-7053.staging.gitpod-dev.com/#/https://github.com/iQQBot/test.test/tree/v117
```

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mrsimonemms** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mrsimonemms` in a comment when ready.

Associated issue: *#7053*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-mk3/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/image-builder-mk3/pkg/resolve/resolve.go [hunk 1]
```diff
@@ -79,14 +84,56 @@ func (sr *StandaloneRefResolver) Resolve(ctx context.Context, ref string, opts .
...
+	}
+
+	var mf ociv1.Manifest
+	err = json.Unmarshal(buf, &mf)
+	if err != nil {
+		return "", fmt.Errorf("cannot unmarshal manifest: %w", err)
+	}
+
+	if mf.Config.Size != 0 {
+		pref, err = reference.WithDigest(pref, mf.Config.Digest)
```
Comment (csweichel) [inline components/image-builder-mk3/pkg/resolve/resolve.go:117]: nit: `err` is ignored due to the `return ..., nil`

File: components/image-builder-mk3/pkg/resolve/resolve.go [hunk 2]
```diff
@@ -79,14 +84,56 @@ func (sr *StandaloneRefResolver) Resolve(ctx context.Context, ref string, opts .
...
+		return
+	}
+
+	var dgst digest.Digest
+	for _, mf := range mfl.Manifests {
+		if fmt.Sprintf("%s-%s", mf.Platform.OS, mf.Platform.Architecture) == "linux-amd64" {
+			dgst = mf.Digest
+			pref, err = reference.WithDigest(pref, dgst)
+			return pref.String(), nil
+		}
```
Comment (csweichel) [inline components/image-builder-mk3/pkg/resolve/resolve.go:133]: nit: align happy path to the left

```suggestion
	var dgst digest.Digest
	for _, mf := range mfl.Manifests {
		if fmt.Sprintf("%s-%s", mf.Platform.OS, mf.Platform.Architecture) == "linux-amd64" {
			dgst = mf.Digest
			break
		}
	}
	if dgst == "" {
		return "", fmt.Errorf("no manifest for platform linux-amd64 found")
	}
	
	pref, err = reference.WithDigest(pref, dgst)
	return pref.String(), err
```

**Review by csweichel — COMMENTED** [review]
Found a few nits. Otherwise works as advertised.

I reckon the impact on existing images should be minimal, considering this mostly affects multi-platform images (which few of them will be). We might see a temporarily increased build volume after deploying this though.

File: components/image-builder-mk3/pkg/resolve/resolve.go (hunk 1 above)
Comment (iQQBot) [reply components/image-builder-mk3/pkg/resolve/resolve.go:117]: new commit pushed

**Comment by csweichel** [comment]
Thank you :)

/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 22112c1f93d3c33739b616053823fd18a2092b6d</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7067#issuecomment-987886232" title="LGTM">csweichel</a>*

Associated issue: *#7053*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-mk3/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
