### PR TITLE
[server] remove setting sync record with limit

### LINKED ISSUE #8589: Settings sync stores more than 20 resource revisions
### Bug description

Settings sync stores more than 20 resource revisions when it should only be 20 rev max

### Steps to reproduce

gp_setting_sync

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Origin code looks fine. So sync-data more than 20, maybe it's caused by `db-sync`.

This PR will alleviate this problem.

## Related Issue(s)

Fixes #8589

## How to test

1. Start a workspace
2. Adjust UI and toggle setting sync to reach config limit 2 (debug only)
3. Repeat prev step, watch minio files and DB record

### How to access minio with UI
```shell
# make sure using correct namespace
kubens staging-hw-fix-8589

# get user and psw
kubectl get secrets minio -oyaml | yq - r "data.root-user" | base64 -d
kubectl get secrets minio -oyaml | yq - r "data.root-password" | base64 -d

# port forward minio console to 1234 (whatever you want)
kubectl pord-forward service/minio 1234:9001

# open port in your browser!! 
```
How to access your configuration?

Buckets -> search with your userId (Chrome DevTools to get it) -> Browser details -> blobs -> code-data -> globalState(which store your UI setting)

### How to access setting sync table
```shell
# get psw
kubectl get secrets mysql -oyaml | yq - r "data.password" | base64 -d

# exec into mysql
kubectl exec -it mysql-0 -c mysql sh

# get your data
mysql -u gitpod -p # then enter your password
use gitpod;
SELECT * FROM d_b_code_sync_resource WHERE userId=<your_user_id>;
```

### How to trigger UI update request to server
Drag your *DEBUG CONSOLE* to *TERMINAL* (any of them)
|Image|
|:-:|
|image|

## Release Notes

```release-note
Fix setting sync limit failure in some cases
```

### CODE REVIEW

**Comment by jeanp413** [comment]
@mustard-mh For globalState resource I see 30 revs, did you found something than causes this?
image

**Comment by mustard-mh** [comment]
> @mustard-mh For globalState resource I see 31 revs, did you found something that causes this?

@jeanp413 I think it's because of `db-sync`. 

Original code looks fine, and it's correct with self-hosted Gitpod

**Comment by mustard-mh** [comment]
The original code, only in case of high concurrency, may have this problem. But according to the time of database rows, it is not a high concurrency.

Original code only updates the last record and deletes the last record JSON file. 

If there is no high concurrency and only one database, it'll work fine. But we have `db-sync`, it'll sync other records from another DB, and sometimes causes some bug, then we get more and more records.

cc @jeanp413

File: components/gitpod-db/src/typeorm/code-sync-resource-db.ts [hunk 1]
```diff
@@ -70,38 +70,43 @@ export class CodeSyncResourceDB {
...
                 latest = resources[0];
                 if (resources.length >= params.revLimit) {
-                    toUpdated = resources[resources.length - 1];
+                    // delete + 1 to insert instead of update
+                    toDeleted = resources.splice(params?.revLimit - 1);
                 }
             } else {
                 latest = await this.doGetResource(manager, userId, kind, 'latest');
             }
+            // TODO(hw): why we use `latest?.rev !== params.latestRev` ? what's latestRev?
```
Comment (jeanp413) [inline components/gitpod-db/src/typeorm/code-sync-resource-db.ts:99]: latestRev is the `etag` of the resource, if the `etag` send from the client is different from the server then it means it got updated already by some other client so we return 412 error, here's an example of how [they mock it](https://github.com/microsoft/vscode/blob/98c97abb8a33a34a3b82434c91ef93fe5ac819fc/src/vs/platform/userDataSync/test/common/userDataSyncClient.ts#L250-L252) in a test

File: components/server/src/code-sync/code-sync-service.ts [hunk 2]
```diff
@@ -303,4 +290,24 @@ export class CodeSyncService {
...
+    protected async deleteObjects(userId: string, resourceKey: ServerResource, revs: string[]) {
+        for (let rev of revs) {
+            const obj = toObjectName(resourceKey, rev)
+            const request = new DeleteRequest();
+            request.setOwnerId(userId);
+            request.setExact(obj);
+            const blobsClient = this.blobsProvider.getDefault();
+            try {
+                await util.promisify<DeleteRequest, DeleteResponse>(blobsClient.delete.bind(blobsClient))(request);
+                await this.db.deleteResource(userId, resourceKey, rev);
```
Comment (akosyakov) [inline components/server/src/code-sync/code-sync-service.ts:302]: I wonder whether it will be better to perform deletion of blob in the transaction of deleting a resource, i.e.:
- open transaction
- delete record from DB
- delete blob from storage (ignore not found exception)
- close transaction

File: components/server/src/code-sync/code-sync-service.ts [hunk 3]
```diff
@@ -253,24 +252,12 @@ export class CodeSyncService {
                 if (response.status !== 200) {
                     throw new Error(`code sync: blob service: upload failed with ${response.status} ${response.statusText}`);
                 }
-                oldObject = oldRev && toObjectName(resourceKey, oldRev);
+                // delete old revs from storage
+                this.deleteObjects(userId, resourceKey, oldRevs).then().catch(e => {
```
Comment (akosyakov) [inline components/server/src/code-sync/code-sync-service.ts:256]: this part should be executed only after successful insert transaction, not before, otherwise it can happen that we delete data but not insert

File: components/gitpod-db/src/typeorm/code-sync-resource-db.ts (hunk 1 above)
Comment (akosyakov) [reply components/gitpod-db/src/typeorm/code-sync-resource-db.ts:99]: @mustard-mh that's a good reference, i used this test impl as a blueprint while implementing our code sync endpoing

**Comment by akosyakov** [comment]
I removed this PR from IDE project and added the corresponding issue instead.

File: components/server/src/code-sync/code-sync-service.ts (hunk 2 above)
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:302]: I think it's the same with steps now

File: components/server/src/code-sync/code-sync-service.ts (hunk 3 above)
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:256]: change DB insert and doInsert order can resolve

File: components/gitpod-db/src/typeorm/code-sync-resource-db.ts (hunk 1 above)
Comment (mustard-mh) [reply components/gitpod-db/src/typeorm/code-sync-resource-db.ts:99]: Got it! 🙏

File: components/server/src/code-sync/code-sync-service.ts (hunk 3 above)
Comment (akosyakov) [reply components/server/src/code-sync/code-sync-service.ts:256]: I don't think so, since we call from within transaction still, no?

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts]: Yes, we trust that the transaction commit will succeed so we put the object to GCP, and we delete objects in this step too. (I added a commit now)

We need to resolve problems if things we trust don't do like we expected, that's why we need some GC things, maybe workspace images also have some leak

Comment (akosyakov) [reply components/server/src/code-sync/code-sync-service.ts]: why cannot we just move out of transaction before, so we don't trust, but know for sure?

File: components/server/src/code-sync/code-sync-service.ts (hunk 2 above)
Comment (akosyakov) [reply components/server/src/code-sync/code-sync-service.ts:304]: Is not it that if deleteResource fails then we have a record without blob?

File: components/server/src/code-sync/code-sync-service.ts [hunk 4]
```diff
@@ -253,28 +253,17 @@ export class CodeSyncService {
...
-                        }
-                        log.error({ userId }, 'code sync: failed to delete', err, { object: oldObject });
-                    }
-                });
-            }
             if (!rev) {
                 res.sendStatus(412);
                 return;
             }
+            // delete old revs from storage
```
Comment (akosyakov) [inline components/server/src/code-sync/code-sync-service.ts:262]: Should not it be performed regardless of if above?

File: components/server/src/code-sync/code-sync-service.ts (hunk 2 above)
Comment (akosyakov) [reply components/server/src/code-sync/code-sync-service.ts:304]: this one does not seem to be addressed, deletion of blob happens outside of delete DB transaction, that can deleted blob, but no a DB record

File: components/gitpod-db/src/typeorm/code-sync-resource-db.ts [hunk 5]
```diff
@@ -70,38 +70,43 @@ export class CodeSyncResourceDB {
...
 
-    async insert(userId: string, kind: ServerResource, doInsert: (rev: string, oldRev?: string) => Promise<void>, params?: CodeSyncInsertOptions): Promise<string | undefined> {
+    async deleteResource(userId: string, kind: ServerResource, rev: string): Promise<void> {
+        const connection = await this.typeORM.getConnection();
+        await connection.transaction(async manager => {
+            await manager.createQueryBuilder()
+                    .delete()
+                    .from(DBCodeSyncResource)
+                    .where("userId = :userId AND kind = :kind AND rev = :rev", { userId, kind, rev: rev })
+                    .execute();
```
Comment (akosyakov) [inline components/gitpod-db/src/typeorm/code-sync-resource-db.ts:80]: we should delete blob here

Comment (mustard-mh) [reply components/gitpod-db/src/typeorm/code-sync-resource-db.ts]: updated

File: components/server/src/code-sync/code-sync-service.ts [hunk 6]
```diff
@@ -303,4 +292,25 @@ export class CodeSyncService {
...
+                await util.promisify<DeleteRequest, DeleteResponse>(blobsClient.delete.bind(blobsClient))(request);
+            } catch (err) {
+                if (err.code === status.NOT_FOUND) {
+                    return;
+                }
+                log.error({ userId }, 'code sync: failed to delete obj', err, { object: obj });
+                throw err;
+            }
+        }).catch(err => {
+            log.error({ userId }, 'code sync: failed to delete', err);
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:312]: Remove this catch and handle it on caller function?

File: components/server/src/code-sync/code-sync-service.ts [hunk 7]
```diff
@@ -253,24 +253,13 @@ export class CodeSyncService {
...
-                        if (err.code === status.NOT_FOUND) {
-                            // we're good here
-                            return;
-                        }
-                        log.error({ userId }, 'code sync: failed to delete', err, { object: oldObject });
-                    }
-                });
-            }
+            // delete old revs from storage
+            this.deleteObjects(userId, resourceKey, oldRevList).then().catch(e => {
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:259]: Remove `.then()`

File: components/server/src/code-sync/code-sync-service.ts [hunk 8]
```diff
@@ -303,4 +292,25 @@ export class CodeSyncService {
         return router;
     }
 
+    protected async deleteObjects(userId: string, resourceKey: ServerResource, revs: string[]) {
+        revs.forEach(rev => this.db.deleteResource(userId, resourceKey, rev, async (rev: string) => {
```
[the remark this answers is not in the document]
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:296]: 😅 I use it because I only want to exec with all this array, forgot it's an `async` function, will do it

File: components/server/src/code-sync/code-sync-service.ts (hunk 6 above)
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:312]: Any of them failed is ok, we should continue to delete other items

File: components/server/src/code-sync/code-sync-service.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts]: @jeanp413 updated

File: components/server/src/code-sync/code-sync-service.ts (hunk 6 above)
Comment (jeanp413) [reply components/server/src/code-sync/code-sync-service.ts:312]: If you catch here then this function will never throw and catch below :arrow_down: will never execute

File: components/server/src/code-sync/code-sync-service.ts [hunk 9]
```diff
@@ -303,4 +292,26 @@ export class CodeSyncService {
...
+                if (err.code === status.NOT_FOUND) {
+                    return;
+                }
+                log.error({ userId }, 'code sync: failed to delete obj', err, { object: obj });
+                throw err;
+            }
+        }).catch(err => {
+            log.error({ userId }, 'code sync: failed to delete', err);
+        }))
+        return Promise.all(tasks)
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:314]: > Any of them failed is ok, we should continue to delete other items

Then is better to use `Promise.allSettled`

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:314]: 👍 Great! I have never used this func before! but in this case, we need some logs which may relate to DB right? We can use `Promise.allSettled` to make it more readable.

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts]: 🙏 updated @jeanp413

Comment (jeanp413) [reply components/server/src/code-sync/code-sync-service.ts]: If we keep the catch here then `Promise.all(tasks) will always resolve successfully and no need to change it to `Promise.allSettled`, other option is to remove catch here and use `Promise.allSettled` handle any error in caller function

File: components/server/src/code-sync/code-sync-service.ts [hunk 10]
```diff
@@ -253,24 +253,10 @@ export class CodeSyncService {
...
-                        if (err.code === status.NOT_FOUND) {
-                            // we're good here
-                            return;
-                        }
-                        log.error({ userId }, 'code sync: failed to delete', err, { object: oldObject });
-                    }
-                });
-            }
+            // sync delete old revs from storage
+            this.deleteObjects(userId, resourceKey, oldRevList)
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:259]: await?

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:259]: We don't need to await this delete func, unless client will fetch list immediately after post their configuration

File: components/server/src/code-sync/code-sync-service.ts (hunk 9 above)
Comment (jeanp413) [reply components/server/src/code-sync/code-sync-service.ts]: I was thinking of something like this, but it's fine either way, feel free to resolve this
```typescript
this.deleteObjects(userId, resourceKey, oldRevList).then(results => {
	results.forEach(p => {
		if (p.status === 'rejected') {
			log.error({ userId }, 'code sync: failed to delete', err);
		} 
	});
});
```

File: components/server/src/code-sync/code-sync-service.ts [hunk 11]
```diff
@@ -303,4 +289,27 @@ export class CodeSyncService {
...
+                if (err.code === status.NOT_FOUND) {
+                    return;
+                }
+                log.error({ userId }, 'code sync: failed to delete obj', err, { object: obj });
+                throw err;
+            }
+        }).catch(err => {
+            log.error({ userId }, 'code sync: failed to delete', err);
+        }))
+        await Promise.allSettled(tasks)
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:311]: missing semicolon, no need to await the last promise just return it

File: components/server/src/code-sync/code-sync-service.ts [hunk 12]
```diff
@@ -24,7 +24,7 @@ import { Config } from '../config';
 import { CachingBlobServiceClientProvider } from '@gitpod/content-service/lib/sugar';
 
 // By default: 5 kind of resources * 20 revs * 1Mb = 100Mb max in the content service for user data.
-const defautltRevLimit = 20;
+const defaultRevLimit = 2;
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:27]: revert this :smile:

File: components/server/src/code-sync/code-sync-service.ts (hunk 11 above)
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:311]: await first and return void to avoid caller use this to check result 😄 https://github.com/gitpod-io/gitpod/pull/8644#discussion_r822938267

File: components/server/src/code-sync/code-sync-service.ts (hunk 12 above)
Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:27]: It's only for debug, I'll revert this after review ok https://github.com/gitpod-io/gitpod/pull/8644/commits/6bd58d59ed5eb15ecf676e77939622748e252780

File: components/server/src/code-sync/code-sync-service.ts [hunk 13]
```diff
@@ -253,24 +253,10 @@ export class CodeSyncService {
                 if (response.status !== 200) {
                     throw new Error(`code sync: blob service: upload failed with ${response.status} ${response.statusText}`);
                 }
-                oldObject = oldRev && toObjectName(resourceKey, oldRev);
+                oldRevList = oldRevs
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:256]: missing semicolon

File: components/server/src/code-sync/code-sync-service.ts (hunk 10 above)
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:259]: missing semicolon

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:259]: That's why we need some lint !!

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:258]: I create a temp .prettierrc file like this to reformat temporarily
```json
{
  "tabWidth": 4,
  "useTabs": false,
  "printWidth": 400,
  "singleQuote": true,
  "arrowParens": "avoid"
}
```

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:258]: @Harry-Hopkinson created a global lint for us 🍊 https://github.com/gitpod-io/gitpod/pull/8607 and @easyCZ created one too https://github.com/gitpod-io/gitpod/pull/8655!!

Hope them can be merged soon 👍

**Review by jeanp413 — APPROVED** [review]

**Comment by mustard-mh** [comment]
I added `How to access minio UI` and `How to access setting sync table` section. 

cc @jeanp413

File: components/server/src/code-sync/code-sync-service.ts [hunk 14]
```diff
@@ -253,24 +252,10 @@ export class CodeSyncService {
...
-                        if (err.code === status.NOT_FOUND) {
-                            // we're good here
-                            return;
-                        }
-                        log.error({ userId }, 'code sync: failed to delete', err, { object: oldObject });
-                    }
-                });
-            }
+            // sync delete old revs from storage
+            this.deleteObjects(userId, resourceKey, oldRevList)
```
Comment (jeanp413) [inline components/server/src/code-sync/code-sync-service.ts:258]: @mustard-mh I just found we have lint check [server package.json](https://github.com/gitpod-io/gitpod/blob/a81c23ee504048414865a53de7af81d2a33b21cf/components/server/package.json#L20-L21)
If you run it we get an errorin this line `ERROR: 258:13  no-floating-promises  Promises must be handled appropriately` so maybe we should go with https://github.com/gitpod-io/gitpod/pull/8644#discussion_r822938267 ?

Comment (mustard-mh) [reply components/server/src/code-sync/code-sync-service.ts:258]: I think we can just pass `.catch(e => {})` to it to pass this lint

Comment (jeanp413) [reply components/server/src/code-sync/code-sync-service.ts:258]: I think that's kinda misleading but your call :+1:

**Review by jeanp413 — APPROVED** [review]

File: components/server/src/code-sync/code-sync-service.ts (hunk 10 above)
Comment (easyCZ) [reply components/server/src/code-sync/code-sync-service.ts]: This has now landed. Not all components are enabled by default but `server` is.

**Review by geropl — APPROVED** [review]

**Comment by mustard-mh** [comment]
removed debug commit

**Comment by jeanp413** [comment]
need to resolve merge conflicts now :eye

**Review by geropl — APPROVED** [review]
