### PR TITLE
[jetbrains] Wait for content before backend start

### LINKED ISSUE #6651: [jetbrains] Wait for content to prevent “Path does not exist” errors
### Bug description

The JetBrains IDE backend service fails from time to time and we see the following error in the logs:

```
JetBrains remote-dev-server.sh (err): Path does not exist: /workspace/gitpod
```

The reason could be that we don't wait for content readiness before we start the IDEs.

We could wait for the project folder in the script that starts the JetBrains IDE backend to fix this.

(see also [internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1636549139465600))

### Steps to reproduce

Start workspaces with JetBrains IDE enabled.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by corneliusludmann**
## Description
When the JetBrains backend starts and the workspace content is not ready yet it results to an error like this:
```
JetBrains remote-dev-server.sh (err): Path does not exist: /workspace/gitpod
```

This PR adds a step that waits for the content before it starts the JetBrains backend.

## Related Issue(s)

Fixes #6651

## How to test

It's hard to reproduce the actual error but testing that a workspace with JetBrains backend starts (change it in the preferences) should be good enough.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **corneliusludmann** after the PR has been reviewed.

Associated issue: *#6651*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ide/jetbrains/image/startup.sh [hunk 1]
```diff
@@ -10,6 +10,10 @@ trap "jobs -p | xargs -r kill" SIGINT SIGTERM EXIT
 
 /ide-desktop/status 24000 "$1" &
 
+echo "Desktop IDE: Waiting for the content initializer ..."
+result=$(curl -sS "$SUPERVISOR_ADDR"/_supervisor/v1/status/content/wait/true)
```
Comment (akosyakov) [inline components/ide/jetbrains/image/startup.sh:14]: can it happen that curl times out and we need to retry? we have such logic in the supervisor frontend, i.e. we only continue if a response is json and it has `available: true`: https://github.com/gitpod-io/gitpod/blob/f3ecc7f5cba0d6045e405f5ee15d1ac7fbab0f20/components/supervisor/frontend/src/ide/supervisor-service-client.ts#L53

Comment (corneliusludmann) [reply components/ide/jetbrains/image/startup.sh:14]: I thought that was overkill since the case of content not being there is so rare anyway. But sure, I can add a loop here.

Comment (akosyakov) [reply components/ide/jetbrains/image/startup.sh:14]: I am just asking, depends on curl, in supervisor frontend we have to do it because connection actually times out. If curl cannot time out then it is overkill. loop would be more robust though

**Review by akosyakov — APPROVED** [review]
/lgtm

`Path does not exist` does not happen anymore. 

There is still records like `JetBrains IDE status: 2021/11/17 12:18:02 projects size != 1` although content is ready now for sure. Maybe it would be good to clarify with JetBrains folks why is that.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6722#pullrequestreview-808520183" title="LGTM">akosyakov</a>*

Associated issue: *#6651*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
