### PR TITLE
[workspace] fix workspace leak on short-lived workspace

### LINKED ISSUE #5573: No logs for short prebuilds
If a prebuild is very short, i.e. doesn't take a while to be built, it appears to not be shown with logs and logs are not persisted in the storage. 

How to reproduce? Just create a project for a not yet configured repo in your account and use the simples `echo something` template form the project configurator.

### LINKED ISSUE #6435: DisposeWorkspace never called form short-lived prebuilds
### Bug description

For shortlived prebuilds, `ws-daemon.DisposeWorkspace` is never called, resulting in missing backup/snapshot and logs.

Causes: #5573

### Steps to reproduce

 - create a test-team on gitpod.io
 - add project https://github.com/geropl/test-repo
 - "run prebuild" and wait until it's done
 - lookup the prebuild in the DB to get/verify instanceId/ownerId/workspaceId
 - Go to GCloud storage, and search for the user&workspaceId: there should be no folder

Alternatively:
- create a preview env (with LOG_LEVEL: debug)
- login with gitlab
- create team, add project https://gitlab.com/geropl1/gitpod-test
- "run prebuild" and wait until it's done
- check logs of `ws-daemon`: `DisposeWorkspace` is never called

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

Workspace leak because short-lived workspace haven't had a chance to set the finalizer

We can advance the setfinalizer to the WorkspacePhase_CREATING phase, since the initializeWorkspaceContent phase is already underway at this point and requires a subsequent cleanup process

## Related Issue(s)

Fixes #6435 
Fixes #5573

## How to test

Start a short-lived workspace
and check /var/gitpod/workspaces/

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **aledbf** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @aledbf` in a comment when ready.

Associated issue: *#6435*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/ws-manager/pkg/manager/monitor.go [hunk 1]
```diff
@@ -317,6 +317,10 @@ func actOnPodEvent(ctx context.Context, m actingManager, status *api.WorkspaceSt
 				}
 			}
 		}()
+		err := m.modifyFinalizer(ctx, workspaceID, gitpodFinalizerName, true)
```
Comment (iQQBot) [inline components/ws-manager/pkg/manager/monitor.go:320]: Did not bother to remove the modifyFinalizer under Running to prevent other accidents

Comment (iQQBot) [reply components/ws-manager/pkg/manager/monitor.go:320]: Current I think it not a best solution, continue to find a better one CC @csweichel

**Comment by csweichel** [comment]
@iQQBot please ping when you think this is ready for review/should go in this way.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 0c97719c13850a58e54921c22d5d90c608e7e7be</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6758#issuecomment-980097293" title="LGTM">csweichel</a>*

Associated issue: *#6435*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
