### PR TITLE
[workspacekit] make /etc/hosts modifiable

### LINKED ISSUE #7981: [jetbrains] many exceptions on spring petclinic example
### Bug description

Exceptions like:
```
java.io.IOException: The server sockets created using the LocalRMIServerSocketFactory only accept connections from clients running on the host where the RMI remote objects have been exported.
	at jdk.management.agent/sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:114) ~[na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394) ~[na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

To reproduce start with petclinic example.

### Steps to reproduce

See above.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Recently we introduced workspace-wide network namespace #6409  for all workspace
This causes the network devices seen in the workspace to be independent of the workspace pod, and the hostname is expected to resolve to an accessible IP address, so it makes sense to point to 127.0.0.1

This does not cause other problems, instead the original value (workspace pod ip) causes some programs to not work properly because it not accessible

And make /ect/hosts editable make sense for users they can customize hosts in .gitpod.yaml or dotfiles

## Related Issue(s)

Fixes #7981

## How to test

this contain 2 test case
1. ensure /etc/hosts modifiable and check the hostname record is point to 127.0.0.1
    1.1 Open a workspace and edit /etc/hosts

2. ensure resolve #7981
    2.1 start [petclinic](https://github.com/gitpod-io/spring-petclinic) with IntelliJ
    2.2 change config flag to "-Dcom.sun.management.jmxremote.local.only=true"
    2.3 launch run configuration
    2.4 it should work without any jmx security errors

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by csweichel** [comment]
We already have this mechanism for `/etc/resolv.conf` - we should be able to reuse that mechanism

**Comment by mustard-mh** [comment]
> We already have this mechanism for `/etc/resolv.conf` - we should be able to reuse that mechanism

we not only make it modifiable, also we need to make the file correct [see detail](https://gitpod.slack.com/archives/C02F19UUW6S/p1643886043639809)

the default IP address is workspace pod IP address, it not accessible in workspace, so we need to change it to 127.0.0.1

reuse means that we need to regexp find it and replace, does it make sense to reuse?

**Comment by mustard-mh** [comment]
a new commit for reuse @csweichel

File: components/workspacekit/cmd/rings.go [hunk 1]
```diff
@@ -340,18 +340,21 @@ var ring1Cmd = &cobra.Command{
...
-		if err != nil {
-			log.WithError(err).Error("cannot copy resolv.conf")
-			return
+
+		copyPaths := []string{"/etc/resolv.conf", "/etc/hosts"}
+		for _, fn := range copyPaths {
+			err = copyRing2Root(ring2Root, fn)
+			if err != nil {
+				log.WithError(err).Error("cannot copy " + fn)
+				return
```
Comment (csweichel) [inline components/workspacekit/cmd/rings.go:351]: We'll still want to try and copy the other file(s) in this case.
```suggestion
				log.WithError(err).Warn("cannot copy " + fn)
```

File: components/workspacekit/cmd/rings.go [hunk 2]
```diff
@@ -670,32 +672,32 @@ func copyResolvConf(ring2root string) error {
...
-fe00::0 ip6-localnet
-fe00::0 ip6-mcastprefix
-fe00::1 ip6-allnodes
-fe00::2 ip6-allrouters
-`
-	hostname, err := os.Hostname()
-	if err == nil {
-		hostsStr += fmt.Sprintf("127.0.0.1 %s\n", hostname)
+	path := filepath.Join(ring2root, "/etc/hosts")
+	stat, err := os.Stat(path)
```
Comment (csweichel) [inline components/workspacekit/cmd/rings.go:681]: if the file does not exist, we would not necessarily want to stop the workspace

**Review by csweichel — COMMENTED** [review]
Nice - thank you for incorporating this.

File: components/workspacekit/cmd/rings.go (hunk 2 above)
Comment (mustard-mh) [reply components/workspacekit/cmd/rings.go:680]: Yes, so this func only return error
https://github.com/gitpod-io/gitpod/blob/5b0af01cf950564d26e25aa525092cbfbe036300/components/workspacekit/cmd/rings.go#L353-L357

in here just log

**Comment by akosyakov** [comment]
I really like that the issue gets resolved 😄 but can someone update the PR description to explain what this PR does and why it is not a workaround to list in hosts file but a proper solution.

**Comment by csweichel** [comment]
I agree with Anton - the PR needs a better description :) 

That said, the change LGTM and works like a charm.
Once the description is updated, I'll happily approve.

**Comment by mustard-mh** [comment]
Hi @csweichel, I already update the PR desc

**Review by csweichel — APPROVED** [review]
Thanks @mustard-mh
