### PR TITLE
[prebuild] Fix view when coming from prefix

### LINKED ISSUE #11079: Prebuild logs view broken when triggering a prebuild manually
When triggering a prebuild manually we see this ([internal context](https://gitpod.slack.com/archives/C02EN94AEPL/p1656625399803479?thread_ts=1656510671.986339&cid=C02EN94AEPL)):

 1. The view is broken (layout)
 2. :question: Does the forwarding to the workspace instance work? The URL is hinting at a workspace location, but why are we seeing prebuild logs here? Does "forward when done" still work? :thinking:

image

### PR DESCRIPTION
**Pull request by laushinka**
## Description
This fixes the broken layout, but doesn't add yet the "Skip Prebuild" button as we intended [in a recent epic](https://github.com/gitpod-io/gitpod/issues/9132). Skipping prebuilds will be covered in [a follow-up issue](https://github.com/gitpod-io/gitpod/issues/11128).

| BEFORE | AFTER |
| - | - |
| Screenshot 2022-07-04 at 15 05 39 | Screenshot 2022-07-04 at 18 19 56 |

## Related Issue(s)

Fixes #11079 

## How to test
1. Run a prebuild using `https://laushinka-be81110388.preview.gitpod-dev.com/#prebuild/[YOUR_REPO]`
2. See the fixed view as in the description.

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@laushinka: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: components/dashboard/src/components/PrebuildLogs.tsx [hunk 1]
```diff
@@ -129,11 +129,13 @@ export default function PrebuildLogs(props: PrebuildLogsProps) {
                     <WorkspaceLogs classes="h-full w-full" logsEmitter={logsEmitter} errorMessage={error?.message} />
                 </Suspense>
             </div>
-            <div className="h-20 px-6 bg-gray-50 dark:bg-gray-800 border-t border-gray-200 dark:border-gray-600 flex space-x-2">
-                {prebuild && <PrebuildStatus prebuild={prebuild} />}
-                <div className="flex-grow" />
-                {props.children}
-            </div>
+            {prebuild && (
+                <div className="h-20 px-6 bg-gray-50 dark:bg-gray-800 border-t border-gray-200 dark:border-gray-600 flex space-x-2 mb-6">
```
Comment (geropl) [inline components/dashboard/src/components/PrebuildLogs.tsx:133]: It seems the new `mb-6` now make the "Prebuild Details" view off again :cry: : 
image

Seems like we need to always test those three (1. PB details, 2. wait for PB, 3. manually trigger PB) in combination. :shield:

File: components/dashboard/src/components/PrebuildLogs.tsx [hunk 2]
```diff
@@ -129,11 +129,13 @@ export default function PrebuildLogs(props: PrebuildLogsProps) {
...
+                    <PrebuildStatus prebuild={prebuild} />
+                    <div className="flex-grow" />
+                    {props.children}
```
Comment (geropl) [inline components/dashboard/src/components/PrebuildLogs.tsx:136]: BTW: What happens if I have a button, say, but no prebuild? :thinking: Not sure it's relevant, but feels like an opportunity to ensure users never get stuck on this view.

File: components/dashboard/src/components/PrebuildLogs.tsx [hunk 3]
```diff
@@ -129,11 +129,13 @@ export default function PrebuildLogs(props: PrebuildLogsProps) {
                     <WorkspaceLogs classes="h-full w-full" logsEmitter={logsEmitter} errorMessage={error?.message} />
                 </Suspense>
             </div>
-            <div className="h-20 px-6 bg-gray-50 dark:bg-gray-800 border-t border-gray-200 dark:border-gray-600 flex space-x-2">
-                {prebuild && <PrebuildStatus prebuild={prebuild} />}
-                <div className="flex-grow" />
-                {props.children}
-            </div>
+            {prebuild && (
```
Comment (geropl) [inline components/dashboard/src/components/PrebuildLogs.tsx:132]: :bulb: Looking at this code made me :sparkles: the reason why we do not have a prebuild (and thus: skip button) here when triggering a manual one: Because at render time, there is no prebuild yet, because we're about to create it :see_no_evil: .

So to solve the prebuild issues, we should either a) poll for the prebuild if we do not find any, or b) make sure we have hooks in place to ge updated whenenver this happens.

Anyway, sth for a follow-up. :+1:

File: components/dashboard/src/components/PrebuildLogs.tsx (hunk 1 above)
Comment (laushinka) [reply components/dashboard/src/components/PrebuildLogs.tsx:133]: Good catch 😭 Need to remind myself to test all three views! Will fix.

File: components/dashboard/src/components/PrebuildLogs.tsx [hunk 4]
```diff
@@ -123,17 +123,19 @@ export default function PrebuildLogs(props: PrebuildLogsProps) {
     }, [logsEmitter, props.workspaceId, workspaceInstance?.id, workspaceInstance?.status.phase]);
 
     return (
-        <div className="rounded-xl overflow-hidden bg-gray-100 dark:bg-gray-800 flex flex-col">
+        <div className="rounded-xl overflow-hidden bg-gray-100 dark:bg-gray-800 flex flex-col mb-8">
             <div className="h-96 flex">
```
Comment (laushinka) [inline components/dashboard/src/components/PrebuildLogs.tsx:127]: Ended up adding the margin here - tested all three views. Also I think moving forward we should make the logs be centered in the screen. It's too off down there at the bottom.

File: components/dashboard/src/components/PrebuildLogs.tsx [hunk 5]
```diff
@@ -123,17 +123,19 @@ export default function PrebuildLogs(props: PrebuildLogsProps) {
     }, [logsEmitter, props.workspaceId, workspaceInstance?.id, workspaceInstance?.status.phase]);
 
     return (
-        <div className="rounded-xl overflow-hidden bg-gray-100 dark:bg-gray-800 flex flex-col">
+        <div className="rounded-xl overflow-hidden bg-gray-100 dark:bg-gray-800 flex flex-col mb-8">
```
Comment (laushinka) [inline components/dashboard/src/components/PrebuildLogs.tsx:126]: Ended up adding the margin here - tested all three views. Also I think moving forward we should make the logs be centered in the screen. It's too off down there at the bottom.

File: components/dashboard/src/components/PrebuildLogs.tsx (hunk 3 above)
Comment (laushinka) [reply components/dashboard/src/components/PrebuildLogs.tsx:132]: Will create a follow-up issue for this.

File: components/dashboard/src/components/PrebuildLogs.tsx (hunk 2 above)
Comment (laushinka) [reply components/dashboard/src/components/PrebuildLogs.tsx:136]: Related to the [above comment](https://github.com/gitpod-io/gitpod/pull/11119/files#r913151873).

File: components/dashboard/src/components/PrebuildLogs.tsx (hunk 1 above)
Comment (geropl) [reply components/dashboard/src/components/PrebuildLogs.tsx]: Works now! :+1:

**Review by geropl — APPROVED** [review]
Tested and works! :heavy_check_mark:
