### PR TITLE
[prebuilds] add metrics for prebuilds 10383

### LINKED ISSUE #10383: Add metrics to be able to identify leaking prebuild
Came up in the context of:
 - https://github.com/gitpod-io/gitpod/issues/8195: prebuilds are stuck in running because of an (suspected) supervisor bug (@AlexTugarev please fill in issue id HERE once created :pray: )
 - https://github.com/gitpod-io/gitpod/issues/9395#issuecomment-1142058473: prebuilds are stuck in `queued` for multiple reasons

First idea:
 - have counters on "queued" ([WorkspaceFactory](https://github.com/gitpod-io/gitpod/blob/81a79af4ec3f9a5de53f40370ab455bf8a054c85/components/server/ee/src/workspace/workspace-factory.ts#L168-L178) in `server`), "running" and end states ("available", "failed", in [bridge](https://github.com/gitpod-io/gitpod/blob/bb0a42a48c39ab6c1457d0624518415a2c3be596/components/ws-manager-bridge/ee/src/bridge.ts#L108), while making sure to only capture flanks :+1: )
 - subtracting those should give a fairly good trend

### PR DESCRIPTION
**Pull request by laushinka**
## Description
Provides counter metrics for prebuilds with states as labels.
- gitpod_prebuilds_started_total ("queued")
- gitpod_prebuilds_completed_total ("available", "failed", "timeout", "aborted" )

## Related Issue(s)

Fixes #10383 

## How to test
1. Trigger prebuilds
2. Check that those prebuilds show up on this Prometheus query page[[1](https://9090-gitpodio-gitpod-wbcbfz9sl3s.ws-eu46.gitpod.io/graph?g0.expr=gitpod_prebuilds_total&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h)]

## Release Notes

```release-note
NONE
```

## Documentation

/werft run with-observability

### CODE REVIEW

File: components/ws-manager-bridge/ee/src/prebuild-updater-db.ts [hunk 1]
```diff
@@ -78,6 +78,7 @@ export class PrebuildUpdaterDB implements PrebuildUpdater {
 
                 span.setTag("updatePrebuildWorkspace.prebuild.state", updatedPrebuild.state);
                 span.setTag("updatePrebuildWorkspace.prebuild.error", updatedPrebuild.error);
+                this.prometheusExporter.increasePrebuildsCounter(updatedPrebuild.state);
```
Comment (laushinka) [inline components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:81]: @geropl I ended up using only one counter because here the updated state can be either starting ("building") or ending.

File: components/ws-manager-bridge/src/prometheus-metrics-exporter.ts [hunk 2]
```diff
@@ -73,6 +74,12 @@ export class PrometheusMetricsExporter {
             labelNames: ["db_write", "workspace_cluster", "workspace_instance_type", "outcome"],
             buckets: prom.exponentialBuckets(2, 2, 8),
         });
+
+        this.prebuildsTotal = new prom.Counter({
```
Comment (laushinka) [inline components/ws-manager-bridge/src/prometheus-metrics-exporter.ts:78]: I created a duplicate one here because `prometheus-metrics.ts` isn't accessible from `ws-manager-bridge`. The metrics show up just fine as one in Prometheus, but please let me know if there is a better way 🙏🏽

File: components/ws-manager-bridge/ee/src/prebuild-updater-db.ts (hunk 1 above)
Comment (easyCZ) [reply components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:81]: Semantically, a counter is not correct for this. You're tracking state which changes over time. This means that if I do `sum(gitpod_prebuilds_total)` I will receive 1 for each state a prebuild has been in, not a total number of prebuilds.

For this case, you need to use multiple metrics - 1 gauge to track the state. If you also want to know things like # of started prebuilds vs # of succesful prebuilds, you may need extra metrics.

**Review by easyCZ — DISMISSED** [review]
Left a comment about semantics of the metrics.

File: components/ws-manager-bridge/ee/src/prebuild-updater-db.ts (hunk 1 above)
Comment (laushinka) [reply components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:81]: Thanks for the comment, @easyCZ! Indeed that for the total number of prebuilds, we will need a gauge. However that means reading the DB and we weren't sure that would be the best way. Having a counter for the amount of each state a prebuild has been in would serve the purpose of comparing how many `queued` and how many ended up in an "end" state. With this we can see how many never got to an end state and debug from there. 
What do you think?

Comment (easyCZ) [reply components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:81]: Also depending on the desired accuracy, you may have to read from the DB as the DB is the only source of truth. If we are happy with some amount of error, handling this from the ws-manager-bridge is fine (but expect that when ws-manager-bridge fails, or otherwise doesn't work, your metrics will be off)

Comment (laushinka) [reply components/ws-manager-bridge/ee/src/prebuild-updater-db.ts]: After discussing with @easyCZ, we'll have this PR to add the counter metrics and see how they help us. If in the future we deem a gauge necessary then we will follow-up with it. 
A fix will be made in this PR to separate the counter into two - started and completed. It is now a draft until the fix is pushed.

File: components/server/src/prometheus-metrics.ts [hunk 3]
```diff
@@ -151,3 +151,25 @@ const instanceStartsFailedTotal = new prometheusClient.Counter({
 export function increaseFailedInstanceStartCounter(reason: "clusterSelectionFailed" | "startOnClusterFailed") {
     instanceStartsFailedTotal.inc({ reason });
 }
+
+const prebuildsStartedTotal = new prometheusClient.Counter({
+    name: "gitpod_prebuilds_started_total",
+    help: "Counter of total prebuilds started.",
+    labelNames: ["state"],
```
Comment (easyCZ) [inline components/server/src/prometheus-metrics.ts:158]: Why do you need the state when the metric is explicitly for "started" prebuilds?

File: components/server/src/prometheus-metrics.ts [hunk 4]
```diff
@@ -151,3 +151,25 @@ const instanceStartsFailedTotal = new prometheusClient.Counter({
...
+});
+
+export function increasePrebuildsStartedCounter(state: string) {
+    prebuildsStartedTotal.inc({ state });
+}
+
+const prebuildsEndedTotal = new prometheusClient.Counter({
+    name: "gitpod_prebuilds_ended_total",
+    help: "Counter of total prebuilds ended.",
+    labelNames: ["state"],
```
Comment (easyCZ) [inline components/server/src/prometheus-metrics.ts:169]: We run multiple replicas of ws-manager-bridge, this means you'll get this metric reported from multiple pods. But not all are `governing` - that means actually affecting the database. This presents a challenge as your data here is not going to reflect reality, and will be `n` times larger depending on the number of replicas. One way to address that is to use the `governing` flag `ws-manager-bridge` has. You can for example add it as a label which will allow you to filter out the extra instances, or better, only increment the metric on governing instances.

File: components/ws-manager-bridge/ee/src/prebuild-updater-db.ts [hunk 5]
```diff
@@ -79,6 +79,10 @@ export class PrebuildUpdaterDB implements PrebuildUpdater {
                 span.setTag("updatePrebuildWorkspace.prebuild.state", updatedPrebuild.state);
                 span.setTag("updatePrebuildWorkspace.prebuild.error", updatedPrebuild.error);
 
+                if (updatedPrebuild.state && updatedPrebuild.state !== "building") {
```
Comment (easyCZ) [inline components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:82]: I'd recommend flipping the logic - list all the "terminal" states for which we do increment the metric. It's more resilient to new states being introduced in the future. 

A better alternative yet, add an instance method on the `prebuild` object to check if it's in terminal state. That way, you can co-locate the logic around the definition of state - higher chance we'll not forget to update something when we make changes.

File: components/server/src/prometheus-metrics.ts (hunk 4 above)
Comment (easyCZ) [reply components/server/src/prometheus-metrics.ts:169]: The `writeToDB` flag being true is what makes an instance governing.

File: components/ws-manager-bridge/ee/src/prebuild-updater-db.ts (hunk 5 above)
Comment (laushinka) [reply components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:82]: > list all the "terminal" states for which we do increment the metric

Agree it would be more resilient 👍🏼

File: components/server/src/prometheus-metrics.ts (hunk 4 above)
Comment (laushinka) [reply components/server/src/prometheus-metrics.ts]: > The `writeToDB` flag being true is what makes an instance governing.

TIL!

File: components/server/ee/src/workspace/workspace-factory.ts [hunk 6]
```diff
@@ -177,6 +178,10 @@ export class WorkspaceFactoryEE extends WorkspaceFactory {
                 statusVersion: 0,
             });
 
+            if (pws) {
+                increasePrebuildsStartedCounter();
```
Comment (easyCZ) [inline components/server/ee/src/workspace/workspace-factory.ts:182]: This is also affected by the multi-replica problem. So depending on which solution you go for, it needs to be done here too.

**Comment by geropl** [comment]
@laushinka Starting to review now.

File: components/server/src/prometheus-metrics.ts [hunk 7]
```diff
@@ -151,3 +151,14 @@ const instanceStartsFailedTotal = new prometheusClient.Counter({
 export function increaseFailedInstanceStartCounter(reason: "clusterSelectionFailed" | "startOnClusterFailed") {
     instanceStartsFailedTotal.inc({ reason });
 }
+
+const prebuildsStartedTotal = new prometheusClient.Counter({
+    name: "gitpod_prebuilds_started_total",
+    help: "Counter of total prebuilds started.",
+    labelNames: ["is_governing"],
```
Comment (geropl) [inline components/server/src/prometheus-metrics.ts:158]: The label is not necessary.

File: components/ws-manager-bridge/ee/src/prebuild-updater-db.ts [hunk 8]
```diff
@@ -79,6 +80,10 @@ export class PrebuildUpdaterDB implements PrebuildUpdater {
                 span.setTag("updatePrebuildWorkspace.prebuild.state", updatedPrebuild.state);
                 span.setTag("updatePrebuildWorkspace.prebuild.error", updatedPrebuild.error);
 
+                if (updatedPrebuild.state && terminatingStates.includes(updatedPrebuild.state)) {
```
Comment (geropl) [inline components/ws-manager-bridge/ee/src/prebuild-updater-db.ts:83]: The `writeToDB`/`is_governing` label should not be in the metric but checked in this if statement:
`if (writeToDB && terminatingStates.includes(updatedPrebuild.state)) { .... }`

File: components/ws-manager-bridge/src/prometheus-metrics-exporter.ts [hunk 9]
```diff
@@ -73,6 +74,12 @@ export class PrometheusMetricsExporter {
             labelNames: ["db_write", "workspace_cluster", "workspace_instance_type", "outcome"],
             buckets: prom.exponentialBuckets(2, 2, 8),
         });
+
+        this.prebuildsCompletedTotal = new prom.Counter({
+            name: "gitpod_prebuilds_completed_total",
+            help: "Counter of total prebuilds ended.",
+            labelNames: ["state", "is_governing"],
```
Comment (geropl) [inline components/ws-manager-bridge/src/prometheus-metrics-exporter.ts:81]: As mentioned before: `is_governing` is not needed here.

File: components/server/src/prometheus-metrics.ts (hunk 4 above)
Comment (geropl) [reply components/server/src/prometheus-metrics.ts]: > We run multiple replicas of ws-manager-bridge

... but only ever one "bridge" is "governing" a given cluster. Thus we don't care about that flag, but should write the metric based on it. See [comment](https://github.com/gitpod-io/gitpod/pull/10435#discussion_r891991889).

Comment (easyCZ) [reply components/server/src/prometheus-metrics.ts]: Basically what we're saying is that we should have
```
if (writeToDB) {
	reportMetric()
}
```
