### PR TITLE
ws-daemon: align to decide if cgroup v2.

### LINKED ISSUE #9389: Cgroup v2 with fusefs doesn't work
### Bug description

Cgroup v2 with fusefs doesn't work. It seems workspace's cgroup doesn't exist.
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"stat /mnt/node-cgroups/kubepods/burstable/podfea31d7c-7776-434e-9803-88c13eaa528f/2cd991f969cee3eb6f7914ea6102d93a17e70e806dd6de79a58ade1bbeae53fb/workspace: no such file or directory","instanceId":"f7f496f3-49db-4f5f-8058-a5b6abac3841","level":"error","message":"EvacuateCGroup: workspace cgroup error","path":"/kubepods/burstable/podfea31d7c-7776-434e-9803-88c13eaa528f/2cd991f969cee3eb6f7914ea6102d93a17e70e806dd6de79a58ade1bbeae53fb/workspace","serviceContext":{"service":"ws-daemon","version":"commit-28db115fda435dcc5ccc4cb7504bb51cd022d275"},"severity":"ERROR","time":"2022-04-19T03:16:35Z","userId":"6a19353b-9080-4a94-85c3-f1fc5ef41874","workspaceId":"checkpointresto-rustcriu-7xg9x19kz7r"}
```

### Steps to reproduce

Create the cgroup v2 with fusefs environment and run a workspace.
https://github.com/gitpod-io/workspace-preview/tree/to/fusefs

### Workspace affected

_No response_

### Expected behavior

Works fine

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by utam0k**
## Description

For some reason, the existing decision process was not working properly to determine using cgroup v2.

## Related Issue(s)

Fixes #9389

## How to test

Create the cgroup v2 with fusefs environment and run a workspace.
https://github.com/gitpod-io/workspace-preview/tree/to/fusefs

## Release Notes

```release-note
ws-daemon: align to decide if cgroup v2 to fix cgroup v2 with fuse
```

## Documentation

No

### CODE REVIEW

File: components/ws-daemon/pkg/iws/iws.go [hunk 1]
```diff
@@ -287,7 +287,12 @@ func (wbs *InWorkspaceServiceServer) PrepareForUserNS(ctx context.Context, req *
 		return nil, status.Errorf(codes.Internal, "cannot mount shiftfs mark")
 	}
 
-	if cgroups.Mode() == cgroups.Unified {
+	unified, err := cgroups.IsUnifiedCgroupSetup()
+	if err != nil {
+		return nil, status.Errorf(codes.FailedPrecondition, "could not determine cgroup setup")
```
Comment (princerachit) [inline components/ws-daemon/pkg/iws/iws.go:292]: should we include the error `err` in the message?

**Comment by princerachit** [comment]
@utam0k can you attach a screenshot where it shows that the issue is resolved, or maybe include a loom video so all reviewers don't have to explicitly test?

File: components/ws-daemon/pkg/iws/iws.go (hunk 1 above)
Comment (csweichel) [reply components/ws-daemon/pkg/iws/iws.go:292]: This error might be exposed to the user to whom it would be confusing.
We should log this instead.

File: components/ws-daemon/pkg/iws/iws.go [hunk 2]
```diff
@@ -889,7 +894,11 @@ func (wbs *InWorkspaceServiceServer) WriteIDMapping(ctx context.Context, req *ap
 // └── workspace       drwxr-xr-x 5 gitpodUid gitpodGid
 //     └── user        drwxr-xr-x 5 gitpodUid gitpodGid
 func (wbs *InWorkspaceServiceServer) EvacuateCGroup(ctx context.Context, req *api.EvacuateCGroupRequest) (*api.EvacuateCGroupResponse, error) {
-	if cgroups.Mode() != cgroups.Unified {
+	unified, err := cgroups.IsUnifiedCgroupSetup()
+	if err != nil {
+		return nil, status.Errorf(codes.FailedPrecondition, "could not determine cgroup setup")
+	}
+	if unified {
```
Comment (sagor999) [inline components/ws-daemon/pkg/iws/iws.go:901]: should this be `!unified` since originally we were checking if mode != unified?

**Comment by Furisto** [comment]
@utam0k While discussing the cgroup issues Pavel had with his PVC work, we discovered that the method to evacuate the cgroup does not get called when using fuse. I have fixed that and added it to this PR.

**Review by sagor999 — APPROVED** [review]
lgtm
added to workspace cluster changelog
