### PR TITLE
Redirect web page when instance changed

### LINKED ISSUE #8226: [supervisor] Ensure we fetch IDEOptions/desktopIDEConfig on re-start
So far we set [dekstopIDEConfig](https://github.com/gitpod-io/gitpod/blob/c0bbf911db3a13c23cd7da8a124c17b5046e245c/components/supervisor/frontend/src/index.ts#L119-L123) and [IDEOptions](https://github.com/gitpod-io/gitpod/blob/0fa9200ac83835463267630ab01f79a01a1db5fb/components/dashboard/src/start/StartWorkspace.tsx#L131-L132) onload. With the [recent change away from auto-reload behavior](https://github.com/gitpod-io/gitpod/pull/8125#issuecomment-1038846404) this does no longer show "Open in < desktopIDE >" in cases where:
 - you open a workspace in tab 1
 - stop it in tab 2 (dashboard, for example)
 - re-start it in tab 2 (dashboard, for example)

We should see
image
but instead see this:
image

The dashboard change is quite [straight forward](https://github.com/gitpod-io/gitpod/pull/8188). In supervisor-frontend we'd need to re-fetch the desktopIDEConfig on re-start as well.

/cc @akosyakov

### LINKED ISSUE #8990: One frame running phase for every workspace start
### Bug description

One frame running phase for every workspace start

This ~~is~~ part because of the time diff between `contentAvailable` and `ideReady`

This PR https://github.com/gitpod-io/gitpod/pull/8313 will wait until `contentAvailable` to get `.gitpod.yml` file to parse extensions and download extensions via URL first, and then start IDE

So `ideReady` will always be after `contentAvailable`, but after `contentAvailable`, workspace phase turns to `Running`.

We can verify it here https://gitpod.io/#github.com/mustard-mh/test/tree/hw/large-file which will download some large files

```yaml
vscode:
  extensions:
    - http://ipv4.download.thinkbroadband.com/1GB.zip
    - http://212.183.159.230/1GB.zip
    - https://speed.hetzner.de/10GB.bin
```

|Image|
|:-:|
|iShot2022-03-29 15 50 04|

### Steps to reproduce

Start a workspace

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Display opening workspace when ide is not ready yet. Relates PR https://github.com/gitpod-io/gitpod/pull/8125

Refresh web page when instanceId changed to get ide config and ws works again

Need to verify
1. One frame running phase does not display (will display `Starting`, `Opening workspace...`
2. Stopped workspace URL contains `not_found` works after ws started
3. Stopped workspace works after ws started https://github.com/gitpod-io/gitpod/pull/9004#issuecomment-1084573937

## Related Issue(s)

Fixes #8990
Fixes #8226

## How to test

1. Start same workspace in tab 1\2\3 (tab1 <-> verify1/3, tab2 <-> verify2
2. After they started, stop workspace in dashboard
3. Wait until tabs 1\2\3 Stopped
4. Refresh tab2
5. Go to tab3 click `Open Workspace`
6. See if tabs 1\2\3 work fine

We can do negative test like this PR https://github.com/gitpod-io/gitpod/pull/8125 in staging here https://hw-fix-8990-crash.staging.gitpod-dev.com/workspaces which will make Insiders VSCode crash https://github.com/gitpod-io/gitpod/commit/bb705e2d9d851b0c3cefb3c6f84f4a392722edba

## Release Notes

```release-note
Fixed one frame running phase when starting workspace
Fixed IDE options display incorrectly when restarting the workspace
Fixed stopped workspace does not work again if it started in another place
```

### CODE REVIEW

**Review by geropl — DISMISSED** [review]
We introduced this change to avoid endless loops where we would start a new workspace on each page load.

IMO the problem here is somewhere else.

**Comment by mustard-mh** [comment]
> We introduced this change to avoid endless loops where we would start a new workspace on each page load.
> 
> IMO the problem here is somewhere else.

@geropl  Code this PR changed, only effect display, logic not changed

**Comment by geropl** [comment]
@mustard-mh Sorry for not being more precise here (still struggling with the virous :dizzy_face: ).

We _need_ the buttons to be there in case of a restart. Also cmp. my later comment [here](https://github.com/gitpod-io/gitpod/issues/8990#issuecomment-1082735140).

**Comment by akosyakov** [comment]
Eh, now we have a problem in another place:
- tab 1: start any workspace
- tab 2: open the same workspace
- note how both end up in the IDE
- stop the workspace
- note how both end up in "Stopped"
- open the workspace again from tab 2
- Note how:
  - both workspaces show up-to-date state
  - only tab 2 reveals the IDE
  - tab 1 still shows the up-to-date state and controls to open/reveal the IDE (with fresh credentials), but it just hangs in opening workspace... forever

**Comment by geropl** [comment]
> tab 1 still shows the up-to-date state and controls to open/reveal the IDE (with fresh credentials), but it just hangs in opening workspace... forever

@akosyakov Ah, yes. That's why I originally combined this with #8226 . If we combine this with https://github.com/gitpod-io/gitpod/pull/8978 I think we should be good! :upside_down_face:

**Comment by akosyakov** [comment]
ok, let's try, @mustard-mh Could you bring other changes?

File: components/dashboard/src/start/StartWorkspace.tsx [hunk 1]
```diff
@@ -431,48 +435,7 @@ export default class StartWorkspace extends React.Component<StartWorkspaceProps,
                 }
                 if (!this.state.desktopIde) {
                     phase = StartPhase.Running;
-
```
Comment (mustard-mh) [inline components/dashboard/src/start/StartWorkspace.tsx:434]: We can delete this condition because it has already been redirected

File: components/supervisor/frontend/src/index.ts [hunk 2]
```diff
@@ -108,9 +108,20 @@ const toStop = new DisposableCollection();
...
+    let currentInstanceId = "";
     const nextFrame = () => {
         const instance = gitpodServiceClient.info.latestInstance;
         if (instance) {
+            // refresh web page when instanceId changed
+            if (currentInstanceId !== "") {
+                if (instance.id !== currentInstanceId && instance.ideUrl !== "") {
+                    currentInstanceId = instance.id;
+                    window.location.href = instance.ideUrl;
+                    return;
```
Comment (akosyakov) [inline components/supervisor/frontend/src/index.ts:120]: you don't need to return here, it will never happen

**Comment by mustard-mh** [comment]
Also updated how to test section

**Comment by mustard-mh** [comment]
@geropl Please have a look 🙏

**Review by andreafalzetti — APPROVED** [review]
I've tested all scenarios and it works as expected.

Great work @mustard-mh 🚀

File: components/dashboard/src/start/StartWorkspace.tsx [hunk 3]
```diff
@@ -324,7 +324,11 @@ export default class StartWorkspace extends React.Component<StartWorkspaceProps,
 
         // Redirect to workspaceURL if we are not yet running in an iframe.
         // It happens this late if we were waiting for a docker build.
-        if (!this.props.runsInIFrame && workspaceInstance.ideUrl && !this.props.dontAutostart) {
+        if (
+            !this.props.runsInIFrame &&
+            workspaceInstance.ideUrl &&
+            (!this.props.dontAutostart || workspaceInstance.status.phase === "running")
```
Comment (geropl) [inline components/dashboard/src/start/StartWorkspace.tsx:330]: :+1:

Comment (geropl) [reply components/dashboard/src/start/StartWorkspace.tsx:330]: Unfortunately I don't have a reproducer for such a scenario... :thinking:

File: components/supervisor/frontend/src/index.ts [hunk 4]
```diff
@@ -108,9 +108,19 @@ const toStop = new DisposableCollection();
...
     let desktopRedirected = false;
+    let currentInstanceId = "";
     const nextFrame = () => {
         const instance = gitpodServiceClient.info.latestInstance;
         if (instance) {
+            // refresh web page when instanceId changed
+            if (currentInstanceId !== "") {
+                if (instance.id !== currentInstanceId && instance.ideUrl !== "") {
+                    currentInstanceId = instance.id;
+                    window.location.href = instance.ideUrl;
```
Comment (geropl) [inline components/supervisor/frontend/src/index.ts:119]: :100:

File: components/dashboard/src/start/StartWorkspace.tsx (hunk 3 above)
Comment (mustard-mh) [reply components/dashboard/src/start/StartWorkspace.tsx:330]: running -> redirect ->   ws-proxy find pod -> ide -> failed -> stopped
                                ｜
                                └>  ws-proxy find no pod -> add not_found -> loop break

@geropl

Comment (mustard-mh) [reply components/dashboard/src/start/StartWorkspace.tsx:330]: Loop only happens when DB shows workspace status as `running` forever

Comment (mustard-mh) [reply components/dashboard/src/start/StartWorkspace.tsx:330]: Steps like Anton said https://github.com/gitpod-io/gitpod/pull/9004#issuecomment-1084573937 will repro this scenario, others has been test in prev PR https://github.com/gitpod-io/gitpod/pull/8125

File: components/dashboard/src/start/StartWorkspace.tsx (hunk 1 above)
Comment (mustard-mh) [reply components/dashboard/src/start/StartWorkspace.tsx:434]: If we are going to use `redirect` for running phase, we can remove this safely. If not, we can change it @geropl

File: components/dashboard/src/start/StartWorkspace.tsx (hunk 3 above)
Comment (geropl) [reply components/dashboard/src/start/StartWorkspace.tsx:330]: > I think after this PR, flow will be like this

@mustard-mh Thx for the flow picture, that explains it! :pray:  We have one failed step, but will break because we still respect `dontAutostart` when triggering the actual workspace start. :heavy_check_mark: :lotus_position:

**Review by geropl — APPROVED** [review]
LGTM - thx for fixing this! :muscle:
