### PR TITLE
Properly handle provider host name when using http(s) prefix when adding a new integration

### LINKED ISSUE #7492: Properly handle provider host name when using http(s) prefix when adding a new integration
### Bug description

When a user tries to add a Git integration, using a URL with the http(s) prefix leads to inproperly configured URL, Redirect URL, etc.

### Steps to reproduce

1. Go to [`/integrations`](https://gitpod.io/integrations)
2. Try adding a GitLab or Github integration using a URL including the http(s) prefix

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
## Description

When a user has manually included http(s) prefixes in their provider hostname, strip it off so that it uses only the gitpod provided prefix in the configured URL and Redirect URL.

## Related Issue(s)

Fixes #7492 

## How to test

Go to dashboard and under integrations try to add new integration with a self-hosted instance of a provider, then notice that any HTTP(s) prefix is removed from the configured URL

## Release Notes

```release-note
Git Integrations UI – improve handling of host name.
```

### CODE REVIEW

**Comment by roboquat** [comment]
@Shulammite-Aso: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jldec** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jldec` in a comment when ready.

Associated issue: *#7492*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Thanks for contributing, @Shulammite-Aso! 🍊 

/werft run

**Comment by gtsiolis** [comment]
@Shulammite-Aso You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓

**Comment by Shulammite-Aso** [comment]
@meysholdt how do i sign the Contributor license agreement?  I followed this [link](https://github.com/gitpod-io/cla) provided in the docs [here](https://www.gitpod.io/docs/contribute/features-and-patches/submitting-a-pull-request) to see if it provides hints on how to sign it, but it appears the link is broken.

**Comment by csweichel** [comment]
cc @meysholdt

**Comment by meysholdt** [comment]
Hi @Shulammite-Aso, I've sent the CLA via email / DocuSign.

**Comment by Shulammite-Aso** [comment]
Hi @meysholdt i just signed the document.

**Comment by meysholdt** [comment]
Hi @Shulammite-Aso! Awesome, thank you for signing!

File: components/dashboard/src/settings/Integrations.tsx [hunk 1]
```diff
@@ -547,8 +547,17 @@ export function GitIntegrationModal(props: ({
 
     const updateHostValue = (host: string) => {
         if (mode === "new") {
-            setHost(host);
-            setRedirectURL(callbackUrl(host));
+
+            let verifiedHost = host;
+
+            if (host.includes("https://")) {
```
Comment (JanKoehnlein) [inline components/dashboard/src/settings/Integrations.tsx:553]:
```suggestion
            if (host.startsWith("https://")) {
```

File: components/dashboard/src/settings/Integrations.tsx [hunk 2]
```diff
@@ -547,8 +547,17 @@ export function GitIntegrationModal(props: ({
...
+                verifiedHost = host.replace("https://","");
+            } else if (host.includes("http://")) {
```
Comment (JanKoehnlein) [inline components/dashboard/src/settings/Integrations.tsx:555]:
```suggestion
            } else if (host.startsWith("http://")) {
```

or use a regexp

**Review by JanKoehnlein — CHANGES_REQUESTED** [review]
Thanks a lot for the change. I've proposed a few changes.

File: components/dashboard/src/settings/Integrations.tsx (hunk 2 above)
Comment (Shulammite-Aso) [reply components/dashboard/src/settings/Integrations.tsx:555]: Yeah @JanKoehnlein i agree `startsWith` is a better method in this case. Would just make the changes. 

Github provides a UI to directly commit the suggestions, but I fear I might need two commits for the two suggestions. So i'd instead manually make the changes in one commit.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#7492*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/dashboard/src/settings/Integrations.tsx [hunk 3]
```diff
@@ -547,8 +547,17 @@ export function GitIntegrationModal(props: ({
...
     const updateHostValue = (host: string) => {
         if (mode === "new") {
-            setHost(host);
-            setRedirectURL(callbackUrl(host));
+
+            let verifiedHost = host;
+
+            if (host.startsWith("https://")) {
+                verifiedHost = host.replace("https://","");
+            } else if (host.startsWith("http://")) {
```
Comment (AlexTugarev) [inline components/dashboard/src/settings/Integrations.tsx:555]: please remove the `http` branch

**Review by AlexTugarev — COMMENTED** [review]
@Shulammite-Aso thanks for the contribution!

I left some comments. The main issue remains is, that Gitpod [won't accept `http` URLs](https://github.com/gitpod-io/gitpod/issues/7492#issuecomment-1028916586) for provider connections on the server side.

File: components/dashboard/src/settings/Integrations.tsx [hunk 4]
```diff
@@ -547,8 +547,17 @@ export function GitIntegrationModal(props: ({
 
     const updateHostValue = (host: string) => {
         if (mode === "new") {
-            setHost(host);
-            setRedirectURL(callbackUrl(host));
+
+            let verifiedHost = host;
```
[the remark this answers is not in the document]
Comment (Shulammite-Aso) [reply components/dashboard/src/settings/Integrations.tsx:551]: I guess so @AlexTugarev, but i can't seem to think of a better variable name that is not too long. Will adding a #comment that briefly describes what the variable and the code below do resolve the issue? I would appreciate a better name suggestion too.

[the remark this answers is not in the document]
Comment (Shulammite-Aso) [reply components/dashboard/src/settings/Integrations.tsx]: Nice, thanks for the suggestion. Has now changed the variable name to this.

File: components/dashboard/src/settings/Integrations.tsx (hunk 3 above)
Comment (Shulammite-Aso) [reply components/dashboard/src/settings/Integrations.tsx]: Done too.

Comment (AlexTugarev) [reply components/dashboard/src/settings/Integrations.tsx]: Thanks!

**Comment by AlexTugarev** [comment]
Let's verify with a preview environment and lend this PR 
⏳

**Review by AlexTugarev — APPROVED** [review]
Thanks for the contribution, @Shulammite-Aso!
🎉 🎉 🎉

**Comment by Shulammite-Aso** [comment]
Hi @gtsiolis this PR is approved, is it now ready to get merged?

**Comment by gtsiolis** [comment]
Hey, @Shulammite-Aso! I wanted to confirm internally that the signed CLA is in place and stored for future contributions.

Let's merge this. 🚀 

Thanks @AlexTugarev @JanKoehnlein @meysholdt @csweichel  for helping move this forward! 🏀

**Review by gtsiolis — APPROVED** [review]
LGTM

**Comment by gtsiolis** [comment]
@JanKoehnlein could you approve this to unblock merging[[1](https://github.com/gitpod-io/gitpod/pull/7831#pullrequestreview-870468778)]?

**Review by JanKoehnlein — APPROVED** [review]
LGTM. Thanks a lot for this contribution
