### PR TITLE
[FIX] Improved UX for Workspace Entry Component

### LINKED ISSUE #4635: Improve items list component
### Problem to solve

In https://github.com/gitpod-io/gitpod/pull/4454, we've added a reusable items list component used in _Workspaces_, _Environement Variables_, etc. In parallel, we've also fixed the issue with multiple dropdowns, see https://github.com/gitpod-io/gitpod/pull/4502. Cc @corneliusludmann 

However, there's still room for improving the UX and interaction of the items list component and the more actions dropdown.

### Proposal

The items list component could be improved by doing the following:
1. Do not remove the hover state on the more actions button when triggered and moving the cursor away. (_Dropdown B_) 
2. Do not remove the hover state of the list item when triggering the more actions and moving away the cursor. (_Dropdown C_) 

| Dropdown A | Dropdown B | Dropdown C |
|-|-|-|
| list-item-1 | list-item-2 | list-item-3 |

### PR DESCRIPTION
**Pull request by henit-chobisa**
## Description

The below issues propose improvement for the UX of the Workspace Entry Components, by keeping the hovered effect ( the background colors ) of the workspace items till the `WorkspaceOverflowMenu` is expanded. Please refer the below images for reference of the improvement.

image

image

## Improvement Graphics 

https://user-images.githubusercontent.com/72302948/216030419-a1c4f4c6-9ce0-4beb-bd63-d1a2cd4a58a9.mov

## Related Issue(s)
* Closes #4635  
* Check a fix from #12033

## How to test
- Change your directory from /gitpod to /gitpod/component/dashboard
- Add your host and token as given in the readme
- Start the development server by `yarn run start` and check on `http://localhost:3000` for checking the dashboard

## Release Notes

```release-note
Improve the ItemsList and ContextMenu components
```

### CODE REVIEW

**Comment by roboquat** [comment]
@henit-chobisa: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

File: components/dashboard/src/components/ContextMenu.tsx [hunk 1]
```diff
@@ -73,7 +89,10 @@ function ContextMenu(props: ContextMenuProps) {
     // Default 'children' is the three dots hamburger button.
     const children = props.children || (
         <svg
-            className="w-8 h-8 p-1 rounded-md text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700"
+            className={cn(
+                "w-8 h-8 p-1 rounded-md text-gray-600 dark:text-gray-300",
+                expanded ? "bg-gray-200 dark:bg-gray-700" : "hover:bg-gray-200 dark:hover:bg-gray-700",
+            )}
```
Comment (gtsiolis) [inline components/dashboard/src/components/ContextMenu.tsx:95]: **issue**: Probably some color mismatch but the workspaces list hover state changes color after expanding the more actions menu, right?

https://user-images.githubusercontent.com/120486/216107110-fff224de-d659-4a4b-b206-8fc1da204bf4.mov

File: components/dashboard/src/components/ItemsList.tsx [hunk 2]
```diff
@@ -38,15 +38,17 @@ export function ItemFieldContextMenu(props: {
...
     const cls = "self-" + (props.position ?? "center");
+
     return (
         <div
             className={`flex hover:bg-gray-200 dark:hover:bg-gray-700 rounded-md cursor-pointer w-8 ${cls} ${
                 props.className || ""
             }`}
         >
-            <ContextMenu menuEntries={props.menuEntries} />
+            <ContextMenu changeMenuState={props.changeMenuState} menuEntries={props.menuEntries} />
```
Comment (gtsiolis) [inline components/dashboard/src/components/ItemsList.tsx:51]: **question**: Not sure if this the best line to add this comments but the environment variables list behaves a bit differently without keeping the hover state of the entry when moving the pointer away. Is this something we could fix here or in a separate PR? What do you think?

https://user-images.githubusercontent.com/120486/216107633-71f21f1e-8b11-455c-91de-d26cab5dd0d5.mov

**Review by gtsiolis — CHANGES_REQUESTED** [review]
Thanks for contributing, @henit-chobisa!

1. UX changes look good! Left two comments we could address before merging.
2. I'd rely on someone from the `@gitpod-io/engineering-webapp` to take a closer look at the code changes as discussed in https://github.com/gitpod-io/gitpod/issues/4635#issuecomment-1410056599.
3. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt

/hold

File: components/dashboard/src/components/ContextMenu.tsx (hunk 1 above)
Comment (henit-chobisa) [reply components/dashboard/src/components/ContextMenu.tsx:95]: Yes @gtsiolis, you're right there was a color mismatch, I have fixed it with a commit.

File: components/dashboard/src/components/ItemsList.tsx (hunk 2 above)
Comment (henit-chobisa) [reply components/dashboard/src/components/ItemsList.tsx:51]: Actually, I am waiting for this PR to get reviewed once, so I will get a bit clear with should I setup a separate context for dropdown menu or the functions approach would be good, 
If I need to go with the Separate context approach then all the components would be fixed at once and no extra PR would be needed, but setting up a separate context needs more code changes through the whole tree, 
If I go by the functions approach then I have to make separate PRs for environment variables, integrations and Access Tokens.

**Comment by henit-chobisa** [comment]
> Thanks for contributing, @henit-chobisa!
> 
> 1. UX changes look good! Left two comments we could address before merging.
> 2. I'd rely on someone from the `@gitpod-io/engineering-webapp` to take a closer look at the code changes as discussed in [#4635 (comment)](https://github.com/gitpod-io/gitpod/issues/4635#issuecomment-1410056599).
> 3. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt
> 
> /hold

Thank you so much for your quick review @gtsiolis, I have signed the CLA now 🐳

**Review by geropl — APPROVED** [review]
Did not notice before, but really like this! :orange_heart:

**Comment by henit-chobisa** [comment]
> Did not notice before, but really like this! :orange_heart: 

Glad @geropl

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

**Comment by gtsiolis** [comment]
Thanks @henit-chobisa for addressing the UX comments and @geropl for taking a look! 🏀 

@henit-chobisa Could you also squash the commits into one?

**Comment by henit-chobisa** [comment]
> Thanks @henit-chobisa for addressing the UX comments and @geropl for taking a look! 🏀
> 
> @henit-chobisa Could you also squash the commits into one?
Sure @gtsiolis, 
I have done it ✌️

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

**Comment by gtsiolis** [comment]
Took one last closer look—Let's merge this!

/unhold

**Comment by gtsiolis** [comment]
@henit-chobisa One last request as I noticed the commit message, could you rebase the commit and change the commit title to something more descriptive like the release note?
> Improve the ItemsList and ContextMenu components
What do you think?

**Comment by henit-chobisa** [comment]
> @henit-chobisa One last request as I noticed the commit message, could you rebase the commit and change the commit title to something more descriptive like the release note?
> 
> > Improve the ItemsList and ContextMenu components
> 
> What do you think?

No issues at all @gtsiolis, I do that now

**Comment by henit-chobisa** [comment]
@gtsiolis Done ✌️

**Comment by gtsiolis** [comment]
Thanks, @henit-chobisa! Let's merge this!

Re-running build and removing the hold.

/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

/unhold

**Review by gtsiolis — APPROVED** [review]

**Comment by henit-chobisa** [comment]
Hey @gtsiolis , thank you so much for merging this one, 
I suppose the methodology is approved, hence should I make PRs for other `ItemList` Components too ?

**Comment by gtsiolis** [comment]
> ... hence should I make PRs for other ItemList Components too ?

Sounds good, @henit-chobisa! 🏀

Overall, having an MVC approach that we can ship faster is always better. We can always iterate and improve the approach (methodology) in later iterations. Done is better than perfect. 🙂

**Comment by henit-chobisa** [comment]
> > ... hence should I make PRs for other ItemList Components too ?
> 
> Sounds good, @henit-chobisa! 🏀
> 
> Overall, having an MVC approach that we can ship faster is always better. We can always iterate and improve the approach (methodology) in later iterations. Done is better than perfect. 🙂

Absolutely, let me fix others too. 🐳
