### PR TITLE
fix: trim repo url while open new workspace

### LINKED ISSUE #12079: Dashboard should trim spaces around URL before creating workspace
### Description

If, by mistake, I copy/paste an additional space before the repo url, the dashboard fails where it could auto heal by trimming the space

Screenshot 2022-08-11 at 21 35 28

### Steps to reproduce

1. Open https://gitpod.io/#%20https://github.com/gitpod-io/spring-petclinic

### Workspace affected

_No response_

### Expected behavior

The dashboards trims the space in the input when submitting avoiding me the error

Screenshot 2022-08-11 at 21 36 33

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

## Description
Bug Fix: This PR propose change to trim url while staring a new workspace from dashboard.

|Before|After **_(ignore UI Change)_**|
|:---:|:---:|
|<video src="https://user-images.githubusercontent.com/55068936/210498585-b0888eb5-15de-42e0-a6c6-7cff3b866c24.mov">|<video src="https://user-images.githubusercontent.com/55068936/210498644-90423345-0cbc-4158-912b-6c26b4f2426a.mov">|

## Related Issue(s)

Fixes #12079

## How to test

- Open [Preview](https://fix-12079.preview.gitpod-dev.com)
- Open [/workspaces](https://fix-12079.preview.gitpod-dev.com/workspaces)
- Click on New Workspace Button
- Type `       https://github.com/gitpod-io/empty` in Repo. URL text box. It will start a new workspace without any error (_repeat same in prod. to exp. the difference_)

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

File: components/dashboard/src/components/RepositoryFinder.tsx [hunk 1]
```diff
@@ -37,13 +37,13 @@ export default function RepositoryFinder(props: RepositoryFinderProps) {
             const result = [...suggestedContextURLs];
             try {
```
Comment (easyCZ) [inline components/dashboard/src/components/RepositoryFinder.tsx:38]:
```suggestion
            const result = [...suggestedContextURLs];
            searchString = searchString.trim();
            try {
```
To avoid having to trim in multiple places below.

Comment (Siddhant-K-code) [reply components/dashboard/src/components/RepositoryFinder.tsx]: Resolved in [`ba6f09d`](https://github.com/gitpod-io/gitpod/pull/15561/commits/ba6f09d4da8fb328d8f72ca2aff0f1b303ef488f)

**Review by easyCZ — APPROVED** [review]
