### PR TITLE
[supervisor] Fixes failing prebuilds are not reported as "headlessTaskFailed"

### LINKED ISSUE #6643: Failing prebuilds are not reported as "headlessTaskFailed"
Exmaple workspace (staging):
 - log showing "exit status code 1": https://storage.cloud.google.com/gitpod-prodcopy-user-4525da00-348f-40e4-b7eb-7d2c4325000e/workspaces/amber-koi-wur0q4ky/instances/a363be89-19a5-40d5-80a1-bbdabc4c966e/logs/0
 - workspaceId: `amber-koi-wur0q4ky`
 - instanceId: `a363be89-19a5-40d5-80a1-bbdabc4c966e`
 - status:
 ```
 {
   [...]
    "phase": "stopped",
    "message": "",
    "timeout": "30m0s",
    "conditions": {
        "failed": "",
        "timeout": "",
        "deployed": true,
        "pullingImages": false,
        "neededImageBuild": true,
        "stoppedByRequest": false,
        "headlessTaskFailed": ""
    }
}
 ```

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

[supervisor] Fixes failing prebuilds are not reported as "headlessTaskFailed"

## Related Issue(s)

Fixes #6643

## How to test

Following this step https://github.com/gitpod-io/gitpod/issues/6643#issuecomment-977904766

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **corneliusludmann** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @corneliusludmann` in a comment when ready.

Associated issue: *#6643*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/supervisor/pkg/supervisor/supervisor.go [hunk 1]
```diff
@@ -1011,13 +1018,19 @@ func stopWhenTasksAreDone(ctx context.Context, wg *sync.WaitGroup, shutdown chan
 		if err != nil {
 			log.WithError(err).Error("err while writing termination log")
 		}
+		shutdown <- ShutdownReasonExecutionError
```
Comment (iQQBot) [inline components/supervisor/pkg/supervisor/supervisor.go:1021]: I want to know whether this was done intentionally? @geropl

Comment (geropl) [reply components/supervisor/pkg/supervisor/supervisor.go:1021]: > I want to know whether this was done intentionally?

What do you mean? :thinking:

Comment (iQQBot) [reply components/supervisor/pkg/supervisor/supervisor.go:1021]: That is, whether the task is successful or failed, the status of the pod is success

Comment (geropl) [reply components/supervisor/pkg/supervisor/supervisor.go]: Still not completely sure what you're referring to.

Prebuilds (most prominent type of headless workspaces) are  _succeeding_ (exit code: 0) whenever they manage to start and execute properly. That includes cases where their (headless) tasks _fail_: they are also meant to return with exit code 0 but with the additional field [`headlessTaskFailed`](https://github.com/gitpod-io/gitpod/blob/92994450900d3b002acc829ef72f208247bf37c1/components/ws-manager-api/go/core.pb.go#L2056) set to a none-empty value.

That should be checked [here](https://github.com/gitpod-io/gitpod/blob/6509092ad43c0253e541b05882cab1a033da3cec/components/ws-manager/pkg/manager/status.go#L320-L327), but for some reasons does not seem to happen anymore.

Or it is set temporarily and then lost on subsequent updates? :thinking:

Comment (iQQBot) [reply components/supervisor/pkg/supervisor/supervisor.go]: According to what you said this PR has been completed, you can have a test

Comment (iQQBot) [reply components/supervisor/pkg/supervisor/supervisor.go]: Only I want to confirm is that
> That includes cases where their (headless) tasks fail: they are also meant to return with exit code 0

File: components/supervisor/pkg/supervisor/supervisor.go [hunk 2]
```diff
@@ -844,6 +847,10 @@ func startAPIEndpoint(ctx context.Context, cfg *Config, wg *sync.WaitGroup, serv
 	defer wg.Done()
 	defer log.Debug("startAPIEndpoint shutdown")
 
+	if cfg.isHeadless() {
+		return
+	}
```
Comment (csweichel) [inline components/supervisor/pkg/supervisor/supervisor.go:852]: headless tasks also need the API endpoint to satisfy the readiness probe, and because we listen to the headless tasks logs this way.

File: components/supervisor/pkg/supervisor/supervisor.go [hunk 3]
```diff
@@ -268,7 +268,10 @@ func Run(options ...RunOption) {
 	// We keep the reaper until the bitter end because:
 	//   - it doesn't need graceful shutdown
 	//   - we want to do as much work as possible (SIGTERM'ing reparented processes during shutdown).
-	go reaper(terminatingReaper)
+	//   - in headless task we don't need reaper
+	if !cfg.isHeadless() {
```
Comment (csweichel) [inline components/supervisor/pkg/supervisor/supervisor.go:272]: Good choice. Much preferable over a random `sleep` :)

File: components/supervisor/pkg/supervisor/supervisor.go (hunk 2 above)
Comment (iQQBot) [reply components/supervisor/pkg/supervisor/supervisor.go:852]: Oh sorry for that

Comment (iQQBot) [reply components/supervisor/pkg/supervisor/supervisor.go]: revert that

**Comment by csweichel** [comment]
This should also improve the failing image build behaviour. Right now we're checking if the image build actually produced an image to ensure it was successful. We did this because the image-builds "did not fail properly". 

/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: efba58cd1c6638b49159cfc912d0b2be17dc55fe</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6963#issuecomment-982370763" title="LGTM">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **corneliusludmann** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @corneliusludmann` in a comment when ready.

Associated issue: *#6643*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/supervisor/pkg/supervisor/supervisor.go (hunk 3 above)
Comment (geropl) [reply components/supervisor/pkg/supervisor/supervisor.go:272]: A more extensive comment would be awesome. "we can not because" reads more explicit than "don't need"

**Review by geropl — APPROVED** [review]
Tested and works, nice! :tada:
```
{
    "failed": "",
    "timeout": "",
    "deployed": false,
    "pullingImages": false,
    "stoppedByRequest": false,
    "headlessTaskFailed": "headless task failed: exit status 1"
}
```

one small nit: https://github.com/gitpod-io/gitpod/pull/6963/files#r759037482
holding to give the change to adjust that; feel free to ignore.

/hold

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6963#issuecomment-982413407" title="Approved">corneliusludmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6963#issuecomment-982370763" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6963#pullrequestreview-818705867" title="Approved">geropl</a>*

Associated issue: *#6643*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

File: components/supervisor/pkg/supervisor/supervisor.go (hunk 3 above)
Comment (iQQBot) [reply components/supervisor/pkg/supervisor/supervisor.go:272]: @geropl I changed this, is it good?

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6963#issuecomment-982413407" title="Approved">corneliusludmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6963#issuecomment-982370763" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6963#issuecomment-982594309" title="LGTM">geropl</a>*

Associated issue: *#6643*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
@iQQBot build fails with `no space left on device`: no space left on device
