### PR TITLE
Fix colon in URL params breaks Gitpod extension

### LINKED ISSUE #6514: A colon in URL params silently breaks Gitpod interface in VSCode
### Bug description

When opening URL of a repo where there's a colon in the URL params, it silently breaks Gitpod interface in VSCode:
* Gitpod menu items in main hamburger menu
* Ability to run `code` in terminal
* Ports panel
* etc...

image

### Steps to reproduce

1. Add URL params to any Gitpod repo
1. Create any variable with `=`, but make sure to add `:` in the value.

Example:
https://gitpod.io/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon

### Workspace affected

_No response_

### Expected behavior

This should either caught as parsing error before the workspace opens, or allow colons that are not encoded, but make sure the Gitpod interface in VSCode doesn't break.

### Example repository

https://gitpod.io/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon

### Anything else?

This was discovered thanks to @rfay

There's no specific need for a colon that is not encoded (`%3A`), Gitpod workspace receive the `colon` correctly, but the interface is broken.

### PR DESCRIPTION
**Pull request by jeanp413**
## Related Issue(s)

Fixes #6514

## How to test

1. Go to https://jp-fix-6514.staging.gitpod-dev.com/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon
2. Check that the gitpod extension is working properly

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@jeanp413: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
Left a couple TODOs as I did not want to touch too many files, but let me know if I should go ahead and address them in this PR.

**Comment by akosyakov** [comment]
@jeanp413 It would be good if the description elaborates why it should be fixed in Gitpod server.
@geropl Could you check please whether it makes sense?

**Review by geropl — CHANGES_REQUESTED** [review]
Hi @jeanp413 , thx for putting all the effort into investigating and trying to fix this issue!

While parts of the changes make sense, some change the semantics of the distinction `contextUrl`/`normalizedContextURL` in ways that are neither backwards compatible or would slightly break Gitpod.

Looking at the current parser output, I also see nothing wrong here:
```
{
    "isFile": false,
    "path": "",
    "title": "shaal/testing--gitpod-url-params-with_colon - main",
    "ref": "main",
    "refType": "branch",
    "revision": "edd94bebe22f8821df177c5f15af4265ef6615bb",
    "repository": {
        "cloneUrl": "https://github.com/shaal/testing--gitpod-url-params-with_colon.git",
        "host": "github.com",
        "name": "testing--gitpod-url-params-with_colon",
        "owner": "shaal",
        "private": false
    },
    "envvars": [
        {
            "name": "TESTING_URL_PARAMS_WITH_COLON",
            "value": ":",
            "repositoryPattern": "#/#"
        }
    ]
}
```
I suspect the issue here lies somewhere else, so I would strongly prefer to dig up the reason (sounds like a display issue?) and fix that.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#6514*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
To clarify a bit more: IMO the problem lies in the fact that the IDE assumes [WorkspaceInfo.getWorkspaceContextUrl](https://github.com/gitpod-io/openvscode-server/blob/6adf300b92efb535dba27dee626a898cdff4aeb0/extensions/gitpod-shared/src/features.ts#L99) to be normalized, while it's ultimately filled with the not-normalized, raw [contextURL](https://github.com/gitpod-io/gitpod/blob/a30a1bff483b02df67e01791b44dfb5bf025d344/components/server/src/workspace/workspace-starter.ts#L617).

To fix this issue we should:
 - make sure `normalizedContextURL` is set during parsing (as you already did in the PR)
 - (while not changing the semantics of `contextURL`)
 - pass it into `supervisor` and thus IDE - either by adding a new env var/field or re-using the existing one

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#6514*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/server/ee/src/workspace/workspace-health-monitoring.ts [hunk 1]
```diff
@@ -47,6 +47,7 @@ export class WorkspaceHealthMonitoring {
                 title: "Workspace Probe",
                 responseURL,
                 responseToken,
+                normalizedContextURL: ""
```
Comment (geropl) [inline components/server/ee/src/workspace/workspace-health-monitoring.ts:50]: Why not leave this undefined?

File: components/gitpod-protocol/src/protocol.ts [hunk 2]
```diff
@@ -779,7 +779,7 @@ export namespace ExternalImageConfigFile {
 
 export interface WorkspaceContext {
     title: string;
-    normalizedContextURL?: string;
+    normalizedContextURL?: string; // TODO: make this NOT optional
```
Comment (geropl) [inline components/gitpod-protocol/src/protocol.ts:782]: IMO a comment ala `/* This contains the URL portion of the contextURL (which might contain other modifiers as well). It's optional because it's not set for older workspaces.' */

File: components/server/src/projects/projects-service.ts [hunk 3]
```diff
@@ -185,8 +185,8 @@ export class ProjectsService {
         if (!project) {
             throw new Error("Project not found");
         }
-        const normalizedContextUrl = this.contextParser.normalizeContextURL(project.cloneUrl);
-        const commitContext = (await this.contextParser.handle(ctx, user, normalizedContextUrl)) as CommitContext;
+
+        const commitContext = (await this.contextParser.handle(ctx, user, project.cloneUrl)) as CommitContext;
```
Comment (geropl) [inline components/server/src/projects/projects-service.ts:189]: I would revert this change. The contract of `contextParser.handle` is that it receives the output of `normalizedContextURL` and we should keep it that way.

I'm aware that this is neither well documented nor obvious from the interface (due to how it evolved over time). :wink:

File: components/server/src/workspace/workspace-starter.ts [hunk 4]
```diff
@@ -614,7 +614,7 @@ export class WorkspaceStarter {
 
         const contextUrlEnv = new EnvironmentVariable();
         contextUrlEnv.setName('GITPOD_WORKSPACE_CONTEXT_URL');
-        contextUrlEnv.setValue(workspace.contextURL);
+        contextUrlEnv.setValue(workspace.context.normalizedContextURL!);
```
Comment (geropl) [inline components/server/src/workspace/workspace-starter.ts:617]: To make sure this is backwards compatible: `workspace.context.normalizedContextURL || workspace.contextURL`

Comment (geropl) [reply components/server/src/workspace/workspace-starter.ts:617]: Note that this is a user-facing change: `GITPOD_WORKSPACE_CONTEXT_URL` ends up in each workspace's environment. Still I think it's ok to "break" that implicit contract here given that `supervisor` and IDE's respectively are fine with that. I assume you verified that?

**Comment by geropl** [comment]
@jeanp413 I posted some comments. Once those are incorporated the PRs LGTM.

File: components/server/src/workspace/workspace-starter.ts (hunk 4 above)
Comment (jeanp413) [reply components/server/src/workspace/workspace-starter.ts:617]: yeah it's fine on the supervisor and IDE part

File: components/server/src/projects/projects-service.ts (hunk 3 above)
Comment (jeanp413) [reply components/server/src/projects/projects-service.ts:189]: Sure, I just want to point out that looking at the code calling `normalizeContextURL` here does nothing as the url is invalid and the prefix needs to be removed first, which is what the `handle` method does internally

Comment (geropl) [reply components/server/src/projects/projects-service.ts]: > which is what the handle method does internally

Yes, unfortunately `normalize` is not idempotent. E.g., if you call it 2 times, it might have a different result then calling it 1 or 3 times in a row (as I mentionend: bad contract which evolved and should be refactored :100: )

File: components/server/src/workspace/workspace-starter.ts [hunk 5]
```diff
@@ -614,7 +614,9 @@ export class WorkspaceStarter {
 
         const contextUrlEnv = new EnvironmentVariable();
         contextUrlEnv.setName('GITPOD_WORKSPACE_CONTEXT_URL');
-        contextUrlEnv.setValue(workspace.contextURL);
+        // Beware that `workspace.contextURL` is not normalized so it might contain other modifiers
```
Comment (geropl) [inline components/server/src/workspace/workspace-starter.ts:617]: :+1:

**Review by geropl — APPROVED** [review]
Thx @jeanp413 ! LGTM, tested and works

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 3fd2e4ebc3723b7b3aa7b260757ac8dffd32ce2f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6608#pullrequestreview-803612326" title="Approved">geropl</a>*

Associated issue: *#6514*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [geropl]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
