### PR TITLE
[dashboard/server] Fix "start-workspace-cycle" on image builder errors

### LINKED ISSUE #4856: Prebuild process gets stuck (when updating `.gitpod.Dockerfile`)
### Bug description

When updating `.gitpod.Dockerfile` and pushing it back to repo on a branch, the prebuild seems stuck.
It takes over half an hour (but I am not sure how long, perhaps 1 hour?) where all I see is this screen with jumping G.
(while console doesn't display any error) 
image

Coming back to the computer after a while, I see this screen -
image
And here's the output I found in `console` -
https://gist.github.com/shaal/b34b1e2ffba2d50deb4e42a3b4ed961c

I checked `gitpod.io/workspaces`, and I see 5(?) workspaces running, even that I only opened 2 windows of the following URL, expecting to see the prebuild output - https://gitpod.io/#https://github.com/shaal/DrupalPod/tree/debug-with-tmate

image

### Steps to reproduce

In my experience, it is difficult to replicate or anticipate how prebuild behave (especially with custom docker image build)
This happened to me also the other day, when I worked on https://github.com/phase2/outline/tree/gitpod, when I opened an issue in https://community.gitpod.io/t/prebuild-is-stuck/4171

I think I usually use the manual prebuild using the `#prebuild/` in the URL, but in repos that has the Gitpod bot, I would get a message that a prebuild is already running.

These workspaces supposed to run prebuild, but they are stuck, and once 4 workspaces are "running", I cannot open another one, but at the same time I cannot stop a prebuild that is stuck like that.
So, I usually wait a few hours, then the workspaces are shutdown, and I can run prebuild using the `#prebuild/` in the URL, and then it finally works.

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by geropl**
Fixes #4856.

I pushed https://github.com/gitpod-io/gitpod/pull/4875/commits/bf44fa1d6653fe1c8b2254caa4fd2bf3a6256193 should serve as reproducer for #4856.

### Test

 1. Go to https://gpl-4856-prebuild-cycle.staging.gitpod-dev.com/workspaces/
 1. Open dev console
 1. Start a prebuild suing `/#prebuild/` which triggers a fresh image-build that takes longer than 1 minute
 2. Note how you see _exactly one_ line of `/start: started workspace instance: ` after ~1 minute
 1. Note how you get stuck on the prebuild page :confused: (cmp. https://github.com/gitpod-io/gitpod/issues/4856#issuecomment-883144199)

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4875#" title="Author self-approved">geropl</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [geropl]
- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [geropl]
- **[components/image-builder/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: components/image-builder/pkg/builder/builder.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ const (
 	LabelTemporary = "gitpod.io/image-builder/temporary"
 
 	// maxBuildRuntime is the maximum time a build is allowed to take
-	maxBuildRuntime = 60 * time.Minute
+	maxBuildRuntime = 1 * time.Minute
```
Comment (AlexTugarev) [inline components/image-builder/pkg/builder/builder.go:47]: r u sure?

Comment (geropl) [reply components/image-builder/pkg/builder/builder.go:47]: See commit message(`DON'T MERGE, FOR TESTING ONLY`) and label (`do-not-merge/hold`) :upside_down_face:

**Comment by AlexTugarev** [comment]
(With the current test setup, i.e. test commit) I get the `deadline exceeded` error as follows

Screen Shot 2021-07-20 at 11 32 54

**Comment by geropl** [comment]
> (With the current test setup, i.e. test commit) I get the deadline exceeded error as follows

@AlexTugarev That looks good so far. Do you see the single line `/start: started workspace instance: ` in the web console as mentioned [here](https://github.com/gitpod-io/gitpod/pull/4875#issue-693203090)?

**Comment by AlexTugarev** [comment]
>  Do you see the single line /start: started workspace instance: in the web console as mentioned here?

yes. that's true.

**Comment by geropl** [comment]
>> Do you see the single line /start: started workspace instance: in the web console as mentioned here?

> yes. that's true.

Test succeeded :heavy_check_mark:

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4875#" title="Author self-approved">geropl</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [geropl]
- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AlexTugarev — APPROVED** [review]
LGTM!
Code changes make sense. 
Waited to for the re-deploy to verify it's not breaking things.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: d6a5ccd70d98e5fd76004a1b140ad785dcf89a58</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4875#pullrequestreview-710400497" title="Approved">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4875#" title="Author self-approved">geropl</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [AlexTugarev,geropl]
- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev,geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
